Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2019-10, with the labels that each got.

#182 A11Y query updates + bug fixes
  sql/2019/04_Media/04_08.sql
  sql/2019/09_Accessibility/09_17.sql
  sql/2019/09_Accessibility/09_18.sql
  sql/2019/09_Accessibility/09_19_a.sql
  sql/2019/09_Accessibility/09_19_b.sql
  sql/2019/09_Accessibility/09_19_c.sql
Labels: Analysis

#185 Mobile web query changes to add more context to results
  sql/2019/12_Mobile_Web/12_08.sql
  sql/2019/12_Mobile_Web/12_13.sql
  sql/2019/12_Mobile_Web/12_14.sql
  sql/2019/12_Mobile_Web/12_15.sql
Labels: Analysis

#177 Script to generate JSON from SQL
  sql/run_queries.sh
Labels: Analysis, Development

#186 PWA chapter
  src/content/en/2019/pwa.md
Labels: Writing

#176 More H2 Queries
  sql/2019/20_HTTP_2/20_01.sql
  sql/2019/20_HTTP_2/20_02.sql
  sql/2019/20_HTTP_2/20_03.sql
  sql/2019/20_HTTP_2/20_04.sql
  sql/2019/20_HTTP_2/20_04a_05a_06a.sql
  sql/2019/20_HTTP_2/20_05.sql
  sql/2019/20_HTTP_2/20_06.sql
  sql/2019/20_HTTP_2/20_07.sql
  sql/2019/20_HTTP_2/20_08.sql
  sql/2019/20_HTTP_2/20_09.sql
  sql/2019/20_HTTP_2/20_10.sql
  sql/2019/20_HTTP_2/20_11.sql
  sql/2019/20_HTTP_2/20_12.sql
  sql/2019/20_HTTP_2/20_13.sql
  sql/2019/20_HTTP_2/20_15.sql
  sql/2019/20_HTTP_2/20_16.sql
Labels: ASAP, Analysis

#183 fix responsive of home page
  src/static/css/2019.css
  src/static/css/index.css
  src/static/images/home-hero-2019.png
  src/static/images/intro-background-fit.png
  src/templates/en/2019/index.html
Labels: Development

#190 Fix logo font on homepage
  src/static/css/index.css
Labels: Development

#191 add decorative lines on the homepage
  src/static/css/2019.css
  src/static/css/index.css
  src/templates/en/2019/index.html
Labels: Development

#188 Both '0' and 'no' will prevent zooming
  sql/2019/09_Accessibility/09_26.sql
  sql/2019/12_Mobile_Web/12_04.sql
Labels: Analysis

#193 Extra Mobile Web queries
  sql/2019/12_Mobile_Web/12_04_b.sql
  sql/2019/12_Mobile_Web/12_12_b.sql
  sql/2019/12_Mobile_Web/12_20_b.sql
Labels: Analysis

#184 Create markup.md
  src/content/en/2019/markup.md
Labels: Writing

#198 Chapter 10: two extra metrics
  sql/2019/10_SEO/10_18.sql
  sql/2019/10_SEO/10_19.sql
Labels: Analysis

#194 Http2 chapter
  src/content/en/2019/http2.md
  src/static/images/2019/20_HTTP_2/TCPconnections.png
  src/static/images/2019/20_HTTP_2/http2usage.png
  src/static/images/2019/20_HTTP_2/numresources.png
  src/static/images/2019/20_HTTP_2/whatpushisusedfor.png
Labels: Writing

#189 Chapter 5: Third Parties article
  src/content/en/2019/third-parties.md
Labels: Writing

#207 people deletion and responsive support
  src/static/css/index.css
  src/templates/en/2019/index.html
Labels: Development

#205 Add design methodology
  src/static/css/2019.css
  src/static/css/methodology.css
  src/static/images/methodology-banner.png
  src/templates/en/2019/methodology.html
Labels: Development

#200 More CMS queries
  sql/2019/14_CMS/14_13d.sql
  sql/2019/14_CMS/14_14b.sql
  sql/2019/14_CMS/14_18b.sql
  sql/2019/14_CMS/14_19b.sql
  sql/2019/14_CMS/14_20.sql
  sql/2019/14_CMS/14_20b.sql
Labels: Analysis

#211 Custom error page, forced lang in URL
  src/main.py
  src/static/css/error.css
  src/static/css/methodology.css
  src/templates/en/2019/base.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/en/2019/outline.html
  src/templates/en/2019/splash.html
  src/templates/error/error.html
  src/validate.py
Labels: Development

#197 Chapter 10: SEO content
  src/content/en/2019/seo.md
Labels: Writing

#213 Generate chapter contents
  src/config/2019.json
  src/content/en/2019/css.md
  src/content/en/2019/http2.md
  src/content/en/2019/javascript.md
  src/content/en/2019/markup.md
  src/content/en/2019/performance.md
  src/content/en/2019/pwa.md
  src/content/en/2019/third-parties.md
  src/content/ja/2019/javascript.md
  src/csp.py
  src/main.py
  src/static/css/chapter.css
  src/static/images/2019/03_Markup/hixie_element_types_per_page.png
  src/static/images/2019/03_Markup/hixie_elements_per_page.png
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/outline.html
  src/templates/ja/2019/chapters/javascript.html
Labels: Development

#212 Home page content
  src/main.py
  src/static/css/index.css
  src/templates/en/2019/index.html
Labels: Development

#215 Performance chapter
  src/config/2019.json
  src/content/en/2019/performance.md
  src/generate_chapters.py
  src/static/images/2019/07_Performance/nav-timing.png
  src/templates/en/2019/chapters/performance.html
Labels: Writing

#225 Merge chapters branch
  src/config/2019.json
  src/content/en/2019/performance.md
  src/generate_chapters.py
  src/static/images/2019/07_Performance/nav-timing.png
  src/templates/en/2019/chapters/performance.html
Labels: Development

#228 more characters!
  src/static/images/character-file.png
  src/static/images/character-measure.png
  src/static/images/character-painter.png
Labels: Design

#217 added hover and focus for interactive element (header/footer)
  src/static/css/2019.css
  src/templates/en/2019/base.html
Labels: Development, enhancement

#222 Converted the markdown generation to showdown.
  src/.gitignore
  src/README.md
  src/package-lock.json
  src/package.json
  src/templates/en/2019/chapter.html
  src/tools/generate/generate_chapters.js
  src/tools/generate/index.js
Labels: Development, bug

#208 New queries for mobile and a11y chapters
  sql/2019/09_Accessibility/09_01b.sql
  sql/2019/09_Accessibility/09_05b.sql
  sql/2019/09_Accessibility/09_16b.sql
  sql/2019/09_Accessibility/09_19a.sql
  sql/2019/09_Accessibility/09_19b.sql
  sql/2019/09_Accessibility/09_19c.sql
  sql/2019/09_Accessibility/09_30a.sql
  sql/2019/09_Accessibility/09_30b.sql
  sql/2019/09_Accessibility/09_32b.sql
  sql/2019/12_Mobile_Web/12_04b.sql
  sql/2019/12_Mobile_Web/12_12b.sql
  sql/2019/12_Mobile_Web/12_20b.sql
  sql/2019/12_Mobile_Web/12_21.sql
Labels: Analysis

#229 Table of contents
  src/main.py
  src/templates/en/2019/base.html
  src/templates/en/2019/index.html
  src/templates/en/2019/outline.html
  src/templates/en/2019/table_of_contents.html
  src/templates/ja/2019/table_of_contents.html
Labels: Development

#235 add toc with desktop resolution footer
  src/static/css/2019.css
  src/templates/en/2019/base.html
Labels: Development

#223 Methodology content
  src/static/css/methodology.css
  src/templates/en/2019/methodology.html
Labels: Writing

#241 Http2 chapter contributors
  src/config/2019.json
  src/content/en/2019/http2.md
Labels: Development, Writing

#233 Copyediting SEO chapter
  src/content/en/2019/seo.md
Labels: Writing

#244 Small fix to zooming and scaling metric
  sql/2019/09_Accessibility/09_26.sql
  sql/2019/12_Mobile_Web/12_04.sql
Labels: Analysis

#242 CDN stats - Update queries
  sql/2019/17_CDN/17_02f.sql
  sql/2019/17_CDN/17_02h.sql
  sql/2019/17_CDN/17_10b.sql
Labels: Analysis

#240 Media stats update for #85
  sql/2019/04_Media/04_01-02.sql
  sql/2019/04_Media/04_01a.sql
  sql/2019/04_Media/04_01b.sql
  sql/2019/04_Media/04_01c.sql
  sql/2019/04_Media/04_01d.sql
  sql/2019/04_Media/04_03.sql
  sql/2019/04_Media/04_03b.sql
  sql/2019/04_Media/04_06.sql
  sql/2019/04_Media/04_06b.sql
  sql/2019/04_Media/04_08.sql
  sql/2019/04_Media/04_09a.sql
  sql/2019/04_Media/04_09b.sql
  sql/2019/04_Media/04_09c.sql
  sql/2019/04_Media/04_09d.sql
  sql/2019/04_Media/04_11.sql
  sql/2019/04_Media/04_11a.sql
  sql/2019/04_Media/04_11b.sql
Labels: Analysis

#245 Copyediting Third Party chapter
  src/content/en/2019/third-parties.md
Labels: Writing

#247 TTFB queries for performance
  sql/2019/07_Performance/07_07.sql
  sql/2019/07_Performance/07_07b.sql
  sql/2019/07_Performance/07_07c.sql
  sql/2019/07_Performance/07_08.sql
  sql/2019/07_Performance/07_08b.sql
  sql/2019/07_Performance/07_08c.sql
  sql/2019/07_Performance/07_08d.sql
Labels: Analysis

#248 simplify footer markup
  src/static/css/2019.css
  src/templates/en/2019/base.html
Labels: Development

#251 Chapter page styling
  src/static/css/page.css
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapter.html
  src/templates/en/2019/methodology.html
Labels: Design, Development

#232 Generate Table of Contents for each chapter
  src/package-lock.json
  src/package.json
  src/templates/en/2019/chapter.html
  src/templates/en/2019/toc.html
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_table_of_contents.js
Labels: ASAP, Development

#250 Lint templates
  src/content/en/2019/markup.md
  src/content/en/2019/pwa.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/package-lock.json
  src/package.json
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/tools/generate/generate_chapters.js
Labels: Development

#234 A11Y chapter
  src/content/en/2019/a11y.md
  src/static/images/2019/09_Accessibility/example-of-a-skip-link-on-google.com.png
  src/static/images/2019/09_Accessibility/example-of-good-and-bad-color-contrast-lookzook.png
Labels: ASAP, Writing

#256 Chapter author prevnext
  src/main.py
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
Labels: Development

#252 Contributors config and design
  src/config.py
  src/config/2019.json
  src/content/en/2019/a11y.md
  src/content/en/2019/http2.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/csp.py
  src/static/images/blog.png
  src/templates/en/2019/contributors.html
Labels: Development

#254 Markup chapter edits
  src/content/en/2019/markup.md
  src/static/css/chapter.css
  src/static/images/2019/03_Markup/element_categories.png
  src/templates/en/2019/chapters/markup.html
Labels: Writing

#255 Chapter style tweaks
  src/static/css/2019.css
  src/static/css/page.css
  src/templates/en/2019/base.html
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/methodology.html
Labels: Design, Development

#266 Fix relative linking in chapters
  src/config/2019.json
  src/content/en/2019/markup.md
  src/content/en/2019/seo.md
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/seo.html
Labels: Development

#265 Add preconnect for https://fonts.gstatic.com
  src/config/2019.json
  src/templates/en/2019/base.html
  src/templates/ja/2019/base.html
Labels: Development

#257 Generate figure IDs
  src/templates/en/2019/chapters/performance.html
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_figure_ids.js
Labels: Development

#267 Formatting bugs
  src/content/en/2019/accessibility.md
  src/content/en/2019/pwa.md
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/tools/generate/generate_chapters.js
Labels: Development

#268 Add Retina Logo & more issues
  src/config/2019.json
  src/static/images/logo.png
  src/static/images/logo@2x.png
  src/templates/en/2019/base.html
  src/templates/en/2019/contributors.html
Labels: Development

#272 Added Twitter Handles I know
  src/config/2019.json
Labels: Development

#246 Ecommerce chapter
  src/content/en/2019/ecommerce.md
Labels: ASAP, Writing

#281 👌 IMPROVE: Button Styles
  src/static/css/2019.css
Labels: Development, enhancement

#277 Created a filter based on the hash #274
  src/templates/en/2019/contributors.html
Labels: Development

#287 Add Calibre App image actions to automatically optimize images
  .github/workflows/calibreapp-image-actions.yml
Labels: Development

#249 Updated Performance content
  sql/2019/07_Performance/07_03.sql
  sql/2019/07_Performance/07_03b.sql
  sql/2019/07_Performance/07_03c.sql
  sql/2019/07_Performance/07_03d.sql
  sql/2019/07_Performance/07_04c.sql
  sql/2019/07_Performance/07_04d.sql
  sql/2019/07_Performance/07_08.sql
  sql/2019/07_Performance/07_08d.sql
  src/content/en/2019/performance.md
  src/templates/en/2019/chapters/performance.html
Labels: Writing
