Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2019-09, with the labels that each got.

#129 E-Commerce queries
  sql/2019/01_JavaScript/01_02a.sql
  sql/2019/13_Ecommerce/13_01.sql
  sql/2019/13_Ecommerce/13_02.sql
  sql/2019/13_Ecommerce/13_02b.sql
  sql/2019/13_Ecommerce/13_06.sql
  sql/2019/13_Ecommerce/13_06b.sql
  sql/2019/13_Ecommerce/13_06c.sql
  sql/2019/13_Ecommerce/13_07.sql
  sql/2019/13_Ecommerce/13_08.sql
  sql/2019/13_Ecommerce/13_09.sql
  sql/2019/13_Ecommerce/13_09b.sql
  sql/2019/13_Ecommerce/13_10.sql
  sql/2019/13_Ecommerce/13_11.sql
  sql/2019/13_Ecommerce/13_12.sql
  sql/2019/13_Ecommerce/13_13.sql
Labels: Analysis

#138 Added gravatar url generation for contributors
  src/config.py
  src/csp.py
  src/static/images/avatars/0.jpg
  src/static/images/avatars/1.jpg
  src/static/images/avatars/10.jpg
  src/static/images/avatars/11.jpg
  src/static/images/avatars/12.jpg
  src/static/images/avatars/13.jpg
  src/static/images/avatars/14.jpg
  src/static/images/avatars/2.jpg
  src/static/images/avatars/3.jpg
  src/static/images/avatars/4.jpg
  src/static/images/avatars/5.jpg
  src/static/images/avatars/6.jpg
  src/static/images/avatars/7.jpg
  src/static/images/avatars/8.jpg
  src/static/images/avatars/9.jpg
  src/templates/en/2019/contributors.html
Labels: Development

#105 Fonts queries
  sql/2019/06_Fonts/06_01.sql
  sql/2019/06_Fonts/06_02.sql
  sql/2019/06_Fonts/06_03.sql
  sql/2019/06_Fonts/06_04.sql
  sql/2019/06_Fonts/06_09a.sql
  sql/2019/06_Fonts/06_09b.sql
  sql/2019/06_Fonts/06_10.sql
  sql/2019/06_Fonts/06_13.sql
  sql/2019/06_Fonts/06_14.sql
  sql/2019/06_Fonts/06_14b.sql
  sql/2019/06_Fonts/06_15.sql
  sql/2019/06_Fonts/06_16.sql
  sql/2019/06_Fonts/06_18.sql
  sql/2019/06_Fonts/06_21.sql
  sql/2019/06_Fonts/06_24.sql
  sql/2019/06_Fonts/06_25.sql
  sql/2019/06_Fonts/06_26.sql
  sql/2019/06_Fonts/06_28.sql
  sql/2019/06_Fonts/06_28b.sql
  sql/2019/06_Fonts/06_29.sql
  sql/2019/06_Fonts/06_30.sql
Labels: ASAP, Analysis

#127 Chapter 15 - Compression Queries
  sql/2019/15_Compression/15_01.sql
  sql/2019/15_Compression/15_04.sql
  sql/2019/15_Compression/15_05.sql
  sql/2019/15_Compression/15_06.sql
  sql/2019/20_HTTP_2/20_01.sql
  sql/2019/20_HTTP_2/20_03.sql
  sql/2019/20_HTTP_2/20_08.sql
  sql/2019/20_HTTP_2/20_09.sql
  sql/2019/20_HTTP_2/20_10.sql
  sql/2019/20_HTTP_2/20_11.sql
  sql/2019/20_HTTP_2/20_12.sql
Labels: ASAP, Analysis

#113 Synthetic performance and CDN queries
  sql/2019/07_Performance/07_10.sql
  sql/2019/07_Performance/07_11.sql
  sql/2019/07_Performance/07_12.sql
  sql/2019/07_Performance/07_13.sql
  sql/2019/07_Performance/07_14.sql
  sql/2019/07_Performance/07_15.sql
  sql/2019/07_Performance/07_16.sql
  sql/2019/07_Performance/07_17.sql
  sql/2019/07_Performance/07_18.sql
  sql/2019/07_Performance/07_19.sql
  sql/2019/07_Performance/07_20.sql
  sql/2019/07_Performance/07_21.sql
  sql/2019/07_Performance/07_22.sql
  sql/2019/07_Performance/07_23.sql
  sql/2019/07_Performance/07_24.sql
Labels: ASAP, Analysis

#148 CDN queries
  sql/2019/17_CDN/17_01.sql
  sql/2019/17_CDN/17_02.sql
  sql/2019/17_CDN/17_02b.sql
  sql/2019/17_CDN/17_02c.sql
  sql/2019/17_CDN/17_02d.sql
  sql/2019/17_CDN/17_03.sql
  sql/2019/17_CDN/17_04.sql
  sql/2019/17_CDN/17_05.sql
  sql/2019/17_CDN/17_06.sql
  sql/2019/17_CDN/17_07.sql
  sql/2019/17_CDN/17_08.sql
  sql/2019/17_CDN/17_09.sql
  sql/2019/17_CDN/17_10.sql
  sql/2019/17_CDN/17_11.sql
  sql/2019/17_CDN/17_12.sql
  sql/2019/17_CDN/17_13.sql
  sql/2019/17_CDN/17_17.sql
  sql/2019/17_CDN/17_18.sql
  sql/2019/17_CDN/17_19.sql
  sql/2019/17_CDN/17_20.sql
  sql/2019/17_CDN/17_21.sql
  sql/2019/17_CDN/17_22.sql
  sql/2019/17_CDN/17_23.sql
  sql/2019/17_CDN/17_24.sql
  sql/2019/17_CDN/17_25.sql
Labels: Analysis

#146 Mobile Web queries 2 of 2
  sql/2019/12_Mobile_Web/12_07.sql
  sql/2019/12_Mobile_Web/12_17.sql
  sql/2019/12_Mobile_Web/12_20.sql
Labels: ASAP, Analysis

#152 JS query fixes
  sql/2019/01_JavaScript/01_14.sql
  sql/2019/01_JavaScript/01_15.sql
  sql/2019/01_JavaScript/01_16.sql
  sql/2019/01_JavaScript/01_24.sql
  sql/2019/01_JavaScript/01_25.sql
Labels: Analysis

#142 Fonts queries
  sql/2019/06_Fonts/06_31.sql
  sql/2019/06_Fonts/06_32.sql
  sql/2019/06_Fonts/06_34.sql
  sql/2019/06_Fonts/06_35.sql
  sql/2019/06_Fonts/06_36.sql
  sql/2019/06_Fonts/06_39.sql
  sql/2019/06_Fonts/06_42.sql
  sql/2019/06_Fonts/06_43.sql
  sql/2019/06_Fonts/06_44.sql
  sql/2019/06_Fonts/06_46.sql
  sql/2019/06_Fonts/06_47.sql
Labels: ASAP, Analysis

#120 Implement home page design
  src/language.py
  src/main.py
  src/static/css/index.css
  src/static/css/main.css
  src/static/css/splash.css
  src/static/images/English.png
  src/static/images/camada-751.png
  src/static/images/camada-752.png
  src/static/images/camada-754.png
  src/static/images/camada-755.png
  src/static/images/camada-756.png
  src/static/images/camada-759.png
  src/static/images/camada-760.png
  src/static/images/cross.png
  src/static/images/dropdown-arrow.png
  src/static/images/github.png
  src/static/images/ha-home.png
  src/static/images/home-browser.png
  src/static/images/home.png
  src/static/images/intro-background.png
  src/static/images/menu.png
  src/static/images/quote.png
  src/static/images/rectangles.png
  src/static/images/twitter.png
  src/static/js/language.js
  src/templates/base.html
  src/templates/en/2019/contributors.html
  src/templates/en/index.html
  src/templates/en/splash.html
Labels: ASAP, Design, Development

#125 PWA queries
  sql/2019/11_PWA/11_01.sql
  sql/2019/11_PWA/11_01b.sql
  sql/2019/11_PWA/11_02.sql
Labels: ASAP, Analysis

#103 Analyst SQL files chapter SEO
  sql/2019/10_SEO/10_01.sql
  sql/2019/10_SEO/10_02.sql
  sql/2019/10_SEO/10_03.sql
  sql/2019/10_SEO/10_04a.sql
  sql/2019/10_SEO/10_04b.sql
  sql/2019/10_SEO/10_05.sql
  sql/2019/10_SEO/10_06.sql
  sql/2019/10_SEO/10_07a.sql
  sql/2019/10_SEO/10_07b.sql
  sql/2019/10_SEO/10_07c.sql
  sql/2019/10_SEO/10_08.sql
  sql/2019/10_SEO/10_09a.sql
  sql/2019/10_SEO/10_09b.sql
  sql/2019/10_SEO/10_10.sql
  sql/2019/10_SEO/10_11.sql
  sql/2019/10_SEO/10_12.sql
  sql/2019/10_SEO/10_13.sql
  sql/2019/10_SEO/10_14.sql
  sql/2019/10_SEO/10_15a.sql
  sql/2019/10_SEO/10_15b.sql
Labels: ASAP, Analysis

#104 Media queries
  sql/2019/04_Media/04_01.sql
  sql/2019/04_Media/04_03.sql
  sql/2019/04_Media/04_04.sql
  sql/2019/04_Media/04_06.sql
  sql/2019/04_Media/04_08.sql
  sql/2019/04_Media/04_09a.sql
  sql/2019/04_Media/04_09b.sql
  sql/2019/04_Media/04_11.sql
  sql/2019/04_Media/04_12.sql
  sql/2019/04_Media/04_13.sql
  sql/2019/04_Media/04_15.sql
  sql/2019/04_Media/04_16.sql
  sql/2019/04_Media/04_17.sql
  sql/2019/04_Media/04_19.sql
  sql/2019/04_Media/04_25.sql
Labels: ASAP, Analysis

#123 CMS queries
  sql/2019/14_CMS/14_01.sql
  sql/2019/14_CMS/14_02.sql
  sql/2019/14_CMS/14_03.sql
Labels: ASAP, Analysis

#137 Chapter config
  src/config.py
  src/config/2019.json
  src/config/contributors.json
  src/contributors.py
  src/csp.py
  src/main.py
  src/static/images/avatars/0.jpg
  src/static/images/avatars/1.jpg
  src/static/images/avatars/10.jpg
  src/static/images/avatars/11.jpg
  src/static/images/avatars/12.jpg
  src/static/images/avatars/13.jpg
  src/static/images/avatars/14.jpg
  src/static/images/avatars/2.jpg
  src/static/images/avatars/3.jpg
  src/static/images/avatars/4.jpg
  src/static/images/avatars/5.jpg
  src/static/images/avatars/6.jpg
  src/static/images/avatars/7.jpg
  src/static/images/avatars/8.jpg
  src/static/images/avatars/9.jpg
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/outline.html
Labels: Development

#159 SEO queries revisited
  sql/2019/10_SEO/10_01.sql
  sql/2019/10_SEO/10_02.sql
  sql/2019/10_SEO/10_03.sql
  sql/2019/10_SEO/10_04a.sql
  sql/2019/10_SEO/10_04b.sql
  sql/2019/10_SEO/10_05.sql
  sql/2019/10_SEO/10_06.sql
  sql/2019/10_SEO/10_07a.sql
  sql/2019/10_SEO/10_07b.sql
  sql/2019/10_SEO/10_07c.sql
  sql/2019/10_SEO/10_08.sql
  sql/2019/10_SEO/10_09a.sql
  sql/2019/10_SEO/10_09b.sql
  sql/2019/10_SEO/10_10.sql
  sql/2019/10_SEO/10_11.sql
  sql/2019/10_SEO/10_12.sql
  sql/2019/10_SEO/10_13.sql
  sql/2019/10_SEO/10_14.sql
  sql/2019/10_SEO/10_15a.sql
  sql/2019/10_SEO/10_15b.sql
Labels: ASAP, Analysis

#162 PWA queries
  sql/2019/11_PWA/11_01.sql
  sql/2019/11_PWA/11_01b.sql
  sql/2019/11_PWA/11_02.sql
  sql/2019/11_PWA/11_03.sql
  sql/2019/11_PWA/11_03b.sql
  sql/2019/11_PWA/11_04.sql
  sql/2019/11_PWA/11_04b.sql
  sql/2019/11_PWA/11_04c.sql
  sql/2019/11_PWA/11_04d.sql
  sql/2019/11_PWA/11_04e.sql
  sql/2019/11_PWA/11_04f.sql
  sql/2019/11_PWA/11_04g.sql
  sql/2019/11_PWA/11_05.sql
  sql/2019/11_PWA/11_06.sql
Labels: ASAP, Analysis

#156 Implement home page design (mobile)
  src/static/css/index.css
  src/static/js/home.js
  src/templates/en/index.html
Labels: ASAP, Development

#178 More markup queries
  sql/2019/03_Markup/03_06.sql
  sql/2019/03_Markup/03_06b.sql
Labels: Analysis
