Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2019-11, with the labels that each got.

#288 Copyediting ecommerce chapter
  src/content/en/2019/ecommerce.md
  src/templates/en/2019/chapters/ecommerce.html
Labels: Writing

#297 Fix the index "Featured Chapter" blockquote #296
  src/config/2019.json
  src/static/css/2019.css
  src/static/css/index.css
  src/static/images/quote.png
  src/templates/en/2019/base.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/table_of_contents.html
Labels: Development, enhancement

#273 Copyediting PWA chapter
  src/content/en/2019/pwa.md
  src/templates/en/2019/chapters/pwa.html
Labels: Writing

#302 SEO fixes for canonical and meta info (inc Meta Descriptions, OG, Twitter and Article Structured Data)
  src/content/en/2019/http2.md
  src/templates/base.html
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
Labels: Development, SEO

#298 Ignorelist on the generator
  src/tools/generate/generate_chapters.js
Labels: Development

#306 Tidied up generator code
  src/package-lock.json
  src/package.json
  src/tools/generate/generate_chapters.js
Labels: Development

#311 Prevent generating ids for Table Headers to fix #310
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/tools/generate/generate_chapters.js
Labels: Development

#313 Moved the subtitle
  src/static/css/2019.css
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
Labels: Development, enhancement

#307 Add resource hints chapter
  src/content/en/2019/resource-hints.md
Labels: ASAP, Writing

#308 SEO Fixes part 2
  src/config/2019.json
  src/content/en/2019/accessibility.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/http2.md
  src/content/en/2019/markup.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/performance.md
  src/content/en/2019/pwa.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/en/2019/methodology.html
  src/templates/en/2019/table_of_contents.html
Labels: Writing

#192 Fonts chapter
  src/content/en/2019/fonts.md
Labels: ASAP, Writing

#314 Author bios
  src/config/2019.json
  src/templates/en/2019/base_chapter.html
Labels: Development

#321 Add page weight chapter
  src/content/en/2019/page-weight.md
  src/static/images/2019/15_Compression/ch15_fig10_lighthouse_compression_byte_savings.jpg
  src/static/images/2019/15_Compression/ch15_fig1_compression_algorithms.jpg
  src/static/images/2019/15_Compression/ch15_fig2_compressed_content_types.jpg
  src/static/images/2019/15_Compression/ch15_fig3_compressed_content_types_filtered.jpg
  src/static/images/2019/15_Compression/ch15_fig4_compression_by_content_type_desktop.jpg
  src/static/images/2019/15_Compression/ch15_fig5_compression_by_content_type_mobile.jpg
  src/static/images/2019/15_Compression/ch15_fig6_compression_by_content_type_pct_desktop.jpg
  src/static/images/2019/15_Compression/ch15_fig7_compression_by_content_type_pct_mobile.jpg
  src/static/images/2019/15_Compression/ch15_fig8_lighthouse.jpg
  src/static/images/2019/15_Compression/ch15_fig9_lighthouse_compression_scores.jpg
  src/static/images/2019/16_Caching/ch16_fig10_invalid_date_formats.jpg
  src/static/images/2019/16_Caching/ch16_fig11_vary_header.jpg
  src/static/images/2019/16_Caching/ch16_fig12_header_example_with_cookie.jpg
  src/static/images/2019/16_Caching/ch16_fig13_cookies_on_cacheable_responses.jpg
  src/static/images/2019/16_Caching/ch16_fig14_service_worker_adoption.jpg
  src/static/images/2019/16_Caching/ch16_fig15_lighthouse_example.jpg
  src/static/images/2019/16_Caching/ch16_fig16_lighthouse_cache_score.jpg
  src/static/images/2019/16_Caching/ch16_fig17_lighthouse_cache_byte_savings.jpg
  src/static/images/2019/16_Caching/ch16_fig1_redbot_example.jpg
  src/static/images/2019/16_Caching/ch16_fig2_cache_control_expires.jpg
  src/static/images/2019/16_Caching/ch16_fig3_distribution_of_cacheable_responses.jpg
  src/static/images/2019/16_Caching/ch16_fig4_caheability_by_content_type_desktop.jpg
  src/static/images/2019/16_Caching/ch16_fig5_caheability_by_content_type_mobile.jpg
  src/static/images/2019/16_Caching/ch16_fig6_usage_of_cache_control_expires.jpg
  src/static/images/2019/16_Caching/ch16_fig7_cache_control_directives.jpg
  src/static/images/2019/16_Caching/ch16_fig8_resource_age.jpg
  src/static/images/2019/16_Caching/ch16_fig9_validating_freshness.jpg
  src/static/images/2019/18_Page_Weight/ch18_fig1_conversion_difference.png
  src/static/images/2019/18_Page_Weight/ch18_fig2_conversion_graph.png
  src/static/images/2019/18_Page_Weight/ch18_fig3_gif_cdf.png
Labels: Writing

#320 Seo fixes3
  src/config/2019.json
  src/content/en/2019/caching.md
  src/content/en/2019/compression.md
  src/content/en/2019/fonts.md
  src/content/en/2019/page-weight.md
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/index.html
Labels: Development

#325 Change HTTP Archive name in Structured Data
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/en/2019/methodology.html
  src/templates/en/2019/table_of_contents.html
Labels: Development

#326 Minor typos and other fixes
  src/config/2019.json
  src/content/en/2019/ecommerce.md
  src/content/en/2019/pwa.md
  src/content/en/2019/third-parties.md
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/third-parties.html
Labels: Writing

#322 Foreword
  src/.gcloudignore
  src/templates/en/2019/table_of_contents.html
Labels: Writing

#329 Use larger image for OG meta data, add image dimensions
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/en/2019/methodology.html
Labels: Development

#305 Editing Mobile Web chapter
  src/config/2019.json
  src/content/en/2019/mobile-web.md
  src/csp.py
  src/static/css/2019.css
  src/static/css/page.css
  src/templates/en/2019/chapters/mobile-web.html
Labels: Writing

#231 CSS Chapter
  src/content/en/2019/css.md
Labels: ASAP, Writing

#259 JavaScript chapter
  src/content/en/2019/javascript.md
  src/static/images/2019/01_JavaScript/js-processing-reddit.png
Labels: ASAP, Writing

#336 Generate chapter content
  src/config/2019.json
  src/content/en/2019/css.md
  src/content/en/2019/javascript.md
  src/static/images/2019/01_JavaScript/js-processing-reddit.png
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/javascript.html
Labels: Development

#337 Update markup.md
  src/content/en/2019/markup.md
Labels: Writing

#341 Create a block formatting context due to containing next-chapter float.
  src/static/css/page.css
Labels: Development

#335 Copyediting for Performance Chapter
  src/content/en/2019/performance.md
Labels: Writing

#338 Media markdown
  src/content/en/2019/media.md
Labels: Writing

#342 Updating author bios
  src/config/2019.json
Labels: Development

#343 Generate chapters
  src/content/en/2019/media.md
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/performance.html
Labels: Writing

#344 Serve a robots.txt file
  src/main.py
  src/static/robots.txt
Labels: Development, SEO

#331 Editing page weight chapter
  src/content/en/2019/page-weight.md
Labels: Writing

#333 Design tweaks
  src/content/en/2019/media.md
  src/package-lock.json
  src/package.json
  src/static/css/2019.css
  src/static/css/index.css
  src/static/css/methodology.css
  src/static/css/page.css
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/methodology.html
  src/tools/generate/generate_chapters.js
  src/tools/generate/wrap_tables.js
Labels: Design, Development

#349 Bigger twitter cards
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/en/2019/methodology.html
  src/templates/en/2019/table_of_contents.html
Labels: Development

#359 HTTP/2 chapter edits
  src/content/en/2019/http2.md
  src/static/css/page.css
  src/templates/en/2019/chapters/http2.html
Labels: Writing

#363 Generate last_updated
  src/content/en/2019/accessibility.md
  src/content/en/2019/caching.md
  src/content/en/2019/compression.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/fonts.md
  src/content/en/2019/http2.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/page-weight.md
  src/content/en/2019/performance.md
  src/content/en/2019/pwa.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_last_updated.js
  src/tools/generate/index.js
  src/tools/generate/shared.js
Labels: Development, enhancement

#334 Copyediting of the HTTP/2 Chapter
  src/content/en/2019/http2.md
  src/static/css/page.css
  src/templates/en/2019/chapters/http2.html
Labels: Writing

#345 Auto generate sitemap
  src/content/en/2019/accessibility.md
  src/content/en/2019/caching.md
  src/content/en/2019/compression.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/fonts.md
  src/content/en/2019/http2.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/page-weight.md
  src/content/en/2019/performance.md
  src/content/en/2019/pwa.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/main.py
  src/static/robots.txt
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/sitemap.ejs.xml
  src/templates/sitemap.xml
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_sitemap.js
Labels: Development

#362 Tables, styling
  src/content/en/2019/accessibility.md
  src/content/en/2019/caching.md
  src/content/en/2019/compression.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/fonts.md
  src/content/en/2019/http2.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/page-weight.md
  src/content/en/2019/performance.md
  src/content/en/2019/pwa.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/static/css/2019.css
  src/static/css/methodology.css
  src/static/css/page.css
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/methodology.html
  src/templates/sitemap.xml
  src/tools/generate/wrap_tables.js
Labels: Development

#360 Change images used for social media for non chapters
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/en/2019/methodology.html
  src/templates/en/2019/table_of_contents.html
Labels: Development, enhancement

#356 Horizontal scrollbar
  src/static/css/page.css
Labels: Development, bug

#364 CMS chapter markdown
  src/config/2019.json
  src/content/en/2019/accessibility.md
  src/content/en/2019/caching.md
  src/content/en/2019/cms.md
  src/content/en/2019/compression.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/fonts.md
  src/content/en/2019/http2.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/page-weight.md
  src/content/en/2019/performance.md
  src/content/en/2019/pwa.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/static/images/2019/14_CMS/cms-logos.png
  src/static/images/2019/14_CMS/perf-perception.png
  src/static/images/2019/14_CMS/web-evolution.png
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
Labels: Writing

#366 Disable auto-generated last-modified
  src/tools/generate/index.js
Labels: Development

#323 Copyediting Compression chapter
  src/content/en/2019/compression.md
  src/templates/en/2019/chapters/compression.html
Labels: Writing

#357 Style tweaks for content pages
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/methodology.html
Labels: Development

#367 Data visualizations
  src/content/en/2019/accessibility.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/third-parties.md
  src/static/css/page.css
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/sitemap.xml
Labels: Development

#372 Fixing typos
  src/content/en/2019/css.md
Labels: Writing

#371 Different social media images for home, toc and contributors
  src/static/images/home-hero-2019-bg.png
  src/static/images/home-hero-bg.png
  src/static/images/methodology-characters-bg.png
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/en/2019/table_of_contents.html
Labels: Development

#328 Editing A11Y chapter
  src/content/en/2019/accessibility.md
Labels: Writing

#376 Final edits to mobile web and a11y
  src/content/en/2019/accessibility.md
  src/content/en/2019/mobile-web.md
Labels: Writing

#370 Final draft of Fonts chapter
  src/content/en/2019/fonts.md
Labels: ASAP, Writing

#382 Add a discuss button to each chapter
  src/content/en/2019/accessibility.md
  src/content/en/2019/caching.md
  src/content/en/2019/cms.md
  src/content/en/2019/compression.md
  src/content/en/2019/css.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/fonts.md
  src/content/en/2019/http2.md
  src/content/en/2019/javascript.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/page-weight.md
  src/content/en/2019/performance.md
  src/content/en/2019/pwa.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/security.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/csp.py
  src/static/css/page.css
  src/static/images/discuss.png
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/sitemap.xml
Labels: Development, enhancement

#384 Accessible data viz for Performance chapter
  src/content/en/2019/performance.md
  src/static/css/2019.css
  src/static/css/page.css
  src/static/images/2019/07_Performance/fig1.png
  src/static/images/2019/07_Performance/fig10.png
  src/static/images/2019/07_Performance/fig11.png
  src/static/images/2019/07_Performance/fig12.png
  src/static/images/2019/07_Performance/fig13.png
  src/static/images/2019/07_Performance/fig14.png
  src/static/images/2019/07_Performance/fig15.png
  src/static/images/2019/07_Performance/fig16.png
  src/static/images/2019/07_Performance/fig17.png
  src/static/images/2019/07_Performance/fig18.png
  src/static/images/2019/07_Performance/fig2.png
  src/static/images/2019/07_Performance/fig3.png
  src/static/images/2019/07_Performance/fig4.png
  src/static/images/2019/07_Performance/fig5.png
  src/static/images/2019/07_Performance/fig6.png
  src/static/images/2019/07_Performance/fig7.png
  src/static/images/2019/07_Performance/fig8.png
  src/templates/en/2019/chapters/performance.html
  src/templates/sitemap.xml
Labels: Writing

#385 Rick's edits for Caching chapter
  src/content/en/2019/caching.md
  src/static/images/2019/16_Caching/ch16_fig10_invalid_date_formats.jpg
  src/static/images/2019/16_Caching/ch16_fig11_vary_header.jpg
  src/static/images/2019/16_Caching/ch16_fig16_lighthouse_cache_score.jpg
  src/static/images/2019/16_Caching/ch16_fig17_lighthouse_cache_byte_savings.jpg
  src/static/images/2019/16_Caching/ch16_fig2_cache_control_expires.jpg
  src/static/images/2019/16_Caching/ch16_fig3_distribution_of_cacheable_responses.jpg
  src/static/images/2019/16_Caching/ch16_fig4_caheability_by_content_type_desktop.jpg
  src/static/images/2019/16_Caching/ch16_fig5_caheability_by_content_type_mobile.jpg
  src/static/images/2019/16_Caching/ch16_fig6_usage_of_cache_control_expires.jpg
  src/static/images/2019/16_Caching/ch16_fig7_cache_control_directives.jpg
  src/static/images/2019/16_Caching/ch16_fig9_validating_freshness.jpg
  src/static/images/2019/16_Caching/fig12.png
  src/static/images/2019/16_Caching/fig13.png
  src/static/images/2019/16_Caching/fig14.png
  src/static/images/2019/16_Caching/fig2.png
  src/static/images/2019/16_Caching/fig21.png
  src/static/images/2019/16_Caching/fig22.png
  src/static/images/2019/16_Caching/fig3.png
  src/static/images/2019/16_Caching/fig5.png
  src/static/images/2019/16_Caching/fig6.png
  src/static/images/2019/16_Caching/fig7.png
  src/static/images/2019/16_Caching/fig9.png
  src/templates/en/2019/chapters/caching.html
  src/templates/sitemap.xml
Labels: Development, Writing

#383 Copyediting Caching chapter
  src/content/en/2019/caching.md
  src/static/images/2019/16_Caching/ch16_fig10_invalid_date_formats.jpg
  src/static/images/2019/16_Caching/ch16_fig11_vary_header.jpg
  src/static/images/2019/16_Caching/ch16_fig16_lighthouse_cache_score.jpg
  src/static/images/2019/16_Caching/ch16_fig17_lighthouse_cache_byte_savings.jpg
  src/static/images/2019/16_Caching/ch16_fig2_cache_control_expires.jpg
  src/static/images/2019/16_Caching/ch16_fig3_distribution_of_cacheable_responses.jpg
  src/static/images/2019/16_Caching/ch16_fig4_caheability_by_content_type_desktop.jpg
  src/static/images/2019/16_Caching/ch16_fig5_caheability_by_content_type_mobile.jpg
  src/static/images/2019/16_Caching/ch16_fig6_usage_of_cache_control_expires.jpg
  src/static/images/2019/16_Caching/ch16_fig7_cache_control_directives.jpg
  src/static/images/2019/16_Caching/ch16_fig9_validating_freshness.jpg
  src/static/images/2019/16_Caching/fig12.png
  src/static/images/2019/16_Caching/fig13.png
  src/static/images/2019/16_Caching/fig14.png
  src/static/images/2019/16_Caching/fig2.png
  src/static/images/2019/16_Caching/fig21.png
  src/static/images/2019/16_Caching/fig22.png
  src/static/images/2019/16_Caching/fig3.png
  src/static/images/2019/16_Caching/fig5.png
  src/static/images/2019/16_Caching/fig6.png
  src/static/images/2019/16_Caching/fig7.png
  src/static/images/2019/16_Caching/fig9.png
  src/templates/en/2019/chapters/caching.html
  src/templates/sitemap.xml
Labels: Writing

#388 Compression figures
  src/content/en/2019/compression.md
  src/static/images/2019/15_Compression/ch15_fig1_compression_algorithms.jpg
  src/static/images/2019/15_Compression/fig2.png
  src/templates/en/2019/chapters/compression.html
  src/templates/sitemap.xml
Labels: Development, Writing

#391 Resource Hints edits and figures
  src/content/en/2019/resource-hints.md
  src/static/css/2019.css
  src/static/css/page.css
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/sitemap.xml
Labels: Development, Writing

#390 Randomize order of contributors
  src/main.py
Labels: Development

#397 CMS edits and data viz
  src/content/en/2019/cms.md
  src/static/images/2019/14_CMS/fig10.png
  src/static/images/2019/14_CMS/fig11.png
  src/static/images/2019/14_CMS/fig12.png
  src/static/images/2019/14_CMS/fig14.png
  src/static/images/2019/14_CMS/fig16.png
  src/static/images/2019/14_CMS/fig18.png
  src/static/images/2019/14_CMS/fig20.png
  src/static/images/2019/14_CMS/fig21.png
  src/static/images/2019/14_CMS/fig22.png
  src/static/images/2019/14_CMS/fig23.png
  src/static/images/2019/14_CMS/fig4.png
  src/static/images/2019/14_CMS/fig5.png
  src/static/images/2019/14_CMS/fig6.png
  src/static/images/2019/14_CMS/fig7.png
  src/templates/en/2019/chapters/cms.html
  src/templates/sitemap.xml
Labels: Development, Writing

#387 Table of Contents Translation
  src/templates/es/2019/table_of_contents.html
Labels: Translation

#395 Translate Performance chapter to Spanish
  src/content/es/2019/performance.md
Labels: Translation

#386 First Commit to Add Spanish Support
  src/language.py
  src/static/css/2019.css
  src/static/images/es.png
  src/templates/es/2019/base.html
  src/templates/es/2019/index.html
Labels: Translation

#392 Validate chapters URLs and add ability to have redirects for common typos
  src/validate.py
Labels: Development

#401 Fix broken links
  src/content/en/2019/ecommerce.md
  src/content/en/2019/javascript.md
  src/content/en/2019/mobile-web.md
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/mobile-web.html
Labels: Writing

#394 Improved Data Vis for HTTP/2 chapter
  src/content/en/2019/http2.md
  src/static/images/2019/20_HTTP_2/ch20_fig10_total_requests_per_page_trend_over_years.png
  src/static/images/2019/20_HTTP_2/ch20_fig13_what_push_is_used_for.png
  src/static/images/2019/20_HTTP_2/ch20_fig2_http2_usage_by_request.png
  src/static/images/2019/20_HTTP_2/ch20_fig9_num_tcp_connections_trend_over_years.png
  src/templates/en/2019/chapters/http2.html
  src/templates/sitemap.xml
Labels: Writing

#405 Ecommerce edits and data viz
  src/content/en/2019/ecommerce.md
  src/static/images/2019/13_Ecommerce/fig11.png
  src/static/images/2019/13_Ecommerce/fig12.png
  src/static/images/2019/13_Ecommerce/fig13.png
  src/static/images/2019/13_Ecommerce/fig15.png
  src/static/images/2019/13_Ecommerce/fig17.png
  src/static/images/2019/13_Ecommerce/fig18.png
  src/static/images/2019/13_Ecommerce/fig19.png
  src/static/images/2019/13_Ecommerce/fig20.png
  src/static/images/2019/13_Ecommerce/fig21.png
  src/static/images/2019/13_Ecommerce/fig22.png
  src/static/images/2019/13_Ecommerce/fig4.png
  src/static/images/2019/13_Ecommerce/fig5.png
  src/static/images/2019/13_Ecommerce/fig6.png
  src/static/images/2019/13_Ecommerce/fig7.png
  src/static/images/2019/13_Ecommerce/fig8.png
  src/templates/en/2019/chapters/ecommerce.html
Labels: Writing

#396 Editing + Visualizations for JavaScript chapter
  src/content/en/2019/javascript.md
Labels: Writing

#409 JS mobile viz
  src/content/en/2019/javascript.md
  src/static/images/2019/01_JavaScript/fig1.png
  src/static/images/2019/01_JavaScript/fig10.png
  src/static/images/2019/01_JavaScript/fig12.png
  src/static/images/2019/01_JavaScript/fig13.png
  src/static/images/2019/01_JavaScript/fig14.png
  src/static/images/2019/01_JavaScript/fig15.png
  src/static/images/2019/01_JavaScript/fig16.png
  src/static/images/2019/01_JavaScript/fig17.png
  src/static/images/2019/01_JavaScript/fig18.png
  src/static/images/2019/01_JavaScript/fig2.png
  src/static/images/2019/01_JavaScript/fig3.png
  src/static/images/2019/01_JavaScript/fig5.png
  src/static/images/2019/01_JavaScript/fig6.png
  src/static/images/2019/01_JavaScript/fig7.png
  src/static/images/2019/01_JavaScript/fig8.png
  src/static/images/2019/01_JavaScript/fig9.png
  src/templates/en/2019/chapters/javascript.html
Labels: Writing

#417 Home screen contributors style
  src/static/css/index.css
  src/static/images/2019/07_Performance/fig9.png
Labels: Development, bug

#393 Copyedit Security chapter
  sql/2019/08_Security/08_25-34.sql
  sql/2019/08_Security/08_43.sql
  src/config/2019.json
  src/content/en/2019/security.md
  src/templates/en/2019/chapters/security.html
Labels: Writing

#422 Update Meta Descriptions and Timestamps
  src/content/en/2019/accessibility.md
  src/content/en/2019/caching.md
  src/content/en/2019/cms.md
  src/content/en/2019/compression.md
  src/content/en/2019/css.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/fonts.md
  src/content/en/2019/http2.md
  src/content/en/2019/javascript.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/page-weight.md
  src/content/en/2019/performance.md
  src/content/en/2019/pwa.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/security.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/en/2019/table_of_contents.html
Labels: Development, Writing

#419 Sitemap date fix
  src/templates/base.html
  src/templates/sitemap.xml
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_sitemap.js
Labels: Development

#402 Translate Markup chapter to Spanish.
  src/content/es/2019/markup.md
Labels: Translation

#404 Fixes home page methodology spacing
  src/static/css/index.css
Labels: Development

#426 Fix typo in chapter.html preventing pages generating
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/sitemap.xml
Labels: Development

#408 Caching and compression chapters
  src/content/en/2019/caching.md
  src/content/en/2019/compression.md
  src/static/images/2019/15_Compression/fig11.png
  src/static/images/2019/15_Compression/fig12.png
  src/static/images/2019/15_Compression/fig3.png
  src/static/images/2019/15_Compression/fig4.png
  src/static/images/2019/15_Compression/fig5.png
  src/static/images/2019/15_Compression/fig6.png
  src/static/images/2019/15_Compression/fig7.png
  src/static/images/2019/15_Compression/fig8.png
  src/static/images/2019/16_Caching/ch16_fig16_cacheable_responses_set_cookie.jpg
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/compression.html
  src/templates/sitemap.xml
Labels: Writing

#410 Fix translation issues from Performance chapter in Spanish
  src/content/es/2019/performance.md
Labels: Translation

#429 Sort sitemap to prevent noisy commits
  src/templates/sitemap.xml
  src/tools/generate/generate_sitemap.js
Labels: Development

#421 Initial drop of the CDN chapter
  src/content/en/2019/cdn.md
  src/static/images/2019/17_CDN/html_cdn_usage.png
  src/static/images/2019/17_CDN/html_tls_negotiation_time.png
  src/static/images/2019/17_CDN/resource_tls_negotiation_time.png
  src/static/images/2019/17_CDN/subdomain_resource_cdn_usage.png
  src/static/images/2019/17_CDN/thirdparty_resource_cdn_usage.png
  src/static/images/2019/17_CDN/use_of_vary.png
  src/static/images/2019/17_CDN/use_of_vary_on_cdn.png
Labels: Writing

#431 Further tweaks to Meta Descriptions to keep to 160 char limit
  src/content/en/2019/cdn.md
  src/content/en/2019/css.md
  src/content/en/2019/resource-hints.md
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
Labels: Development

#424 Copyediting Fonts chapter
  src/content/en/2019/fonts.md
  src/templates/en/2019/chapters/fonts.html
Labels: Writing

#430 Editing and data viz for CDN
  src/config/2019.json
  src/content/en/2019/cdn.md
  src/content/en/2019/javascript.md
  src/static/css/page.css
  src/static/images/2019/17_CDN/fig1.png
  src/static/images/2019/17_CDN/fig11.png
  src/static/images/2019/17_CDN/fig13.png
  src/static/images/2019/17_CDN/fig15.png
  src/static/images/2019/17_CDN/fig16.png
  src/static/images/2019/17_CDN/fig17.png
  src/static/images/2019/17_CDN/fig18.png
  src/static/images/2019/17_CDN/fig19.png
  src/static/images/2019/17_CDN/fig20.png
  src/static/images/2019/17_CDN/fig22.png
  src/static/images/2019/17_CDN/fig26.png
  src/static/images/2019/17_CDN/fig27.png
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/sitemap.xml
Labels: Writing

#435 fixed treemap visualizations
  src/static/images/2019/17_CDN/html_cdn_usage.png
  src/static/images/2019/17_CDN/subdomain_resource_cdn_usage.png
  src/static/images/2019/17_CDN/thirdparty_resource_cdn_usage.png
Labels: Writing

#434 Add XML declaration to sitemap and fix whitespace issue
  src/templates/en/2019/chapters/cdn.html
  src/templates/sitemap.ejs.xml
  src/templates/sitemap.xml
Labels: Development

#438 Fix HTML validation issues. Add default favicon
  src/content/en/2019/http2.md
  src/main.py
  src/templates/en/2019/base.html
  src/templates/en/2019/chapters/http2.html
  src/templates/es/2019/base.html
Labels: Development

#440 Minor copyedits of Methodology and Foreword
  src/templates/en/2019/methodology.html
  src/templates/en/2019/table_of_contents.html
Labels: Writing

#443 Update Compression fig4 screenshot
  src/static/images/2019/15_Compression/fig4.png
Labels: Development

#444 Security edits
  src/content/en/2019/security.md
  src/templates/en/2019/chapters/security.html
Labels: Writing

#442 Third Parties edits and data viz
  src/content/en/2019/third-parties.md
  src/static/images/2019/05_Third_Parties/fig5.png
  src/templates/en/2019/chapters/third-parties.html
Labels: Development, Writing

#445 Instead of "todo" show "unedited"
  src/config/2019.json
  src/content/en/2019/fonts.md
  src/content/en/2019/media.md
  src/content/en/2019/pwa.md
  src/content/en/2019/seo.md
  src/static/css/page.css
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
Labels: Development

#447 Fix mweb data viz
  src/content/en/2019/mobile-web.md
  src/static/css/page.css
  src/static/images/2019/12_Mobile_Web/fig5.png
  src/templates/en/2019/chapters/mobile-web.html
Labels: Development

#451 Fix a11y data viz
  src/content/en/2019/accessibility.md
  src/static/images/2019/09_Accessibility/fig2.png
  src/static/images/2019/09_Accessibility/fig3.png
  src/static/images/2019/09_Accessibility/fig4.png
  src/static/images/2019/09_Accessibility/fig5.png
  src/static/images/2019/09_Accessibility/fig6.png
  src/static/images/2019/09_Accessibility/fig8.png
  src/static/images/2019/09_Accessibility/fig9.png
  src/templates/en/2019/chapters/accessibility.html
Labels: Development

#450 Meta tweaks for Twitter
  src/templates/en/2019/index.html
  src/templates/en/2019/methodology.html
  src/templates/en/2019/table_of_contents.html
Labels: Development

#455 Address 404s
  src/config/2019.json
  src/content/en/2019/fonts.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/security.md
  src/main.py
  src/static/images/apple-touch-icon-160x160.png
  src/static/images/apple-touch-icon.png
  src/templates/base.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
Labels: Development

#465 Typo edits
  src/config/2019.json
  src/config/spelling_ignore_words.txt
  src/content/en/2019/accessibility.md
  src/content/en/2019/caching.md
  src/content/en/2019/cdn.md
  src/content/en/2019/cms.md
  src/content/en/2019/compression.md
  src/content/en/2019/css.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/http2.md
  src/content/en/2019/javascript.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/page-weight.md
  src/content/en/2019/performance.md
  src/content/en/2019/security.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
Labels: Writing

#469 More robust 404 handling
  src/main.py
Labels: Development

#477 fix: markdown typo on Third Parties chapter
  src/content/en/2019/third-parties.md
Labels: Writing

#476 fix: typo on JavaScript chapter
  src/content/en/2019/javascript.md
Labels: Writing

#473 Copyedits of SEO chapter
  src/content/en/2019/seo.md
  src/templates/en/2019/chapters/seo.html
Labels: Writing

#472 Fix typo
  src/content/en/2019/compression.md
  src/templates/en/2019/chapters/compression.html
Labels: Writing

#482 Lang attribute
  src/language.py
Labels: SEO

#483 Fix 404_links
  src/config/2019.json
  src/content/en/2019/markup.md
  src/content/en/2019/security.md
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/security.html
Labels: Writing

#479 japanese translation of chapter 3 markup
  src/content/ja/2019/markup.md
Labels: Translation, Writing

#474 Hide rel="alternative" xreflang if only one language exists
  src/language.py
  src/static/images/2019/03_Markup/fig5.png
  src/templates/base.html
Labels: Development, SEO

#484 Lazy loading images iframes
  src/templates/en/2019/base.html
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/en/2019/table_of_contents.html
  src/templates/es/2019/base.html
  src/templates/es/2019/index.html
  src/templates/es/2019/table_of_contents.html
  src/templates/ja/2019/chapters/markup.html
  src/tools/generate/generate_chapters.js
  src/tools/generate/lazy_load_content.js
Labels: Development

#471 Consistent titles and subtitles
  src/static/css/2019.css
  src/static/css/index.css
  src/static/css/methodology.css
  src/static/css/page.css
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/en/2019/methodology.html
  src/templates/en/2019/table_of_contents.html
  src/templates/es/2019/index.html
  src/templates/es/2019/table_of_contents.html
Labels: Development

#485 Lazy loading the background image
  src/static/css/index.css
  src/templates/base.html
  src/templates/en/2019/index.html
Labels: Development, enhancement

#487 Update javascript.md
  src/content/en/2019/javascript.md
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/media.html
Labels: Writing

#489 Update css.md
  src/content/en/2019/css.md
  src/templates/en/2019/chapters/css.html
Labels: Writing

#437 Updated links for TLS visualizations
  src/content/en/2019/cdn.md
  src/static/images/2019/17_CDN/fig15.png
  src/static/images/2019/17_CDN/fig16.png
  src/templates/en/2019/chapters/cdn.html
Labels: Writing

#493 A few more edits to the fonts chapter
  src/content/en/2019/fonts.md
Labels: Writing

#496 Create data viz and minor edits to the SEO chapter
  src/content/en/2019/seo.md
  src/static/images/2019/10_SEO/fig1.png
  src/static/images/2019/10_SEO/fig10.png
  src/static/images/2019/10_SEO/fig2.png
  src/static/images/2019/10_SEO/fig3.png
  src/static/images/2019/10_SEO/fig5.png
  src/static/images/2019/10_SEO/fig6.png
  src/static/images/2019/10_SEO/fig7.png
  src/static/images/2019/10_SEO/fig8.png
  src/static/images/2019/10_SEO/fig9.png
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/seo.html
  src/templates/sitemap.xml
Labels: Writing

#492 Optimize performance of home page header
  src/static/css/2019.css
  src/static/css/index.css
  src/static/css/methodology.css
  src/static/images/intro-background-fit.svg
  src/templates/base.html
  src/templates/en/2019/base.html
  src/templates/en/2019/index.html
  src/templates/es/2019/base.html
  src/templates/es/2019/index.html
Labels: Development

#503 fixed markup japanese grammar
  src/content/ja/2019/markup.md
Labels: Translation

#506 Rick's media edits
  src/content/en/2019/media.md
  src/templates/en/2019/chapters/media.html
  src/templates/sitemap.xml
Labels: Writing

#504 Copyediting Media chapter
  src/content/en/2019/media.md
  src/static/images/2019/04_Media/fig10_image_format_size.png
  src/static/images/2019/04_Media/fig11_bytes_per_pixel.png
  src/static/images/2019/04_Media/fig12_percentage_optimized_images.png
  src/static/images/2019/04_Media/fig13_project_perf_improvements_image_optimization.png
  src/static/images/2019/04_Media/fig14_html_usage_of_responsive_images.png
  src/static/images/2019/04_Media/fig16_top_patterns_of_img_sizes.png
  src/static/images/2019/04_Media/fig17_usage_of_accept-ch_http_v_html.png
  src/static/images/2019/04_Media/fig18_enabled_client_hints.png
  src/static/images/2019/04_Media/fig19_lighthouse_audit_offscreen.png
  src/static/images/2019/04_Media/fig1_bytes_images_and_video_versus_other.png
  src/static/images/2019/04_Media/fig20_video_files_by_extension.png
  src/static/images/2019/04_Media/fig21_median_vidoe_file_size_by_extension.png
  src/static/images/2019/04_Media/fig22_html_video_tag_attributes_usage.png
  src/static/images/2019/04_Media/fig23_top_javascript_video_players.png
  src/static/images/2019/04_Media/fig2_total_image_bytes_per_web_page_mobile.png
  src/static/images/2019/04_Media/fig3_image_pixel_per_page_mobile_css_v_actual.png
  src/static/images/2019/04_Media/fig4_image_pixel_per_page_desktop_css_v_actual.png
  src/static/images/2019/04_Media/fig5_image_pixel_volume_v_css_pixels.png
  src/static/images/2019/04_Media/fig7_image_format_usage.png
  src/static/images/2019/04_Media/fig8_image_format_usage_per_page.png
  src/static/images/2019/04_Media/fig9_pages_using_at_least_1_image.png
  src/templates/en/2019/chapters/media.html
  src/templates/sitemap.xml
Labels: Writing

#508 Add translators meta data to chapters
  src/static/css/page.css
  src/templates/en/2019/base_chapter.html
  src/tools/generate/generate_chapters.js
Labels: Development, Translation

#502 japanese translation of chapter 7 performance
  src/content/ja/2019/performance.md
Labels: Translation

#510 Copyediting and data viz for the Fonts chapter
  src/content/en/2019/fonts.md
  src/static/images/2019/06_Fonts/fig1.png
  src/static/images/2019/06_Fonts/fig11.png
  src/static/images/2019/06_Fonts/fig12.png
  src/static/images/2019/06_Fonts/fig13.png
  src/static/images/2019/06_Fonts/fig17.png
  src/static/images/2019/06_Fonts/fig7.png
  src/static/images/2019/06_Fonts/fig8.png
  src/templates/en/2019/chapters/fonts.html
  src/templates/sitemap.xml
Labels: Writing

#514 Style fix for Home Page top of page on Safari
  src/static/css/index.css
  src/templates/en/2019/chapters/security.html
  src/templates/ja/2019/chapters/performance.html
Labels: Development

#515 Fix "Q" unit in CSS chapter
  sql/2019/02_CSS/02_07.sql
  src/content/en/2019/css.md
  src/static/images/2019/02_CSS/fig5.png
  src/templates/en/2019/chapters/css.html
  src/templates/sitemap.xml
Labels: Analysis, Writing

#516 Add translators meta data
  src/content/es/2019/performance.md
Labels: Translation

#501 Translate ecommerce chapter to Spanish
  src/content/es/2019/ecommerce.md
Labels: Translation

#491 Detect whether Google Sheets will work
  src/content/en/2019/accessibility.md
  src/content/en/2019/http2.md
  src/csp.py
  src/static/js/chapter.js
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/http2.html
  src/templates/sitemap.xml
Labels: Development

#523 Use preserveAspectRatio="none" to avoid browsers inconsistencies
  src/static/css/index.css
  src/static/images/intro-background-fit.svg
Labels: Development

#527 Misc typos and image edits
  src/content/en/2019/javascript.md
  src/content/en/2019/performance.md
  src/content/en/2019/seo.md
  src/static/images/2019/07_Performance/fig18.png
  src/static/images/2019/10_SEO/fig6.png
  src/static/images/2019/10_SEO/fig8.png
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/seo.html
  src/templates/sitemap.xml
Labels: Writing

#529 Fix CDN typos
  src/content/en/2019/cdn.md
  src/templates/en/2019/chapters/cdn.html
  src/templates/sitemap.xml
Labels: Writing

#533 Set Javascript chapter to new format and fix dates
  src/content/en/2019/javascript.md
  src/templates/en/2019/chapters/javascript.html
  src/templates/sitemap.xml
  src/tools/generate/generate_sitemap.js
Labels: Development

#537 Take Effective Connection Type into account when upgrading to interactive visuals
  src/static/js/chapter.js
  src/templates/en/2019/base_chapter.html
Labels: Development

#511 Migrate English chapter visualisations to new format
  src/content/en/2019/accessibility.md
  src/content/en/2019/caching.md
  src/content/en/2019/cdn.md
  src/content/en/2019/cms.md
  src/content/en/2019/compression.md
  src/content/en/2019/css.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/fonts.md
  src/content/en/2019/http2.md
  src/content/en/2019/javascript.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/page-weight.md
  src/content/en/2019/performance.md
  src/content/en/2019/pwa.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/security.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/content/es/2019/ecommerce.md
  src/content/es/2019/markup.md
  src/content/es/2019/performance.md
  src/content/ja/2019/markup.md
  src/static/js/chapter.js
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/sitemap.xml
  src/tools/generate/generate_last_updated.js
Labels: Development

#544 Fix misc typos in various chapters
  src/config/spelling_ignore_words.txt
  src/content/en/2019/accessibility.md
  src/content/en/2019/cdn.md
  src/content/en/2019/cms.md
  src/content/en/2019/compression.md
  src/content/en/2019/http2.md
  src/content/en/2019/markup.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/pwa.md
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/pwa.html
Labels: Writing

#543 Fix display issues with Copyright logo
  src/static/css/2019.css
  src/templates/en/2019/base.html
Labels: Development

#541 Add keyboard shortcuts for previous/next chapter #377
  src/config/2019.json
  src/templates/en/2019/base_chapter.html
Labels: Development

#536 Translate JavaScript chapter to Spanish
  src/content/es/2019/javascript.md
Labels: Translation

#547 Fix various typos and markup issues
  src/config/2019.json
  src/content/en/2019/compression.md
  src/content/en/2019/css.md
  src/content/en/2019/http2.md
  src/content/en/2019/markup.md
  src/content/en/2019/pwa.md
  src/content/en/2019/seo.md
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/seo.html
Labels: Writing

#553 Fix typo in mobile web chapter
  src/content/en/2019/mobile-web.md
Labels: Writing

#555 Fix some minor typos
  src/content/en/2019/markup.md
  src/static/images/ha-home.png
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/mobile-web.html
Labels: Writing

#554 Update 2019.json
  src/config/2019.json
Labels: Translation

#560 :pencil2: typofix 2,000 is now used instead of 2,00
  src/content/en/2019/markup.md
  src/templates/en/2019/chapters/markup.html
Labels: Writing

#562 Use the HTTP Archive logo as an SVG
  src/static/images/ha-home.svg
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
Labels: Development

#569 Localized Team Names
  src/templates/en/2019/contributors.html
Labels: Development, Translation

#551 Add ability to overwrite HTML tag (e.g. for dir="rtl" for Arabic)
  src/templates/ar/2019/base.html
  src/templates/base.html
Labels: Development, Translation

#570 Switch to hi-res images for Twitter as slightly blurred now
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
Labels: SEO

#572 Add blank translators to English chapters
  src/content/en/2019/accessibility.md
  src/content/en/2019/caching.md
  src/content/en/2019/cdn.md
  src/content/en/2019/cms.md
  src/content/en/2019/compression.md
  src/content/en/2019/css.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/fonts.md
  src/content/en/2019/http2.md
  src/content/en/2019/javascript.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/page-weight.md
  src/content/en/2019/performance.md
  src/content/en/2019/pwa.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/security.md
  src/content/en/2019/seo.md
  src/content/en/2019/third-parties.md
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
Labels: Development, Translation

#566 Handle print mode
  src/static/css/print.css
  src/static/js/chapter.js
  src/templates/base.html
  src/templates/en/2019/contributors.html
Labels: Development

#550 FR - Markup chapter
  src/content/fr/2019/markup.md
Labels: Translation

#575 Revert "FR - Markup chapter (#550)"
  src/content/fr/2019/markup.md
Labels: Translation
