Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2019-07, with the labels that each got.

#74 Added hreflang alternate tags
  src/templates/base.html
Labels: Development, SEO, Translation

#69 Language class
  src/language.py
  src/main.py
  src/static/js/language.js
  src/templates/base.html
  src/templates/en/base.html
  src/templates/ja/base.html
  src/validate.py
  src/validate_test.py
Labels: Development, Translation

#77 Build custom error pages
  src/main.py
  src/templates/base.html
  src/templates/error/400.html
  src/templates/error/404.html
  src/templates/error/500.html
  src/templates/error/502.html
  src/templates/error/error.html
  src/validate.py
Labels: Development
