Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2019-12, with the labels that each got.

#577 modified to new Data Visualization Format (japanese) #542
  src/content/ja/2019/markup.md
  src/content/ja/2019/performance.md
Labels: Translation

#576 Translated seo chapter to Japanese.
  src/content/ja/2019/seo.md
Labels: Translation

#583 Fix typo in CDN chapter
  src/content/en/2019/cdn.md
Labels: Writing

#584 FR - "’" instead of "'" (French microtypography)
  src/templates/fr/2019/base.html
  src/templates/fr/2019/chapter.html
  src/templates/fr/2019/contributors.html
  src/templates/fr/2019/index.html
Labels: Translation

#581 FR - Translations of the TOC template
  src/templates/fr/2019/table_of_contents.html
  src/templates/fr/2019/toc.html
Labels: Translation

#582 Misc editorial fixes
  src/content/en/2019/cdn.md
  src/content/en/2019/javascript.md
  src/content/en/2019/markup.md
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/ja/2019/chapters/seo.html
  src/templates/sitemap.xml
Labels: Writing

#578 FR - Translation of the methodology template
  src/templates/fr/2019/methodology.html
Labels: Translation

#588 FR - Bugfix in template
  src/templates/fr/2019/base_chapter.html
Labels: Development, Translation

#589 Add Author Website to chapter template
  src/templates/en/2019/base_chapter.html
Labels: Development

#595 FR - Third Parties Chapter
  src/content/fr/2019/third-parties.md
  src/templates/fr/2019/base.html
  src/templates/fr/2019/chapters/third-parties.html
  src/templates/fr/2019/index.html
  src/templates/fr/2019/methodology.html
  src/templates/fr/2019/table_of_contents.html
Labels: Translation

#597 Update 2019.json
  src/config/2019.json
Labels: Translation

#598 Show translators even if there is only one
  src/templates/en/2019/base_chapter.html
  src/templates/fr/2019/base_chapter.html
Labels: Development, Translation

#600 Encode Unicode bullet character in before content
  src/static/css/page.css
Labels: Design, Development

#602 Japanese Markup chapter corrections
  src/content/ja/2019/markup.md
Labels: Translation

#610 Review of Japanese Performance chapter
  src/content/ja/2019/performance.md
Labels: Translation

#611 Fix typo in en 2019 Javascript, 'cam' to 'can'
  src/content/en/2019/javascript.md
Labels: Writing

#613 Regenerate JavaScript chapter
  src/content/en/2019/javascript.md
  src/templates/en/2019/chapters/javascript.html
  src/templates/sitemap.xml
Labels: Writing

#604 Home page Hero Image fix
  src/static/css/index.css
  src/templates/ar/2019/base.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
Labels: Design, Development
