Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-01, with the labels that each got.

#612 Review of Japanese SEO chapter
  src/content/ja/2019/seo.md
Labels: Translation

#605 Responsive images for Methodology hero image - inc webp versions
  src/static/images/methodology-banner-sm.png
  src/static/images/methodology-banner-sm.webp
  src/static/images/methodology-banner.webp
  src/templates/en/2019/methodology.html
  src/templates/fr/2019/methodology.html
Labels: Design, Development

#608 Add better default caching
  src/app.yaml
  src/main.py
Labels: Development

#603 Use appropriate chapter hero images
  src/templates/en/2019/chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/templates/fr/2019/chapter.html
  src/templates/fr/2019/chapters/third-parties.html
Labels: Development

#609 Translation of Accessibility chapter to Japanese
  src/content/ja/2019/accessibility.md
Labels: Translation

#591 Translating CSS chapter to Spanish
  src/content/es/2019/css.md
Labels: Translation

#601 FR - Markup chapter
  src/content/fr/2019/markup.md
  src/templates/fr/2019/chapters/markup.html
Labels: Translation

#606 Remove flags from language menu
  src/static/images/English.png
  src/static/images/es.png
  src/templates/ar/2019/base.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
Labels: Design, Translation

#623 Making sure that the chapter generation works on windows
  src/tools/generate/generate_chapters.js
Labels: Development, bug

#620 FR - CMS chapter
  src/content/fr/2019/cms.md
  src/templates/fr/2019/chapters/cms.html
  src/templates/fr/2019/chapters/markup.html
  src/templates/ja/2019/chapters/accessibility.html
Labels: Translation

#592 Removes framework usage section
  src/content/en/2019/javascript.md
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/methodology.html
Labels: Analysis, Writing

#624 Update note on frameworks section
  src/content/en/2019/javascript.md
  src/templates/en/2019/chapters/javascript.html
Labels: Writing

#627 Ecommerce link correction
  src/content/en/2019/ecommerce.md
  src/content/es/2019/ecommerce.md
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/sitemap.xml
Labels: bug

#618 Added warning on BigQuery costs
  src/templates/en/2019/methodology.html
Labels: Analysis

#628 Correct yaml file
  src/app.yaml
Labels: bug

#607 Change to host Google Fonts locally for performance reasons
  src/static/css/2019.css
  src/static/fonts/Lato-Black-ext.woff2
  src/static/fonts/Lato-Black.woff2
  src/static/fonts/Lato-Bold-ext.woff2
  src/static/fonts/Lato-Bold.woff2
  src/static/fonts/Lato-BoldItalic-ext.woff2
  src/static/fonts/Lato-BoldItalic.woff2
  src/static/fonts/Lato-Italic-ext.woff2
  src/static/fonts/Lato-Italic.woff2
  src/static/fonts/Lato-Regular-ext.woff2
  src/static/fonts/Lato-Regular.woff2
  src/static/fonts/Poppins-Black-devanagari.woff2
  src/static/fonts/Poppins-Black-ext.woff2
  src/static/fonts/Poppins-Black.woff2
  src/static/fonts/Poppins-Bold-devanagari.woff2
  src/static/fonts/Poppins-Bold-ext.woff2
  src/static/fonts/Poppins-Bold.woff2
  src/static/fonts/Poppins-Light-devanagari.woff2
  src/static/fonts/Poppins-Light-ext.woff2
  src/static/fonts/Poppins-Light.woff2
  src/static/fonts/Poppins-Regular-devanagari.woff2
  src/static/fonts/Poppins-Regular-ext.woff2
  src/static/fonts/Poppins-Regular.woff2
  src/templates/ar/2019/base.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
Labels: Development

#631 Fix fonts 404ing
  src/app.yaml
Labels: bug

#633 FR - Adding missing translations in Methodology (fix #626)
  src/templates/fr/2019/methodology.html
Labels: Translation

#636 Add a "Join the team" card
  src/templates/en/2019/contributors.html
Labels: Development, enhancement

#637 Fix blank "Translated By" lines
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/fonts.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/performance.html
  src/templates/en/2019/chapters/pwa.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/en/2019/chapters/third-parties.html
  src/tools/generate/shared.js
Labels: bug

#642 Only compress images if including images in PR
  .github/workflows/calibreapp-image-action.yml
Labels: Development, enhancement

#641 Correct error where wrong date is used in sitemap for non-chapters
  src/tools/generate/generate_sitemap.js
Labels: Development, bug

#644 Fix misc errors and inconsistencies
  src/content/en/2019/cdn.md
  src/csp.py
  src/templates/ar/2019/base.html
  src/templates/en/2019/base.html
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/contributors.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/fr/2019/base_chapter.html
  src/templates/fr/2019/contributors.html
Labels: Development, bug

#643 Translation of Cdn chapter to Japanese
  src/content/ja/2019/cdn.md
Labels: Translation

#647 FR - Improvement wording
  src/templates/fr/2019/chapter.html
  src/templates/fr/2019/chapters/cms.html
  src/templates/fr/2019/chapters/markup.html
  src/templates/fr/2019/chapters/third-parties.html
Labels: Translation

#649 Fix typo in resource hints chapter
  src/content/en/2019/resource-hints.md
  src/templates/en/2019/chapters/resource-hints.html
Labels: Writing

#650 Resource Hints - Duplication Fix
  src/content/en/2019/resource-hints.md
Labels: Writing

#651 Missing end of code snippet
  src/content/en/2019/resource-hints.md
Labels: Writing

#655 FR - toc - space before ":"
  src/templates/fr/2019/table_of_contents.html
Labels: Translation

#652 FR - Translation "Resource Hints" Chapter
  src/content/fr/2019/resource-hints.md
  src/templates/fr/2019/chapters/resource-hints.html
  src/templates/fr/2019/table_of_contents.html
Labels: Translation

#658 FR - Resource Hints - Missing translation
  src/content/fr/2019/resource-hints.md
  src/templates/fr/2019/chapters/resource-hints.html
Labels: Translation
