Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-09, with the labels that each got.

#1259 SQL utilities for the BigQuery dataset
  sql/lib/css-parser.js
  sql/util/README.md
  sql/util/parsed_css.sql
  sql/util/parsed_css_inline.sql
  sql/util/summary_requests.sql
  sql/util/summary_response_bodies.sql
  sql/util/third_parties.sql
Labels: analysis, project management

#1256 Voiceover percentiles for English chapters
  src/content/en/2019/cdn.md
  src/content/en/2019/javascript.md
  src/content/en/2019/media.md
Labels: accessibility, writing

#1262 Fix empty image formats
  sql/util/README.md
  sql/util/requests.sql
Labels: analysis

#1266 Stop having comma for two person lists
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/base_ebook.html
  src/templates/base/2019/ebook.ejs.html
Labels: bug, development

#1271 GitHub Action to test generated template changes
  .github/workflows/test-template-changes.yml
  src/package.json
  src/tools/scripts/test_template_changes.sh
Labels: development

#1265 Avoid using p10 - p90 in Japanese chapters for accessibility reasons
  src/content/ja/2019/cdn.md
  src/content/ja/2019/javascript.md
  src/content/ja/2019/media.md
Labels: accessibility, translation

#1264 Avoid using p10 - p90 in Spanish chapters for accessibility reasons
  src/content/es/2019/javascript.md
  src/content/es/2019/media.md
Labels: accessibility, translation

#1275 Fix version numbering deploy script
  src/tools/scripts/deploy.sh
Labels: development

#1276 Lint all files on Super Linter upgrade
  .github/workflows/linter.yml
Labels: development

#1277 Few small perf fixes for home page
  src/static/css/2019.css
  src/static/images/2019/css/hero_lg.webp
  src/static/images/2019/css/hero_sm.webp
  src/static/images/2019/markup/hero_lg.webp
  src/static/images/2019/markup/hero_sm.webp
  src/static/images/2019/page-weight/hero_lg.webp
  src/static/images/2019/page-weight/hero_sm.webp
  src/static/images/2019/seo/hero_sm.webp
  src/static/images/character-star.png
  src/templates/base/2019/index.html
  src/templates/base/2020/index.html
Labels: performance

#1087 CMS 2020 queries
  sql/2020/15_CMS/README.md
  sql/2020/15_CMS/adoption_of_image_formats_in_cmss.sql
  sql/2020/15_CMS/cms_adoption_compared_to_2019.sql
  sql/2020/15_CMS/core_web_vitals_distribution.sql
  sql/2020/15_CMS/core_web_vitals_passing.sql
  sql/2020/15_CMS/distribution_of_cms_page_kilobytes_per_resource_type.sql
  sql/2020/15_CMS/distribution_of_page_weight_requests_and_co2_grams_per_cms_web_page.sql
  sql/2020/15_CMS/image_bytes_on_cmss.sql
  sql/2020/15_CMS/median_lighthouse_score.sql
  sql/2020/15_CMS/third_party_bytes_and_requests_on_cmss.sql
  sql/2020/15_CMS/top_cms_platforms_compared_to_2019.sql
  sql/2020/15_CMS/top_cmss_yoy_all_clients.sql
Labels: analysis

#1285 Update requests.sql
  sql/util/requests.sql
Labels: analysis

#1286 Update summary_response_bodies.sql
  sql/util/summary_response_bodies.sql
Labels: analysis

#1287 Workaround linting error
  .github/workflows/test_website.yml
Labels: bug

#1289 PWA candidates SQL
  sql/util/README.md
  sql/util/pwa_candidates.sql
Labels: analysis

#1291 PWA table utils
  sql/util/README.md
  sql/util/manifests.sql
  sql/util/pwa_candidates.sql
  sql/util/service_workers.sql
Labels: analysis

#1214 Dropdown styles for language and year switcher
  src/static/css/2019.css
  src/templates/base/2019/base.html
Labels: development

#1292 Upgrade to Python 3.8
  .github/workflows/generate_chapters.yml
  .github/workflows/generate_ebooks.yml
  .github/workflows/python-tests.yml
  .github/workflows/test_website.yml
  src/app.yaml
Labels: development

#1296 Compress Images on pushes to main and at other times
  .github/workflows/calibreapp-image-action.yml
Labels: development, performance

#1137 Markup 2020 queries
  sql/2020/03_Markup/README.md
  sql/2020/03_Markup/pages_almanac_by_device.sql
  sql/2020/03_Markup/pages_almanac_by_device_and_attribute_name_frequency.sql
  sql/2020/03_Markup/pages_almanac_by_device_and_attribute_name_present.sql
  sql/2020/03_Markup/pages_almanac_by_device_and_data_attribute_name_frequency.sql
  sql/2020/03_Markup/pages_almanac_by_device_and_favicon_image_type.sql
  sql/2020/03_Markup/pages_almanac_by_device_and_html_lang.sql
  sql/2020/03_Markup/pages_almanac_by_device_and_percentile.sql
  sql/2020/03_Markup/pages_element_count_by_device.sql
  sql/2020/03_Markup/pages_element_count_by_device_and_custom_dash_elements.sql
  sql/2020/03_Markup/pages_element_count_by_device_and_element_type_frequency.sql
  sql/2020/03_Markup/pages_element_count_by_device_and_element_type_present.sql
  sql/2020/03_Markup/pages_element_count_by_device_and_obsolete_elements.sql
  sql/2020/03_Markup/pages_element_count_by_device_and_percentile.sql
  sql/2020/03_Markup/pages_markup_by_device.sql
  sql/2020/03_Markup/pages_markup_by_device_and_button_types.sql
  sql/2020/03_Markup/pages_markup_by_device_and_percentile.sql
  sql/2020/03_Markup/pages_wpt_bodies_by_device.sql
  sql/2020/03_Markup/pages_wpt_bodies_by_device_and_percentile.sql
  sql/2020/03_Markup/pages_wpt_bodies_by_device_and_percentile_and_heading_level.sql
  sql/2020/03_Markup/pages_wpt_bodies_by_device_and_protocol.sql
  sql/2020/03_Markup/summary_pages_by_device.sql
  sql/2020/03_Markup/summary_pages_by_device_and_doctype.sql
  sql/2020/03_Markup/summary_pages_by_device_and_percentile.sql
  sql/2020/03_Markup/summary_pages_by_device_and_viewport.sql
Labels: analysis

#1301 Add DISTINCT to ServiceWorker queries
  sql/util/manifests.sql
  sql/util/pwa_candidates.sql
  sql/util/service_workers.sql
Labels: analysis

#1302 Fixes made as the data was being gathered.
  sql/2020/03_Markup/pages_almanac_by_device_and_attribute_name_frequency.sql
  sql/2020/03_Markup/pages_almanac_by_device_and_data_attribute_name_frequency.sql
  sql/2020/03_Markup/pages_almanac_by_device_and_favicon_image_type.sql
  sql/2020/03_Markup/pages_almanac_by_device_and_html_lang.sql
  sql/2020/03_Markup/pages_element_count_by_device_and_element_type_frequency.sql
  sql/2020/03_Markup/pages_markup_by_device_and_button_types.sql
  sql/2020/03_Markup/pages_wpt_bodies_by_device_and_percentile.sql
  sql/2020/03_Markup/pages_wpt_bodies_by_device_and_protocol.sql
Labels: analysis

#1305 Fix image compress action
  .github/workflows/calibreapp-image-action.yml
Labels: development

#1306 Fix image compress action take 2
  .github/workflows/compress-images.yml
Labels: development

#1308 Figure reference corrections
  src/content/en/2019/accessibility.md
  src/content/en/2019/caching.md
  src/content/en/2019/cms.md
  src/content/en/2019/compression.md
  src/content/en/2019/css.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/fonts.md
  src/content/en/2019/http2.md
  src/content/en/2019/javascript.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/performance.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/security.md
  src/content/es/2019/css.md
  src/content/es/2019/ecommerce.md
  src/content/es/2019/fonts.md
  src/content/es/2019/javascript.md
  src/content/es/2019/markup.md
  src/content/es/2019/media.md
  src/content/es/2019/performance.md
  src/content/fr/2019/accessibility.md
  src/content/fr/2019/caching.md
  src/content/fr/2019/cms.md
  src/content/fr/2019/compression.md
  src/content/fr/2019/javascript.md
  src/content/fr/2019/markup.md
  src/content/fr/2019/mobile-web.md
  src/content/fr/2019/resource-hints.md
  src/content/ja/2019/accessibility.md
  src/content/ja/2019/caching.md
  src/content/ja/2019/cms.md
  src/content/ja/2019/compression.md
  src/content/ja/2019/css.md
  src/content/ja/2019/ecommerce.md
  src/content/ja/2019/fonts.md
  src/content/ja/2019/http2.md
  src/content/ja/2019/javascript.md
  src/content/ja/2019/markup.md
  src/content/ja/2019/media.md
  src/content/ja/2019/mobile-web.md
  src/content/ja/2019/performance.md
  src/content/ja/2019/resource-hints.md
  src/content/ja/2019/security.md
  src/content/zh-CN/2019/accessibility.md
  src/content/zh-CN/2019/performance.md
  src/tools/generate/generate_ebooks.js
  src/tools/generate/generate_figure_ids.js
Labels: bug

#1310 Translate JavaScript chapter to Portuguese
  src/content/pt/2019/javascript.md
Labels: translation

#1312 Add HakaCode to the 2019 team
  src/config/2019.json
Labels: translation

#1098 HTTP/2 2020 queries
  sql/2020/22_HTTP_2/adoption_of_http_2_by_site_and_requests.sql
  sql/2020/22_HTTP_2/count_of_h2_and_h3_sites_grouped_by_server.sql
  sql/2020/22_HTTP_2/count_of_h2_and_h3_sites_using_push.sql
  sql/2020/22_HTTP_2/count_of_non_h2_and_h3_sites_grouped_by_server.sql
  sql/2020/22_HTTP_2/count_of_preload_http_headers_with_nopush_attribute_set.sql
  sql/2020/22_HTTP_2/detailed_alt_svc_headers.sql
  sql/2020/22_HTTP_2/detailed_upgrade_headers.sql
  sql/2020/22_HTTP_2/measure_number_of_tcp_connections_per_site.sql
  sql/2020/22_HTTP_2/measure_of_all_http_versions_for_main_page_of_all_sites.sql
  sql/2020/22_HTTP_2/number_of_h2_and h3_pushed_resources_and_bytes_transferred.sql
  sql/2020/22_HTTP_2/number_of_h2_and_h3_pushed_resources_and_bytes_by_content_type.sql
  sql/2020/22_HTTP_2/number_of_http_requests_returning_upgrade_http_header_containing_h2.sql
  sql/2020/22_HTTP_2/number_of_https_requests_not_using_h2_or_h3_returning_upgrade_http_upgrade_header_containing_h2.sql
  sql/2020/22_HTTP_2/number_of_https_requests_using_h2_returning_upgrade_http_header_containing_h2.sql
  sql/2020/22_HTTP_2/percentage_of_h2_and_h3_sites_affected_by_cdn_prioritization.sql
  sql/2020/22_HTTP_2/percentage_of_resources_loaded_over_HTTP_by_version_per_site.sql
  sql/2020/22_HTTP_2/tls_adoption_by_http_version.sql
Labels: analysis

#1062 SEO 2020 queries
  sql/2020/07_SEO/README.md
  sql/2020/07_SEO/lighthouse.sql
  sql/2020/07_SEO/pages_almanac_video_by_device.sql
  sql/2020/07_SEO/pages_almanac_video_by_device_and_percentile.sql
  sql/2020/07_SEO/pages_markup_by_device.sql
  sql/2020/07_SEO/pages_markup_by_device_and_img_loading.sql
  sql/2020/07_SEO/pages_markup_by_device_and_percentile.sql
  sql/2020/07_SEO/pages_robots_txt_by_device_and_status.sql
  sql/2020/07_SEO/pages_robots_txt_by_device_and_useragent.sql
  sql/2020/07_SEO/pages_wpt_bodies_by_device.sql
  sql/2020/07_SEO/pages_wpt_bodies_by_device_and_number_rel_attribute.sql
  sql/2020/07_SEO/pages_wpt_bodies_by_device_and_percentile.sql
  sql/2020/07_SEO/pages_wpt_bodies_hreflang_by_device_and_http_header_value.sql
  sql/2020/07_SEO/pages_wpt_bodies_hreflang_by_device_and_link_tag_value.sql
  sql/2020/07_SEO/pages_wpt_bodies_structured_data_by_device_and_format.sql
  sql/2020/07_SEO/pages_wpt_bodies_structured_data_by_device_and_type.sql
Labels: analysis

#1314 Turn on Portuguese
  src/config/2019.json
  src/config/2020.json
  src/templates/pt/2019/featured_chapters.html
Labels: translation

#1316 Add plaintext alt attributes where necessary
  src/content/en/2019/caching.md
  src/content/en/2019/cdn.md
  src/content/en/2019/fonts.md
  src/content/en/2019/javascript.md
  src/content/en/2019/media.md
  src/content/en/2019/seo.md
  src/content/es/2019/fonts.md
  src/content/es/2019/javascript.md
  src/content/es/2019/media.md
  src/content/fr/2019/caching.md
  src/content/fr/2019/javascript.md
  src/content/ja/2019/caching.md
  src/content/ja/2019/cdn.md
  src/content/ja/2019/fonts.md
  src/content/ja/2019/javascript.md
  src/content/ja/2019/media.md
  src/content/pt/2019/javascript.md
Labels: writing

#1319 Translate featured_chapters to Portuguese
  src/templates/pt/2019/featured_chapters.html
Labels: translation

#1320 Update Portuguese Language to README
  README.md
Labels: translation

#1322 Move voltek62 from Author to Reviewer
  src/config/2019.json
Labels: writing

#1321 Add command line options and GitHub CLI to release script
  src/tools/scripts/deploy.sh
Labels: development

#1323 Correct Portuguese name
  src/server/language.py
Labels: translation

#1324 Remove GitHuc CLI from Release Script
  src/tools/scripts/deploy.sh
Labels: development

#1283 PWA 2020 queries
  sql/2020/14_PWA/README.md
  sql/2020/14_PWA/beforeinstallprompt_usage.sql
  sql/2020/14_PWA/dist_sw_payload_sizes.sql
  sql/2020/14_PWA/lighthouse_pwa_audits.sql
  sql/2020/14_PWA/lighthouse_pwa_score.sql
  sql/2020/14_PWA/manifests_and_service_workers.sql
  sql/2020/14_PWA/manifests_not_json_parsable.sql
  sql/2020/14_PWA/manifests_not_json_parsable_sw.sql
  sql/2020/14_PWA/manifests_preferring_native_apps.sql
  sql/2020/14_PWA/manifests_preferring_native_apps_sw.sql
  sql/2020/14_PWA/popular_pwa_libraries.sql
  sql/2020/14_PWA/popular_pwa_libraries_helper.sql
  sql/2020/14_PWA/pwa_blink_usage.sql
  sql/2020/14_PWA/sw_adoption_over_time.sql
  sql/2020/14_PWA/sw_events.sql
  sql/2020/14_PWA/top_manifest_categories.sql
  sql/2020/14_PWA/top_manifest_categories_sw.sql
  sql/2020/14_PWA/top_manifest_display_values.sql
  sql/2020/14_PWA/top_manifest_display_values_sw.sql
  sql/2020/14_PWA/top_manifest_icon_sizes.sql
  sql/2020/14_PWA/top_manifest_icon_sizes_sw.sql
  sql/2020/14_PWA/top_manifest_orientations.sql
  sql/2020/14_PWA/top_manifest_orientations_sw.sql
  sql/2020/14_PWA/top_manifest_properties.sql
  sql/2020/14_PWA/top_manifest_properties_sw.sql
  sql/2020/14_PWA/workbox_package_methods.sql
  sql/2020/14_PWA/workbox_usage.sql
Labels: analysis

#1328 Switch LH weighting to AVG
  sql/2020/14_PWA/lighthouse_pwa_audits.sql
Labels: analysis

#1090 Resource Hints 2020 queries
  sql/2020/21_Resource_Hints/README.md
  sql/2020/21_Resource_Hints/adoption.sql
  sql/2020/21_Resource_Hints/adoption_service_workers.sql
  sql/2020/21_Resource_Hints/attribute_usage.sql
  sql/2020/21_Resource_Hints/guess_js.sql
  sql/2020/21_Resource_Hints/h2_preload_nopush.sql
  sql/2020/21_Resource_Hints/h2_push.sql
  sql/2020/21_Resource_Hints/hints_by_type.sql
  sql/2020/21_Resource_Hints/hints_per_page.sql
  sql/2020/21_Resource_Hints/lighthouse_offscreen_images.sql
  sql/2020/21_Resource_Hints/lighthouse_preconnect.sql
  sql/2020/21_Resource_Hints/lighthouse_preconnect_warnings.sql
  sql/2020/21_Resource_Hints/lighthouse_preload.sql
  sql/2020/21_Resource_Hints/lighthouse_preload_warnings.sql
  sql/2020/21_Resource_Hints/native_lazy_loading.sql
  sql/2020/21_Resource_Hints/native_lazy_loading_attrs.sql
  sql/2020/21_Resource_Hints/preconnect_and_dnsprefetch.sql
  sql/2020/21_Resource_Hints/priority_hints.sql
  sql/2020/21_Resource_Hints/priority_hints_by_element.sql
  sql/2020/21_Resource_Hints/priority_hints_by_element_and_importance.sql
  sql/2020/21_Resource_Hints/priority_hints_by_importance.sql
Labels: analysis

#1330 Better median weight for PWA LH query
  sql/2020/14_PWA/lighthouse_pwa_audits.sql
Labels: analysis

#1331 Fixes as I gathered the real data
  sql/2020/07_SEO/pages_almanac_video_by_device.sql
  sql/2020/07_SEO/pages_almanac_video_by_device_and_percentile.sql
  sql/2020/07_SEO/pages_markup_by_device.sql
  sql/2020/07_SEO/pages_markup_by_device_and_img_loading.sql
  sql/2020/07_SEO/pages_markup_by_device_and_percentile.sql
  sql/2020/07_SEO/pages_robots_txt_by_device_and_status.sql
  sql/2020/07_SEO/pages_robots_txt_by_device_and_useragent.sql
  sql/2020/07_SEO/pages_wpt_bodies_hreflang_by_device_and_http_header_value.sql
  sql/2020/07_SEO/pages_wpt_bodies_hreflang_by_device_and_link_tag_value.sql
  sql/2020/07_SEO/pages_wpt_bodies_structured_data_by_device_and_format.sql
  sql/2020/07_SEO/pages_wpt_bodies_structured_data_by_device_and_type.sql
Labels: analysis

#1281 CSS 2020 queries
  sql/2020/01_CSS/README.md
  sql/2020/01_CSS/box_sizing.sql
  sql/2020/01_CSS/css_in_js.sql
  sql/2020/01_CSS/custom_property_names.sql
  sql/2020/01_CSS/custom_property_values.sql
  sql/2020/01_CSS/selector_parts_freq_per_page.sql
  sql/2020/01_CSS/selectors.sql
  sql/2020/01_CSS/sourcemap_adoption.sql
  sql/2020/01_CSS/sourcemap_preprocessors.sql
  sql/2020/01_CSS/specificity.sql
  sql/2020/01_CSS/specificity_hacks.sql
  sql/2020/01_CSS/stylesheet_count.sql
  sql/2020/01_CSS/stylesheet_kbytes.sql
  sql/2020/01_CSS/top_selector_attributes.sql
  sql/2020/01_CSS/top_selector_classes.sql
  sql/2020/01_CSS/top_selector_ids.sql
  sql/2020/01_CSS/top_selector_pseudo_classes.sql
  sql/2020/01_CSS/top_selector_pseudo_elements.sql
  sql/lib/css-utils.js
  sql/lib/gcs_copy.sh
  sql/lib/get-css-utils.js
Labels: analysis
