Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-06, with the labels that each got.

#868 Accessibility statement improvements
  src/static/css/2019.css
  src/templates/base/2019/accessibility_statement.html
  src/templates/en/2019/accessibility_statement.html
  src/templates/ja/2019/accessibility_statement.html
Labels: accessibility, translation

#870 Formatting changes to ToC page
  src/config/2019.json
  src/main.py
  src/static/css/page.css
  src/templates/ar/2019/base.html
  src/templates/base/2019/contributors.html
  src/templates/base/2019/table_of_contents.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
Labels: design, development

#867 Move generate script language and year config to JSON
  src/README.md
  src/config.py
  src/config/2019.json
  src/package.json
  src/templates/en/2019/ebook.html
  src/templates/ja/2019/ebook.html
  src/templates/sitemap.xml
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_ebook_pdfs.js
  src/tools/generate/generate_ebooks.js
  src/tools/generate/generate_last_updated.js
  src/tools/generate/generate_sitemap.js
  src/tools/generate/shared.js
Labels: development

#872 Fix colour on Language selector as causing Firefox issue
  src/static/css/2019.css
  src/templates/base/2019/base.html
Labels: accessibility, bug

#888 Add noindex meta tag for on-canonical URLs
  src/templates/base.html
Labels: SEO

#890 Tidy up breadcrumbs for multi-year support
  src/templates/ar/2019/base.html
  src/templates/base/2019/accessibility_statement.html
  src/templates/base/2019/base.html
  src/templates/base/2019/index.html
  src/templates/en/2019/accessibility_statement.html
  src/templates/en/2019/base.html
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/base_ebook.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/en/2019/methodology.html
  src/templates/en/2019/table_of_contents.html
  src/templates/es/2019/base.html
  src/templates/es/2019/base_chapter.html
  src/templates/es/2019/contributors.html
  src/templates/es/2019/index.html
  src/templates/es/2019/table_of_contents.html
  src/templates/fr/2019/base.html
  src/templates/fr/2019/base_chapter.html
  src/templates/fr/2019/contributors.html
  src/templates/fr/2019/index.html
  src/templates/fr/2019/methodology.html
  src/templates/fr/2019/table_of_contents.html
  src/templates/ja/2019/accessibility_statement.html
  src/templates/ja/2019/base.html
  src/templates/ja/2019/base_chapter.html
  src/templates/ja/2019/base_ebook.html
  src/templates/ja/2019/contributors.html
  src/templates/ja/2019/index.html
  src/templates/ja/2019/methodology.html
  src/templates/ja/2019/table_of_contents.html
Labels: SEO

#893 2020 year support and basic 2020 landing page
  src/config/2020.json
  src/main.py
  src/static/css/2019.css
  src/static/css/index.css
  src/static/images/home-hero-2020.png
  src/templates/ar/2019/base.html
  src/templates/base.html
  src/templates/base/2019/accessibility_statement.html
  src/templates/base/2019/base.html
  src/templates/base/2019/index.html
  src/templates/base/2020/index.html
  src/templates/en/2019/base.html
  src/templates/en/2019/error.html
  src/templates/en/2020/index.html
  src/templates/es/2019/base.html
  src/templates/es/2019/error.html
  src/templates/es/2020/index.html
  src/templates/fr/2019/base.html
  src/templates/fr/2019/error.html
  src/templates/fr/2020/index.html
  src/templates/ja/2019/base.html
  src/templates/ja/2019/error.html
  src/templates/ja/2020/index.html
Labels: development

#928 Sort contributors
  src/config/2019.json
Labels: development

#930 CSS logo
  src/static/css/2019.css
  src/static/css/index.css
  src/templates/ar/2019/base.html
  src/templates/base/2019/base.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
Labels: development

#931 Fix index font zoom
  src/content/en/2020/README.md
  src/static/css/2019.css
  src/static/css/page.css
Labels: bug

#936 Windows ebook generation
  src/tools/generate/generate_ebook_pdfs.js
Labels: bug, development

#932 Allow the development server to be backgrounded with optional command line argument
  src/main.py
Labels: development

#939 GitHub linter
  .github/linters/.markdown-lint.yml
  .github/linters/.python-lint
  .github/linters/.stylelintrc.json
  .github/workflows/calibreapp-image-action.yml
  .github/workflows/generate_chapters.yml
  .github/workflows/linter.yml
  sql/2020/README.md
  src/README.md
  src/content/en/2019/caching.md
  src/content/en/2019/compression.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/javascript.md
  src/content/en/2019/markup.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/security.md
  src/content/es/2019/javascript.md
  src/content/es/2019/performance.md
  src/content/fr/2019/accessibility.md
  src/content/fr/2019/caching.md
  src/content/fr/2019/resource-hints.md
  src/content/ja/2019/caching.md
  src/content/ja/2019/compression.md
  src/content/ja/2019/ecommerce.md
  src/content/ja/2019/fonts.md
  src/content/ja/2019/javascript.md
  src/content/ja/2019/resource-hints.md
  src/content/ja/2019/security.md
  src/static/css/2019.css
  src/static/css/ebook.css
  src/static/css/index.css
  src/static/css/normalize.css
  src/static/css/page.css
  src/static/css/print.css
  src/static/css/splash.css
Labels: development

#941 Fixed typo in js featured snippet
  src/static/css/2019.css
  src/templates/en/2019/featured_chapters.html
  src/templates/es/2019/featured_chapters.html
  src/templates/fr/2019/featured_chapters.html
Labels: bug, development
