Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-03, with the labels that each got.

#669 Translation of caching chapter to French
  src/config/2019.json
  src/content/fr/2019/caching.md
  src/templates/fr/2019/chapters/caching.html
Labels: Translation

#679 Translation of Caching chapter to French
  src/content/fr/2019/caching.md
Labels: Translation

#672 Translation of Caching chapter to Japanese
  src/content/ja/2019/caching.md
Labels: Translation

#675 Translation of PWA chapter to Japanese
  src/content/ja/2019/pwa.md
Labels: Translation

#677 Translation of CSS chapter to Japanese
  src/content/ja/2019/css.md
Labels: Translation

#680 Fix typo
  src/content/en/2019/caching.md
Labels: Writing

#684 Support translations
  src/config/2019.json
  src/main.py
  src/static/css/2019.css
  src/templates/base/2019/base.html
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/table_of_contents.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
  src/templates/ja/2019/base_chapter.html
  src/templates/ja/2019/contributors.html
  src/templates/ja/2019/methodology.html
  src/templates/ja/2019/table_of_contents.html
Labels: Development, Translation

#682 Translation of page-weight chapter to Japanese
  src/content/ja/2019/page-weight.md
Labels: Translation

#687 Base chapter translations to Spanish
  src/templates/es/2019/base.html
  src/templates/es/2019/base_chapter.html
Labels: Translation

#688 Enable first translations boris review
  src/templates/base/2019/contributors.html
  src/templates/base/2019/methodology.html
  src/templates/fr/2019/index.html
Labels: Translation

#689 Improve language selector
  src/static/css/2019.css
Labels: Design

#685 Enable first translations (French and Spanish)
  src/content/fr/2019/third-parties.md
  src/static/css/2019.css
  src/templates/base/2019/base.html
  src/templates/base/2019/contributors.html
  src/templates/base/2019/index.html
  src/templates/base/2019/methodology.html
  src/templates/en/2019/contributors.html
  src/templates/en/2019/index.html
  src/templates/es/2019/index.html
  src/templates/fr/2019/chapters/third-parties.html
  src/templates/fr/2019/contributors.html
  src/templates/fr/2019/index.html
  src/templates/sitemap.xml
  src/tools/generate/generate_chapters.js
  src/validate.py
Labels: Translation

#692 Translation bug fixes
  src/static/css/2019.css
  src/templates/base/2019/base.html
Labels: Translation

#693 Lang selector fix
  src/static/css/2019.css
  src/templates/base/2019/base.html
Labels: Translation

#694 HTTP/2 fixes
  src/content/en/2019/http2.md
  src/content/ja/2019/http2.md
  src/templates/en/2019/chapters/http2.html
  src/templates/ja/2019/chapters/http2.html
  src/templates/ja/2019/featured_chapters.html
Labels: Translation, bug

#695 Better header and footer on tablet
  src/static/css/2019.css
Labels: Translation

#696 Footer mobile fix
  src/static/css/2019.css
Labels: bug

#697 Fix for no lang
  src/main.py
Labels: Development, bug

#699 Fix sitemap
  src/templates/sitemap.xml
  src/tools/generate/generate_sitemap.js
Labels: Development, bug

#700 Add fallbacks for browsers which don't support content alt text
  src/static/css/2019.css
  src/static/css/page.css
Labels: Accessibility, bug

#701 Language picker accessibility
  src/static/css/2019.css
  src/templates/base/2019/base.html
  src/templates/en/2019/base.html
  src/templates/en/2019/featured_chapters.html
  src/templates/es/2019/base.html
  src/templates/es/2019/featured_chapters.html
  src/templates/fr/2019/base.html
  src/templates/fr/2019/featured_chapters.html
  src/templates/ja/2019/base.html
  src/templates/ja/2019/featured_chapters.html
Labels: Accessibility, Translation

#702 Author bio translations
  src/config/2019.json
  src/templates/ar/2019/base.html
  src/templates/base/2019/base_chapter.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
Labels: Translation

#703 Escape nico3333fr's website properly
  src/config/2019.json
Labels: Translation, bug

#706 Translation of compression chapter to Japanese
  src/content/ja/2019/caching.md
  src/content/ja/2019/compression.md
Labels: Translation

#707 Translation of third-parties chapter to Japanese
  src/content/ja/2019/third-parties.md
Labels: Translation

#708 Update Japanese names of translated chapters
  src/templates/ja/2019/base.html
Labels: Translation
