Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-05, with the labels that each got.

#764 Media japanese translation
  src/content/en/2019/media.md
  src/content/ja/2019/media.md
  src/templates/ja/2019/featured_chapters.html
Labels: translation

#770 Featured chapters methodology japanese translation
  src/templates/ja/2019/featured_chapters.html
  src/templates/ja/2019/methodology.html
Labels: translation

#771 Stop overriding username as think that is breaking the action
  .github/workflows/generate_chapters.yml
Labels: bug, development

#772 Update date on ja Methodology as a test
  src/templates/ja/2019/methodology.html
Labels: bug

#773 Generate chapters action fix
  .github/workflows/generate_chapters.yml
Labels: bug

#775 Gen chaps
  src/templates/ja/2019/index.html
Labels: bug

#776 Contributors table accessibility japanese translation
  src/config/2019.json
  src/templates/ja/2019/accessibility_statement.html
  src/templates/ja/2019/contributors.html
  src/templates/ja/2019/table_of_contents.html
Labels: translation

#777 Generate chapters
  src/templates/sitemap.xml
Labels: translation

#785 Translation of javascript chapter to Japanese
  src/content/ja/2019/javascript.md
  src/templates/ja/2019/featured_chapters.html
Labels: translation

#786 Add support for the old grid spec for IE
  src/static/css/index.css
  src/static/css/page.css
  src/templates/base/2019/contributors.html
Labels: design, development

#783 Generate chapters action fix
  .github/workflows/generate_chapters.yml
Labels: development

#779 Don't cache redirects and errors
  src/main.py
Labels: development

#787 Update HTTP/3 links
  src/content/en/2019/http2.md
  src/content/ja/2019/http2.md
Labels: writing

#789 Update labels and projects on chapter gen GitHub action
  .github/workflows/generate_chapters.yml
Labels: development

#790 Fix bad Japanese links
  src/content/ja/2019/cms.md
  src/content/ja/2019/ecommerce.md
  src/content/ja/2019/mobile-web.md
  src/content/ja/2019/resource-hints.md
Labels: translation

#792 Fix GitHub Action labels and projets
  .github/workflows/generate_chapters.yml
Labels: development

#793 Generate Chapters Action fix
  .github/workflows/generate_chapters.yml
Labels: bug

#794 Fix bad link in French Third-parties chapter
  src/content/fr/2019/third-parties.md
Labels: bug, writing

#781 SVG icons system #740
  src/static/css/2019.css
  src/static/css/index.css
  src/static/css/page.css
  src/static/images/blog.png
  src/static/images/close.png
  src/static/images/discuss.png
  src/static/images/dropdown-arrow.png
  src/static/images/github.png
  src/static/images/ha-home.png
  src/static/images/ha-home.svg
  src/static/images/menu.png
  src/static/images/queries.png
  src/static/images/rectangles.png
  src/static/images/results.png
  src/static/images/twitter.png
  src/templates/base.html
  src/templates/base/2019/base.html
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/contributors.html
Labels: development, performance

#800 Bump CSS version numbers
  src/templates/base/2019/accessibility_statement.html
  src/templates/base/2019/base.html
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/index.html
  src/templates/base/2019/methodology.html
Labels: development

#805 Remove project from chapter generate GitHub action
  .github/workflows/generate_chapters.yml
Labels: development

#802 Add CSS incrementer GitHub action
  .github/workflows/increment_css.yml
  src/templates/base.html
  src/templates/ja/2019/splash.html
Labels: development

#807 French Organization translation
  src/templates/fr/2019/base.html
Labels: translation

#811 Fix some bad markup spotted in French SEO chapter
  src/content/fr/2019/seo.md
  src/templates/base/2019/base_chapter.html
  src/templates/fr/2019/chapters/seo.html
  src/templates/sitemap.xml
Labels: bug

#816 Restrict Image Compression Action to pull requests from this repo
  .github/workflows/calibreapp-image-action.yml
Labels: development

#782 Time to Interactive is NOT the time until a page is interactive
  src/content/en/2019/mobile-web.md
Labels: writing

#820 Translation TTL Mobile
  src/content/ja/2019/mobile-web.md
Labels: translation

#824 Fix typos in Increment CSS Actions
  .github/workflows/increment_css.yml
Labels: bug

#825 Track ebook link clicks
  src/templates/base/2019/table_of_contents.html
Labels: development

#829 Translation of base.html to Japanese
  src/templates/ja/2019/base.html
  src/templates/ja/2019/base_ebook.html
Labels: translation

#831 Fix <table> markup
  src/content/en/2019/caching.md
  src/content/en/2019/cdn.md
  src/content/en/2019/compression.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/security.md
  src/content/es/2019/ecommerce.md
  src/content/fr/2019/caching.md
  src/content/ja/2019/caching.md
  src/content/ja/2019/cdn.md
  src/content/ja/2019/compression.md
  src/content/ja/2019/ecommerce.md
  src/content/ja/2019/fonts.md
  src/content/ja/2019/security.md
Labels: bug

#834 More table and figure markup cleanup
  src/content/en/2019/caching.md
  src/content/en/2019/cdn.md
  src/content/en/2019/compression.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/media.md
  src/content/en/2019/security.md
  src/content/es/2019/ecommerce.md
  src/content/fr/2019/caching.md
  src/content/ja/2019/caching.md
  src/content/ja/2019/cdn.md
  src/content/ja/2019/compression.md
  src/content/ja/2019/ecommerce.md
  src/content/ja/2019/http2.md
  src/content/ja/2019/markup.md
  src/content/ja/2019/media.md
  src/content/ja/2019/security.md
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/media.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/ebook.html
  src/templates/es/2019/chapters/ecommerce.html
  src/templates/fr/2019/chapters/caching.html
  src/templates/ja/2019/chapters/caching.html
  src/templates/ja/2019/chapters/cdn.html
  src/templates/ja/2019/chapters/compression.html
  src/templates/ja/2019/chapters/ecommerce.html
  src/templates/ja/2019/chapters/http2.html
  src/templates/ja/2019/chapters/markup.html
  src/templates/ja/2019/chapters/media.html
  src/templates/ja/2019/chapters/security.html
  src/templates/ja/2019/ebook.html
Labels: bug

#836 One more table markup fix for security chapter
  src/content/ja/2019/security.md
  src/templates/ja/2019/chapters/security.html
  src/templates/ja/2019/ebook.html
Labels: bug

#839 Correct digit to respect figure
  src/content/en/2019/javascript.md
Labels: writing

#841 Fix JavaScript Chapter errors
  src/content/es/2019/javascript.md
  src/content/ja/2019/javascript.md
  src/templates/es/2019/chapters/javascript.html
  src/templates/ja/2019/chapters/javascript.html
  src/templates/ja/2019/ebook.html
  src/templates/sitemap.xml
Labels: bug, translation

#838 Fr Translation – Mobile Web chapter
  src/content/fr/2019/mobile-web.md
  src/templates/fr/2019/featured_chapters.html
Labels: translation

#837 Video print fallbacks plus other Mobile Web chapter fixes
  src/content/en/2019/mobile-web.md
  src/content/ja/2019/mobile-web.md
  src/static/css/page.css
  src/static/css/print.css
  src/static/images/2019/mobile-web/fig2.png
Labels: development, translation

#851 Merge Generate Chapters and Increment CSS GitHub actions
  .github/workflows/generate_chapters.yml
  .github/workflows/increment_css.yml
Labels: development

#858 Translation of fig2-description to Japanese
  src/content/ja/2019/mobile-web.md
Labels: translation

#859 Translation about PDF to Japanese
  src/templates/ja/2019/accessibility_statement.html
Labels: translation

#863 Colour contrast image fixes
  src/content/en/2019/accessibility.md
  src/content/en/2019/mobile-web.md
  src/content/fr/2019/accessibility.md
  src/content/fr/2019/mobile-web.md
  src/content/ja/2019/accessibility.md
  src/content/ja/2019/mobile-web.md
  src/static/images/2019/accessibility/example-of-good-and-bad-color-contrast-lookzook.svg
  src/static/images/2019/mobile-web/example-of-good-and-bad-color-contrast-lookzook.svg
Labels: accessibility, translation, writing

#862 Increment JS version file on change - same as we do for CSS
  .github/workflows/generate_chapters.yml
Labels: development

#857 Add a "Show Description" button
  src/static/css/page.css
  src/static/css/print.css
  src/static/js/chapter.js
  src/templates/ar/2019/base.html
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/contributors.html
  src/templates/base/2019/methodology.html
  src/templates/en/2019/base.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
  src/tools/generate/generate_figure_ids.js
Labels: accessibility, development
