Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-08, with the labels that each got.

#1141 Fix typo in Accessibility chapter
  src/content/en/2019/accessibility.md
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/ebook.html
  src/templates/sitemap.xml
Labels: bug

#1143 Auto generate print ready versions of the eBooks
  .github/workflows/generate_ebooks.yml
  src/README.md
  src/tools/generate/generate_ebook_pdfs.js
Labels: development

#1147 Use Asian fonts in GitHub Ebook Action
  .github/workflows/generate_ebooks.yml
Labels: development

#1144 Fix French translation of text added to Accessibility Chapter
  src/content/fr/2019/accessibility.md
Labels: bug, translation

#1151 Add Author LinkedIn data
  src/config/2019.json
  src/config/2020.json
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/base_ebook.html
  src/templates/base/2019/contributors.html
  src/templates/base/2019/ebook.ejs.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
  src/templates/zh-CN/2019/base.html
Labels: development

#1164 Test website on pull requests as well as pushes to main
  .github/workflows/generate_chapters.yml
  .github/workflows/python-tests.yml
Labels: development

#1146 Portuguese translation of base template
  src/templates/pt/2019/base.html
Labels: translation

#1167 Add more test cases
  src/tools/generate/generate_chapters.js
  src/tools/generate/shared.js
  src/tools/test/test_status_codes.js
Labels: development

#1161 Allow different commas per language
  src/static/css/ebook.css
  src/templates/base/2019/base_ebook.html
  src/templates/base/2019/contributors.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
  src/templates/zh-CN/2019/base.html
Labels: translation

#1163 Adds focus back to highlighted contributor
  src/templates/base/2019/contributors.html
Labels: accessibility, bug, design, development

#1166 Remove dates from base templates
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/chapter.html
  src/templates/en/2019/base.html
  src/templates/en/2019/error.html
  src/templates/es/2019/base.html
  src/templates/es/2019/error.html
  src/templates/fr/2019/base.html
  src/templates/fr/2019/error.html
  src/templates/ja/2019/base.html
  src/templates/ja/2019/error.html
  src/templates/pt/2019/base.html
  src/templates/zh-CN/2019/base.html
  src/templates/zh-CN/2019/error.html
Labels: development

#1170 Better chapter dates to avoid duplication
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/chapter.html
Labels: development

#1173 Internationalise more commas
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/ebook.ejs.html
Labels: translation

#1172 Refactor actions
  .github/workflows/generate_chapters.yml
  .github/workflows/generate_ebooks.yml
  .github/workflows/test_website.yml
  src/tools/scripts/run_and_test_website.sh
  src/tools/scripts/update_timestamps_versions.sh
Labels: development

#1177 Add Bash linter
  .github/workflows/linter.yml
  src/tools/scripts/run_and_test_website.sh
  src/tools/scripts/update_timestamps_versions.sh
Labels: development

#1160 Some missed Japanese translations
  src/content/ja/2019/cms.md
  src/content/ja/2019/mobile-web.md
  src/templates/ja/2019/accessibility_statement.html
  src/templates/ja/2019/contributors.html
  src/templates/ja/2019/index.html
  src/templates/ja/2020/contributors.html
  src/templates/ja/2020/index.html
Labels: translation

#1175 Go crazy with GitHub Badges
  README.md
Labels: project management

#1179 Remove run_queries.sh as no longer used
  sql/run_queries.sh
Labels: analysis

#1183 Fix Page Weight Links to new format
  src/content/ja/2019/page-weight.md
Labels: translation

#1176 Refactor main.py #949
  src/config.py
  src/config/2020.json
  src/language.py
  src/main.py
  src/server/__init__.py
  src/server/config.py
  src/server/csp.py
  src/server/errors.py
  src/server/feature_policy.py
  src/server/helpers.py
  src/server/language.py
  src/server/routes.py
  src/server/tests/__init__.py
  src/server/tests/validate_test.py
  src/server/validate.py
Labels: development

#1185 Better author social media on website
  src/static/css/page.css
  src/templates/base/2019/base_chapter.html
Labels: design, development

#1187 Add Flake8 Python linter
  .github/linters/.flake8
  .github/workflows/linter.yml
  src/server/helpers.py
Labels: development

#1193 Rename chapter.html to make it more obvious it's an EJS template
  src/templates/base/2019/chapter.ejs.html
  src/tools/generate/generate_chapters.js
Labels: development

#1191 Narrow home page
  src/static/css/index.css
  src/templates/base/2019/base.html
  src/templates/base/2019/contributors.html
  src/templates/base/2019/index.html
  src/templates/base/2019/table_of_contents.html
  src/templates/base/2020/index.html
Labels: development

#1197 Freeze GitHub Action versions so they can be managed via dependabot
  .github/workflows/calibreapp-image-action.yml
  .github/workflows/generate_chapters.yml
  .github/workflows/generate_ebooks.yml
  .github/workflows/linter.yml
  .github/workflows/progress-tracker.yml
  .github/workflows/python-tests.yml
  .github/workflows/test_website.yml
Labels: development

#1196 Translated accessibility statement to French
  src/templates/en/2019/accessibility_statement.html
  src/templates/fr/2019/accessibility_statement.html
  src/templates/ja/2019/accessibility_statement.html
  src/templates/zh-CN/2019/accessibility_statement.html
Labels: translation

#1181 Spanish translation of Media chapter
  src/content/en/2019/media.md
  src/content/es/2019/media.md
Labels: translation

#1192 Fix Viper Typo
  src/content/ja/2019/media.md
Labels: bug, writing

#1139 Chinese translation of Accessibility chapters and templates bugs fix
  src/content/zh-CN/2019/accessibility.md
  src/templates/zh-CN/2019/base.html
  src/templates/zh-CN/2019/featured_chapters.html
  src/templates/zh-CN/2019/methodology.html
  src/templates/zh-CN/2019/table_of_contents.html
Labels: translation

#1188 Refactor Featured Chapter Code to avoid repetition
  src/templates/base/2019/index.html
  src/templates/en/2019/base.html
  src/templates/en/2019/featured_chapters.html
  src/templates/es/2019/base.html
  src/templates/es/2019/featured_chapters.html
  src/templates/fr/2019/base.html
  src/templates/fr/2019/featured_chapters.html
  src/templates/ja/2019/base.html
  src/templates/ja/2019/featured_chapters.html
  src/templates/pt/2019/base.html
  src/templates/zh-CN/2019/base.html
  src/templates/zh-CN/2019/featured_chapters.html
Labels: development

#1208 Fix Contributors on home page on mobile
  src/static/css/index.css
Labels: ASAP, bug, design

#1210 Run website tests on every pull request
  .github/workflows/generate_chapters.yml
  .github/workflows/generate_ebooks.yml
  .github/workflows/test_website.yml
Labels: development

#1211 Update the fix for the home contributors block
  src/static/css/index.css
Labels: design

#1213 Portuguese translation of base template
  src/templates/pt/2019/base_chapter.html
Labels: translation

#1215 Portuguese translation of base template
  src/templates/pt/2019/contributors.html
  src/templates/pt/2019/error.html
  src/templates/pt/2019/index.html
  src/templates/pt/2019/table_of_contents.html
  src/templates/pt/2020/contributors.html
  src/templates/pt/2020/index.html
Labels: translation

#1216 Fix lighthouse regressions
  src/static/css/page.css
  src/templates/base/2019/base_chapter.html
Labels: SEO, accessibility, bug, design, development

#1231 Remove flex grow to top align the contributors
  src/templates/base/2019/contributors.html
Labels: design

#1227 Chinese translation of Performance chapter + some clean ups of previous translations.
  src/content/zh-CN/2019/accessibility.md
  src/content/zh-CN/2019/performance.md
  src/templates/zh-CN/2019/base.html
  src/templates/zh-CN/2019/featured_chapters.html
Labels: translation

#1218 French Translation - JavaScript Chapter
  src/content/fr/2019/javascript.md
  src/templates/fr/2019/featured_chapters.html
Labels: translation

#1232 Config updates for new chapters and other misc cleanups
  README.md
  src/config/2020.json
  src/server/language.py
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
  src/templates/pt/2019/base.html
  src/templates/zh-CN/2019/base.html
Labels: translation

#1234 Translating 2019 Fonts chapter to Spanish
  src/content/es/2019/fonts.md
  src/content/es/2019/performance.md
  src/templates/es/2019/base.html
  src/templates/es/2019/featured_chapters.html
Labels: translation

#1217 French Translation - All 2019 Authors
  src/templates/fr/2019/base.html
Labels: translation

#1246 Set explicitly GitHub Actions versions were not set
  .github/workflows/generate_chapters.yml
  .github/workflows/generate_ebooks.yml
  .github/workflows/progress-tracker.yml
Labels: development

#1249 Fix percentiles in FR translation of JavaScript chapter
  src/content/fr/2019/javascript.md
Labels: translation

#1253 Display Ebook download size on link
  src/server/__init__.py
  src/server/helpers.py
  src/server/routes.py
  src/templates/base/2019/table_of_contents.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
  src/templates/pt/2019/base.html
  src/templates/zh-CN/2019/base.html
Labels: development
