Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-12, with the labels that each got.

#1513 2020 CMS Chapter
  sql/2020/15_CMS/median_lighthouse_score.sql
  src/config/2020.json
  src/content/en/2020/cms.md
  src/static/images/2020/cms/cms-accessibility-lighthouse-score.png
  src/static/images/2020/cms/cms-adoption-share-2020.png
  src/static/images/2020/cms/cms-adoption-share-for-top-5-cmss.png
  src/static/images/2020/cms/cms-adoption.png
  src/static/images/2020/cms/cms-carbon-emissions-per-cms-page-view.png
  src/static/images/2020/cms/cms-distribution-of-cms-pages-sizes.png
  src/static/images/2020/cms/cms-median-cms-kb-per-resource-type.png
  src/static/images/2020/cms/cms-popularity-of-image-formats.png
  src/static/images/2020/cms/cms-real-user-cumulative-layout-shift-experiences.png
  src/static/images/2020/cms/cms-real-user-first-input-delay-experiences.png
  src/static/images/2020/cms/cms-real-user-largest-contentful-paint-experiences.png
  src/static/images/2020/cms/cms-seo-lighthouse-score.png
  src/static/images/2020/cms/cms-third-party-bytes.png
  src/static/images/2020/cms/cms-top-5-cms-by-client.png
  src/static/images/2020/cms/cms-wordpress-plugin-resource-per-page.png
Labels: writing

#1605 Pytest config.py
  src/config/2020.json
  src/server/config.py
  src/server/tests/config_test.py
Labels: development

#1606 Mobile Web: Add two new metrics
  sql/2020/12_Mobile_Web/color_contrast.sql
  sql/2020/12_Mobile_Web/tap_targets.sql
Labels: ASAP, analysis

#1599 2020 HTTP2 chapter
  src/content/en/2020/http2.md
  src/static/images/2020/http2/http2-cdn-http2-usage.png
  src/static/images/2020/http2/http2-first-and-third-party-http2-usage.png
  src/static/images/2020/http2/http2-h2-or-gquic-requests-per-page.png
  src/static/images/2020/http2/http2-h2-usage-by-server.png
  src/static/images/2020/http2/http2-h2-usage.png
  src/static/images/2020/http2/http2-pushed-content-types.png
  src/static/images/2020/http2/http2-server-protocol-usage.png
  src/static/images/2020/http2/http2-third-party-http2-usage-by-category.png
  src/static/images/2020/http2/http2-third-party-http2-usage-by-content-type.png
  src/static/images/2020/http2/http2-total-number-of-connections-per-page.png
  src/templates/base/base.html
Labels: writing

#1587 2020 Resource Hints chapter
  src/content/en/2020/resource-hints.md
Labels: writing

#1589 2020 SEO chapter
  src/content/en/2020/seo.md
  src/static/images/2020/seo/seo-aggregate-cwv-performance-by-country.png
  src/static/images/2020/seo/seo-canonical-implementation-method.png
  src/static/images/2020/seo/seo-good-core-web-vitals-score-per-device.png
  src/static/images/2020/seo/seo-google-trends.png
  src/static/images/2020/seo/seo-image-links.png
  src/static/images/2020/seo/seo-img-elements-per-page.png
  src/static/images/2020/seo/seo-lighthouse-v5-vs-v6.png
  src/static/images/2020/seo/seo-meta-description-character-length.png
  src/static/images/2020/seo/seo-meta-description-word-length.png
  src/static/images/2020/seo/seo-nofollow-ugc-sponsored-attributes.png
  src/static/images/2020/seo/seo-outgoing-links-external.png
  src/static/images/2020/seo/seo-outgoing-links-internal.png
  src/static/images/2020/seo/seo-outgoing-links.png
  src/static/images/2020/seo/seo-percentage-of-blank-img-alt-attributes.png
  src/static/images/2020/seo/seo-percentage-of-https.png
  src/static/images/2020/seo/seo-percentage-of-img-alt-attributes-present.png
  src/static/images/2020/seo/seo-percentage-of-missing-img-alt-attribute.png
  src/static/images/2020/seo/seo-presence-of-canonical-tag.png
  src/static/images/2020/seo/seo-presence-of-h-elements.png
  src/static/images/2020/seo/seo-presence-of-non-empty-h-elements.png
  src/static/images/2020/seo/seo-robots-directive-use.png
  src/static/images/2020/seo/seo-text-links.png
  src/static/images/2020/seo/seo-title-character-count.png
  src/static/images/2020/seo/seo-title-word-count.png
  src/static/images/2020/seo/seo-visible-words-per-page-raw.png
  src/static/images/2020/seo/seo-visible-words-per-page-rendered.png
Labels: writing

#1607 Add pytests for routes.py
  src/package.json
  src/server/tests/config_test.py
  src/server/tests/routes_test.py
Labels: development

#1615 SEO edit to AMP section
  src/content/en/2020/seo.md
Labels: writing

#1604 2020 Markup chapter editing
  src/content/en/2020/markup.md
Labels: editing

#1612 Media 2020 queries
  sql/2020/05_Media/video_source_types.sql
Labels: ASAP, analysis

#1608 2020 Performance Chapter
  src/content/en/2020/performance.md
  src/static/images/2020/performance/performance-change-in-lighthouse-score.png
  src/static/images/2020/performance/performance-cls-by-connection-type.png
  src/static/images/2020/performance/performance-cls-by-device.png
  src/static/images/2020/performance/performance-cls-by-geo.png
  src/static/images/2020/performance/performance-fcp-by-connection-type.png
  src/static/images/2020/performance/performance-fcp-by-geo.png
  src/static/images/2020/performance/performance-fcp-desktop-distribution.png
  src/static/images/2020/performance/performance-fcp-mobile-distribution.png
  src/static/images/2020/performance/performance-fcp-mobile-year-on-year.png
  src/static/images/2020/performance/performance-fid-by-connection-type.png
  src/static/images/2020/performance/performance-fid-by-device.png
  src/static/images/2020/performance/performance-fid-by-geo.png
  src/static/images/2020/performance/performance-lcp-by-connection-type.png
  src/static/images/2020/performance/performance-lcp-by-device.png
  src/static/images/2020/performance/performance-lcp-by-geo.png
  src/static/images/2020/performance/performance-lighthouse-score-distributions-yoy.png
  src/static/images/2020/performance/performance-performance-observer-usage.png
  src/static/images/2020/performance/performance-ttfb-by-connection-type.png
  src/static/images/2020/performance/performance-ttfb-by-device.png
  src/static/images/2020/performance/performance-ttfb-by-geo.png
Labels: writing

#1620 Media 2020 queries
  sql/2020/05_Media/meta_open_graph.sql
  sql/2020/05_Media/meta_open_image_types.sql
  sql/2020/05_Media/meta_open_video_types.sql
Labels: analysis

#1590 Capabilities japanese translation
  src/content/ja/2020/capabilities.md
Labels: translation

#1623 Add alts for easier translations
  src/content/en/2020/capabilities.md
Labels: translation

#1621 Security SQL 2020: fixes
  sql/2020/11_Security/csp_script_source_list_keywords.sql
  sql/2020/11_Security/feature_adoption_by_other_features.sql
  sql/2020/11_Security/version-evolution-top-technologies.sql
Labels: analysis

#1627 Media Chapter: Added sql script for video preload attribute values.
  sql/2020/05_Media/video_preload_values.sql
Labels: analysis

#1626 Security SQL 2020: additional query
  sql/2020/11_Security/feature_adoption_by_topN_technologies.sql
Labels: analysis

#1624 Copyedit of the CMS 2020 Chapter
  src/content/en/2020/cms.md
  src/static/images/2020/cms/cms-adoption-share-for-top-5-cmss.png
  src/static/images/2020/cms/cms-top-5-cms-by-client.png
Labels: editing

#1634 no-wrap class added in 2019.css and used at featured chapter stats in index.html
  src/static/css/2019.css
  src/static/css/page.css
  src/templates/base/index.html
Labels: development

#1642 Better colour contrast for social media icons
  src/static/css/2019.css
Labels: accessibility, bug, development

#1638 Remove todo label from chapters with content
  src/config/2020.json
Labels: writing

#1622 Copyedit of 2020 Performance chapter
  src/content/en/2020/performance.md
  src/static/images/2020/performance/performance-change-in-lighthouse-score.png
  src/static/images/2020/performance/performance-cls-by-connection-type.png
  src/static/images/2020/performance/performance-cls-by-device.png
  src/static/images/2020/performance/performance-cls-by-geo.png
  src/static/images/2020/performance/performance-fcp-by-connection-type.png
  src/static/images/2020/performance/performance-fcp-by-geo.png
  src/static/images/2020/performance/performance-fcp-desktop-distribution.png
  src/static/images/2020/performance/performance-fcp-mobile-distribution.png
  src/static/images/2020/performance/performance-fcp-mobile-year-on-year.png
  src/static/images/2020/performance/performance-fid-by-connection-type.png
  src/static/images/2020/performance/performance-fid-by-device.png
  src/static/images/2020/performance/performance-fid-by-geo.png
  src/static/images/2020/performance/performance-lcp-by-connection-type.png
  src/static/images/2020/performance/performance-lcp-by-device.png
  src/static/images/2020/performance/performance-lcp-by-geo.png
  src/static/images/2020/performance/performance-lighthouse-score-distributions-yoy.png
  src/static/images/2020/performance/performance-performance-observer-usage.png
  src/static/images/2020/performance/performance-ttfb-by-connection-type.png
  src/static/images/2020/performance/performance-ttfb-by-device.png
  src/static/images/2020/performance/performance-ttfb-by-geo.png
Labels: editing

#1644 Security SQL 2020: add 2019 results for security header adoption
  sql/2020/11_Security/security_headers_prevalence.sql
Labels: ASAP, analysis

#1645 Better heading sizes
  src/static/css/2019.css
Labels: design, development

#1646 Fix reason for Lighthouse failure affecting other branches
  src/content/en/2020/seo.md
Labels: ASAP, bug, writing

#1613 PWA 2020 chapter.
  src/content/en/2020/pwa.md
  src/static/images/2020/pwa/pwa-manifest-and-service-worker-usage.png
  src/static/images/2020/pwa/pwa-manifest-categories.png
  src/static/images/2020/pwa/pwa-manifest-preferring-native.png
  src/static/images/2020/pwa/pwa-manifest-properties-on-service-worker-pages.png
  src/static/images/2020/pwa/pwa-most-used-display-values-for-service-worker-pages.png
  src/static/images/2020/pwa/pwa-most-used-service-worker-events.png
  src/static/images/2020/pwa/pwa-most-used-workbox-packages.png
  src/static/images/2020/pwa/pwa-timeseries-of-service-worker-installations.png
  src/static/images/2020/pwa/pwa-top-manifest-icon-sizes.png
  src/static/images/2020/pwa/pwa-top-manifest-orientations.png
Labels: writing

#1649 fix: resource hints images
  src/content/en/2020/resource-hints.md
  src/static/images/2020/resource-hints/adoption-of-resource-hints.png
  src/static/images/2020/resource-hints/median-number-of-hints-per-page.png
  src/static/images/2020/resource-hints/mobile-as-attribute-values-by-year.png
  src/static/images/2020/resource-hints/resource-hint-adoption-onservice-worker-pages.png
Labels: writing

#1618 HTTP/2 edits
  src/content/en/2020/http2.md
  src/static/images/2020/http2/http2-h2-or-gquic-requests-per-page.png
  src/static/images/2020/http2/http2-h2-usage-by-server.png
  src/static/images/2020/http2/http2-pushed-content-types.png
  src/static/images/2020/http2/http2-total-number-of-connections-per-page.png
Labels: editing

#1632 2020 Jamstack Chapter
  src/config/2020.json
  src/content/en/2020/jamstack.md
  src/static/images/2020/jamstack/jamstack-adoption-share-2020-pie.png
  src/static/images/2020/jamstack/jamstack-adoption-share-2020.png
  src/static/images/2020/jamstack/jamstack-adoption.png
  src/static/images/2020/jamstack/jamstack-carbon-emissions-per-jamstack-page-view.png
  src/static/images/2020/jamstack/jamstack-popularity-of-image-formats.png
  src/static/images/2020/jamstack/jamstack-real-user-cumulative-layout-shift-experiences.png
  src/static/images/2020/jamstack/jamstack-real-user-first-input-delay-experiences.png
  src/static/images/2020/jamstack/jamstack-real-user-largest-contentful-paint-experiences.png
  src/static/images/2020/jamstack/jamstack-third-party-bytes.png
Labels: writing

#1650 Security SQL 2020: fix version evolution top technologies query
  sql/2020/11_Security/version-evolution-top-technologies.sql
Labels: analysis

#1639 Fonts 2020 queries
  sql/2020/04_Fonts/04_11a.popular_typeface.sql
Labels: ASAP, analysis

#1651 Update the post-launch 2020 home page
  src/config/2020.json
  src/server/helpers.py
  src/templates/en/2019/index.html
  src/templates/en/2020/index.html
  src/templates/en/base.html
  src/templates/es/2019/index.html
  src/templates/es/2020/index.html
  src/templates/es/base.html
  src/templates/fr/2019/index.html
  src/templates/fr/2020/index.html
  src/templates/fr/base.html
  src/templates/hi/2019/index.html
  src/templates/hi/2020/index.html
  src/templates/hi/base.html
  src/templates/ja/2019/index.html
  src/templates/ja/2020/index.html
  src/templates/ja/base.html
  src/templates/pt/2019/index.html
  src/templates/pt/2020/index.html
  src/templates/pt/base.html
  src/templates/ru/2019/index.html
  src/templates/ru/2020/index.html
  src/templates/ru/base.html
  src/templates/zh-CN/2019/index.html
  src/templates/zh-CN/2020/index.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/2019/index.html
  src/templates/zh-TW/2020/index.html
  src/templates/zh-TW/base.html
Labels: development

#1640 Chinese Translation - capabilities&methodology Chapter #1067
  src/content/zh-CN/2020/capabilities.md
  src/templates/zh-CN/2020/methodology.html
Labels: translation

#1655 Modifications to Caching 2020 queries during editing.
  sql/2020/20_Caching/cache_control_and_max_age_and_expires_2019.sql
Labels: ASAP, analysis, bug

#1648 Fix typos in Capabilities figure descriptions
  src/content/en/2020/capabilities.md
  src/content/ja/2020/capabilities.md
  src/content/ru/2020/capabilities.md
Labels: bug, writing

#1661 Security SQL 2020: update unsafe-inline and unsafe-eval query
  sql/2020/11_Security/csp_script_source_list_keywords.sql
Labels: analysis

#1614 Markup 2020 TODOs
  src/content/en/2020/markup.md
  src/static/images/2020/markup/document-language.png
Labels: editing

#1647 A11Y chapter: Additional metrics
  sql/2020/08_Accessibility/sites_using_role.sql
  sql/2020/08_Accessibility/sites_with_empty_alts.sql
Labels: ASAP, analysis

#1570 Add dropdown menu to show extra figure information
  src/static/css/page.css
  src/templates/base/base.html
  src/templates/en/base_chapter.html
  src/templates/es/base_chapter.html
  src/templates/fr/base_chapter.html
  src/templates/hi/base_chapter.html
  src/templates/ja/base_chapter.html
  src/templates/pt/base_chapter.html
  src/templates/ru/base_chapter.html
  src/templates/zh-CN/base_chapter.html
  src/templates/zh-TW/base_chapter.html
Labels: design, development

#1625 SEO 2020 edits
  src/content/en/2020/seo.md
  src/static/images/2020/seo/seo-canonical-implementation-method.png
  src/static/images/2020/seo/seo-nofollow-ugc-sponsored-attributes.png
  src/static/images/2020/seo/seo-presence-of-canonical-tag.png
  src/static/images/2020/seo/seo-presence-of-h-elements.png
  src/static/images/2020/seo/seo-presence-of-non-empty-h-elements.png
  src/static/images/2020/seo/seo-robots-directive-use.png
  src/static/images/2020/seo/seo-title-character-count.png
Labels: editing

#1665 Copyedit of Jamstack chapter
  src/content/en/2020/jamstack.md
  src/static/images/2020/jamstack/jamstack-adoption-share-2020-pie.png
  src/static/images/2020/jamstack/jamstack-adoption-share-2020.png
  src/static/images/2020/jamstack/jamstack-adoption-share-yoy.png
  src/static/images/2020/jamstack/jamstack-popularity-of-image-formats.png
  src/static/images/2020/jamstack/jamstack-third-party-bytes.png
Labels: editing

#1658 Log contributor mismatches between JSON and chapter meta data
  src/tools/generate/generate_chapters.js
  src/tools/generate/get_contributors_diff.js
Labels: development

#1657 Adding privacy 2020 chapter
  src/content/en/2020/privacy.md
  src/static/images/2020/privacy/privacy-adoption-of-the-tcf-banner.png
  src/static/images/2020/privacy/privacy-biggest-third-party-trackers.png
  src/static/images/2020/privacy/privacy-consent-management-platform-popularity.png
  src/static/images/2020/privacy/privacy-tracker-categories.png
  src/static/images/2020/privacy/privacy-websites-that-load-trackers.png
  src/static/images/2020/privacy/privacy-websites-with-consent-management-platform.png
  src/static/images/2020/privacy/privacy-websites-with-fingerprintjs-library.png
  src/static/images/2020/privacy/privacy-websites-with-privacy-link.png
Labels: writing

#1671 Stop doing author check for single chapter generation
  src/tools/generate/generate_chapters.js
Labels: ASAP, bug, development

#1643 2020 Fonts chapter
  src/config/2020.json
  src/content/en/2020/fonts.md
  src/static/images/2020/fonts/fonts-font-display-performance-desktop.png
  src/static/images/2020/fonts/fonts-font-display-performance-mobile.png
  src/static/images/2020/fonts/fonts-font-variation-settings-usage.png
  src/static/images/2020/fonts/fonts-popular-typefaces.png
  src/static/images/2020/fonts/fonts-resource-hints-performance-desktop.png
  src/static/images/2020/fonts/fonts-resource-hints-performance-mobile.png
  src/static/images/2020/fonts/fonts-resource-hints-use.png
  src/static/images/2020/fonts/fonts-usage-of-font-display.png
  src/static/images/2020/fonts/fonts-usage-of-unicode-range.png
  src/static/images/2020/fonts/fonts-web-font-mime-types.png
  src/static/images/2020/fonts/fonts-web-fonts-usage-by-country.png
  src/static/images/2020/fonts/fonts-web-fonts-usage-top-countries.png
  src/static/images/2020/fonts/fonts-web-fonts-usage.png
  src/static/images/2020/fonts/fonts-web-hosting-performance-desktop.png
  src/static/images/2020/fonts/fonts-web-hosting-performance-mobile.png
Labels: ASAP, writing

#1656 Compression chapter 2020
  src/config/2020.json
  src/content/en/2020/compression.md
  src/static/images/2020/compression/compession-methods-by-content-type.png
  src/static/images/2020/compression/compression-algorithms-by-content-type-desktop.png
  src/static/images/2020/compression/compression-algorithms-for-http-requests.png
  src/static/images/2020/compression/content-encoding.png
  src/static/images/2020/compression/http-compression-methods-for-image-types.png
  src/static/images/2020/compression/text-compression-lighthouse-scores.png
Labels: ASAP, writing

#1609 Caching 2020 chapter.
  src/content/en/2020/caching.md
  src/static/images/2020/caching/cache-control-and-max-age-and-expires-2019.png
  src/static/images/2020/caching/cache-control-and-max-age-and-expires.png
  src/static/images/2020/caching/cache-control-directives.png
  src/static/images/2020/caching/cache-ttl-lighthouse-score.png
  src/static/images/2020/caching/cache-wasted-bytes-lighthouse.png
  src/static/images/2020/caching/cacheable-and-non-cacheable.png
  src/static/images/2020/caching/cacheable-by-resource-type.png
  src/static/images/2020/caching/chrome-dev-tools.png
  src/static/images/2020/caching/invalid-last-modified-and-expires-and-date.png
  src/static/images/2020/caching/last-modified-and-etag-2019.png
  src/static/images/2020/caching/last-modified-and-etag.png
  src/static/images/2020/caching/lighthouse-caching-audit.png
  src/static/images/2020/caching/request-response-flow-with-caching.png
  src/static/images/2020/caching/resource-age-party-and-type-wise-groups-1st-party.png
  src/static/images/2020/caching/resource-age-party-and-type-wise-groups-3rd-party.png
  src/static/images/2020/caching/service-workers-controlled-pages-2019-2020.png
  src/static/images/2020/caching/set-cookie-usage-on-cacheable-responses.png
  src/static/images/2020/caching/set-cookie-usage-on-private-and-non-private-cacheable-responses.png
  src/static/images/2020/caching/ttl-cachable-responses.png
  src/static/images/2020/caching/valid-if-none-match-returns-304.png
  src/static/images/2020/caching/vary-headers.png
Labels: ASAP, writing

#1673 Add exterkamp back into contributors
  src/config/2020.json
Labels: development

#1674 More contributor cleanup
  src/config/2020.json
  src/content/en/2020/caching.md
  src/content/en/2020/fonts.md
Labels: development

#1662 2020 HTTP/2 edits
  src/content/en/2020/http2.md
Labels: ASAP, editing

#1679 Extra query for TLS section of Security chapter
  sql/2020/11_Security/home_page_https_usage.sql
Labels: analysis

#1680 Mobile Web 2020 chapter
  src/content/en/2020/mobile-web.md
Labels: ASAP, writing

#1685 HTTP/2 figure caption spelling correction
  src/content/en/2020/http2.md
Labels: editing

#1663 Security 2020: markdown content
  src/config/2020.json
  src/content/en/2020/security.md
  src/static/css/page.css
  src/static/images/2020/security/security-adoption-of-csp-and-xfo-per-country.png
  src/static/images/2020/security/security-adoption-of-https-per-country.png
  src/static/images/2020/security/security-adoption-of-security-headers.png
  src/static/images/2020/security/security-cryptominer-market-share.png
  src/static/images/2020/security/security-cryptominer-usage.png
  src/static/images/2020/security/security-csp-header-length.png
  src/static/images/2020/security/security-distribution-of-cipher-suites.png
  src/static/images/2020/security/security-evolution-of-wordpress-5-3and5-4-after-update.png
  src/static/images/2020/security/security-headers-as-drivers-of-adotpions-of-other-headers.png
  src/static/images/2020/security/security-hsts-max-age-values-in-days.png
  src/static/images/2020/security/security-httponly-secure-samesite-cookie-usage.png
  src/static/images/2020/security/security-https-request-growth.png
  src/static/images/2020/security/security-https-usage-by-site.png
  src/static/images/2020/security/security-jquery-version-evolution.png
  src/static/images/2020/security/security-nginx-version-evolution.png
  src/static/images/2020/security/security-samesite-cookie-attributes.png
  src/static/images/2020/security/security-subresource-integrity-coverage-per-page.png
  src/static/images/2020/security/security-tls-version-by-site.png
  src/static/images/2020/security/security-wordpress-version-evolution.png
Labels: ASAP, writing

#1686 Security meta data
  src/config/2020.json
  src/content/en/2020/security.md
Labels: writing

#1668 WIP: 2020 Third Parties Chapter
  src/config/2020.json
  src/content/en/2020/third-parties.md
  src/static/images/2020/third-parties/cpu-time-by-category.png
  src/static/images/2020/third-parties/distribution-of-request-count.png
  src/static/images/2020/third-parties/page-size-by-category.png
  src/static/images/2020/third-parties/page-size-by-host.png
  src/static/images/2020/third-parties/pages-with-thirdparties.png
  src/static/images/2020/third-parties/redirects-body-size.png
  src/static/images/2020/third-parties/requests-before-dom-by-category.png
  src/static/images/2020/third-parties/requests-cached-by-content-type.png
  src/static/images/2020/third-parties/requests-with-tao.png
  src/static/images/2020/third-parties/thirdparty-by-content-types.png
  src/static/images/2020/third-parties/top-domains-by-prevalence.png
Labels: ASAP, writing

#1687 log of add contributors and their team fixes
  src/config/2019.json
  src/config/2020.json
  src/tools/generate/get_contributors_diff.js
Labels: development

#1690 Page Weight 2020
  src/content/en/2020/page-weight.md
  src/static/images/2020/page-weight/bytes-distribution-content-type.png
  src/static/images/2020/page-weight/bytes-distribution.png
  src/static/images/2020/page-weight/requests-content-type.png
  src/static/images/2020/page-weight/requests-distribution.png
  src/static/images/2020/page-weight/response-distribution-format.png
  src/static/images/2020/page-weight/response-distribution-images.png
Labels: writing

#1684 Mobile web chapter: Figures added to markdown
  src/content/en/2020/mobile-web.md
  src/static/images/2020/mobile-web/aggregate-lcp-performance-by-device.png
  src/static/images/2020/mobile-web/eastpak-12-ctr.png
  src/static/images/2020/mobile-web/eastpak-20-ctr.png
  src/static/images/2020/mobile-web/ecommerce-sites-using-a-search-input.png
  src/static/images/2020/mobile-web/example-of-a-site-shifting-content-while-it-loads-lookzook.gif
  src/static/images/2020/mobile-web/landing-page-cta.png
  src/static/images/2020/mobile-web/median-p75-lcp-score.png
  src/static/images/2020/mobile-web/mobile-traffic-distribution.png
  src/static/images/2020/mobile-web/page-loads-across-origins-ranked-by-popularity.png
  src/static/images/2020/mobile-web/pages-with-properly-sized-images.png
  src/static/images/2020/mobile-web/search-input-lyst.png
  src/static/images/2020/mobile-web/sites-with-inputs-using-the-following-input-types.png
  src/static/images/2020/mobile-web/sites-with-properly-sized-tap-targets.png
  src/static/images/2020/mobile-web/sites-with-sufficient-color-contrast.png
Labels: writing

#1659 2020 Accessibility chapter
  src/config/2020.json
  src/content/en/2020/accessibility.md
  src/static/images/2020/accessibility/descriptive-page-titles.png
  src/static/images/2020/accessibility/labels-and-placeholders.png
  src/static/images/2020/accessibility/link-types.png
  src/static/images/2020/accessibility/role-tab-list.png
  src/static/images/2020/accessibility/role-tab-panel.png
  src/static/images/2020/accessibility/role-tab.png
  src/static/images/2020/accessibility/skip-links.png
  src/static/images/2020/accessibility/tab-index-values.png
  src/static/images/2020/accessibility/title-and-alt-same.png
  src/static/images/2020/accessibility/valid-html-lang.png
  src/static/images/2020/accessibility/videos-using-track.png
  src/static/images/2020/accessibility/zoom-and-scale.png
Labels: ASAP, writing

#1692 Fixes in the markdown.
  src/content/en/2020/caching.md
Labels: editing

#1672 Copyediting of the Privacy chapter
  src/content/en/2020/privacy.md
Labels: ASAP, editing

#1652 2020 JS Chapter
  sql/2020/02_JavaScript/frameworks-bytes-by-framework.sql
  sql/2020/02_JavaScript/resource-hints-prefetch-preload-percentage.sql
  sql/2020/02_JavaScript/resource-hints-preload-prefetch-distribution.sql
  src/config/2020.json
  src/content/en/2020/javascript.md
  src/static/images/2020/javascript/async-defer-mobile.png
  src/static/images/2020/javascript/bytes-2020.png
  src/static/images/2020/javascript/bytes-by-3p-desktop.png
  src/static/images/2020/javascript/bytes-by-3p-mobile.png
  src/static/images/2020/javascript/compression-method-3p.png
  src/static/images/2020/javascript/compression-method-request.png
  src/static/images/2020/javascript/external-inline-mobile.png
  src/static/images/2020/javascript/frameworks-libraries.png
  src/static/images/2020/javascript/lighthouse-unminified-js-by-3p.png
  src/static/images/2020/javascript/lighthouse-unminified-js.png
  src/static/images/2020/javascript/main-thread-time.png
  src/static/images/2020/javascript/page-weight-per-content-type.png
  src/static/images/2020/javascript/requests-2019.png
  src/static/images/2020/javascript/requests-2020.png
  src/static/images/2020/javascript/requests-by-3p-desktop.png
  src/static/images/2020/javascript/requests-by-3p-mobile.png
  src/static/images/2020/javascript/unused-js-bytes-distribution.png
  src/static/images/2020/javascript/vulnerabilities-by-severity.png
Labels: ASAP, writing

#1694 Foreword
  src/templates/en/2019/base.html
  src/templates/en/2020/base.html
Labels: writing

#1696 Security 2020: markdown edits
  src/content/en/2020/security.md
Labels: editing

#1664 Resource Hints 2020 edits
  src/content/en/2020/resource-hints.md
  src/static/images/2020/resource-hints/median-number-of-hints-per-page.png
  src/static/images/2020/resource-hints/mobile-as-attribute-values-by-year.png
  src/static/images/2020/resource-hints/resource-hint-adoption-2019-vs-2020.png
  src/static/images/2020/resource-hints/resource-hint-adoption-onservice-worker-pages.png
Labels: ASAP, editing

#1699 Fix minor security linting error
  src/tools/generate/generate_ebooks.js
Labels: bug

#1698 Security 2020: edits
  src/content/en/2020/security.md
Labels: editing

#1701 Caching 2020 markdown fixes for editing 1
  src/content/en/2020/caching.md
  src/static/images/2020/caching/cache-control-and-max-age-and-expires-2019.png
  src/static/images/2020/caching/cache-control-and-max-age-and-expires.png
  src/static/images/2020/caching/cache-control-directives.png
  src/static/images/2020/caching/cache-ttl-lighthouse-score.png
  src/static/images/2020/caching/cache-wasted-bytes-lighthouse.png
  src/static/images/2020/caching/cacheable-and-non-cacheable.png
  src/static/images/2020/caching/cacheable-by-resource-type.png
  src/static/images/2020/caching/invalid-last-modified-and-expires-and-date.png
  src/static/images/2020/caching/last-modified-and-etag-2019.png
  src/static/images/2020/caching/last-modified-and-etag.png
  src/static/images/2020/caching/resource-age-party-and-type-wise-groups-1st-party.png
  src/static/images/2020/caching/service-workers-controlled-pages-2019-2020.png
  src/static/images/2020/caching/set-cookie-usage-on-cacheable-responses.png
  src/static/images/2020/caching/set-cookie-usage-on-private-and-non-private-cacheable-responses.png
  src/static/images/2020/caching/ttl-cachable-responses.png
  src/static/images/2020/caching/valid-if-none-match-returns-304.png
  src/static/images/2020/caching/vary-headers.png
Labels: editing

#1702 Security 2020: fix spelling
  src/content/en/2020/security.md
  src/static/images/2020/security/security-headers-as-drivers-of-adoption-of-other-headers.png
Labels: editing

#1703 Spell check - part 1
  src/config/spelling_ignore_words.txt
  src/content/en/2020/css.md
  src/content/en/2020/fonts.md
  src/content/en/2020/javascript.md
  src/content/en/2020/page-weight.md
  src/content/en/2020/privacy.md
  src/content/en/2020/seo.md
  src/templates/en/2020/methodology.html
Labels: editing

#1704 Spell checks part 2
  src/config/spelling_ignore_words.txt
  src/content/en/2019/accessibility.md
  src/content/en/2020/accessibility.md
  src/content/en/2020/compression.md
  src/content/en/2020/http2.md
  src/content/en/2020/mobile-web.md
  src/content/en/2020/page-weight.md
  src/content/en/2020/performance.md
  src/content/en/2020/pwa.md
  src/content/en/2020/resource-hints.md
Labels: editing

#1695 Third-Party 2020 - Minor Edits
  src/config/2020.json
  src/content/en/2020/third-parties.md
Labels: ASAP, writing

#1705 More spellchecks
  src/config/spelling_ignore_words.txt
  src/content/en/2020/accessibility.md
  src/content/en/2020/css.md
Labels: editing

#1707 Fix various issues
  src/content/en/2020/accessibility.md
  src/content/en/2020/cms.md
  src/content/en/2020/css.md
  src/content/en/2020/javascript.md
  src/content/en/2020/mobile-web.md
  src/content/en/2020/page-weight.md
  src/content/en/2020/pwa.md
Labels: ASAP, editing

#1709 Update spelling list
  src/config/spelling_ignore_words.txt
Labels: editing

#1710 Update Security image for cryptominer usage
  src/static/images/2020/security/security-cryptominer-usage.png
Labels: editing

#1711 Fix broken links
  sql/2020/17_Jamstack/README.md
  sql/2020/17_Jamstack/adoption_of_image_formats_in_ssgs.sql
  sql/2020/17_Jamstack/core_web_vitals_distribution.sql
  sql/2020/17_Jamstack/core_web_vitals_passing.sql
  sql/2020/17_Jamstack/distribution_of_page_weight_requests_and_co2_grams_per_ssg_web_page.sql
  sql/2020/17_Jamstack/median_lighthouse_score.sql
  sql/2020/17_Jamstack/ssg_compared_to_2019.sql
  sql/2020/17_Jamstack/third_party_bytes_and_requests_on_ssgs.sql
  src/config/2020.json
  src/content/en/2020/accessibility.md
  src/content/en/2020/cms.md
  src/content/en/2020/css.md
  src/content/en/2020/javascript.md
  src/content/en/2020/mobile-web.md
  src/content/en/2020/pwa.md
  src/content/en/2020/security.md
  src/content/en/2020/seo.md
  src/content/ja/2019/cms.md
  src/templates/en/accessibility_statement.html
  src/templates/fr/accessibility_statement.html
  src/templates/hi/accessibility_statement.html
  src/templates/ja/accessibility_statement.html
  src/templates/zh-CN/accessibility_statement.html
Labels: editing

#1713 Update playground URL
  src/content/en/2020/css.md
Labels: writing

#1720 fixes typo for in-page link in css chapter
  src/content/en/2020/css.md
Labels: bug, editing

#1688 Compression 2020 edits
  src/content/en/2020/compression.md
  src/static/images/2020/compression/text-compression-lighthouse-scores.png
Labels: editing

#1719 fix: resource hints image style
  src/static/images/2020/resource-hints/adoption-of-resource-hints.png
Labels: analysis

#1724 Fix JS chapter image 404
  src/static/images/2020/javascript/correlations.png
Labels: editing

#1718 Add highlight to inline code
  src/static/css/2019.css
Labels: design, development

#1721 Various minor fixes
  src/config/2020.json
  src/content/en/2020/accessibility.md
  src/content/en/2020/compression.md
  src/content/en/2020/css.md
  src/content/en/2020/fonts.md
  src/content/en/2020/javascript.md
  src/content/en/2020/mobile-web.md
  src/content/en/2020/page-weight.md
  src/content/en/2020/performance.md
  src/content/en/2020/resource-hints.md
  src/content/en/2020/seo.md
  src/content/en/2020/third-parties.md
Labels: editing

#1726 Big figure tweaks
  src/content/en/2020/accessibility.md
  src/static/css/page.css
Labels: bug, design, development

#1729 Improve inline code styling
  src/static/css/2019.css
Labels: design, development

#1731 Fix bug with unsetting code background color in places
  src/static/css/2019.css
Labels: bug, development

#1733 Improve Russian translation
  src/content/ru/2020/capabilities.md
  src/templates/ru/2020/base.html
  src/templates/ru/base.html
Labels: translation

#1706 Support redirecting uppercase chapter urls to lowercase
  .github/linters/.python-lint
  src/server/tests/routes_test.py
  src/server/tests/validate_test.py
  src/server/validate.py
  src/tools/test/test_status_codes.js
Labels: development

#1714 Stop including chapters with no featured quote in home page
  src/tools/generate/generate_featured_chapters.js
Labels: bug, development

#1723 Caching: Added new picture and tweaked text
  src/config/2020.json
  src/content/en/2020/caching.md
  src/static/images/2020/caching/cache-control-and-max-age-and-expires-2019.png
  src/static/images/2020/caching/cache-control-and-max-age-and-expires.png
  src/static/images/2020/caching/cache-control-directives.png
  src/static/images/2020/caching/cache-ttl-lighthouse-score.png
  src/static/images/2020/caching/cache-wasted-bytes-lighthouse.png
  src/static/images/2020/caching/cacheable-and-non-cacheable.png
  src/static/images/2020/caching/cacheable-by-resource-type.png
  src/static/images/2020/caching/chrome-dev-tools.png
  src/static/images/2020/caching/invalid-last-modified-and-expires-and-date.png
  src/static/images/2020/caching/last-modified-and-etag-2019.png
  src/static/images/2020/caching/last-modified-and-etag.png
  src/static/images/2020/caching/lighthouse-caching-audit.png
  src/static/images/2020/caching/luna-cat.png
  src/static/images/2020/caching/request-response-flow-with-caching.png
  src/static/images/2020/caching/resource-age-party-and-type-wise-groups-1st-party.png
Labels: editing

#1722 Update Third Parties contributors
  src/content/en/2020/third-parties.md
Labels: editing

#1738 Remove formatting character from caching.md
  src/content/en/2020/caching.md
Labels: editing

#1740 Adjust position of switcher arrow
  src/config/2020.json
  src/static/css/2019.css
Labels: bug, development

#1743 Update Twitter handle for Caleb Queern
  src/config/2020.json
Labels: editing

#1745 Replace gzip with Gzip and brotli with Brotli
  src/content/en/2019/caching.md
  src/content/en/2019/cdn.md
  src/content/en/2019/compression.md
  src/content/en/2019/http2.md
  src/content/en/2019/javascript.md
  src/content/en/2020/caching.md
  src/content/es/2019/javascript.md
  src/content/fr/2019/caching.md
  src/content/fr/2019/compression.md
  src/content/fr/2019/javascript.md
  src/content/ja/2019/caching.md
  src/content/ja/2019/cdn.md
  src/content/ja/2019/compression.md
  src/content/ja/2019/http2.md
  src/content/ja/2019/javascript.md
  src/content/pt/2019/http2.md
  src/content/pt/2019/javascript.md
Labels: editing

#1744 Fix relative links in ebook
  src/templates/base/base.html
Labels: bug, development

#1748 Caption and Description fix for CSS Figure 28
  src/content/en/2020/css.md
Labels: editing

#1741 Add object support for CSS chapter
  src/content/en/2020/css.md
  src/static/css/page.css
  src/static/images/2020/css/p3-chromaticity-big.svg
  src/templates/base/base.html
Labels: development

#1757 Fix large table in CSS chapter in ebook
  src/content/en/2020/css.md
Labels: bug, development

#1762 Fix typo in 2020 Performance chapter
  src/content/en/2020/performance.md
Labels: editing

#1765 Fix mention of font-weight instead of font-width
  src/content/en/2020/fonts.md
Labels: editing

#1763 Fix one last TODO comment in 2020 Performance chapter
  src/content/en/2020/performance.md
Labels: editing

#1755 Fix spacing in ToC footer menu
  src/static/css/2019.css
Labels: bug, design, development

#1753 Track ebook clicks from menu
  src/templates/base/base.html
  src/templates/base/table_of_contents.html
Labels: development

#1767 Added Dutch base templates
  src/config/2019.json
  src/config/2020.json
  src/server/language.py
  src/templates/nl/2019/base.html
  src/templates/nl/2019/contributors.html
  src/templates/nl/2019/index.html
  src/templates/nl/2019/methodology.html
  src/templates/nl/2019/table_of_contents.html
  src/templates/nl/2020/base.html
  src/templates/nl/2020/contributors.html
  src/templates/nl/2020/index.html
  src/templates/nl/2020/methodology.html
  src/templates/nl/2020/table_of_contents.html
  src/templates/nl/accessibility_statement.html
  src/templates/nl/base.html
  src/templates/nl/base_chapter.html
  src/templates/nl/base_ebook.html
  src/templates/nl/error.html
Labels: translation

#1737 2020 JavaScript edits
  src/content/en/2020/javascript.md
  src/static/images/2020/javascript/frameworks-bytes.png
  src/static/images/2020/javascript/frameworks-main-thread-no-ember-diff.png
  src/static/images/2020/javascript/frameworks-main-thread-no-ember.png
  src/static/images/2020/javascript/frameworks-main-thread.png
  src/static/images/2020/javascript/prefetch-distribution.png
  src/static/images/2020/javascript/preload-distribution.png
Labels: editing

#1761 Simplified Chinese translation for 2020 Performance chapter
  src/config/2020.json
  src/content/zh-CN/2020/performance.md
Labels: translation

#1774 a few more fixes of Simplified Chinese translation for 2020 Performan…
  src/content/zh-CN/2020/performance.md
Labels: translation

#1768 Media 2020 queries.
  sql/2020/05_Media/bytes_per_pixel.sql
  sql/2020/05_Media/img_covid_in_path.sql
  sql/2020/05_Media/pixel_volume.sql
Labels: analysis

#1777 Further edits to the JS chapter
  sql/2020/02_JavaScript/module_and_nomodule.sql
  src/content/en/2020/javascript.md
Labels: editing

#1752 Copyedit of 2020 Accessibility chapter and addition of more figures
  src/content/en/2020/accessibility.md
  src/static/images/2020/accessibility/alt-attribute-lengths.png
  src/static/images/2020/accessibility/common-aria-roles.png
  src/static/images/2020/accessibility/common-video-attributes.png
  src/static/images/2020/accessibility/descriptive-page-titles.png
  src/static/images/2020/accessibility/labels-and-placeholders.png
  src/static/images/2020/accessibility/link-types.png
  src/static/images/2020/accessibility/most-used-aria-attributes.png
  src/static/images/2020/accessibility/sites-with-sufficient-color-contrast-2019-2020.png
  src/static/images/2020/accessibility/sites-with-zooming-and-scaling-disabled.png
  src/static/images/2020/accessibility/skip-links.png
  src/static/images/2020/accessibility/tab-index-values.png
  src/static/images/2020/accessibility/title-and-alt-same.png
  src/static/images/2020/accessibility/valid-html-lang.png
  src/static/images/2020/accessibility/videos-using-track.png
  src/static/images/2020/accessibility/zoom-and-scale.png
Labels: editing

#1779 Typo Fixed
  src/content/en/2020/pwa.md
Labels: editing

#1776 Translate 2019 Accessibility chapter to Dutch
  src/content/nl/2019/accessibility.md
Labels: translation

#1782 Extra space causing comment to show in French Third-Parties chapter
  src/content/fr/2019/third-parties.md
Labels: bug, translation

#1780 Clean up various GitHub action log messages
  .github/workflows/code-static-analysis.yml
  .github/workflows/compress-images.yml
  .github/workflows/generate_chapters.yml
  .github/workflows/linter.yml
  .github/workflows/predeploy.yml
  .github/workflows/test_website.yml
  src/server/validate.py
Labels: development

#1785 Misc README updates
  README.md
Labels: project management

#1786 Recompress JavaScript images
  src/static/images/2020/javascript/async-defer-mobile.png
  src/static/images/2020/javascript/bytes-2020.png
  src/static/images/2020/javascript/bytes-by-3p-desktop.png
  src/static/images/2020/javascript/bytes-by-3p-mobile.png
  src/static/images/2020/javascript/compression-method-3p.png
  src/static/images/2020/javascript/compression-method-request.png
  src/static/images/2020/javascript/correlations.png
  src/static/images/2020/javascript/external-inline-mobile.png
  src/static/images/2020/javascript/frameworks-bytes.png
  src/static/images/2020/javascript/frameworks-libraries.png
  src/static/images/2020/javascript/frameworks-main-thread-no-ember-diff.png
  src/static/images/2020/javascript/frameworks-main-thread-no-ember.png
  src/static/images/2020/javascript/frameworks-main-thread.png
  src/static/images/2020/javascript/lighthouse-unminified-js-by-3p.png
  src/static/images/2020/javascript/lighthouse-unminified-js.png
  src/static/images/2020/javascript/main-thread-time.png
  src/static/images/2020/javascript/page-weight-per-content-type.png
  src/static/images/2020/javascript/prefetch-distribution.png
  src/static/images/2020/javascript/preload-distribution.png
  src/static/images/2020/javascript/requests-2019.png
  src/static/images/2020/javascript/requests-2020.png
  src/static/images/2020/javascript/requests-by-3p-desktop.png
  src/static/images/2020/javascript/requests-by-3p-mobile.png
  src/static/images/2020/javascript/unused-js-bytes-distribution.png
  src/static/images/2020/javascript/vulnerabilities-by-severity.png
Labels: performance

#1787 TinyPng Images
  src/static/images/2020/capabilities/async_clipboard_api.png
  src/static/images/2020/capabilities/badging_api.png
  src/static/images/2020/capabilities/content_indexing_api.png
  src/static/images/2020/capabilities/get_installed_related_apps.png
  src/static/images/2020/capabilities/idle_detection_api.png
  src/static/images/2020/capabilities/notification_triggers_api.png
  src/static/images/2020/capabilities/periodic_background_sync_api.png
  src/static/images/2020/capabilities/quic_transport.png
  src/static/images/2020/capabilities/screen_wake_lock_api.png
  src/static/images/2020/capabilities/storage_manager_api_estimate.png
  src/static/images/2020/capabilities/storage_manager_api_persist.png
  src/static/images/2020/capabilities/websocketstreams.png
  src/static/images/2020/mobile-web/aggregate-lcp-performance-by-device.png
  src/static/images/2020/mobile-web/eastpak-12-ctr.png
  src/static/images/2020/mobile-web/eastpak-20-ctr.png
  src/static/images/2020/mobile-web/ecommerce-sites-using-a-search-input.png
  src/static/images/2020/mobile-web/landing-page-cta.png
  src/static/images/2020/mobile-web/median-p75-lcp-score.png
  src/static/images/2020/mobile-web/mobile-traffic-distribution.png
  src/static/images/2020/mobile-web/page-loads-across-origins-ranked-by-popularity.png
  src/static/images/2020/mobile-web/pages-with-properly-sized-images.png
  src/static/images/2020/mobile-web/search-input-lyst.png
  src/static/images/2020/mobile-web/sites-with-inputs-using-the-following-input-types.png
  src/static/images/2020/mobile-web/sites-with-properly-sized-tap-targets.png
  src/static/images/2020/mobile-web/sites-with-sufficient-color-contrast.png
  src/static/images/2020/page-weight/bytes-distribution-content-type.png
  src/static/images/2020/page-weight/bytes-distribution.png
  src/static/images/2020/page-weight/requests-content-type.png
  src/static/images/2020/page-weight/requests-distribution.png
  src/static/images/2020/page-weight/response-distribution-format.png
  src/static/images/2020/page-weight/response-distribution-images.png
  src/static/images/2020/third-parties/cpu-time-by-category.png
  src/static/images/2020/third-parties/distribution-of-request-count.png
  src/static/images/2020/third-parties/page-size-by-category.png
  src/static/images/2020/third-parties/page-size-by-host.png
  src/static/images/2020/third-parties/pages-with-thirdparties.png
  src/static/images/2020/third-parties/redirects-body-size.png
  src/static/images/2020/third-parties/requests-before-dom-by-category.png
  src/static/images/2020/third-parties/requests-cached-by-content-type.png
  src/static/images/2020/third-parties/requests-with-tao.png
  src/static/images/2020/third-parties/thirdparty-by-content-types.png
  src/static/images/2020/third-parties/top-domains-by-prevalence.png
Labels: performance

#1790 High resolution images
  src/static/images/2020/accessibility/common-aria-roles.png
  src/static/images/2020/compression/compession-methods-by-content-type.png
  src/static/images/2020/markup/distribution-of-elements-per-page.png
  src/static/images/2020/markup/document-language.png
  src/static/images/2020/markup/document-size.png
  src/static/images/2020/markup/element-diversity-element-types.png
  src/static/images/2020/markup/element-diversity.png
  src/static/images/2020/markup/script-use.png
  src/static/images/2020/mobile-web/aggregate-lcp-performance-by-device.png
  src/static/images/2020/mobile-web/ecommerce-sites-using-a-search-input.png
  src/static/images/2020/mobile-web/median-p75-lcp-score.png
  src/static/images/2020/mobile-web/mobile-traffic-distribution.png
  src/static/images/2020/mobile-web/page-loads-across-origins-ranked-by-popularity.png
  src/static/images/2020/mobile-web/pages-with-properly-sized-images.png
  src/static/images/2020/mobile-web/sites-with-inputs-using-the-following-input-types.png
  src/static/images/2020/mobile-web/sites-with-properly-sized-tap-targets.png
  src/static/images/2020/mobile-web/sites-with-sufficient-color-contrast.png
  src/static/images/2020/privacy/privacy-websites-with-privacy-link.png
  src/static/images/2020/resource-hints/adoption-of-resource-hints.png
  src/static/images/2020/resource-hints/median-number-of-hints-per-page.png
  src/static/images/2020/resource-hints/resource-hint-adoption-2019-vs-2020.png
  src/static/images/2020/resource-hints/resource-hint-adoption-onservice-worker-pages.png
  src/static/images/2020/security/security-adoption-of-https-per-country.png
  src/static/images/2020/seo/seo-canonical-implementation-method.png
  src/static/images/2020/seo/seo-nofollow-ugc-sponsored-attributes.png
  src/static/images/2020/seo/seo-presence-of-canonical-tag.png
  src/static/images/2020/seo/seo-presence-of-h-elements.png
  src/static/images/2020/seo/seo-presence-of-non-empty-h-elements.png
  src/static/images/2020/seo/seo-robots-directive-use.png
  src/static/images/2020/seo/seo-title-character-count.png
Labels: editing

#1792 Create a stories directory
  src/templates/en/2020/stories/README.md
Labels: development

#1791 translated 2020/performance to Dutch
  src/content/nl/2020/performance.md
Labels: translation

#1778 Alternative improvement to figure menus
  src/static/css/page.css
  src/templates/base/base.html
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_ebooks.js
  src/tools/generate/generate_table_figure_dropdowns.js
Labels: bug, development

#1793 Identify links in languages that differ to the page
  src/static/css/2019.css
Labels: design, development, translation

#1799 Oxford commas for Contributor teams
  src/static/css/ebook.css
  src/templates/base/base_ebook.html
  src/templates/base/contributors.html
Labels: bug, development

#1789 Improved home hero image
  src/static/images/home-hero-2019.png
  src/static/images/home-hero-2020.png
  src/static/images/home-hero-bg.png
  src/templates/base/base_ebook.html
  src/templates/base/index.html
Labels: development

#1801 Fix dropdown JS issue raised by CodeQL
  src/tools/generate/generate_table_figure_dropdowns.js
Labels: bug

#1805 Fix JS figure img
  src/static/images/2020/javascript/requests-by-3p-desktop.png
Labels: editing

#1794 ES: #498: 2019 templates, improve translation in Spanish templates
  src/templates/es/2019/base.html
  src/templates/es/2019/contributors.html
  src/templates/es/2019/index.html
  src/templates/es/2019/table_of_contents.html
Labels: good first issue, translation

#1795 ES: #498: templates, error.html, improve translation in Spanish
  src/templates/es/error.html
Labels: good first issue, translation

#1803 translated Javascript 2020 dutch
  src/content/nl/2020/javascript.md
Labels: translation

#1797 ES: #498: templates, base.html, improve translation in Spanish
  src/templates/es/base.html
Labels: good first issue, translation

#1806 ES: #498: templates, add base_ebook.html, translate to Spanish
  src/templates/es/base_ebook.html
Labels: translation

#1802 ES: #498: templates, base_chapter.html, improve translation in Spanish
  src/templates/es/base_chapter.html
Labels: translation

#1812 Jamstack 2020 queries: Add Nuxt.js and Docusaurus
  sql/2020/17_Jamstack/adoption_of_image_formats_in_ssgs.sql
  sql/2020/17_Jamstack/core_web_vitals_distribution.sql
  sql/2020/17_Jamstack/core_web_vitals_passing.sql
  sql/2020/17_Jamstack/distribution_of_page_weight_requests_and_co2_grams_per_ssg_web_page.sql
  sql/2020/17_Jamstack/median_lighthouse_score.sql
  sql/2020/17_Jamstack/ssg_compared_to_2019.sql
  sql/2020/17_Jamstack/third_party_bytes_and_requests_on_ssgs.sql
Labels: analysis

#1814 Translated 2020 Markup in Dutch
  src/content/en/2020/cms.md
  src/content/nl/2020/markup.md
Labels: translation

#1820 Translated CMS 2020 to Dutch
  src/content/nl/2020/cms.md
Labels: translation

#1809 Translate 2020 methodology for Traditional Chinese
  src/templates/zh-TW/2020/methodology.html
Labels: translation

#1788 Translate 2020 Performance chapter for Traditional Chinese
  src/config/2020.json
  src/content/zh-TW/2020/performance.md
Labels: translation

#1813 ES: #498: templates, add accessibility_statement.html, translate to Spanish
  src/templates/es/accessibility_statement.html
Labels: accessibility, translation

#1818 Allow quotes in featured quotes and stats
  src/templates/base/index.html
Labels: development

#1815 Add stories to sitemap
  src/server/routes.py
  src/templates/en/2020/stories/page_content.html
  src/templates/en/2020/stories/web-almanac-2020-page-content/index.html
  src/tools/generate/generate_sitemap.js
Labels: development

#1823 Linting fixes for Stories
  src/server/routes.py
  src/templates/en/2020/stories/page_content.html
Labels: bug, development

#1824 Ignore Stories from Lighthouse Checks
  src/tools/scripts/set_lighthouse_urls.sh
Labels: development

#1825 Minor fixes for the Edited by functionality
  src/content/fr/2019/css.md
  src/static/css/page.css
Labels: bug, development

#1816 Copyedit of Fonts 2020 chapter
  sql/2020/04_Fonts/04_04.self_hosted_vs_hosted_with_fcp.sql
  sql/2020/04_Fonts/04_14a.variable_font_comparison_fcp.sql
  src/content/en/2020/fonts.md
  src/static/images/2020/fonts/fonts-font-display-performance-desktop.png
  src/static/images/2020/fonts/fonts-font-display-performance-mobile.png
  src/static/images/2020/fonts/fonts-median-fcp-of-sites-using-hosted-fonts.png
  src/static/images/2020/fonts/fonts-median-lcp-of-sites-using-hosted-fonts.png
  src/static/images/2020/fonts/fonts-web-hosting-performance-desktop.png
  src/static/images/2020/fonts/fonts-web-hosting-performance-mobile.png
Labels: editing

#1827 Add timestamps to stories
  src/templates/en/2020/stories/page_content.html
  src/tools/generate/generate_timestamps.js
Labels: development

#1829 Correct Twitter Meta data for Story
  src/static/images/home-hero-2020-part-1.png
  src/static/images/home-hero-2020-part-2.png
  src/static/images/home-hero-2020-part-3.png
  src/static/images/home-hero-2020-part-4.png
  src/templates/en/2020/stories/page_content.html
Labels: bug, development

#1831 Fix screenshots for CMS chapter
  src/static/images/2020/cms/cms-accessibility-lighthouse-score.png
  src/static/images/2020/cms/cms-adoption.png
  src/static/images/2020/cms/cms-carbon-emissions-per-cms-page-view.png
  src/static/images/2020/cms/cms-median-cms-kb-per-resource-type.png
  src/static/images/2020/cms/cms-real-user-largest-contentful-paint-experiences.png
  src/static/images/2020/cms/cms-seo-lighthouse-score.png
Labels: bug, editing
