Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-10, with the labels that each got.

#1159 A11Y queries
  sql/2020/08_Accessibility/alt_ending_in_image_extension.sql
  sql/2020/08_Accessibility/alt_text_length.sql
  sql/2020/08_Accessibility/anchors_with_role_button.sql
  sql/2020/08_Accessibility/color_contrast.sql
  sql/2020/08_Accessibility/common_alt_text_length.sql
  sql/2020/08_Accessibility/common_aria_role.sql
  sql/2020/08_Accessibility/common_element_attributes.sql
  sql/2020/08_Accessibility/common_html_lang_attrib.sql
  sql/2020/08_Accessibility/common_video_attributes.sql
  sql/2020/08_Accessibility/div_span_with_button_or_link_role.sql
  sql/2020/08_Accessibility/duplicate_id.sql
  sql/2020/08_Accessibility/form_labels.sql
  sql/2020/08_Accessibility/lighthouse_a11y_audits.sql
  sql/2020/08_Accessibility/lighthouse_a11y_score.sql
  sql/2020/08_Accessibility/page_title.sql
  sql/2020/08_Accessibility/placeholder_but_no_label.sql
  sql/2020/08_Accessibility/positive_tabindex.sql
  sql/2020/08_Accessibility/same_page_links.sql
  sql/2020/08_Accessibility/shortcut_keys.sql
  sql/2020/08_Accessibility/skip_links.sql
  sql/2020/08_Accessibility/sr_only_classes.sql
  sql/2020/08_Accessibility/table_stats.sql
  sql/2020/08_Accessibility/th_td_stats.sql
  sql/2020/08_Accessibility/title_used_with_alt.sql
  sql/2020/08_Accessibility/total_role_tab_with_selected_and_controls.sql
  sql/2020/08_Accessibility/valid_html_lang.sql
  sql/2020/08_Accessibility/video_track_usage.sql
  sql/2020/08_Accessibility/viewport_zoom_scale.sql
Labels: analysis

#1339 Fix incorrectly escaped symbols
  src/content/en/2019/fonts.md
  src/content/en/2019/media.md
  src/content/en/2019/seo.md
  src/content/es/2019/fonts.md
  src/content/es/2019/media.md
  src/content/ja/2019/fonts.md
  src/content/ja/2019/media.md
  src/content/ja/2019/seo.md
Labels: bug

#1337 Translate 2019 Media chapter to French
  src/content/fr/2019/media.md
  src/templates/fr/2019/featured_chapters.html
Labels: translation

#1336 Translate accessibility.md to Portuguese
  src/config/2019.json
  src/content/pt/2019/accessibility.md
  src/templates/pt/2019/featured_chapters.html
Labels: translation

#1344 Http2 query fixes
  sql/2020/22_HTTP_2/avg_percentage_of_resources_loaded_over_HTTP_by_version_per_site.sql
  sql/2020/22_HTTP_2/percentage_of_resources_loaded_over_HTTP_by_version_per_site.sql
  sql/2020/22_HTTP_2/tls_adoption_by_http_version.sql
Labels: analysis

#1341 Adds translation of http2.md to Portuguese
  src/config/2019.json
  src/content/pt/2019/http2.md
  src/templates/pt/2019/featured_chapters.html
Labels: hacktoberfest-accepted, translation

#1355 WordPress query for 2020 CMS
  sql/2020/15_CMS/wp_resources.sql
Labels: analysis

#1356 Include media attr in Resource Hints 2020 analysis
  sql/2020/21_Resource_Hints/attribute_usage.sql
Labels: analysis

#1228 Jamstack 2020 queries
  sql/2020/17_JAMstack/README.md
  sql/2020/17_JAMstack/adoption_of_image_formats_in_ssgs.sql
  sql/2020/17_JAMstack/core_web_vitals_distribution.sql
  sql/2020/17_JAMstack/core_web_vitals_passing.sql
  sql/2020/17_JAMstack/distribution_of_page_weight_requests_and_co2_grams_per_ssg_web_page.sql
  sql/2020/17_JAMstack/median_lighthouse_score.sql
  sql/2020/17_JAMstack/ssg_compared_to_2019.sql
  sql/2020/17_JAMstack/third_party_bytes_and_requests_on_ssgs.sql
Labels: analysis

#1091 Performance 2020 queries
  sql/2020/09_Performance/lh5_performance_score_distribution.sql
  sql/2020/09_Performance/lh6_performance_score_distribution.sql
  sql/2020/09_Performance/lh6_vs_lh5_performance_score_01.sql
  sql/2020/09_Performance/lh6_vs_lh5_performance_score_02.sql
  sql/2020/09_Performance/lighthouse_performace_audits.sql
  sql/2020/09_Performance/median_lcp_score_by_month.sql
  sql/2020/09_Performance/offline_origins.sql
  sql/2020/09_Performance/performance_observer.sql
  sql/2020/09_Performance/web_vitals_by_country.sql
  sql/2020/09_Performance/web_vitals_by_device.sql
  sql/2020/09_Performance/web_vitals_by_ect.sql
  sql/2020/09_Performance/web_vitals_distribution_by_device.sql
Labels: analysis

#1338 Check if audit is applicable
  sql/2020/08_Accessibility/lighthouse_a11y_audits.sql
  sql/2020/14_PWA/lighthouse_pwa_audits.sql
Labels: analysis

#1358 2020 graphics
  src/static/images/2019/capabilities/hero_lg.jpg
  src/static/images/2019/capabilities/hero_lg.webp
  src/static/images/2019/capabilities/hero_sm.jpg
  src/static/images/2019/capabilities/hero_sm.webp
  src/static/images/2019/capabilities/hero_xl.jpg
  src/static/images/2019/jamstack/hero_lg.jpg
  src/static/images/2019/jamstack/hero_lg.webp
  src/static/images/2019/jamstack/hero_sm.jpg
  src/static/images/2019/jamstack/hero_sm.webp
  src/static/images/2019/jamstack/hero_xl.jpg
  src/static/images/2019/privacy/hero_lg.jpg
  src/static/images/2019/privacy/hero_lg.webp
  src/static/images/2019/privacy/hero_sm.jpg
  src/static/images/2019/privacy/hero_sm.webp
  src/static/images/2019/privacy/hero_xl.jpg
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/ebook.ejs.html
Labels: design

#1360 SEO 2020 review changes
  sql/2020/07_SEO/pages_almanac_by_device_and_alternate_media.sql
  sql/2020/07_SEO/pages_almanac_by_device_and_content_language.sql
  sql/2020/07_SEO/summary_requests_by_device_and_http_content_language.sql
  sql/2020/07_SEO/summary_requests_by_device_and_http_vary.sql
Labels: analysis

#1135 Ecommerce 2020 queries
  sql/2020/16_Ecommerce/README.md
  sql/2020/16_Ecommerce/core_web_vitals_distribution_byvendor_bydevice.sql
  sql/2020/16_Ecommerce/core_web_vitals_passingmetrics_byvendor_bydevice.sql
  sql/2020/16_Ecommerce/pagestats_html_bydevice.sql
  sql/2020/16_Ecommerce/pagestats_image_bydevice.sql
  sql/2020/16_Ecommerce/pagestats_image_bydevice_format.sql
  sql/2020/16_Ecommerce/pagestats_image_dimensions_bydevice.sql
  sql/2020/16_Ecommerce/pagestats_percentile_bydevice_format.sql
  sql/2020/16_Ecommerce/pagestats_percentiles_bydevice.sql
  sql/2020/16_Ecommerce/pct_3pusage_bydevice.sql
  sql/2020/16_Ecommerce/pct_3pusage_bydevice_vendor.sql
  sql/2020/16_Ecommerce/pct_3pusage_bydevice_vendor_category.sql
  sql/2020/16_Ecommerce/pct_ampusage_bydevice_vendor.sql
  sql/2020/16_Ecommerce/pct_ecommsites_bydevice_compare20192020.sql
  sql/2020/16_Ecommerce/top_adplatform_bydevice_vendor.sql
  sql/2020/16_Ecommerce/top_adplatform_bydevice_vendor_wapp.sql
  sql/2020/16_Ecommerce/top_analytics_bydevice_vendor.sql
  sql/2020/16_Ecommerce/top_analytics_bydevice_vendor_wapp.sql
  sql/2020/16_Ecommerce/top_cdn_bydevice.sql
  sql/2020/16_Ecommerce/top_cdn_bydevice_vendor_cdn.sql
  sql/2020/16_Ecommerce/top_cdn_bydevice_vendor_wapp.sql
  sql/2020/16_Ecommerce/top_vendors.sql
Labels: analysis

#1366 Add sheets_gid and sql_file to figure_link
  src/templates/base/2019/base.html
Labels: development

#1367 Remove use of set-env as being deprecated by GitHub Actions
  .github/workflows/linter.yml
  .github/workflows/test-template-changes.yml
  src/tools/scripts/test_template_changes.sh
Labels: development

#1368 Correction to HTTP/2 by site usage queries
  sql/2020/22_HTTP_2/avg_percentage_of_resources_loaded_over_HTTP_by_version_per_site.sql
  sql/2020/22_HTTP_2/percentiles_of_resources_loaded_over_HTTP2_or_better_per_site.sql
Labels: analysis

#1371 Stop over linting
  .github/workflows/linter.yml
  .github/workflows/test_website.yml
Labels: development

#1369 Markup 2020 script tag types
  sql/2020/03_Markup/pages_almanac_by_device_and_script_type_frequency.sql
Labels: analysis

#1370 SEO 2020 meta robots and link additions
  sql/2020/07_SEO/pages_wpt_bodies_by_device.sql
  sql/2020/07_SEO/pages_wpt_bodies_by_device_and_percentile.sql
  sql/2020/07_SEO/pages_wpt_bodies_by_device_and_same_site_link_count.sql
Labels: analysis

#1372 Add CodeQL GitHub Action
  .github/workflows/code-static-analysis.yml
  src/static/js/chapter.js
  src/templates/base/2019/base_ebook.html
  src/templates/base/2019/contributors.html
  src/tools/generate/generate_chapters.js
  src/tools/test/test_status_codes.js
Labels: development

#1329 Security 2020 queries
  sql/2020/11_Security/cookie_attributes.sql
  sql/2020/11_Security/csp_allowed_host_frequency.sql
  sql/2020/11_Security/csp_directives_usage.sql
  sql/2020/11_Security/csp_most_common_header.sql
  sql/2020/11_Security/csp_number_of_allowed_hosts.sql
  sql/2020/11_Security/hsts_attributes.sql
  sql/2020/11_Security/hsts_max_age_percentiles.sql
  sql/2020/11_Security/iframe_allow_directives.sql
  sql/2020/11_Security/iframe_attribute_popular_hosts.sql
  sql/2020/11_Security/iframe_attributes_usage.sql
  sql/2020/11_Security/iframe_sandbox_directives.sql
  sql/2020/11_Security/security_headers_prevalence.sql
  sql/2020/11_Security/sri_coverage_per_page.sql
  sql/2020/11_Security/sri_hash_functions.sql
  sql/2020/11_Security/sri_popular_hosts.sql
  sql/2020/11_Security/sri_usage.sql
  sql/2020/11_Security/tls_ca_issuers_pages.sql
  sql/2020/11_Security/tls_ca_issuers_requests.sql
  sql/2020/11_Security/tls_cipher_suite.sql
  sql/2020/11_Security/tls_forward_secrecy.sql
  sql/2020/11_Security/tls_versions_pages.sql
  sql/2020/11_Security/tls_versions_requests.sql
Labels: ASAP, analysis

#1376 Highlight H4, H5 and H6 in table of contents as well
  src/static/js/chapter.js
Labels: design, development

#1384 Fix chapter generation and display for 2020 chapters
  src/templates/base/2019/base_chapter.html
  src/tools/generate/generate_chapters.js
Labels: development

#1389 Fixes to no-deploy version of deployment script
  src/tools/scripts/deploy.sh
Labels: development

#1388 added element frequency queries
  sql/2020/03_Markup/pages_element_count_by_device_and_element_count.sql
  sql/2020/03_Markup/pages_element_count_by_device_and_element_type_count.sql
Labels: analysis

#1395 Add error handling for base template
  src/server/helpers.py
  src/tools/test/test_status_codes.js
Labels: bug, development
