Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-02, with the labels that each got.

#660 Another batch of Accessibility fixes
  src/config/2019.json
  src/content/en/2019/accessibility.md
  src/content/en/2019/caching.md
  src/content/en/2019/cdn.md
  src/content/en/2019/cms.md
  src/content/en/2019/compression.md
  src/content/en/2019/css.md
  src/content/en/2019/ecommerce.md
  src/content/en/2019/http2.md
  src/content/en/2019/javascript.md
  src/content/en/2019/markup.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/page-weight.md
  src/content/en/2019/security.md
  src/content/en/2019/seo.md
  src/content/es/2019/css.md
  src/content/es/2019/ecommerce.md
  src/content/es/2019/javascript.md
  src/content/es/2019/markup.md
  src/content/fr/2019/cms.md
  src/content/fr/2019/markup.md
  src/content/ja/2019/cdn.md
  src/content/ja/2019/markup.md
  src/templates/en/2019/base_chapter.html
  src/templates/en/2019/chapters/accessibility.html
  src/templates/en/2019/chapters/caching.html
  src/templates/en/2019/chapters/cdn.html
  src/templates/en/2019/chapters/cms.html
  src/templates/en/2019/chapters/compression.html
  src/templates/en/2019/chapters/css.html
  src/templates/en/2019/chapters/ecommerce.html
  src/templates/en/2019/chapters/http2.html
  src/templates/en/2019/chapters/javascript.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/chapters/mobile-web.html
  src/templates/en/2019/chapters/page-weight.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/en/2019/chapters/security.html
  src/templates/en/2019/chapters/seo.html
  src/templates/fr/2019/base_chapter.html
  src/templates/fr/2019/chapters/cms.html
  src/templates/fr/2019/chapters/markup.html
Labels: Development

#662 Typo in SPDY
  src/content/en/2019/http2.md
  src/templates/en/2019/chapters/http2.html
Labels: Writing

#661 Translation of Http2 chapter to Japanese
  src/content/ja/2019/http2.md
Labels: Translation

#667 FR+EN boris improvements
  src/content/en/2019/caching.md
  src/content/fr/2019/resource-hints.md
  src/content/fr/2019/third-parties.md
  src/templates/fr/2019/chapters/resource-hints.html
  src/templates/fr/2019/chapters/third-parties.html
Labels: Translation

#664 Home page accessibility fixes
  src/static/css/2019.css
  src/static/css/index.css
  src/static/css/page.css
  src/static/images/intro-background-fit.svg
  src/templates/ar/2019/base.html
  src/templates/en/2019/base.html
  src/templates/en/2019/index.html
  src/templates/es/2019/base.html
  src/templates/es/2019/index.html
  src/templates/fr/2019/base.html
  src/templates/fr/2019/index.html
Labels: Design

#659 Security chapter typos
  src/content/en/2019/security.md
  src/templates/en/2019/chapters/security.html
Labels: Writing

#614 Add randomized featured chapters
  src/templates/en/2019/featured_chapters.html
  src/templates/en/2019/index.html
  src/templates/fr/2019/featured_chapters.html
  src/templates/fr/2019/index.html
Labels: Design, Development

#653 Autogenerate chapters on commit to master
  .github/workflows/generate_chapters.yml
Labels: Development

#670 HTTP2 typos
  src/content/en/2019/http2.md
Labels: Writing

#665 Add Accessibility Statement
  src/main.py
  src/static/css/2019.css
  src/templates/ar/2019/base.html
  src/templates/en/2019/accessibility_statement.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/sitemap.xml
  src/tools/generate/generate_sitemap.js
Labels: Writing, enhancement

#674 Improve wording and links in accessibility statement
  src/templates/en/2019/accessibility_statement.html
Labels: Accessibility, Writing
