Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-04, with the labels that each got.

#709 Translation of security chapter to Japanese
  src/templates/ja/2019/base.html
Labels: Translation

#710 Review of Security Chapter into Japanese
  src/config/2019.json
  src/content/en/2019/pwa.md
  src/content/ja/2019/pwa.md
  src/content/ja/2019/security.md
Labels: Translation

#712 Validate chapters, languages and years
  src/config.py
  src/config/2019.json
  src/language.py
  src/main.py
  src/validate.py
  src/validate_test.py
Labels: Development

#714 Fix some 404s
  src/config/2019.json
  src/content/en/2019/cdn.md
  src/content/en/2019/javascript.md
  src/content/fr/2019/third-parties.md
  src/content/ja/2019/cdn.md
  src/content/ja/2019/security.md
  src/templates/en/2019/chapters/javascript.html
  src/validate.py
Labels: bug

#715 Fix misc typos and update word list
  src/config/spelling_ignore_words.txt
  src/templates/en/2019/accessibility_statement.html
  src/templates/en/2019/index.html
  src/templates/en/2019/methodology.html
  src/templates/ja/2019/index.html
Labels: Writing

#717 Add vary header for base URL
  src/main.py
Labels: ASAP, Development, bug

#718 Translation of mobile-web chapter to Japanese
  src/content/ja/2019/mobile-web.md
Labels: Translation

#720 Validate lang and year before chapter
  src/validate.py
Labels: bug

#722 Server log improvements and error GA events
  src/main.py
  src/templates/error/error.html
  src/validate.py
Labels: Development, enhancement

#724 Add link for full image for markup fig 7
  src/content/en/2019/markup.md
  src/content/es/2019/markup.md
  src/content/fr/2019/markup.md
  src/content/ja/2019/markup.md
  src/static/images/2019/markup/fig7_full.png
Labels: Writing

#723 Language and year specific error pages
  src/main.py
  src/templates/base/2019/error.html
  src/templates/en/2019/error.html
  src/templates/error/400.html
  src/templates/error/404.html
  src/templates/error/500.html
  src/templates/error/502.html
  src/templates/es/2019/error.html
  src/templates/fr/2019/error.html
  src/templates/ja/2019/error.html
  src/validate.py
Labels: Development, Translation

#725 Comment lang code
  src/main.py
Labels: Development

#727 Fix Default Lang for sitemap
  src/main.py
Labels: bug

#729 Resize dropdown arrow image
  src/static/images/dropdown-arrow.png
Labels: performance

#730 Fix incorrect image in CSS chapter.
  src/static/images/2019/css/fig15.png
Labels: analysis, bug

#732 Improved index sidebar
  src/static/css/page.css
  src/static/js/chapter.js
  src/templates/base/2019/methodology.html
Labels: development, enhancement

#734 Add test for index
  src/static/js/chapter.js
Labels: bug

#735 Stop showing scrollbars when not needed for code blocks
  src/static/css/page.css
Labels: bug

#739 Slightly better icons
  src/static/images/queries.png
  src/static/images/results.png
Labels: design

#741 Translation of ecommerce chapter to Japanese
  src/content/ja/2019/ecommerce.md
  src/templates/ja/2019/base.html
  src/templates/ja/2019/featured_chapters.html
Labels: translation

#737 Ref links for chapter headings and figures
  src/content/en/2019/fonts.md
  src/content/en/2019/security.md
  src/content/en/2019/third-parties.md
  src/content/ja/2019/third-parties.md
  src/static/css/page.css
  src/static/images/2019/fonts/fig19.png
  src/static/images/link.svg
  src/templates/base/2019/base_chapter.html
  src/templates/en/2019/accessibility_statement.html
  src/templates/en/2019/chapters/markup.html
  src/templates/en/2019/methodology.html
  src/templates/fr/2019/methodology.html
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_figure_ids.js
  src/tools/generate/generate_header_links.js
Labels: design, enhancement

#736 Translation of cms chapter to Japanese
  src/content/ja/2019/cms.md
Labels: translation

#742 Translation of SEO chapter
  src/content/fr/2019/seo.md
  src/templates/fr/2019/base.html
  src/templates/fr/2019/featured_chapters.html
Labels: translation

#744 Missing escape in one of the Japanese Bios
  src/templates/ja/2019/base.html
Labels: bug

#745 Misc HTML fixes
  src/content/en/2019/ecommerce.md
  src/content/es/2019/ecommerce.md
  src/content/ja/2019/ecommerce.md
  src/templates/base/2019/base_chapter.html
  src/templates/ja/2019/base.html
Labels: bug

#746 Featured chapters fr
  src/templates/fr/2019/featured_chapters.html
Labels: translation

#747 Bio hyperlinks
  src/config/2019.json
  src/templates/ar/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
Labels: writing

#748 Missing escape
  src/templates/fr/2019/base.html
Labels: bug

#749 Fix errors in Japanese featured chapters and enable ecommerce
  src/templates/ja/2019/featured_chapters.html
Labels: translation

#750 Translation of featured_chapters to Japanese
  src/templates/ja/2019/featured_chapters.html
Labels: translation

#751 Translation of base.html to Japanese
  src/templates/ja/2019/base.html
Labels: translation

#754 Translation of base_chapter to Japanese
  src/templates/ja/2019/base_chapter.html
  src/templates/ja/2019/index.html
Labels: translation

#756 Fix unintended escape
  src/templates/ja/2019/base.html
Labels: bug

#755 Fonts japanese translation
  src/content/en/2019/fonts.md
  src/content/ja/2019/fonts.md
  src/templates/ja/2019/featured_chapters.html
Labels: translation

#758 Don't translate Web Almanac and HTTP Archive
  src/content/ja/2019/caching.md
  src/content/ja/2019/cdn.md
  src/content/ja/2019/cms.md
  src/content/ja/2019/compression.md
  src/content/ja/2019/css.md
  src/content/ja/2019/ecommerce.md
  src/content/ja/2019/http2.md
  src/content/ja/2019/mobile-web.md
  src/content/ja/2019/page-weight.md
  src/content/ja/2019/performance.md
  src/content/ja/2019/pwa.md
  src/content/ja/2019/security.md
  src/content/ja/2019/third-parties.md
  src/templates/ja/2019/base.html
  src/templates/ja/2019/chapters/caching.html
  src/templates/ja/2019/chapters/cdn.html
  src/templates/ja/2019/chapters/cms.html
  src/templates/ja/2019/chapters/compression.html
  src/templates/ja/2019/chapters/css.html
  src/templates/ja/2019/chapters/ecommerce.html
  src/templates/ja/2019/chapters/http2.html
  src/templates/ja/2019/chapters/mobile-web.html
  src/templates/ja/2019/chapters/page-weight.html
  src/templates/ja/2019/chapters/performance.html
  src/templates/ja/2019/chapters/pwa.html
  src/templates/ja/2019/chapters/security.html
  src/templates/ja/2019/chapters/third-parties.html
  src/templates/ja/2019/contributors.html
  src/templates/ja/2019/featured_chapters.html
  src/templates/ja/2019/index.html
  src/templates/ja/2019/splash.html
Labels: translation

#757 Translate "and" and show correct localized chapter name
  src/templates/ar/2019/base.html
  src/templates/base/2019/base_chapter.html
  src/templates/en/2019/base.html
  src/templates/en/2019/base_chapter.html
  src/templates/es/2019/base.html
  src/templates/es/2019/base_chapter.html
  src/templates/fr/2019/base.html
  src/templates/fr/2019/base_chapter.html
  src/templates/ja/2019/base.html
  src/templates/ja/2019/base_chapter.html
Labels: translation

#753 Remove lastmod from sitemap
  src/templates/sitemap.ejs.xml
  src/templates/sitemap.xml
Labels: SEO

#726 Automatically remove any trailing slashes
  src/main.py
  src/validate.py
Labels: development

#731 Allow up to 200% font zooming for Accessibility
  src/content/en/2019/resource-hints.md
  src/content/fr/2019/resource-hints.md
  src/static/css/2019.css
  src/static/css/index.css
  src/static/css/page.css
  src/templates/base/2019/base.html
  src/templates/base/2019/contributors.html
  src/templates/base/2019/error.html
  src/templates/en/2019/chapters/resource-hints.html
  src/templates/fr/2019/chapters/resource-hints.html
Labels: accessibility, development

#759 FR translation for a11y chapter
  src/content/en/2019/accessibility.md
  src/content/fr/2019/accessibility.md
  src/templates/fr/2019/base.html
  src/templates/fr/2019/featured_chapters.html
Labels: translation

#760 Misc fixes for accessibility translations
  src/templates/ar/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/featured_chapters.html
Labels: translation

#762 Translation of resource-hints chapter to Japanese
  src/content/ja/2019/resource-hints.md
  src/templates/ja/2019/featured_chapters.html
Labels: translation

#761 Stop the intersection observer menus on mobile
  src/static/css/page.css
  src/static/js/chapter.js
Labels: development

#763 Enable Resource Hints in Ja Featured Chapters
  src/templates/ja/2019/featured_chapters.html
Labels: translation
