Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-11, with the labels that each got.

#1398 Resource Hints 2020 query
  sql/2020/21_Resource_Hints/as_attribute_by_year.sql
Labels: analysis

#1400 Freeze GitHub super-linter due to buggy release
  .github/workflows/linter.yml
  .github/workflows/test_website.yml
Labels: ASAP, bug

#1383 Fill out 2020 home page and make it default
  src/server/config.py
  src/server/helpers.py
  src/static/css/index.css
  src/templates/base/2019/accessibility_statement.html
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/base_ebook.html
  src/templates/base/2019/chapter.ejs.html
  src/templates/base/2019/contributors.html
  src/templates/base/2019/ebook.ejs.html
  src/templates/base/2019/error.html
  src/templates/base/2019/index.html
  src/templates/base/2019/methodology.html
  src/templates/base/2019/table_of_contents.html
  src/templates/base/2020/contributors.html
  src/templates/base/2020/index.html
  src/templates/en/2019/base.html
  src/templates/en/2020/base.html
  src/templates/en/2020/contributors.html
  src/templates/en/2020/index.html
  src/templates/en/2020/methodology.html
  src/templates/en/2020/table_of_contents.html
  src/templates/es/2019/base.html
  src/templates/es/2020/base.html
  src/templates/es/2020/contributors.html
  src/templates/es/2020/index.html
  src/templates/es/2020/table_of_contents.html
  src/templates/fr/2019/base.html
  src/templates/fr/2020/base.html
  src/templates/fr/2020/contributors.html
  src/templates/fr/2020/index.html
  src/templates/fr/2020/table_of_contents.html
  src/templates/ja/2019/base.html
  src/templates/ja/2020/base.html
  src/templates/ja/2020/contributors.html
  src/templates/ja/2020/index.html
  src/templates/ja/2020/table_of_contents.html
  src/templates/pt/2019/base.html
  src/templates/pt/2020/base.html
  src/templates/pt/2020/contributors.html
  src/templates/pt/2020/index.html
  src/templates/pt/2020/table_of_contents.html
  src/templates/zh-CN/2019/base.html
  src/templates/zh-CN/2020/base.html
  src/templates/zh-CN/2020/contributors.html
  src/templates/zh-CN/2020/index.html
  src/templates/zh-CN/2020/table_of_contents.html
  src/tools/test/test_status_codes.js
Labels: development

#1401 Lighthouse ci action
  .github/lighthouse/lighthouse-config-dev.json
  .github/lighthouse/lighthouse-config-prod.json
  .github/workflows/production-checks.yml
  .github/workflows/test_website.yml
  src/content/es/2019/css.md
  src/static/css/page.css
  src/tools/scripts/set_lighthouse_urls.sh
Labels: SEO, accessibility, development

#1414 Fix regression introduced which prevents 2020 chapters generating
  src/templates/base/2019/chapter.ejs.html
  src/templates/base/2019/ebook.ejs.html
Labels: bug

#1364 Performance 2020 queries adjustments
  sql/2020/09_Performance/median_lcp_score_by_month.sql
  sql/2020/09_Performance/performance_observer.sql
  sql/2020/09_Performance/web_vitals_distribution_by_device.sql
Labels: ASAP, analysis

#1415 Production lighthouse bugfix
  .github/lighthouse/lighthouse-config-prod.json
  .github/workflows/production-checks.yml
Labels: bug

#1349 Page Weight 2020 SQL queries
  sql/2020/18_Page_Weight/average_resource_size.sql
  sql/2020/18_Page_Weight/bytes_per_type_2019.sql
  sql/2020/18_Page_Weight/bytes_per_type_2020.sql
  sql/2020/18_Page_Weight/request_type_distribution_2019.sql
  sql/2020/18_Page_Weight/request_type_distribution_2020.sql
  sql/2020/18_Page_Weight/response_format_distribution.sql
  sql/2020/18_Page_Weight/response_type_distribution.sql
Labels: ASAP, analysis

#1412 Web Page Test corrections in Methodology
  src/templates/en/2019/methodology.html
  src/templates/en/2020/methodology.html
  src/templates/fr/2019/methodology.html
  src/templates/ja/2019/methodology.html
  src/templates/zh-CN/2019/methodology.html
Labels: writing

#1419 More HTTP/2 queries
  sql/2020/22_HTTP_2/cdn_detail_by_cdn.sql
  sql/2020/22_HTTP_2/cdn_summary.sql
  sql/2020/22_HTTP_2/http2_%_1st_party_vs_3rd_party.sql
  sql/2020/22_HTTP_2/http2_%_1st_party_vs_3rd_party_by_type.sql
  sql/2020/22_HTTP_2/http2_3rd_party_by_types.sql
Labels: analysis

#1424 Remove dotted line on Help Translate menu
  src/templates/base/2019/base.html
Labels: bug, design

#1420 Add 2020 Methodology in French
  src/templates/fr/2020/methodology.html
Labels: translation

#1201 Mobile web queries
  sql/2020/12_Mobile_Web/correctly_sized_images.sql
  sql/2020/12_Mobile_Web/credential_management_api_usage.sql
  sql/2020/12_Mobile_Web/ecommerce_with_type_search.sql
  sql/2020/12_Mobile_Web/ect_distribution.sql
  sql/2020/12_Mobile_Web/lazy_loading_usage.sql
  sql/2020/12_Mobile_Web/mobile_traffic_distribution.sql
  sql/2020/12_Mobile_Web/most_used_apps.sql
  sql/2020/12_Mobile_Web/payment_request_api_usage.sql
  sql/2020/12_Mobile_Web/picture_source_srcset_usage.sql
  sql/2020/12_Mobile_Web/popular_mobile_input_types.sql
  sql/2020/12_Mobile_Web/service_worker.sql
Labels: ASAP, analysis

#1427 Custom property adoption
  sql/2020/01_CSS/custom_property_adoption.sql
Labels: analysis

#1428 Featured chapter fix
  src/server/__init__.py
  src/server/helpers.py
  src/templates/base/2019/index.html
  src/tools/scripts/set_lighthouse_urls.sh
Labels: bug, development

#1429 README and Deployment udpates
  src/README.md
  src/tools/scripts/deploy.sh
Labels: development

#1409 feat: init Markup chapter
  src/content/en/2020/markup.md
  src/static/images/2020/markup/distribution-of-elements-per-page.png
  src/static/images/2020/markup/document-size.png
  src/static/images/2020/markup/element-diversity-element-types.png
  src/static/images/2020/markup/element-diversity.png
  src/static/images/2020/markup/script-use.png
Labels: writing

#1436 Add npm run start command
  src/README.md
  src/package-lock.json
  src/package.json
  src/tools/scripts/run_and_test_website.bat
Labels: development

#1418 Traditional Chinese Translation-templates
  src/config/2019.json
  src/config/2020.json
  src/server/language.py
  src/templates/zh-CHT/2019/base.html
  src/templates/zh-CHT/2019/base_chapter.html
  src/templates/zh-CHT/2019/base_ebook.html
  src/templates/zh-CHT/2019/contributors.html
  src/templates/zh-CHT/2019/error.html
  src/templates/zh-CHT/2019/index.html
  src/templates/zh-CHT/2019/table_of_contents.html
  src/templates/zh-CHT/2020/base.html
  src/templates/zh-CHT/2020/contributors.html
  src/templates/zh-CHT/2020/index.html
  src/tools/scripts/set_lighthouse_urls.sh
Labels: translation

#1439 Use todos for 2020 Table of Contents
  src/config/2020.json
  src/content/en/2020/markup.md
  src/templates/base/2019/table_of_contents.html
Labels: development

#1441 Add Abby, add ToC and remove unused index.html
  src/config/2019.json
  src/config/2020.json
  src/templates/base/2020/index.html
  src/templates/zh-CHT/2020/table_of_contents.html
Labels: translation

#1437 Add option to generate individual watchers and a watcher
  src/README.md
  src/package-lock.json
  src/package.json
  src/tools/generate/chapter_watcher.js
  src/tools/generate/generate_chapters.js
  src/tools/generate/index.js
Labels: development

#1446 Add year to ebook chapter lookup
  src/tools/generate/generate_ebooks.js
Labels: bug

#1443 Add kill scripts
  src/README.md
  src/package.json
  src/tools/scripts/run_and_test_website.bat
  src/tools/scripts/run_and_test_website.sh
Labels: development

#1438 Fix colour contrast issues with 2020 Table of Contents
  src/templates/base/2019/table_of_contents.html
Labels: accessibility, bug

#1447 Support closed issues in progress tracker
  .github/workflows/progress-tracker.yml
Labels: development, project management

#1133 Fonts 2020 queries
  sql/2020/04_Fonts/04_01.web_fonts_usage.sql
  sql/2020/04_Fonts/04_02.web_fonts_usage_by_country.sql
  sql/2020/04_Fonts/04_03.popular_font_hosts_by_country.sql
  sql/2020/04_Fonts/04_04.local_vs_host_with_fcp.sql
  sql/2020/04_Fonts/04_05.web_font_usage_breakdown_with_fcp.sql
  sql/2020/04_Fonts/04_06.font_display_with_fcp.sql
  sql/2020/04_Fonts/04_07.font_resource_hints_with_fcp.sql
  sql/2020/04_Fonts/04_08.font_unicode_range_with_fcp.sql
  sql/2020/04_Fonts/04_09.font_subset_with_fcp.sql
  sql/2020/04_Fonts/04_10.font_formats.sql
  sql/2020/04_Fonts/04_11.popular_typeface_by_country.sql
  sql/2020/04_Fonts/04_11a.popular_typeface.sql
  sql/2020/04_Fonts/04_12.font_weight_font_style.sql
  sql/2020/04_Fonts/04_14.variable_font.sql
  sql/2020/04_Fonts/04_14a.variable_font_comparison_fcp.sql
  sql/2020/04_Fonts/04_17.VF_axis_value.sql
  sql/2020/04_Fonts/04_18.VF_animation.sql
  sql/2020/04_Fonts/04_19.color_fonts.sql
  sql/2020/04_Fonts/04_20.icon_fonts.sql
  sql/2020/04_Fonts/04_21.openType_axis.sql
  sql/2020/04_Fonts/4_10a.font_formats_font_face.sql
  sql/2020/04_Fonts/README.md
Labels: ASAP, analysis

#1451 Add a comment fallback for when comments fail to load
  src/templates/base/2019/base_chapter.html
  src/templates/en/2019/base_chapter.html
  src/templates/es/2019/base_chapter.html
  src/templates/fr/2019/base_chapter.html
  src/templates/ja/2019/base_chapter.html
  src/templates/pt/2019/base_chapter.html
  src/templates/zh-CHT/2019/base_chapter.html
  src/templates/zh-CN/2019/base_chapter.html
Labels: accessibility, bug, development

#1453 Add "npm run stage" command
  src/package.json
Labels: development

#1448 2020 chapter metadata
  src/content/en/2019/ecommerce.md
  src/content/en/2020/accessibility.md
  src/content/en/2020/caching.md
  src/content/en/2020/cms.md
  src/content/en/2020/compression.md
  src/content/en/2020/css.md
  src/content/en/2020/ecommerce.md
  src/content/en/2020/fonts.md
  src/content/en/2020/http2.md
  src/content/en/2020/jamstack.md
  src/content/en/2020/javascript.md
  src/content/en/2020/media.md
  src/content/en/2020/mobile-web.md
  src/content/en/2020/page-weight.md
  src/content/en/2020/performance.md
  src/content/en/2020/privacy.md
  src/content/en/2020/pwa.md
  src/content/en/2020/resource-hints.md
  src/content/en/2020/security.md
  src/content/en/2020/seo.md
  src/content/en/2020/third-parties.md
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_table_of_contents.js
Labels: project management, writing

#1454 Change Analysis by to Analysed by
  src/templates/en/2019/base.html
Labels: development, writing

#1421 Add 2020 Methodology in Japanese
  src/templates/ja/2020/methodology.html
Labels: translation

#1382 Capabilities 2020 chapter
  sql/2020/13_Capabilities/durable_storage_estimate_usage.sql
  sql/2020/13_Capabilities/durable_storage_persist_usage.sql
  sql/2020/13_Capabilities/get_installed_related_apps_usage.sql
  sql/2020/13_Capabilities/periodic_background_sync_usage.sql
  sql/2020/13_Capabilities/wake_lock_acquire_screen_lock_usage.sql
  src/config/2020.json
  src/content/en/2020/capabilities.md
  src/static/images/2020/capabilities/async_clipboard_api.png
  src/static/images/2020/capabilities/badging_api.png
  src/static/images/2020/capabilities/content_indexing_api.png
  src/static/images/2020/capabilities/get_installed_related_apps.png
  src/static/images/2020/capabilities/idle_detection_api.png
  src/static/images/2020/capabilities/notification_triggers_api.png
  src/static/images/2020/capabilities/periodic_background_sync_api.png
  src/static/images/2020/capabilities/quic_transport.png
  src/static/images/2020/capabilities/screen_wake_lock_api.png
  src/static/images/2020/capabilities/storage_manager_api_estimate.png
  src/static/images/2020/capabilities/storage_manager_api_persist.png
  src/static/images/2020/capabilities/websocketstreams.png
Labels: editing, writing

#1457 Auto start npm run watch
  src/README.md
  src/package.json
  src/tools/generate/chapter_watcher.js
  src/tools/generate/generate_chapters.js
  src/tools/scripts/run_and_test_website.bat
  src/tools/scripts/run_and_test_website.sh
  src/tools/scripts/stop_website.bat
  src/tools/scripts/stop_website.sh
Labels: development

#1458 Translation of base.html to Hindi
  src/templates/hi/2019/base.html
Labels: translation

#1396 Compression 2020 queries
  sql/2020/19_Compression/19_01.type_of_content_encoding.sql
  sql/2020/19_Compression/19_02.byte_saving_of_text_compression.sql
  sql/2020/19_Compression/19_03.party_of_content_encoding.sql
  sql/2020/19_Compression/19_04.distribution_of_text_compression_lighthouse.sql
  sql/2020/19_Compression/19_05.static_dynamic_compression.sql
Labels: ASAP, analysis

#1449 2020 methodology updates
  src/templates/en/2020/methodology.html
Labels: writing

#1452 Update home page to reference 2020 chapters now we have some ready
  src/templates/base/2019/index.html
  src/templates/en/2019/base.html
  src/templates/en/2020/base.html
  src/templates/es/2019/base.html
  src/templates/es/2020/base.html
  src/templates/fr/2019/base.html
  src/templates/fr/2020/base.html
  src/templates/ja/2019/base.html
  src/templates/ja/2020/base.html
  src/templates/pt/2019/base.html
  src/templates/pt/2020/base.html
  src/templates/zh-CHT/2019/base.html
  src/templates/zh-CHT/2020/base.html
  src/templates/zh-CN/2019/base.html
  src/templates/zh-CN/2020/base.html
Labels: development

#1461 Support Markdown in Table of Contents titles
  src/templates/base/2019/chapter.ejs.html
  src/templates/base/2019/toc.ejs.html
  src/tools/generate/generate_table_of_contents.js
  src/tools/scripts/set_lighthouse_urls.sh
Labels: development

#1462 Add author bios to 2020 Markup chapter
  src/content/en/2020/markup.md
Labels: editing, writing

#1469 Dynamic year in chapter metadata
  src/templates/en/2019/base_chapter.html
Labels: development

#1470 Fix chapter hero image metadata URLs
  src/templates/base/2019/base_chapter.html
  src/templates/es/2019/base_chapter.html
  src/templates/fr/2019/base_chapter.html
  src/templates/ja/2019/base_chapter.html
  src/templates/pt/2019/base_chapter.html
  src/templates/zh-CHT/2019/base_chapter.html
  src/templates/zh-CN/2019/base_chapter.html
Labels: development

#1472 Translation of some core templates(2020) to Hindi
  src/config/2019.json
  src/config/2020.json
  src/server/language.py
  src/templates/hi/2019/contributors.html
  src/templates/hi/2019/error.html
  src/templates/hi/2019/index.html
  src/templates/hi/2019/table_of_contents.html
  src/templates/hi/2020/base.html
  src/templates/hi/2020/contributors.html
  src/templates/hi/2020/index.html
  src/templates/hi/2020/table_of_contents.html
Labels: translation

#1474 Add lang attribute when using fallback quote
  src/templates/base/2019/featured_chapters.ejs.html
  src/templates/base/2019/index.html
  src/tools/generate/generate_featured_chapters.js
Labels: accessibility, translation

#1476 Add a min height to intro section on mobile
  src/static/css/index.css
Labels: accessibility, bug, development

#1477 Add chapter links heading and link
  src/static/css/page.css
  src/templates/base/2019/base_chapter.html
  src/templates/en/2019/base_chapter.html
  src/templates/es/2019/base_chapter.html
  src/templates/fr/2019/base_chapter.html
  src/templates/ja/2019/base_chapter.html
  src/templates/pt/2019/base_chapter.html
  src/templates/zh-CHT/2019/base_chapter.html
  src/templates/zh-CN/2019/base_chapter.html
Labels: design, development

#1464 Update headers with code or English language
  src/content/en/2019/caching.md
  src/content/es/2019/media.md
  src/content/fr/2019/accessibility.md
  src/content/fr/2019/caching.md
  src/content/fr/2019/javascript.md
  src/content/fr/2019/media.md
  src/content/fr/2019/resource-hints.md
  src/content/fr/2019/seo.md
  src/content/ja/2019/caching.md
  src/tools/generate/generate_chapters.js
Labels: accessibility, translation

#1352 JS 2020 queries
  sql/2020/02_JavaScript/README.md
  sql/2020/02_JavaScript/avg_pct_per_page_scripts_using_async_defer_module_nomodule.sql
  sql/2020/02_JavaScript/breakdown_of_scripts_using_async_defer_module_nomodule.sql
  sql/2020/02_JavaScript/bytes_2019.sql
  sql/2020/02_JavaScript/bytes_2020.sql
  sql/2020/02_JavaScript/bytes_by_3p.sql
  sql/2020/02_JavaScript/bytes_by_3p_histogram.sql
  sql/2020/02_JavaScript/compression_method.sql
  sql/2020/02_JavaScript/compression_method_by_3p.sql
  sql/2020/02_JavaScript/correlations.sql
  sql/2020/02_JavaScript/dist_pct_per_page_scripts_using_async_defer_module_nomodule.sql
  sql/2020/02_JavaScript/frameworks_libraries.sql
  sql/2020/02_JavaScript/frameworks_libraries_by_version.sql
  sql/2020/02_JavaScript/frameworks_libraries_combos.sql
  sql/2020/02_JavaScript/js_bytes_histogram.sql
  sql/2020/02_JavaScript/lighthouse_unminified_js.sql
  sql/2020/02_JavaScript/lighthouse_unminified_js_by_3p.sql
  sql/2020/02_JavaScript/lighthouse_unminified_js_bytes.sql
  sql/2020/02_JavaScript/lighthouse_unminified_js_requests.sql
  sql/2020/02_JavaScript/lighthouse_vulnerabilities.sql
  sql/2020/02_JavaScript/lighthouse_vulnerabilities_by_severity.sql
  sql/2020/02_JavaScript/lighthouse_vulnerable_libraries.sql
  sql/2020/02_JavaScript/main_thread_time.sql
  sql/2020/02_JavaScript/main_thread_time_frameworks.sql
  sql/2020/02_JavaScript/requests_2019.sql
  sql/2020/02_JavaScript/requests_2020.sql
  sql/2020/02_JavaScript/requests_by_3p.sql
  sql/2020/02_JavaScript/resource_hints.sql
  sql/2020/02_JavaScript/resource_hints_per_page.sql
  sql/2020/02_JavaScript/sourcemap_header.sql
  sql/2020/02_JavaScript/sourcemap_header_by_3p.sql
  sql/2020/02_JavaScript/unused_js_bytes_distribution.sql
  src/templates/en/2020/featured_chapters.html
Labels: ASAP, analysis

#1491 Remove the 2020 featured chapters file
  src/templates/en/2020/featured_chapters.html
Labels: bug

#1092 Third Parties 2020 queries
  sql/2020/06_Third_Parties/distribution_of_3XX_response_body_size.sql
  sql/2020/06_Third_Parties/distribution_of_size_and_time_by_third_parties.sql
  sql/2020/06_Third_Parties/distribution_of_third_parties_by_number_of_websites.sql
  sql/2020/06_Third_Parties/distribution_of_websites_by number_of_third_parties.sql
  sql/2020/06_Third_Parties/percent_of_third_parties_by_content_type.sql
  sql/2020/06_Third_Parties/percent_of_third_party_cache.sql
  sql/2020/06_Third_Parties/percent_of_third_party_loaded_before_DOMContentLoaded.sql
  sql/2020/06_Third_Parties/percent_of_third_party_requests_and_bytes_by_category_and_content_type.sql
  sql/2020/06_Third_Parties/percent_of_third_party_with_security_headers.sql
  sql/2020/06_Third_Parties/percent_of_websites_with_third_party.sql
  sql/2020/06_Third_Parties/tao_by_third_party.sql
  sql/2020/06_Third_Parties/top100_third_parties_by_median_body_size_and_time.sql
  sql/2020/06_Third_Parties/top100_third_parties_by_number_of_websites.sql
  sql/2020/06_Third_Parties/zero_third_party_websites.sql
Labels: ASAP, analysis

#1495 2020 CSS queries
  sql/2020/01_CSS/custom_property_cycles_max.sql
  sql/2020/01_CSS/custom_property_depth.sql
  sql/2020/01_CSS/custom_property_registered.sql
  sql/2020/01_CSS/custom_property_root.sql
  sql/2020/01_CSS/gradient_bg_properties.sql
  sql/2020/01_CSS/gradient_stops_per_gradient.sql
  sql/2020/01_CSS/houdini_animated_custom_properties.sql
  sql/2020/01_CSS/meta_unknown_properties.sql
  sql/2020/01_CSS/vendor_prefix_keywords.sql
Labels: analysis

#1494 2020 JS SQL
  sql/2020/02_JavaScript/compression_none_by_bytes.sql
Labels: analysis

#1318 Caching 2020 queries
  sql/2020/20_Caching/README.md
  sql/2020/20_Caching/appcache_and_serviceworkers.sql
  sql/2020/20_Caching/cache_control_and_max_age_and_expires.sql
  sql/2020/20_Caching/cache_control_directives.sql
  sql/2020/20_Caching/cache_ttl_and_content_age_diff.sql
  sql/2020/20_Caching/content_age_older_than_ttl.sql
  sql/2020/20_Caching/content_age_older_than_ttl_by_party.sql
  sql/2020/20_Caching/invalid_cache_control_directives.sql
  sql/2020/20_Caching/invalid_last_modified_and_expires_and_date.sql
  sql/2020/20_Caching/last_modified_and_etag.sql
  sql/2020/20_Caching/non_cacheable_by_resource_type.sql
  sql/2020/20_Caching/set_cookie.sql
  sql/2020/20_Caching/ttl.sql
  sql/2020/20_Caching/ttl_by_resource.sql
  sql/2020/20_Caching/valid_if_modified_since_returns_304.sql
  sql/2020/20_Caching/valid_if_non_match_returns_304.sql
  sql/2020/20_Caching/vary_headers.sql
Labels: ASAP, analysis

#1480 Set min-width for translation text to avoid menu errors
  src/static/css/2019.css
  src/templates/base/2019/base.html
Labels: bug, development

#1489 Translate the 2020 Methodology in French
  src/templates/fr/2020/methodology.html
Labels: translation

#1500 Methodology html fixes
  src/templates/en/2020/methodology.html
  src/templates/fr/2020/methodology.html
Labels: bug

#1393 Add table of contents dropdown list
  src/server/routes.py
  src/static/css/2019.css
  src/static/css/print.css
  src/templates/base/2019/base.html
Labels: development

#1504 ToC drop down clean ups
  src/templates/base/2019/base.html
  src/templates/base/2019/table_of_contents.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/hi/2019/base.html
  src/templates/ja/2019/base.html
  src/templates/pt/2019/base.html
  src/templates/zh-CHT/2019/base.html
  src/templates/zh-CN/2019/base.html
Labels: development

#1493 Add ability to run the linter locally
  src/README.md
  src/package.json
  src/templates/base/2019/chapter.ejs.html
  src/templates/base/2019/ebook.ejs.html
  src/tools/scripts/run_linter_locally.sh
Labels: development

#1505 make minor change in Trad chinese (templates) to smooth display
  src/templates/zh-CHT/2019/base.html
  src/templates/zh-CHT/2019/index.html
  src/templates/zh-CHT/2020/base.html
  src/templates/zh-CHT/2020/contributors.html
  src/templates/zh-CHT/2020/index.html
Labels: translation

#1507 Remove htmlhint hint as incorrectly showing in HTML
  src/templates/base/2019/chapter.ejs.html
  src/templates/base/2019/ebook.ejs.html
  src/tools/scripts/run_linter_locally.sh
Labels: ASAP, bug

#1492 Edit 2020 Capabilities chapter
  src/content/en/2020/capabilities.md
Labels: editing

#1479 Security 2020: additional queries
  sql/2020/11_Security/bot_detection.sql
  sql/2020/11_Security/feature_adoption_by_country.sql
  sql/2020/11_Security/feature_adoption_by_other_features.sql
  sql/2020/11_Security/feature_adoption_by_technology.sql
  sql/2020/11_Security/web_cryptography_api.sql
Labels: ASAP, analysis

#1435 Edit 2020 Markup chapter
  src/content/en/2020/markup.md
Labels: editing

#1514 2020 Foreword place holder
  src/templates/base/2019/table_of_contents.html
  src/templates/en/2020/base.html
  src/templates/es/2020/base.html
  src/templates/fr/2020/base.html
  src/templates/hi/2020/base.html
  src/templates/ja/2020/base.html
  src/templates/pt/2020/base.html
  src/templates/zh-CHT/2020/base.html
  src/templates/zh-CN/2020/base.html
Labels: development

#1518 Allow HTML in Big Issues
  src/templates/base/2019/base.html
Labels: bug, development

#1510 Lower HTML cache times to 10 mins for 2020 launch
  src/server/__init__.py
Labels: development

#1512 Misc fixes for ToC dropdown
  src/static/css/2019.css
  src/templates/base/2019/base.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/hi/2019/base.html
  src/templates/ja/2019/base.html
  src/templates/pt/2019/base.html
  src/templates/zh-CHT/2019/base.html
  src/templates/zh-CN/2019/base.html
Labels: bug, development

#1525 Fix Featured Quotes
  src/content/en/2019/caching.md
  src/content/en/2019/cms.md
  src/content/en/2019/compression.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/page-weight.md
  src/content/es/2019/media.md
  src/static/css/index.css
Labels: bug

#1511 Translation of 2020-methodology to Japanese
  src/templates/ja/2020/methodology.html
Labels: translation

#1529 Remove incorrect disabled attributes from divs
  src/templates/base/2019/base.html
Labels: bug, development

#1519 French translation - CSS Chapter
  src/content/en/2019/css.md
  src/content/fr/2019/css.md
  src/content/ja/2019/css.md
Labels: translation

#1532 Tiny typo
  src/content/fr/2019/mobile-web.md
Labels: bug

#1535 Upgrade setup-node
  .github/workflows/generate_chapters.yml
  .github/workflows/generate_ebooks.yml
  .github/workflows/test-template-changes.yml
  .github/workflows/test_website.yml
Labels: ASAP, bug

#1540 Move virtual env folder
  .gitignore
  src/.gcloudignore
  src/README.md
Labels: development

#1541 Update web-vitals script
  src/static/js/web-vitals.js
  src/tools/generate/generate_js.js
Labels: bug, development

#1526 SEO 2020 adding more details on disallow and noindex
  sql/2020/07_SEO/lighthouse.sql
  sql/2020/07_SEO/pages_almanac_by_device_and_meta_tag_name.sql
  sql/2020/07_SEO/pages_almanac_by_device_and_meta_tag_property.sql
Labels: analysis

#1522 Prevent author and reviewer names from wrapping in chapter pages
  src/config/2020.json
  src/static/css/page.css
Labels: development

#1545 Translation of Accessibility Statement to Hindi
  src/templates/hi/2019/accessibility_statement.html
  src/templates/hi/2019/base_chapter.html
Labels: translation

#1531 Fixes for printing chapters
  src/static/css/print.css
  src/templates/base/2019/base.html
Labels: bug

#1546 Make Footer spacing consistent with header and fix spacing issue
  src/static/css/2019.css
Labels: bug, development

#1543 Start website in full in Docker
  src/Dockerfile
  src/README.md
  src/tools/scripts/run_and_test_website.sh
  src/tools/scripts/stop_website.sh
Labels: development

#1523 Support language redirects
  src/server/language.py
  src/server/tests/validate_test.py
  src/server/validate.py
  src/tools/test/test_status_codes.js
Labels: development

#1550 2020 Resource Hints query update
  sql/2020/21_Resource_Hints/preconnect_and_dnsprefetch_relative.sql
Labels: analysis

#1539 Change percentiles for two HTTP/2 queries
  sql/2020/22_HTTP_2/cdn_summary.sql
  sql/2020/22_HTTP_2/http2_%_1st_party_vs_3rd_party.sql
Labels: analysis

#1551 Move sitemap to new timestamps
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_last_updated.js
  src/tools/generate/generate_sitemap.js
  src/tools/generate/index.js
Labels: ASAP, bug, development

#1553 Node fail on error
  src/tools/generate/generate_ebook_pdfs.js
  src/tools/generate/generate_timestamps.js
  src/tools/generate/index.js
  src/tools/test/index.js
Labels: bug, development

#1554 Move Traditional Chinese from zh-CHT to zh-TW
  src/config/2019.json
  src/config/2020.json
  src/config/last_updated.json
  src/server/language.py
  src/server/tests/validate_test.py
  src/server/validate.py
  src/templates/zh-TW/2019/base.html
  src/templates/zh-TW/2019/base_chapter.html
  src/templates/zh-TW/2019/base_ebook.html
  src/templates/zh-TW/2019/contributors.html
  src/templates/zh-TW/2019/error.html
  src/templates/zh-TW/2019/index.html
  src/templates/zh-TW/2019/table_of_contents.html
  src/templates/zh-TW/2020/base.html
  src/templates/zh-TW/2020/contributors.html
  src/templates/zh-TW/2020/index.html
  src/templates/zh-TW/2020/table_of_contents.html
  src/tools/test/test_status_codes.js
Labels: development, translation

#1561 Translate core templates into Russian
  src/config/2019.json
  src/config/2020.json
  src/server/language.py
  src/templates/ru/2019/base.html
  src/templates/ru/2019/base_chapter.html
  src/templates/ru/2019/base_ebook.html
  src/templates/ru/2019/contributors.html
  src/templates/ru/2019/error.html
  src/templates/ru/2019/index.html
  src/templates/ru/2019/methodology.html
  src/templates/ru/2019/table_of_contents.html
  src/templates/ru/2020/base.html
  src/templates/ru/2020/contributors.html
  src/templates/ru/2020/index.html
  src/templates/ru/2020/methodology.html
  src/templates/ru/2020/table_of_contents.html
Labels: translation

#1563 Update language section of README
  README.md
Labels: translation

#1564 Add support for EditorConfig
  .editorconfig
  src/README.md
Labels: development

#1566 Small Tweaks to Traditional Chinese templates
  src/templates/zh-TW/2019/base.html
  src/templates/zh-TW/2019/base_ebook.html
  src/templates/zh-TW/2019/contributors.html
  src/templates/zh-TW/2019/index.html
  src/templates/zh-TW/2020/contributors.html
  src/templates/zh-TW/2020/index.html
Labels: translation

#1538 Address Markup TODOs, light editing
  src/content/en/2020/markup.md
Labels: editing

#1567 Improve queries with CDNs, update tables dates
  sql/2020/17_JAMstack/core_web_vitals_distribution.sql
  sql/2020/17_JAMstack/core_web_vitals_passing.sql
Labels: ASAP, analysis

#1560 2020 CSS SQL updates
  sql/2020/01_CSS/custom_property_value_types.sql
  sql/2020/01_CSS/rework_errors.sql
  sql/2020/01_CSS/units_properties.sql
Labels: ASAP, analysis

#1555 Adds pytest-cov to track Python test coverage
  .github/linters/.flake8
  .github/workflows/python-tests.yml
  src/.gcloudignore
  src/.gitignore
  src/Dockerfile
  src/README.md
  src/package.json
  src/requirements.txt
  src/tools/scripts/run_and_test_website.bat
  src/tools/scripts/run_and_test_website.sh
Labels: development

#1568 Make 2020 language templates independent from 2019
  src/server/helpers.py
  src/server/routes.py
  src/templates/base/chapter.ejs.html
  src/templates/base/ebook.ejs.html
  src/templates/en/2019/base.html
  src/templates/en/2020/base.html
  src/templates/en/accessibility_statement.html
  src/templates/en/base.html
  src/templates/en/base_chapter.html
  src/templates/en/base_ebook.html
  src/templates/en/error.html
  src/templates/es/2019/base.html
  src/templates/es/2020/base.html
  src/templates/es/base.html
  src/templates/es/base_chapter.html
  src/templates/es/error.html
  src/templates/fr/2019/base.html
  src/templates/fr/2020/base.html
  src/templates/fr/accessibility_statement.html
  src/templates/fr/base.html
  src/templates/fr/base_chapter.html
  src/templates/fr/error.html
  src/templates/hi/2019/base.html
  src/templates/hi/2020/base.html
  src/templates/hi/accessibility_statement.html
  src/templates/hi/base.html
  src/templates/hi/base_chapter.html
  src/templates/hi/error.html
  src/templates/ja/2019/base.html
  src/templates/ja/2019/splash.html
  src/templates/ja/2020/base.html
  src/templates/ja/accessibility_statement.html
  src/templates/ja/base.html
  src/templates/ja/base_chapter.html
  src/templates/ja/base_ebook.html
  src/templates/ja/error.html
  src/templates/pt/2019/base.html
  src/templates/pt/2020/base.html
  src/templates/pt/base.html
  src/templates/pt/base_chapter.html
  src/templates/pt/error.html
  src/templates/ru/2019/base.html
  src/templates/ru/2020/base.html
  src/templates/ru/base.html
  src/templates/ru/base_chapter.html
  src/templates/ru/base_ebook.html
  src/templates/ru/error.html
  src/templates/zh-CN/2019/base.html
  src/templates/zh-CN/2020/base.html
  src/templates/zh-CN/accessibility_statement.html
  src/templates/zh-CN/base.html
  src/templates/zh-CN/base_chapter.html
  src/templates/zh-CN/base_ebook.html
  src/templates/zh-CN/error.html
  src/templates/zh-TW/2019/base.html
  src/templates/zh-TW/2020/base.html
  src/templates/zh-TW/base.html
  src/templates/zh-TW/base_chapter.html
  src/templates/zh-TW/base_ebook.html
  src/templates/zh-TW/error.html
Labels: development

#1569 Translation of Methodology to Hindi
  src/templates/hi/2019/methodology.html
  src/templates/hi/2020/methodology.html
  src/templates/hi/base_ebook.html
Labels: translation

#1534 Security SQL: final queries
  sql/2020/11_Security/cryptominer_share.sql
  sql/2020/11_Security/cryptominer_usage.sql
  sql/2020/11_Security/tls_forward_secrecy.sql
  sql/2020/11_Security/version-evolution-top-technologies.sql
Labels: ASAP, analysis

#1575 Bug with error template since template reorg
  src/server/helpers.py
Labels: bug, development

#1498 Modifications to Caching 2020 queries
  sql/2020/20_Caching/appcache_and_serviceworkers_2019.sql
  sql/2020/20_Caching/cache_ttl_and_content_age_diff.sql
  sql/2020/20_Caching/cache_ttl_lighthouse_score.sql
  sql/2020/20_Caching/cache_wastedbytes_lighthouse.sql
  sql/2020/20_Caching/content_age_older_than_ttl.sql
  sql/2020/20_Caching/content_age_older_than_ttl_by_party.sql
  sql/2020/20_Caching/last_modified_and_etag_2019.sql
  sql/2020/20_Caching/resource_age_party_and_type_wise.sql
  sql/2020/20_Caching/top_domains_using_immutable.sql
Labels: ASAP, analysis

#1579 JS 2020 query
  sql/2020/02_JavaScript/async_and_defer.sql
Labels: ASAP, analysis

#1576 Pytest tests for helpers.py
  .github/linters/.flake8
  src/package.json
  src/server/helpers.py
  src/server/tests/helpers_test.py
Labels: development

#1583 Fix prevnext for todo chapters
  src/server/helpers.py
  src/server/tests/helpers_test.py
Labels: ASAP, bug, development

#1586 Fix typo in Capabilities chapter
  src/content/en/2020/capabilities.md
Labels: bug, writing

#1588 Fix issue with French Resource Hints Featured Quote
  src/content/fr/2019/resource-hints.md
Labels: bug, translation, writing

#1584 Translate Capabilities chapter into Russian
  src/content/ru/2020/capabilities.md
  src/templates/ru/base.html
  src/templates/ru/base_chapter.html
Labels: translation

#1129 Privacy 2020 queries
  sql/2020/10_Privacy/percent_of_websites_using_each_cmp.sql
  sql/2020/10_Privacy/percent_of_websites_with_cmp.sql
  sql/2020/10_Privacy/percent_of_websites_with_fingerprinting.sql
  sql/2020/10_Privacy/percent_of_websites_with_iab_tcf_banner.sql
  sql/2020/10_Privacy/percent_of_websites_with_privacy_links.sql
  sql/2020/10_Privacy/top100_cookies_set_from_header.sql
Labels: ASAP, analysis

#1327 Media 2020 queries
  sql/2020/05_Media/big_non_custom_metrics.sql
  sql/2020/05_Media/image_alt.sql
  sql/2020/05_Media/image_mimetype_ext.sql
  sql/2020/05_Media/image_srcset_candidates.sql
  sql/2020/05_Media/image_srcset_descriptor.sql
  sql/2020/05_Media/image_srcset_sizes.sql
  sql/2020/05_Media/picture_format_distribution.sql
  sql/2020/05_Media/picture_orientation.sql
  sql/2020/05_Media/picture_using_min_resolution.sql
  sql/2020/05_Media/score_progressive_jpeg.sql
  sql/2020/05_Media/video_autoplay_muted.sql
  sql/2020/05_Media/video_preload.sql
  sql/2020/05_Media/video_source_types.sql
  sql/2020/05_Media/video_tag_and_js_player.sql
Labels: ASAP, analysis

#1591 Fix 2020 Capabilities typos
  src/content/en/2020/capabilities.md
Labels: editing

#1592 Accessibility 2020 queries: Find the pages with the longest alts
  sql/2020/08_Accessibility/README.md
  sql/2020/08_Accessibility/pages_with_longest_alts.sql
Labels: analysis

#1574 Syntax Highlighting Capabilities
  src/package-lock.json
  src/package.json
  src/static/css/2019.css
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_syntax_highlighting.js
Labels: development

#1593 Add missing languages to code blocks
  src/content/en/2019/fonts.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/security.md
  src/content/fr/2019/resource-hints.md
  src/content/ja/2019/fonts.md
  src/content/ja/2019/resource-hints.md
  src/content/ja/2019/security.md
  src/content/ru/2020/capabilities.md
Labels: development

#1580 Caching 2020 SQL updates
  sql/2020/20_Caching/resource_age_party_and_type_wise_groups.sql
Labels: ASAP, analysis

#1594 Move Methodology code block to Rainbow styles
  src/static/css/page.css
  src/templates/en/2019/methodology.html
  src/templates/en/2020/methodology.html
  src/templates/fr/2019/methodology.html
  src/templates/fr/2020/methodology.html
  src/templates/hi/2019/methodology.html
  src/templates/hi/2020/methodology.html
  src/templates/ja/2019/methodology.html
  src/templates/ja/2020/methodology.html
  src/templates/ru/2019/methodology.html
  src/templates/ru/2020/methodology.html
  src/templates/zh-CN/2019/methodology.html
Labels: development

#1595 Performance 2020 query update
  sql/2020/09_Performance/lh6_vs_lh5_performance_score_02.sql
  sql/2020/09_Performance/lh6_vs_lh5_performance_score_distribution.sql
Labels: ASAP, analysis

#1597 Update progress-tracker.yml
  .github/workflows/progress-tracker.yml
Labels: project management

#1601 bharatagsrwal contributor details added
  src/config/2020.json
Labels: development

#1603 Support h5 and h6 in chapters
  src/static/css/2019.css
  src/static/css/page.css
Labels: design, development

#1602 Add no-wrap utility class for better table layouts
  src/static/css/page.css
Labels: design, development
