Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2020-07, with the labels that each got.

#960 Fix incorrect colour for ToC highlighter
  src/static/css/page.css
Labels: bug, development

#963 Add ibnesayeed in 2020.json
  src/config/2020.json
Labels: project management

#951 Make header/footer padding consistent
  src/config/2020.json
  src/static/css/2019.css
  src/static/css/index.css
  src/templates/base/2019/base.html
Labels: design, development

#965 Clean up inline styles
  src/content/en/2019/caching.md
  src/content/en/2019/compression.md
  src/content/en/2019/css.md
  src/content/en/2019/media.md
  src/content/es/2019/css.md
  src/content/fr/2019/caching.md
  src/content/ja/2019/caching.md
  src/content/ja/2019/compression.md
  src/content/ja/2019/css.md
  src/content/ja/2019/media.md
  src/static/css/page.css
Labels: development

#952 Web vitals
  src/config/2020.json
  src/package-lock.json
  src/package.json
  src/static/js/web-vitals.js
  src/templates/base.html
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_js.js
Labels: development, performance

#956 Add Docker-based development environment
  src/.dockerignore
  src/Dockerfile
  src/README.md
  src/main.py
  src/tools/generate/generate_ebooks.js
  src/validate.py
Labels: development

#967 Only modify changed or added files - not deleted ones
  .github/workflows/generate_chapters.yml
Labels: bug, development

#950 2020 landing page content
  src/config/2020.json
  src/templates/base/2020/index.html
  src/templates/en/2020/index.html
  src/templates/es/2020/index.html
  src/templates/fr/2020/index.html
  src/templates/ja/2020/index.html
Labels: development, writing

#970 Fix spacing issues in header on tablet
  src/static/css/2019.css
Labels: bug

#954 Hero image with year as text
  src/static/css/2019.css
  src/static/css/ebook.css
  src/static/css/index.css
  src/static/images/home-hero-2019-bg.png
  src/static/images/home-hero-2019.png
  src/static/images/home-hero-2020.png
  src/static/images/home-hero.png
  src/templates/base/2019/index.html
  src/templates/base/2020/index.html
Labels: design, development

#973 Fix font size for logo year
  src/static/css/index.css
Labels: bug, design

#976 Remove offset for image which is now no longer required
  src/templates/base/2020/index.html
Labels: bug

#980 Fix typo
  src/content/en/2019/compression.md
Labels: bug

#982 Compression chapter fix K to k
  src/content/en/2019/compression.md
Labels: bug

#979 REM units for page.css for eBook
  src/static/css/page.css
Labels: design, development

#993 Fix typo
  src/templates/fr/2019/contributors.html
Labels: bug

#996 Translation of index.html to Japanese
  src/templates/ja/2020/index.html
Labels: good first issue, translation

#1000 Misc cleanups for 2020 landing page
  src/templates/en/2020/index.html
  src/templates/es/2020/index.html
  src/templates/fr/2020/index.html
  src/templates/ja/2020/index.html
Labels: editing

#1001 Correct Compression Featured Chapter quote
  src/templates/en/2019/featured_chapters.html
Labels: bug

#1003 Add feature-policy
  src/feature_policy.py
  src/main.py
Labels: development, enhancement

#997 Misc fixes in preparation of adding HTML Linter
  README.md
  src/content/es/2019/ecommerce.md
  src/content/fr/2019/caching.md
  src/templates/base/2019/accessibility_statement.html
  src/templates/base/2019/base.html
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/contributors.html
  src/templates/base/2019/methodology.html
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
  src/visualisation_lexer.py
Labels: development

#977 Translation of Compression chapter(2019) to French
  src/content/fr/2019/compression.md
  src/templates/fr/2019/base.html
  src/templates/fr/2019/featured_chapters.html
Labels: translation

#1011 fix compression
  src/templates/ja/2019/featured_chapters.html
Labels: translation

#1012 Fix featured chapters japanese translation
  src/templates/ja/2019/featured_chapters.html
Labels: translation

#1014 Compression featured quote #1002 in French
  src/templates/fr/2019/featured_chapters.html
Labels: bug, translation

#1008 Pin requirements version
  src/requirements.txt
Labels: development

#998 Add HTML Linter
  .github/linters/.htmlhintrc
  .github/workflows/linter.yml
Labels: development

#1018 Add unique id for each section to enable enhanced link tracking
  src/templates/base.html
  src/templates/base/2019/base.html
  src/templates/base/2019/index.html
  src/templates/base/2020/index.html
  src/templates/en/2019/featured_chapters.html
  src/templates/es/2019/featured_chapters.html
  src/templates/fr/2019/featured_chapters.html
  src/templates/ja/2019/featured_chapters.html
Labels: development

#1010 Remove inline styles from CSP
  src/csp.py
  src/main.py
  src/templates/base/2019/base_ebook.html
  src/templates/base/2019/contributors.html
  src/templates/base/2019/error.html
  src/templates/base/2019/table_of_contents.html
  src/templates/base/2020/index.html
Labels: development

#1019 Compress base images again
  src/static/images/apple-touch-icon-160x160.png
  src/static/images/apple-touch-icon.png
  src/static/images/blog.png
  src/static/images/character-file.png
  src/static/images/character-hat.png
  src/static/images/character-markup.png
  src/static/images/character-measure.png
  src/static/images/character-painter.png
  src/static/images/character-star.png
  src/static/images/github.png
  src/static/images/ha.png
  src/static/images/home-hero-bg.png
  src/static/images/home-hero.png
  src/static/images/methodology-banner-sm.png
  src/static/images/methodology-banner.png
  src/static/images/methodology-characters-bg.png
  src/static/images/methodology-characters.png
  src/static/images/twitter.png
Labels: performance

#1027 Generate non-chapter pages in Sitemap based on JSON config
  src/templates/sitemap.xml
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_sitemap.js
Labels: SEO, development

#1029 CSP for Sitemap
  src/main.py
Labels: bug, development

#1030 Sitemap CSP fix - take 2
  src/main.py
Labels: bug, development

#1034 Fix bad padding
  src/static/css/page.css
Labels: bug, design, development

#1036 Bad padding
  src/static/css/page.css
Labels: bug

#1038 Add dimensions to Home Page Hero Image
  src/templates/base/2019/index.html
  src/templates/base/2020/index.html
Labels: development, performance

#1039 Reorganise HEAD to load CSS as quickly as possible
  src/templates/base.html
Labels: performance

#1050 Fix bug where code block causes scrolling issues on mobile
  src/static/css/page.css
Labels: bug, development

#1048 2020 Config Updates
  src/config/2020.json
Labels: development

#1053 CSS newline linter
  .github/linters/.stylelintrc.json
  src/static/css/2019.css
  src/static/css/ebook.css
  src/static/css/page.css
  src/static/css/print.css
Labels: development, enhancement

#1042 Make Contributor buttons accessible
  src/main.py
  src/templates/base/2019/contributors.html
  src/templates/base/2020/contributors.html
  src/templates/en/2019/contributors.html
  src/templates/en/2020/contributors.html
  src/templates/es/2019/contributors.html
  src/templates/es/2020/contributors.html
  src/templates/fr/2019/contributors.html
  src/templates/fr/2020/contributors.html
  src/templates/ja/2019/contributors.html
  src/templates/ja/2020/contributors.html
Labels: accessibility, development

#1056 Fix bug where code block causes scrolling issues on mobile - repeat
  src/static/css/page.css
Labels: bug, development

#1059 Refactoring, sorting, and enhancing progress report
  .github/workflows/progress-tracker.yml
Labels: development, project management

#1063 fix typo
  src/content/ja/2019/javascript.md
Labels: translation

#1066 Fix contributor padding issues and wrap control in a form
  src/templates/base/2019/contributors.html
Labels: accessibility, bug

#1064 Fix translation “accessibility" in Japanese
  src/content/ja/2019/cms.md
  src/content/ja/2019/media.md
  src/templates/ja/2019/chapters/cms.html
  src/templates/ja/2019/chapters/media.html
  src/templates/ja/2019/ebook.html
  src/templates/ja/2019/featured_chapters.html
Labels: translation

#1060 Support hyphens in usernames and sort contributors by most to least chapters
  .github/workflows/progress-tracker.yml
Labels: project management

#1071 Add collective team in the progress report
  .github/workflows/progress-tracker.yml
Labels: development, project management

#1080 Spanish translation of the temp 2020 landing page
  src/config/2020.json
  src/templates/es/2020/index.html
Labels: translation

#1089 Create empty sql dirs for each chapter
  sql/2020/01_CSS/README.md
  sql/2020/02_JavaScript/README.md
  sql/2020/03_Markup/README.md
  sql/2020/04_Fonts/README.md
  sql/2020/05_Media/README.md
  sql/2020/06_Third_Parties/README.md
  sql/2020/07_SEO/README.md
  sql/2020/08_Accessibility/README.md
  sql/2020/09_Performance/README.md
  sql/2020/10_Privacy/README.md
  sql/2020/11_Security/README.md
  sql/2020/12_Mobile_Web/README.md
  sql/2020/13_Capabilities/README.md
  sql/2020/14_PWA/README.md
  sql/2020/15_CMS/README.md
  sql/2020/16_Ecommerce/README.md
  sql/2020/17_JAMstack/README.md
  sql/2020/18_Page_Weight/README.md
  sql/2020/19_Compression/README.md
  sql/2020/20_Caching/README.md
  sql/2020/21_Resource_Hints/README.md
  sql/2020/22_HTTP_2/README.md
Labels: analysis

#1093 Fix Join the Team contributor card on mobile
  src/templates/base/2019/contributors.html
Labels: bug, development

#1096 Update create pull request to v3
  .github/workflows/generate_chapters.yml
Labels: development

#1095 Build site on Package.JSON change
  .github/workflows/generate_chapters.yml
Labels: development

#1094 Remove header fallback
  src/static/css/index.css
Labels: bug, development

#1100 Change localizedChapter names to look up by slug rather than Title
  src/templates/base/2019/base_chapter.html
  src/templates/base/2019/base_ebook.html
  src/templates/base/2019/table_of_contents.html
  src/templates/en/2019/base.html
  src/templates/en/2019/featured_chapters.html
  src/templates/es/2019/base.html
  src/templates/es/2019/featured_chapters.html
  src/templates/fr/2019/base.html
  src/templates/fr/2019/featured_chapters.html
  src/templates/ja/2019/base.html
  src/templates/ja/2019/featured_chapters.html
Labels: development

#1105 Fix bug in Localized chapter slugs
  src/templates/en/2019/featured_chapters.html
  src/templates/es/2019/featured_chapters.html
Labels: bug

#1110 Allow language and country code languages when choosing best site for visitor
  src/validate.py
Labels: development, translation

#1111 Adds nowrap whitespace for japanese language in contributor-team style
  src/templates/base/2019/contributors.html
Labels: development

#1112 Removes copyright year from footer
  src/config/2020.json
  src/templates/en/2019/base.html
  src/templates/es/2019/base.html
  src/templates/fr/2019/base.html
  src/templates/ja/2019/base.html
Labels: development

#1114 Fix contributor numbers when more than 100 of them
  src/static/css/index.css
Labels: design

#1073 Simplified Chinese translation of non-chapters
  src/config/2019.json
  src/config/2020.json
  src/language.py
  src/templates/zh-CN/2019/accessibility_statement.html
  src/templates/zh-CN/2019/base.html
  src/templates/zh-CN/2019/base_chapter.html
  src/templates/zh-CN/2019/base_ebook.html
  src/templates/zh-CN/2019/contributors.html
  src/templates/zh-CN/2019/error.html
  src/templates/zh-CN/2019/featured_chapters.html
  src/templates/zh-CN/2019/index.html
  src/templates/zh-CN/2019/methodology.html
  src/templates/zh-CN/2019/table_of_contents.html
  src/templates/zh-CN/2020/contributors.html
  src/templates/zh-CN/2020/index.html
Labels: translation

#1120 Correct pytests
  src/validate_test.py
Labels: bug, development

#1121 Add Python Test GitHub Action
  .github/workflows/python-tests.yml
Labels: development

#1117 Fix redirects when chapter does not exist in that language for that year
  src/main.py
  src/validate.py
Labels: bug, translation

#1118 Translate Accessibility Statement H1
  src/templates/base/2019/accessibility_statement.html
  src/templates/en/2019/accessibility_statement.html
  src/templates/ja/2019/accessibility_statement.html
  src/templates/zh-CN/2019/accessibility_statement.html
Labels: translation

#1116 Better language code for Simplified Chinese
  src/config.py
  src/config/2019.json
  src/config/2020.json
Labels: development

#1123 Add action to auto generate Ebooks
  .github/workflows/generate_ebooks.yml
  src/README.md
Labels: development

#1124 Automate website status tests
  .github/workflows/generate_chapters.yml
  src/package-lock.json
  src/package.json
  src/tools/test/index.js
  src/tools/test/test_status_codes.js
Labels: development

#1125 Website tests typo
  .github/workflows/generate_chapters.yml
Labels: bug, development

#1128 Fix Chinese language selector
  src/static/css/2019.css
Labels: bug, development, translation

#1107 Randomize contributors on reload
  src/templates/base/2019/contributors.html
Labels: development
