Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-10, with the labels that each got.

#2344 Extra PWA queries
  sql/2021/pwa/pwa_notification_acceptance_rates_over_time.sql
  sql/2021/pwa/top_manifest_display_values.sql
  sql/2021/pwa/workbox_methods.sql
  sql/2021/pwa/workbox_packages.sql
Labels: analysis

#2356 Fix chapter tracker
  .github/workflows/progress-tracker.yml
Labels: bug

#2338 Fonts 2021 sql
  sql/2021/fonts/color_fonts.sql
  sql/2021/fonts/font_display.sql
  sql/2021/fonts/fonts_format.sql
  sql/2021/fonts/popular_typeface.sql
  sql/2021/fonts/self_hosted_vs_hosted_with_fcp_lcp.sql
  sql/2021/fonts/variable_font_adoption.sql
  sql/2021/fonts/variable_font_axes_used.sql
  sql/2021/fonts/web_font_usage_breakdown_with_fcp_lcp.sql
  sql/2021/fonts/web_fonts_usage.sql
  sql/2021/fonts/web_fonts_usage_by_country.sql
Labels: analysis

#2360 Fix old 2019 CSS query preventing the code base from linting properly
  sql/2019/css/02_18.sql
Labels: analysis

#2309 HTTP 2021 queries
  sql/2021/http/README.md
  sql/2021/http/adoption_of_http_2_by_site_and_requests.sql
  sql/2021/http/avg_percentage_of_resources_loaded_over_HTTP_by_version_per_site.sql
  sql/2021/http/count_of_h2_and_h3_sites_grouped_by_server.sql
  sql/2021/http/count_of_h2_and_h3_sites_using_push.sql
  sql/2021/http/count_of_non_h2_and_h3_sites_grouped_by_server.sql
  sql/2021/http/count_of_preload_http_headers_with_nopush_attribute_set.sql
  sql/2021/http/detailed_alt_svc_headers_pages.sql
  sql/2021/http/detailed_alt_svc_headers_requests.sql
  sql/2021/http/detailed_upgrade_headers.sql
  sql/2021/http/favicons_number_404s.sql
  sql/2021/http/http2_1st_party_vs_3rd_party.sql
  sql/2021/http/http2_1st_party_vs_3rd_party_by_type.sql
  sql/2021/http/http2_3_support_by_cdn_per_page_and_request.sql
  sql/2021/http/http2_3rd_party_by_types.sql
  sql/2021/http/http2_http3_usage_by_rank.sql
  sql/2021/http/http3_support_by_rank.sql
  sql/2021/http/measure_number_of_tcp_connections_per_site.sql
  sql/2021/http/measure_of_all_http_versions_for_main_page_of_all_sites.sql
  sql/2021/http/number_of_h2_and_h3_pushed_resources_and_bytes_by_content_type.sql
  sql/2021/http/number_of_h2_and_h3_pushed_resources_and_bytes_transferred.sql
  sql/2021/http/number_of_http_requests_returning_upgrade_http_header_containing_h2.sql
  sql/2021/http/number_of_https_requests_not_using_h2_or_h3_returning_upgrade_http_upgrade_header_containing_h2.sql
  sql/2021/http/number_of_https_requests_using_h2_returning_upgrade_http_header_containing_h2.sql
  sql/2021/http/pages_most_requests.sql
  sql/2021/http/percentage_of_h2_and_h3_sites_affected_by_cdn_prioritization.sql
  sql/2021/http/percentiles_of_resources_loaded_over_HTTP2_or_better_per_site.sql
  sql/2021/http/response_headers_largest.sql
  sql/2021/http/response_headers_size_growth.sql
  sql/2021/http/response_headers_type_percentile_size.sql
  sql/2021/http/response_headers_type_usage.sql
  sql/2021/http/response_invalid_headers.sql
  sql/2021/http/response_number_and_size.sql
  sql/2021/http/response_status_code_counts.sql
  sql/2021/http/response_status_code_number_and_size.sql
  sql/2021/http/response_status_lots_nonsuccess_large.sql
  sql/2021/http/tls_adoption_by_http_version.sql
Labels: analysis

#2412 CSS analysis: image format popularity
  sql/2021/css/image_formats.sql
Labels: analysis, ASAP

#2418 Add designers to config file
  src/config/2021.json
Labels: project management

#2420 Few more small tweaks to 2021 Third Party queries
  sql/2021/third-parties/distribution_of_websites_by_number_of_third_parties.sql
  sql/2021/third-parties/number_of_third_parties_by_rank_and_category.sql
  sql/2021/third-parties/percent_of_websites_with_third_party.sql
  sql/2021/third-parties/top100_third_parties_by_number_of_websites.sql
Labels: analysis
