Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-03, with the labels that each got.

#2046 Translate the 2020 3rd parties chapter to Dutch
  src/content/en/2020/third-parties.md
  src/content/ja/2020/third-parties.md
  src/content/nl/2020/third-parties.md
Labels: translation

#2048 Revert GitHub Super Linter upgrade
  .github/workflows/linter.yml
  .github/workflows/test_website.yml
Labels: 2020 chapter, development

#2049 Translation of the 2020 PWA chapter to Dutch
  src/content/nl/2020/pwa.md
  src/content/nl/2020/security.md
Labels: translation

#2051 Fixed edited by link
  src/templates/base/base_chapter.html
Labels: bug, development

#2053 Fix typo in security.md
  src/content/en/2020/security.md
Labels: editing

#2055 Translation of jamstack chapter to Japanese
  src/content/en/2020/jamstack.md
  src/content/ja/2020/jamstack.md
Labels: translation

#2056 Fix typos in templates
  src/templates/nl/2020/base.html
  src/templates/nl/base.html
Labels: translation

#2057 Translation of the 2020 Resource hints chapter in Dutch
  src/content/en/2020/security.md
  src/content/ja/2020/security.md
  src/content/nl/2020/resource-hints.md
  src/content/nl/2020/security.md
  src/templates/nl/2019/base.html
  src/templates/nl/2019/methodology.html
  src/templates/nl/2020/methodology.html
  src/templates/nl/accessibility_statement.html
Labels: translation

#2030 Translates 2019 compression chapter to portuguese
  src/config/2019.json
  src/content/pt/2019/compression.md
Labels: translation

#2059 Reorder stories HEAD
  src/templates/en/2020/stories/content_distribution.html
  src/templates/en/2020/stories/content_publishing.html
  src/templates/en/2020/stories/page_content.html
  src/templates/en/2020/stories/user_experience.html
Labels: SEO, bug

#2063 Add missing Sheets reference to Accessibility chapter
  src/content/en/2020/accessibility.md
  src/content/ja/2020/accessibility.md
  src/content/nl/2020/accessibility.md
Labels: editing

#2058 Translate 2020 CSS chapter to Portuguese
  src/content/pt/2020/css.md
Labels: translation

#2062 Translated 2020 CSS chapter to Italian
  src/content/en/2020/css.md
  src/content/it/2020/css.md
Labels: translation

#2064 Translation of the 2020 mobile web chapter to Dutch
  src/content/en/2020/mobile-web.md
  src/content/nl/2019/accessibility.md
  src/content/nl/2020/cms.md
  src/content/nl/2020/compression.md
  src/content/nl/2020/fonts.md
  src/content/nl/2020/jamstack.md
  src/content/nl/2020/javascript.md
  src/content/nl/2020/markup.md
  src/content/nl/2020/mobile-web.md
  src/content/nl/2020/page-weight.md
  src/content/nl/2020/pwa.md
  src/content/nl/2020/security.md
  src/content/nl/2020/third-parties.md
  src/templates/nl/2019/methodology.html
  src/templates/nl/2020/base.html
Labels: translation

#2066 Translation of the 2020 Media chapter to Dutch
  src/content/en/2020/media.md
  src/content/nl/2020/media.md
Labels: translation

#2071 Upgrade super linter and change it to work on pull requests
  .github/workflows/linter.yml
  .github/workflows/test_website.yml
Labels: development

#2070 Translated 2020 http2 chapter to Italian
  src/content/it/2020/http2.md
Labels: translation

#2074 Add AVIF hero images
  src/static/images/2019/accessibility/hero_lg.avif
  src/static/images/2019/accessibility/hero_sm.avif
  src/static/images/2019/caching/hero_lg.avif
  src/static/images/2019/caching/hero_sm.avif
  src/static/images/2019/cdn/hero_lg.avif
  src/static/images/2019/cdn/hero_sm.avif
  src/static/images/2019/cms/hero_lg.avif
  src/static/images/2019/cms/hero_sm.avif
  src/static/images/2019/compression/hero_lg.avif
  src/static/images/2019/compression/hero_sm.avif
  src/static/images/2019/css/hero_lg.avif
  src/static/images/2019/css/hero_sm.avif
  src/static/images/2019/ecommerce/hero_lg.avif
  src/static/images/2019/ecommerce/hero_sm.avif
  src/static/images/2019/fonts/hero_lg.avif
  src/static/images/2019/fonts/hero_sm.avif
  src/static/images/2019/http2/hero_lg.avif
  src/static/images/2019/http2/hero_sm.avif
  src/static/images/2019/javascript/hero_lg.avif
  src/static/images/2019/javascript/hero_sm.avif
  src/static/images/2019/markup/hero_lg.avif
  src/static/images/2019/markup/hero_sm.avif
  src/static/images/2019/media/hero_lg.avif
  src/static/images/2019/media/hero_sm.avif
  src/static/images/2019/mobile-web/hero_lg.avif
  src/static/images/2019/mobile-web/hero_sm.avif
  src/static/images/2019/page-weight/hero_lg.avif
  src/static/images/2019/page-weight/hero_sm.avif
  src/static/images/2019/performance/hero_lg.avif
  src/static/images/2019/performance/hero_sm.avif
  src/static/images/2019/pwa/hero_lg.avif
  src/static/images/2019/pwa/hero_sm.avif
  src/static/images/2019/resource-hints/hero_lg.avif
  src/static/images/2019/resource-hints/hero_sm.avif
  src/static/images/2019/security/hero_lg.avif
  src/static/images/2019/security/hero_sm.avif
  src/static/images/2019/seo/hero_lg.avif
  src/static/images/2019/seo/hero_sm.avif
  src/static/images/2019/third-parties/hero_lg.avif
  src/static/images/2019/third-parties/hero_sm.avif
  src/static/images/2020/capabilities/hero_lg.avif
  src/static/images/2020/capabilities/hero_sm.avif
  src/static/images/2020/jamstack/hero_lg.avif
  src/static/images/2020/jamstack/hero_sm.avif
  src/static/images/2020/privacy/hero_lg.avif
  src/static/images/2020/privacy/hero_sm.avif
  src/templates/base/base_chapter.html
  src/templates/base/ebook.ejs.html
Labels: development, performance

#2075 Fix scrolling issue on logo on mobile view in desktop
  src/static/css/almanac.css
Labels: bug, development

#2076 Add some more resource hints
  src/templates/base.html
  src/templates/base/accessibility_statement.html
  src/templates/base/base.html
  src/templates/base/methodology.html
Labels: development, performance

#2079 Add a shortcut key to show/hide all the descriptions
  src/static/js/almanac.js
Labels: development

#2083 Translated 2020 Compression chapter to Italian
  src/content/it/2020/compression.md
Labels: translation

#2082 Translation of 2020 pwa chapter to Japanese
  src/content/ja/2020/pwa.md
Labels: translation

#2085 Dutch 2020 Ecommerce chapter translation
  src/content/en/2020/ecommerce.md
  src/content/nl/2020/ecommerce.md
Labels: translation

#2089 Handle code table layouts better
  src/content/en/2020/css.md
  src/content/it/2020/css.md
  src/content/ja/2020/css.md
  src/content/pt/2020/css.md
  src/static/css/almanac.css
Labels: bug, development

#2086 Upgrade NPM to v7
  .github/workflows/predeploy.yml
  .github/workflows/test-template-changes.yml
  .github/workflows/test_website.yml
  src/package-lock.json
Labels: development

#2091 User older version of super-linter for test website
  .github/workflows/test_website.yml
Labels: development

#2095 Update nl/ecommerce
  src/content/nl/2020/ecommerce.md
Labels: translation

#2096 Remove unnecessary focus-visible style
  src/static/css/almanac.css
Labels: development

#2098 Translated 2020 Privacy chapter to Italian
  src/content/it/2020/privacy.md
Labels: translation

#2101 Translation of the 2020 Privacy chapter to Dutch
  src/content/nl/2020/privacy.md
  src/content/nl/2020/resource-hints.md
Labels: translation

#2105 Fix show all description code
  src/static/js/almanac.js
Labels: development

#2106 y18n update for security issue
  src/package-lock.json
Labels: development
