Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-06, with the labels that each got.

#2218 Fix labels
  src/content/en/2019/accessibility.md
  src/content/en/2020/accessibility.md
  src/content/en/2020/css.md
  src/content/en/2020/fonts.md
  src/content/it/2020/css.md
  src/content/ja/2019/accessibility.md
  src/content/ja/2020/accessibility.md
  src/content/ja/2020/capabilities.md
  src/content/ja/2020/css.md
  src/content/ja/2020/fonts.md
  src/content/ja/2020/security.md
  src/content/nl/2020/accessibility.md
  src/content/nl/2020/fonts.md
  src/content/pt/2019/accessibility.md
  src/content/pt/2020/css.md
  src/content/zh-CN/2019/accessibility.md
Labels: editing

#2225 Upgrade ws package to avoid security alert
  src/package-lock.json
Labels: development

#2222 2020 privacy japanese translation
  src/content/ja/2020/privacy.md
Labels: translation

#2231 Update my LinkedIn profile
  src/config/2019.json
  src/config/2020.json
  src/config/2021.json
Labels: editing

#2233 Portuguese Translation 2019 - Resource Hints Chapter
  src/content/pt/2019/ecommerce.md
  src/content/pt/2019/resource-hints.md
  src/templates/pt/base.html
Labels: translation

#2241 Better overflow wrap
  src/content/en/2020/capabilities.md
  src/static/css/almanac.css
  src/static/css/page.css
Labels: bug, design, development

#2242 Upgrade flask-talisman to 0.8.1 and remove workaround
  src/requirements.txt
  src/server/routes.py
Labels: dependencies, development

#2239 2020 compression japanese translation
  src/content/ja/2020/compression.md
Labels: translation

#2243 Better CSP
  src/server/csp.py
  src/templates/base.html
  src/templates/base/base.html
Labels: development

#2247 Latest chapter updates
  src/config/2021.json
Labels: project management

#2248 Update badges on README to 2021 milestones
  README.md
Labels: project management

#2196 Fixed position chapter CTAs
  src/config/2021.json
  src/static/css/almanac.css
  src/static/css/page.css
  src/static/js/almanac.js
  src/templates/base/base_chapter.html
  src/templates/en/base.html
  src/templates/en/base_chapter.html
  src/templates/es/base_chapter.html
  src/templates/fr/base_chapter.html
  src/templates/hi/base_chapter.html
  src/templates/it/base.html
  src/templates/it/base_chapter.html
  src/templates/ja/base_chapter.html
  src/templates/nl/base.html
  src/templates/nl/base_chapter.html
  src/templates/pt/base.html
  src/templates/pt/base_chapter.html
  src/templates/ru/base_chapter.html
  src/templates/tr/base.html
  src/templates/tr/base_chapter.html
  src/templates/uk/base_chapter.html
  src/templates/zh-CN/base_chapter.html
  src/templates/zh-TW/base_chapter.html
Labels: design, development

#2250 2020 ecommerce japanese translation
  src/content/ja/2020/ecommerce.md
Labels: translation

#2256 Fix axis on font graphs
  src/static/images/2020/fonts/fonts-median-fcp-of-sites-using-hosted-fonts.png
  src/static/images/2020/fonts/fonts-median-lcp-of-sites-using-hosted-fonts.png
Labels: 2020 chapter

#2255 ES #498: 2020 SEO Spanish Translation
  src/config/2020.json
  src/content/en/2020/seo.md
  src/content/es/2020/seo.md
  src/content/it/2020/seo.md
  src/content/ja/2020/seo.md
Labels: good first issue, translation

#2258 2020 media japanese translation
  src/content/ja/2020/media.md
Labels: translation
