Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-08, with the labels that each got.

#2273 Add Site Search to website
  .github/lighthouse/lighthouse-config-dev.json
  src/server/routes.py
  src/server/search_csp.py
  src/server/tests/routes_test.py
  src/static/css/almanac.css
  src/static/js/almanac.js
  src/templates/base.html
  src/templates/base/base.html
  src/templates/base/index.html
  src/templates/base/search.html
  src/templates/en/base.html
  src/templates/en/search.html
  src/templates/es/base.html
  src/templates/es/search.html
  src/templates/fr/base.html
  src/templates/fr/search.html
  src/templates/hi/base.html
  src/templates/hi/search.html
  src/templates/it/base.html
  src/templates/it/search.html
  src/templates/ja/base.html
  src/templates/ja/search.html
  src/templates/nl/base.html
  src/templates/nl/search.html
  src/templates/pt/base.html
  src/templates/pt/search.html
  src/templates/ru/base.html
  src/templates/ru/search.html
  src/templates/tr/base.html
  src/templates/tr/search.html
  src/templates/uk/base.html
  src/templates/uk/search.html
  src/templates/zh-CN/base.html
  src/templates/zh-CN/search.html
  src/templates/zh-TW/base.html
  src/templates/zh-TW/search.html
  src/tools/scripts/set_lighthouse_urls.sh
  src/tools/test/test_status_codes.js
Labels: design, development

#2291 2021 Landing Page
  src/config/2021.json
  src/server/helpers.py
  src/server/tests/validate_test.py
  src/server/validate.py
  src/static/css/index.css
  src/templates/base/base.html
  src/templates/base/index.html
  src/templates/en/2021/base.html
  src/templates/en/2021/index.html
  src/templates/en/base.html
  src/templates/es/2021/base.html
  src/templates/es/2021/index.html
  src/templates/es/base.html
  src/templates/fr/2021/base.html
  src/templates/fr/2021/index.html
  src/templates/fr/base.html
  src/templates/hi/2021/base.html
  src/templates/hi/2021/index.html
  src/templates/hi/base.html
  src/templates/it/2021/base.html
  src/templates/it/2021/index.html
  src/templates/it/base.html
  src/templates/ja/2021/base.html
  src/templates/ja/2021/index.html
  src/templates/ja/base.html
  src/templates/nl/2021/base.html
  src/templates/nl/2021/index.html
  src/templates/nl/base.html
  src/templates/pt/2021/base.html
  src/templates/pt/2021/index.html
  src/templates/pt/base.html
  src/templates/ru/2021/base.html
  src/templates/ru/2021/index.html
  src/templates/ru/base.html
  src/templates/tr/2021/base.html
  src/templates/tr/2021/index.html
  src/templates/tr/base.html
  src/templates/uk/2021/base.html
  src/templates/uk/2021/index.html
  src/templates/uk/base.html
  src/templates/zh-CN/2021/base.html
  src/templates/zh-CN/2021/index.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/2021/base.html
  src/templates/zh-TW/2021/index.html
  src/templates/zh-TW/base.html
  src/tools/test/test_status_codes.js
Labels: development

#2302 Search input improvements
  src/static/css/almanac.css
  src/static/js/almanac.js
Labels: bug, development

#2304 Further tweaks to Search Input
  src/static/css/almanac.css
Labels: development

#2301 added rank and security details to requests table
  sql/.sqlfluff
  sql/util/requests.sql
Labels: analysis

#2307 Add Search button to Contributors page
  src/templates/base/contributors.html
Labels: development

#2314 Add SQLFluff as a dependency with instructions on how to lint locally
  src/README.md
  src/requirements.txt
Labels: analysis

#2315 Even more SQL linting fixes
  sql/2019/performance/07_13.sql
  sql/2019/performance/07_20.sql
  sql/2019/performance/07_21.sql
  sql/2019/performance/07_22.sql
  sql/2019/performance/07_23.sql
  sql/2019/performance/07_24.sql
  sql/2019/pwa/11_02.sql
  sql/2019/security/08_03-04.sql
  sql/2019/security/08_06.sql
  sql/2019/security/08_07.sql
  sql/2019/security/08_08.sql
  sql/2019/security/08_09.sql
  sql/2019/security/08_19.sql
  sql/2019/security/08_23-24.sql
  sql/2019/security/08_23-24b.sql
  sql/2019/security/08_25-34.sql
  sql/2019/security/08_28b.sql
  sql/2019/security/08_28c.sql
  sql/2019/seo/10_06.sql
  sql/2019/seo/10_07a.sql
  sql/2019/third-parties/05_03.sql
  sql/2019/third-parties/05_04.sql
  sql/2019/third-parties/05_06.sql
  sql/2019/third-parties/05_07.sql
  sql/2019/third-parties/05_09.sql
  sql/2020/security/feature_adoption_by_topN_technologies.sql
Labels: analysis

#2317 Incorrect linting unnest
  sql/2019/cms/14_13.sql
  sql/2019/cms/14_13c.sql
  sql/2019/cms/14_13d.sql
  sql/2019/cms/14_15.sql
  sql/2019/cms/14_15b.sql
  sql/2019/cms/14_15c.sql
  sql/2019/cms/14_15d.sql
  sql/2019/cms/14_15e.sql
  sql/2019/ecommerce/13_06.sql
  sql/2019/ecommerce/13_06c.sql
  sql/2019/ecommerce/13_09.sql
  sql/2019/ecommerce/13_09b.sql
  sql/2019/ecommerce/13_09c.sql
  sql/2019/ecommerce/13_09d.sql
  sql/2019/ecommerce/13_09e.sql
  sql/2019/mobile-web/12_12.sql
  sql/2019/mobile-web/12_14.sql
  sql/2020/ecommerce/pagestats_percentile_bydevice_format.sql
  sql/2020/ecommerce/pagestats_percentiles_bydevice.sql
  sql/2020/ecommerce/pct_3pusage_bydevice.sql
  sql/2020/ecommerce/pct_3pusage_bydevice_vendor.sql
  sql/2020/ecommerce/pct_3pusage_bydevice_vendor_category.sql
  sql/2020/http2/cdn_detail_by_cdn.sql
  sql/2020/http2/cdn_summary.sql
  sql/2020/http2/http2_1st_party_vs_3rd_party.sql
  sql/2020/http2/http2_1st_party_vs_3rd_party_by_type.sql
  sql/2020/http2/http2_3rd_party_by_types.sql
  sql/2020/markup/pages_almanac_by_device_and_percentile.sql
  sql/2020/markup/pages_element_count_by_device_and_percentile.sql
  sql/2020/markup/pages_markup_by_device_and_percentile.sql
  sql/2020/markup/pages_wpt_bodies_by_device_and_percentile.sql
  sql/2020/markup/pages_wpt_bodies_by_device_and_percentile_and_heading_level.sql
  sql/2020/markup/pages_wpt_bodies_by_device_and_protocol.sql
  sql/2020/security/feature_adoption_by_other_features.sql
  sql/2020/security/feature_adoption_by_topN_technologies.sql
  sql/2020/seo/pages_almanac_by_device_and_meta_tag_name.sql
  sql/2020/seo/pages_almanac_by_device_and_meta_tag_property.sql
  sql/2020/seo/pages_almanac_video_by_device_and_percentile.sql
  sql/2020/seo/pages_markup_by_device_and_iframe_loading.sql
  sql/2020/seo/pages_markup_by_device_and_percentile.sql
  sql/2020/seo/pages_robots_txt_by_device_and_useragent.sql
  sql/2020/seo/pages_wpt_bodies_by_device_and_number_rel_attribute.sql
  sql/2020/seo/pages_wpt_bodies_by_device_and_percentile.sql
Labels: bug, analysis

#2322 Add Capabilities queries
  sql/2021/capabilities/fugu.sql
  sql/2021/capabilities/top.sql
Labels: analysis

#2325 Upgrade SuperLinter to latest
  .github/workflows/linter.yml
  .github/workflows/test_website.yml
Labels: development
