Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-11, with the labels that each got.

#2421 Update to A11Y and Mobile Web query
  sql/2021/accessibility/focus_outline_0_or_none.sql
  sql/2021/mobile-web/client_hints.sql
Labels: analysis, ASAP

#2416 Stat updates for 2021
  src/templates/en/2021/base.html
  src/templates/es/2021/base.html
  src/templates/fr/2021/base.html
  src/templates/hi/2021/base.html
  src/templates/it/2021/base.html
  src/templates/ja/2021/base.html
  src/templates/nl/2021/base.html
  src/templates/pt/2021/base.html
  src/templates/ru/2021/base.html
  src/templates/tr/2021/base.html
  src/templates/uk/2021/base.html
  src/templates/zh-CN/2021/base.html
  src/templates/zh-TW/2021/base.html
Labels: project management

#2413 Resource Hints 2021 query amends
  sql/2021/resource-hints/dns-prefetch_host.sql
  sql/2021/resource-hints/dns-prefetch_host_by_url.sql
  sql/2021/resource-hints/lazy_viewport_images.sql
  sql/2021/resource-hints/native_iframe_lazy_loading.sql
  sql/2021/resource-hints/preconnect_host.sql
  sql/2021/resource-hints/preconnect_host_by_url.sql
  sql/2021/resource-hints/preload_host.sql
  sql/2021/resource-hints/preload_host_by_url.sql
Labels: analysis, ASAP

#2422 Hide discussion icons if no discuss metadata
  src/templates/base/base_chapter.html
Labels: development

#2349 Jamstack 2021 queries
  sql/2021/jamstack/adoption_of_image_formats_in_ssgs.sql
  sql/2021/jamstack/core_web_vitals_distribution.sql
  sql/2021/jamstack/core_web_vitals_passing.sql
  sql/2021/jamstack/distribution_of_page_weight_requests_and_co2_grams_per_ssg_web_page.sql
  sql/2021/jamstack/median_lighthouse_score.sql
  sql/2021/jamstack/ranking.sql
  sql/2021/jamstack/ssg_compared_to_2020.sql
  sql/2021/jamstack/third_party_bytes_and_requests_on_ssgs.sql
Labels: analysis, ASAP

#2424 Add total blocking time query
  sql/2021/performance/max_tbt.sql
  sql/2021/performance/tbt.sql
Labels: analysis, ASAP

#2426 Add two new chapters to base.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/tr/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: translation

#2429 Change icon ids to allow chapters to use them
  src/templates/base.html
  src/templates/base/base.html
  src/templates/base/base_chapter.html
  src/templates/base/base_ebook.html
  src/templates/base/contributors.html
  src/templates/base/ebook.ejs.html
  src/templates/base/search.html
Labels: development

#2430 Last Third Party SQL changes
  sql/2021/third-parties/third_parties_blocking_main_thread.sql
  sql/2021/third-parties/third_parties_blocking_main_thread_percentiles.sql
Labels: analysis

#2431 Fix two tiny typos in 2019 JavaScript Spanish translation
  src/content/es/2020/javascript.md
Labels: translation

#2436 Fix Lighthouse tests
  src/tools/scripts/set_lighthouse_urls.sh
Labels: development

#2438 Fix Top CMSs by rank query
  sql/2021/cms/top_cms_by_rank.sql
Labels: bug, analysis, ASAP

#2437 PWA 2021 chapter
  src/config/2021.json
  src/content/en/2021/pwa.md
  src/static/images/2021/pwa/pwa-industry-categories.png
  src/static/images/2021/pwa/pwa-lighthouse-pwa-audits.png
  src/static/images/2021/pwa/pwa-lighthouse-pwa-scores.png
  src/static/images/2021/pwa/pwa-manifests-preferring-native-app.png
  src/static/images/2021/pwa/pwa-most-used-service-worker-events.png
  src/static/images/2021/pwa/pwa-notification-acceptance-rates.png
  src/static/images/2021/pwa/pwa-service-worker-and-manifest-usage.png
  src/static/images/2021/pwa/pwa-service-worker-controlled-pages-by-rank.png
  src/static/images/2021/pwa/pwa-top-pwa-manifest-icon-sizes.png
  src/static/images/2021/pwa/pwa-top-workbox-packages.png
  src/static/images/2021/pwa/pwa-workbox-runtime-caching-strategies.png
  src/tools/scripts/run_and_test_website.sh
Labels: writing

#2448 Switch all GitHub avatars to same domain
  src/config/2019.json
  src/config/2020.json
  src/config/2021.json
Labels: development, performance

#2446 Avoid -- to em-dash conversion
  src/tools/generate/generate_typographic_punctuation.js
Labels: development

#2392 Media 2021 queries - video
  sql/2021/media/siteswithvideo_desktop.sql
  sql/2021/media/siteswithvideo_mobile.sql
  sql/2021/media/video_attribute_count_desktop.sql
  sql/2021/media/video_attribute_count_mobile.sql
  sql/2021/media/video_durations_desktop.sql
  sql/2021/media/video_durations_mobile.sql
  sql/2021/media/video_ext.sql
  sql/2021/media/video_number_of_sources_desktop.sql
  sql/2021/media/video_number_of_sources_mobile.sql
  sql/2021/media/video_source_formats_desktop.sql
  sql/2021/media/video_source_formats_mobile.sql
  sql/2021/media/video_styles_desktop.sql
  sql/2021/media/video_styles_mobile.sql
Labels: analysis, ASAP

#2451 Resource Hints queries - added imgLazy
  sql/2021/resource-hints/imgLazy.sql
Labels: analysis, ASAP

#2450 A11Y query bugfixes
  sql/2021/accessibility/audio_track_usage.sql
  sql/2021/accessibility/form_required_controls.sql
  sql/2021/accessibility/video_track_usage.sql
Labels: analysis, ASAP

#2442 Structured Data 2021 SQL update - add page counts
  sql/2021/structured-data/classic_microformats_types.sql
  sql/2021/structured-data/dublin_core_types.sql
  sql/2021/structured-data/facebook_types.sql
  sql/2021/structured-data/jsonld_contexts.sql
  sql/2021/structured-data/jsonld_depth_percentiles.sql
  sql/2021/structured-data/jsonld_entities_relationships.sql
  sql/2021/structured-data/jsonld_relationship_values.sql
  sql/2021/structured-data/jsonld_relationships.sql
  sql/2021/structured-data/jsonld_same_ases.sql
  sql/2021/structured-data/jsonld_types.sql
  sql/2021/structured-data/microdata_item_types.sql
  sql/2021/structured-data/microformats2_types.sql
  sql/2021/structured-data/open_graph_types.sql
  sql/2021/structured-data/present_types.sql
  sql/2021/structured-data/rdfa_prefixes.sql
  sql/2021/structured-data/rdfa_type_ofs.sql
  sql/2021/structured-data/rdfa_vocabs.sql
  sql/2021/structured-data/summary_count.sql
  sql/2021/structured-data/twitter_types.sql
Labels: analysis

#2455 Updated Page Weight queries
  sql/2021/page-weight/group_responsesize_by_cdn.sql
  sql/2021/page-weight/pageweight_by_header_body.sql
Labels: analysis, ASAP

#2456 Fix Syntax Highlighting Colour Contrast issue
  src/static/css/almanac.css
Labels: bug, development, accessibility

#2419 Third parties 2021 markdown
  src/config/2021.json
  src/content/en/2021/third-parties.md
  src/static/images/2021/third-parties/third-parties-bytes-by-content-type-and-category-on-mobile.png
  src/static/images/2021/third-parties/third-parties-facebook-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-google-analytics-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-google-doubleclick-ads-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-google-maps-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-google-tag-manager-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-median-third-party-requests-by-type-and-rank-on-mobile.png
  src/static/images/2021/third-parties/third-parties-most-popular-third-parties-impact-on-render.png
  src/static/images/2021/third-parties/third-parties-number-of-third-parties-per-website.png
  src/static/images/2021/third-parties/third-parties-per-website-by-rank.png
  src/static/images/2021/third-parties/third-parties-popular-third-parties-main-thread-blocking-time.png
  src/static/images/2021/third-parties/third-parties-requests-by-content-type-and-category-on-mobile.png
  src/static/images/2021/third-parties/third-parties-requests-by-type.png
  src/static/images/2021/third-parties/third-parties-timing-allow-origin-header-usage.png
  src/static/images/2021/third-parties/third-parties-top-15-by-usage.png
  src/static/images/2021/third-parties/third-parties-twitter-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-usage-by-content-type.png
  src/static/images/2021/third-parties/third-parties-websites-using-third-parties-by-rank.png
  src/static/images/2021/third-parties/third-parties-websites-using-third-parties-by-year.png
  src/static/images/2021/third-parties/third-parties-youtube-main-thread-impact.png
  src/tools/scripts/set_lighthouse_urls.sh
Labels: writing

#2462 Reorder 2021 chapters
  src/config/2021.json
  src/content/en/2021/fonts.md
Labels: project management

#2461 Add script to auto generate figure images
  src/README.md
  src/package-lock.json
  src/package.json
  src/tools/generate/generate_figure_images.js
Labels: development

#2417 Add 2021 Methodology Page
  src/server/tests/routes_test.py
  src/templates/en/2021/methodology.html
Labels: writing, project management

#2463 Create wasm_stats.sql
  sql/util/wasm_stats.sql
Labels: analysis, project management

#2444 CSS 2021 figures
  src/content/en/2021/css.md
  src/static/css/page.css
  src/static/images/2021/css/animation-name-categories.png
  src/static/images/2021/css/border-box-declarations-per-page.png
  src/static/images/2021/css/css-in-js-libraries.png
  src/static/images/2021/css/css-initiated-image-formats.png
  src/static/images/2021/css/custom-property-depth.png
  src/static/images/2021/css/custom-property-names.png
  src/static/images/2021/css/custom-property-properties.png
  src/static/images/2021/css/custom-property-usage.png
  src/static/images/2021/css/custom-property-value-types.png
  src/static/images/2021/css/declaration-repetition.png
  src/static/images/2021/css/distribution-of-transition-delays.png
  src/static/images/2021/css/distribution-of-transition-durations.png
  src/static/images/2021/css/flexbox-grid-adoption.png
  src/static/images/2021/css/global-keyword-adoption.png
  src/static/images/2021/css/important-properties-per-page.png
  src/static/images/2021/css/logical-property-and-value-usage.png
  src/static/images/2021/css/media-query-features.png
  src/static/images/2021/css/most-color-stops.png
  src/static/images/2021/css/most-common-shorthands-after-longhands.png
  src/static/images/2021/css/most-popular-attribute-selectors.png
  src/static/images/2021/css/most-popular-breakpoints.png
  src/static/images/2021/css/most-popular-class-names.png
  src/static/images/2021/css/most-popular-color-formats.png
  src/static/images/2021/css/most-popular-features-queried.png
  src/static/images/2021/css/most-popular-font-relative-units-of-length.png
  src/static/images/2021/css/most-popular-id-names.png
  src/static/images/2021/css/most-popular-length-units.png
  src/static/images/2021/css/most-popular-longhand-properties-after-shorthands.png
  src/static/images/2021/css/most-popular-operators-using-calc.png
  src/static/images/2021/css/most-popular-properties-used-in-media-queries.png
  src/static/images/2021/css/most-popular-properties-using-calc.png
  src/static/images/2021/css/most-popular-pseudo-classes.png
  src/static/images/2021/css/most-popular-sass-function-calls.png
  src/static/images/2021/css/most-popular-transition-properties.png
  src/static/images/2021/css/most-popular-units-using-calc.png
  src/static/images/2021/css/most-popular-unknown-properties.png
  src/static/images/2021/css/most-popular-unprefixed-gradient-functions.png
  src/static/images/2021/css/most-popular-unprefixed-pseudo-elements.png
  src/static/images/2021/css/number-of-images-loaded.png
  src/static/images/2021/css/rules-per-page.png
  src/static/images/2021/css/stylesheet-transfer-size.png
  src/static/images/2021/css/stylesheets-per-page.png
  src/static/images/2021/css/timing-functions.png
  src/static/images/2021/css/top-important-properties.png
  src/static/images/2021/css/top-layout-methods.png
  src/static/images/2021/css/total-image-weight.png
  src/static/images/2021/css/units-per-calc-occurence.png
  src/static/images/2021/css/usage-of-background-shorthand-vs-longhands.png
  src/static/images/2021/css/usage-of-control-flow-statements-in-scss.png
  src/static/images/2021/css/usage-of-explicit-nesting-in-scss.png
  src/static/images/2021/css/usage-of-flex-shorthands-vs-longhands.png
  src/static/images/2021/css/usage-of-font-shorthand-vs-longhands.png
  src/static/images/2021/css/usage-of-grid-properties.png
  src/static/images/2021/css/usage-of-margin-padding-shorthands-vs-longhands.png
  src/static/images/2021/css/zero-lengths-by-unit.png
Labels: writing

#2465 Fix Safari print view for chapters
  src/static/css/page.css
Labels: bug, development

#2468 Stop GitHub names auto linking
  src/tools/generate/shared.js
Labels: bug, development

#2467 Wasm hero image
  src/config/2021.json
  src/static/images/2021/webassembly/hero_lg.avif
  src/static/images/2021/webassembly/hero_lg.jpg
  src/static/images/2021/webassembly/hero_lg.webp
  src/static/images/2021/webassembly/hero_sm.avif
  src/static/images/2021/webassembly/hero_sm.jpg
  src/static/images/2021/webassembly/hero_sm.webp
  src/static/images/2021/webassembly/hero_xl.jpg
Labels: design, project management

#2469 Allow markdown in blockquotes
  src/tools/generate/generate_extra_markdown_conversions.js
Labels: development

#2471 Change predeloy to use booleans
  .github/workflows/predeploy.yml
Labels: development

#2470 Allow staged versions to be redeployed
  src/README.md
  src/tools/scripts/deploy.sh
Labels: development, project management

#2472 Fix printing in Safari take 2
  src/static/css/page.css
Labels: development

#2473 Support emphasis within italic sections
  src/static/css/almanac.css
  src/static/css/page.css
Labels: development, design

#2474 Fix line height bug on links
  src/static/css/almanac.css
Labels: bug, development

#2439 Privacy 2021 Markdown
  src/config/2021.json
  src/content/en/2021/privacy.md
  src/static/images/2021/privacy/data_breaches_pwned_accounts_per_class.png
  src/static/images/2021/privacy/data_breaches_pwned_websites_per_date_and_breach_sensitivity.png
  src/static/images/2021/privacy/most_common_cmps_for_iab_tcf_v2.png
  src/static/images/2021/privacy/most_common_featurepolicy_permissionspolicy_directive_values.png
  src/static/images/2021/privacy/most_common_featurepolicy_permissionspolicy_directives.png
  src/static/images/2021/privacy/most_common_referrerpolicy_values.png
  src/static/images/2021/privacy/most_common_strings_for_iab_usp.png
  src/static/images/2021/privacy/most_common_tracker_categories.png
  src/static/images/2021/privacy/most_common_trackers.png
  src/static/images/2021/privacy/nb_sites_with_cname_tracking.png
  src/static/images/2021/privacy/nb_sites_with_cname_tracking_per_public_suffix.png
  src/static/images/2021/privacy/nb_sites_with_cname_tracking_per_rank.png
  src/static/images/2021/privacy/nb_websites_using_each_cmp.png
  src/static/images/2021/privacy/nb_websites_using_each_fingerprinting.png
  src/static/images/2021/privacy/nb_websites_using_each_geolocation.png
  src/static/images/2021/privacy/nb_websites_using_each_retargeting.png
  src/static/images/2021/privacy/nb_websites_with_cmp.png
  src/static/images/2021/privacy/nb_websites_with_device_sensor_events.png
  src/static/images/2021/privacy/nb_websites_with_dnt_blink_usage.png
  src/static/images/2021/privacy/nb_websites_with_floc_opt_out.png
  src/static/images/2021/privacy/nb_websites_with_geolocation_blink_usage.png
  src/static/images/2021/privacy/nb_websites_with_iab.png
  src/static/images/2021/privacy/nb_websites_with_mediadevices_blink_usage.png
  src/static/images/2021/privacy/nb_websites_with_nb_trackers.png
  src/static/images/2021/privacy/nb_websites_with_privacy_links.png
  src/static/images/2021/privacy/nb_websites_with_referrerpolicy.png
  src/static/images/2021/privacy/nb_websites_with_user_agent_client_hints.png
  src/static/images/2021/privacy/same_party_cookie_attribute.png
  src/static/images/2021/privacy/top100_cookies_set_from_header.png
  src/static/images/2021/privacy/top100_domains_that_set_cookies_via_response_header.png
Labels: writing

#2354 Compression 2021 queries
  sql/2021/compression/compression_by_content_type.sql
  sql/2021/compression/compression_format_trend.sql
  sql/2021/compression/compression_formats.sql
  sql/2021/compression/compression_formats_text_responses.sql
  sql/2021/compression/first_vs_third_party.sql
  sql/2021/compression/lighthouse_compression_byte_savings.sql
  sql/2021/compression/lighthouse_compression_scores.sql
Labels: analysis, ASAP

#2466 Structured Data 2021 Markdown
  src/config/2021.json
  src/content/en/2021/structured-data.md
  src/static/images/2021/structured-data/hero_lg.avif
  src/static/images/2021/structured-data/hero_lg.jpg
  src/static/images/2021/structured-data/hero_lg.webp
  src/static/images/2021/structured-data/hero_sm.avif
  src/static/images/2021/structured-data/hero_sm.jpg
  src/static/images/2021/structured-data/hero_sm.webp
  src/static/images/2021/structured-data/hero_xl.jpg
  src/static/images/2021/structured-data/structured-data-dublin-core.jpg
  src/static/images/2021/structured-data/structured-data-facebook.jpg
  src/static/images/2021/structured-data/structured-data-json-ld.jpg
  src/static/images/2021/structured-data/structured-data-microdata.jpg
  src/static/images/2021/structured-data/structured-data-microformats.jpg
  src/static/images/2021/structured-data/structured-data-microformats2.jpg
  src/static/images/2021/structured-data/structured-data-open-graph.jpg
  src/static/images/2021/structured-data/structured-data-rdfa-types.jpg
  src/static/images/2021/structured-data/structured-data-twitter.jpg
  src/static/images/2021/structured-data/structured-data-usage-by-type.jpg
Labels: writing

#2452 Resource hints 2021 markdown
  sql/2021/resource-hints/resource_hints_distribution_by_rank.sql
  src/config/2021.json
  src/content/en/2021/resource-hints.md
  src/static/images/2021/resource-hints/adoption-of-loading-lazy-on-img.png
  src/static/images/2021/resource-hints/correlation-of-good-cwv-and-preload.png
  src/static/images/2021/resource-hints/correlation-of-good-lcp-and-preload.png
  src/static/images/2021/resource-hints/google-fonts.png
  src/static/images/2021/resource-hints/http-headers-vs-html-markup.png
  src/static/images/2021/resource-hints/incorrect-crossorigin-attribute-by-file-extension.png
  src/static/images/2021/resource-hints/lazy-loaded-images.png
  src/static/images/2021/resource-hints/preload-as-attribute-values.png
  src/static/images/2021/resource-hints/rel-dns-prefetch-adoption-by-rank.png
  src/static/images/2021/resource-hints/rel-preconnect-adoption-by-rank.png
  src/static/images/2021/resource-hints/rel-preload-adoption-by-rank.png
  src/static/images/2021/resource-hints/resource-hints-adoption.png
Labels: writing

#2477 Privacy 2021 minor edits
  src/content/en/2021/privacy.md
Labels: editing

#2478 Fix image generator to work on Windows
  src/tools/generate/generate_figure_images.js
Labels: bug, development

#2479 Misc README updates on running locally
  src/README.md
Labels: development

#2482 Fix search button on iOS
  src/static/css/almanac.css
Labels: bug, development, design

#2398 Capabilities 2021
  src/config/2021.json
  src/content/en/2021/capabilities.md
  src/static/images/2021/capabilities/async-clipboard-api-page-loads.png
  src/static/images/2021/capabilities/async-clipboard-api.png
  src/static/images/2021/capabilities/file-system-access-api.png
  src/static/images/2021/capabilities/fugu-podium.png
  src/static/images/2021/capabilities/generic-sensor-api-usage.png
  src/static/images/2021/capabilities/generic-sensor-api.png
  src/static/images/2021/capabilities/web-bluetooth.png
  src/static/images/2021/capabilities/web-serial.png
  src/static/images/2021/capabilities/web-share-api-page-loads.png
  src/static/images/2021/capabilities/web-share-api.png
  src/static/images/2021/capabilities/web-usb.png
Labels: writing

#2484 Jamstack adoption by (sub)region
  sql/2021/jamstack/adoption_by_region.sql
  sql/2021/jamstack/adoption_by_subregion.sql
Labels: analysis, ASAP

#2483 Allow optional `feat` query param for home page to force Featured Chapter
  src/templates/base/featured_chapters.ejs.html
Labels: development

#2498 HTTP chapter query fixes
  sql/2021/http/http2_3_support_by_cdn_per_page_and_request.sql
  sql/2021/http/percentiles_of_resources_loaded_over_HTTP2_or_better_per_site.sql
Labels: analysis

#2501 Fix Test Website badge to only look at main branch
  .github/workflows/test_website.yml
  README.md
Labels: development, project management

#2494 Update CDN 2021 contributors
  src/config/2021.json
  src/content/en/2021/cdn.md
Labels: writing, project management

#2490 Update Mobile Web 2021 contributors
  src/config/2021.json
  src/content/en/2021/mobile-web.md
Labels: writing, project management

#2447 2021 PWA Russian translation
  src/config/2020.json
  src/config/2021.json
  src/content/en/2021/pwa.md
  src/content/ru/2021/pwa.md
  src/templates/ru/base_chapter.html
Labels: translation

#2502 Fix one font query
  sql/2021/fonts/variable_font_adoption.sql
Labels: analysis

#2481 Update JavaScript 2021 contributors
  src/config/2021.json
  src/content/en/2021/javascript.md
Labels: writing, project management

#2503 Added font-variant property table
  src/content/en/2021/css.md
Labels: writing

#2491 Update Ecommerce 2021 contributors
  src/config/2021.json
  src/content/en/2021/ecommerce.md
Labels: writing, project management

#2434 Performance 2021 chapter markdown
  src/config/2021.json
  src/content/en/2021/performance.md
  src/static/images/2021/performance/cms-adoption-by-rank.png
  src/static/images/2021/performance/cms_ttfb_cwv_report.png
  src/static/images/2021/performance/performance-1-good-cwv-by-device.png
  src/static/images/2021/performance/performance-2-good-cwv-by-ect.png
  src/static/images/2021/performance/performance-3-change-in-ect.png
  src/static/images/2021/performance/performance-4-top-cwv-country.png
  src/static/images/2021/performance/performance-5-country-top-origins-vs-pop.png
  src/static/images/2021/performance/performance-6-country-top-pop-vs-origins.png
  src/static/images/2021/performance/performance-7-cwv-by-rank.png
  src/static/images/2021/performance/performance-CLS-by-device.png
  src/static/images/2021/performance/performance-CLS-by-ect.png
  src/static/images/2021/performance/performance-CLS-by-rank.png
  src/static/images/2021/performance/performance-FCP-by-device.png
  src/static/images/2021/performance/performance-FCP-by-ect.png
  src/static/images/2021/performance/performance-FCP-by-rank.png
  src/static/images/2021/performance/performance-FID-by-device.png
  src/static/images/2021/performance/performance-FID-by-ect.png
  src/static/images/2021/performance/performance-FID-by-rank.png
  src/static/images/2021/performance/performance-LCP-by-device.png
  src/static/images/2021/performance/performance-LCP-by-ect.png
  src/static/images/2021/performance/performance-LCP-by-rank.png
  src/static/images/2021/performance/performance-TTFB-by-device.png
  src/static/images/2021/performance/performance-TTFB-by-ect.png
  src/static/images/2021/performance/performance-TTFB-by-rank.png
  src/static/images/2021/performance/performance-lcp-antipatterns.png
  src/static/images/2021/performance/performance-lcp-with-image.png
  src/static/images/2021/performance/performance-tbt.png
  src/static/images/2021/performance/performance-top-15-lcp-nodes.png
  src/static/images/2021/performance/top-cmss-by-rank.png
Labels: writing

#2497 Update HTTP 2021 contributors
  src/config/2021.json
  src/content/en/2021/http.md
Labels: writing, project management

#2475 Edit Privacy 2021 Chapter
  sql/2021/privacy/most_common_cmps_for_iab_tcf_v2.sql
  sql/2021/privacy/most_common_featurepolicy_permissionspolicy_directive_values.sql
  sql/2021/privacy/most_common_strings_for_iab_usp.sql
  sql/2021/privacy/most_common_trackers.sql
  sql/2021/privacy/nb_sites_with_cname_tracking.sql
  sql/2021/privacy/nb_sites_with_cname_tracking_per_public_suffix.sql
  sql/2021/privacy/nb_sites_with_cname_tracking_per_rank.sql
  sql/2021/privacy/number_of_websites_with_device_sensor_events.sql
  sql/2021/privacy/top100_cookies_set_from_header.sql
  sql/2021/privacy/top100_domains_that_set_cookies_via_response_header.sql
  src/content/en/2021/privacy.md
  src/static/images/2021/privacy/most_common_cmps_for_iab_tcf_v2.png
  src/static/images/2021/privacy/most_common_featurepolicy_permissionspolicy_directive_values.png
  src/static/images/2021/privacy/most_common_featurepolicy_permissionspolicy_directives.png
  src/static/images/2021/privacy/most_common_referrerpolicy_values.png
  src/static/images/2021/privacy/most_common_strings_for_iab_usp.png
  src/static/images/2021/privacy/most_common_tracker_categories.png
  src/static/images/2021/privacy/most_common_trackers.png
  src/static/images/2021/privacy/nb_sites_with_cname_tracking.png
  src/static/images/2021/privacy/nb_sites_with_cname_tracking_per_public_suffix.png
  src/static/images/2021/privacy/nb_sites_with_cname_tracking_per_rank.png
  src/static/images/2021/privacy/nb_websites_using_each_retargeting.png
  src/static/images/2021/privacy/nb_websites_with_device_sensor_events.png
  src/static/images/2021/privacy/nb_websites_with_mediadevices_blink_usage.png
  src/static/images/2021/privacy/nb_websites_with_privacy_links.png
  src/static/images/2021/privacy/nb_websites_with_user_agent_client_hints.png
  src/static/images/2021/privacy/top100_cookies_set_from_header.png
  src/static/images/2021/privacy/top100_domains_that_set_cookies_via_response_header.png
Labels: editing

#2509 Only allow "done" chapters to be generated
  src/tools/generate/generate_chapters.js
Labels: development

#2510 Misc corrections to contributors
  src/config/2019.json
  src/config/2021.json
  src/content/en/2019/fonts.md
  src/content/en/2019/mobile-web.md
  src/content/en/2019/pwa.md
  src/content/en/2021/resource-hints.md
  src/content/es/2019/fonts.md
  src/content/fr/2019/fonts.md
  src/content/fr/2019/mobile-web.md
  src/content/ja/2019/fonts.md
  src/content/ja/2019/mobile-web.md
  src/content/ja/2019/pwa.md
Labels: project management

#2512 Temporarily remove some chapters from the ToC
  src/config/2021.json
Labels: project management

#2513 Better foreword handling
  src/templates/base/base.html
  src/templates/base/base_ebook.html
  src/templates/base/table_of_contents.html
  src/templates/es/2020/base.html
  src/templates/hi/2020/base.html
  src/templates/ru/2020/base.html
  src/templates/zh-TW/2020/base.html
Labels: development, project management

#2514 Fix some chapter references
  src/content/en/2021/performance.md
  src/content/en/2021/pwa.md
Labels: editing

#2515 Prevent Generate script erroring if chapter does not exist in config
  src/tools/generate/generate_chapters.js
Labels: bug, development

#2516 Misc metadata fixes
  src/config/spelling_ignore_words.txt
  src/content/en/2021/performance.md
  src/content/en/2021/privacy.md
  src/content/en/2021/resource-hints.md
  src/content/en/2021/structured-data.md
  src/content/en/2021/third-parties.md
Labels: editing

#2493 Page Weight 2021 Contributors
  src/config/2021.json
  src/content/en/2021/page-weight.md
Labels: writing

#2518 Add Page Weight and Markdown back in
  src/config/2021.json
Labels: project management

#2521 Correct figure numbering for blockquotes
  src/tools/generate/generate_figure_ids.js
  src/tools/scripts/test_template_changes.sh
Labels: bug, development

#2506 2021 CSS chapter
  src/config/2021.json
  src/content/en/2021/css.md
Labels: writing

#2523 Fix links in Capabilities and PWA chapters
  src/content/en/2021/capabilities.md
  src/content/en/2021/pwa.md
Labels: editing

#2524 Mark CSS as unedited
  src/content/en/2021/css.md
Labels: writing, editing

#2441 CMS 2021 - Markdown
  src/config/2021.json
  src/content/en/2021/cms.md
  src/static/images/2021/cms/cms-adoption-geo-region.png
  src/static/images/2021/cms/cms-adoption-geo.png
  src/static/images/2021/cms/cms-adoption-rank.png
  src/static/images/2021/cms/cms-adoption-share.png
  src/static/images/2021/cms/cms-adoption.png
  src/static/images/2021/cms/core-web-vitals-cls-yoy.png
  src/static/images/2021/cms/core-web-vitals-cls.png
  src/static/images/2021/cms/core-web-vitals-fid-yoy.png
  src/static/images/2021/cms/core-web-vitals-fid.png
  src/static/images/2021/cms/core-web-vitals-lcp-yoy.png
  src/static/images/2021/cms/core-web-vitals-lcp.png
  src/static/images/2021/cms/core-web-vitals-yoy.png
  src/static/images/2021/cms/core-web-vitals.png
  src/static/images/2021/cms/image-formats.png
  src/static/images/2021/cms/lighthouse-accessibility.png
  src/static/images/2021/cms/lighthouse-best-practices.png
  src/static/images/2021/cms/lighthouse-performance.png
  src/static/images/2021/cms/lighthouse-seo.png
  src/static/images/2021/cms/resource-weights-css.png
  src/static/images/2021/cms/resource-weights-distribution.png
  src/static/images/2021/cms/resource-weights-fonts.png
  src/static/images/2021/cms/resource-weights-html.png
  src/static/images/2021/cms/resource-weights-images.png
  src/static/images/2021/cms/resource-weights-javascript.png
  src/static/images/2021/cms/resource-weights-page.png
  src/static/images/2021/cms/top-cms-by-rank.png
  src/static/images/2021/cms/top-cms.png
  src/static/images/2021/cms/wordpress-adoption-geo.png
  src/static/images/2021/cms/wordpress-passing-cwv.png
  src/static/images/2021/cms/wordpress-resources-loaded.png
Labels: writing

#2522 Adds contributors for the security chapter of 2021
  src/config/2021.json
  src/content/en/2021/security.md
Labels: writing, project management

#2526 Fix link and logicalphase's username
  src/content/en/2021/cms.md
  src/static/css/almanac.css
Labels: bug

#2485 Update Markup 2021 contributors
  src/config/2021.json
  src/content/en/2021/markup.md
Labels: writing, project management

#2527 Set CMS back to todo so it's not included in early release
  src/config/2021.json
Labels: project management

#2519 Ecommerce 2021
  src/content/en/2021/ecommerce.md
  src/static/images/2021/ecommerce/distribution-of-html-bytes-per-ecommerce-page.png
  src/static/images/2021/ecommerce/distribution-of-image-bytes-for-ecommerce.png
  src/static/images/2021/ecommerce/distribution-of-image-requests-for-ecommerce.png
  src/static/images/2021/ecommerce/distribution-of-third-party-bytes.png
  src/static/images/2021/ecommerce/distribution-of-third-party-requests.png
  src/static/images/2021/ecommerce/ecommerce-comparison-2019-to-2021.png
  src/static/images/2021/ecommerce/ecommerce-median-page-kilobytes-by-type.png
  src/static/images/2021/ecommerce/ecommerce-median-page-requests-by-type.png
  src/static/images/2021/ecommerce/ecommerce-page-requests-by-type-at-90th-percentile.png
  src/static/images/2021/ecommerce/ecommerce-page-requests-distribution.png
  src/static/images/2021/ecommerce/ecommerce-page-weight-distribution.png
  src/static/images/2021/ecommerce/ecommerce-real-user-core-web-vitals-experiences.png
  src/static/images/2021/ecommerce/ecommerce-real-user-cumulative-layout-shift-experiences.png
  src/static/images/2021/ecommerce/ecommerce-real-user-first-input-delay-experiences.png
  src/static/images/2021/ecommerce/ecommerce-real-user-largest-contentful-paint-experiences.png
  src/static/images/2021/ecommerce/ecommerce-vendor-growth-covid-19-impact.png
  src/static/images/2021/ecommerce/hreflang-links-ecommerce.png
  src/static/images/2021/ecommerce/median-lighthouse-accessibility-scores-for-ecommerce-websites.png
  src/static/images/2021/ecommerce/median-lighthouse-best-practices-scores-for-ecommerce-websites.png
  src/static/images/2021/ecommerce/median-lighthouse-performance-scores-for-ecommerce-websites.png
  src/static/images/2021/ecommerce/median-lighthouse-scores-for-ecommerce-websites.png
  src/static/images/2021/ecommerce/poppular-image-formats-ecommerce.png
  src/static/images/2021/ecommerce/top-5-ecommerce-platforms-by-crux-rank.png
  src/static/images/2021/ecommerce/top-ab-testing-ecommerce.png
  src/static/images/2021/ecommerce/top-analytics-ecommerce.png
  src/static/images/2021/ecommerce/top-ecommerce-platforms-top-100k-sites.png
  src/static/images/2021/ecommerce/top-ecommerce-platforms-top-10k-sites.png
  src/static/images/2021/ecommerce/top-ecommerce-platforms-top-1m-sites.png
  src/static/images/2021/ecommerce/top-ecommerce-platforms.png
  src/static/images/2021/ecommerce/top-javascript-frameworks-ecommerce.png
  src/static/images/2021/ecommerce/top-javascript-libraries-ecommerce.png
  src/static/images/2021/ecommerce/top-tag-managers-ecommerce.png
  src/static/images/2021/ecommerce/web-push-notification-acceptance-rates-ecommerce.png
Labels: writing

#2486 Update Media 2021 contributors
  src/config/2021.json
  src/content/en/2021/media.md
Labels: writing, project management

#2488 Update SEO 2021 contributors
  src/config/2021.json
  src/content/en/2021/seo.md
Labels: writing, project management

#2492 Update Jamstack 2021 contributors
  src/config/2021.json
  src/content/en/2021/jamstack.md
Labels: writing, project management

#2495 Update Compression 2021 contributors
  src/config/2021.json
  src/content/en/2021/compression.md
Labels: writing, project management

#2496 Update Caching 2021 contributors
  src/content/en/2021/caching.md
Labels: writing, project management

#2489 Update Accessibility 2021 contributors
  src/config/2021.json
  src/content/en/2021/accessibility.md
Labels: writing, project management

#2531 Compression 2021 contributors
  src/config/2021.json
  src/content/en/2021/compression.md
Labels: writing, project management

#2530 Mobile web 2021
  src/content/en/2021/mobile-web.md
  src/static/images/2021/mobile-web/desktop-cls-example.gif
  src/static/images/2021/mobile-web/mobile-cls-example.gif
  src/static/images/2021/mobile-web/mobile-web-akimai-device-distribution-by-day.png
  src/static/images/2021/mobile-web/mobile-web-akimai-device-distribution-by-hour-weekdays.png
  src/static/images/2021/mobile-web/mobile-web-akimai-device-distribution-by-hour-weekends.png
  src/static/images/2021/mobile-web/mobile-web-cumulative-layout-shift.png
  src/static/images/2021/mobile-web/mobile-web-first-input-delay.png
  src/static/images/2021/mobile-web/mobile-web-largest-contentful-paint.png
  src/static/images/2021/mobile-web/mobile-web-mobile-traffic-distribution.png
  src/static/images/2021/mobile-web/mobile-web-more-mobile-than-desktop-traffic.png
  src/static/images/2021/mobile-web/mobile-web-most-common-mobile-aria-roles.png
  src/static/images/2021/mobile-web/mobile-web-native-lazy-loading-over-time.png
  src/static/images/2021/mobile-web/mobile-web-responsive-images.png
  src/static/images/2021/mobile-web/mobile-web-sufficient-color-contrast.png
  src/static/images/2021/mobile-web/mobile-web-usage-of-device-client-hints.png
  src/static/images/2021/mobile-web/mobile-web-usage-of-navigator-devicememory.png
  src/static/images/2021/mobile-web/mobile-web-usage-of-network-client-hints.png
  src/static/images/2021/mobile-web/mobile-web-usage-of-networkinformation-effectivetype.png
  src/static/images/2021/mobile-web/mobile-web-zoom-blocking-viewport-tags.png
Labels: writing

#2532 Update SEO 2021 contributors
  src/config/2021.json
  src/content/en/2021/seo.md
Labels: project management

#2536 Prefer Almanac characters to default GitHub avatars
  src/config/2021.json
Labels: project management

#2511 Add note about color contrast visualization issues to Accessibility Statement
  src/templates/en/accessibility_statement.html
  src/templates/es/accessibility_statement.html
  src/templates/fr/accessibility_statement.html
  src/templates/hi/accessibility_statement.html
  src/templates/ja/accessibility_statement.html
  src/templates/nl/accessibility_statement.html
  src/templates/zh-CN/accessibility_statement.html
Labels: writing, accessibility

#2541 Fix GitHub avatars
  src/config/2019.json
  src/config/2020.json
  src/config/2021.json
Labels: project management

#2543 Fix typo in Accessibility Statement
  src/templates/en/accessibility_statement.html
  src/templates/es/accessibility_statement.html
  src/templates/fr/accessibility_statement.html
  src/templates/hi/accessibility_statement.html
  src/templates/ja/accessibility_statement.html
  src/templates/zh-CN/accessibility_statement.html
Labels: bug, accessibility, editing

#2538 Change Markup queries to order by pct first
  sql/2021/markup/attributes.sql
  sql/2021/markup/buttons.sql
  sql/2021/markup/content_encoding.sql
  sql/2021/markup/data_attributes.sql
  sql/2021/markup/doctype.sql
  sql/2021/markup/element_popularity.sql
  sql/2021/markup/favicons.sql
  sql/2021/markup/html_lang.sql
  sql/2021/markup/meta_nodes_name.sql
  sql/2021/markup/meta_viewport.sql
  sql/2021/markup/top_elements.sql
Labels: analysis

#2546 Social media image for home page
  src/static/images/home-hero-2021.png
Labels: bug, ASAP

#2547 Update 2021.json
  src/config/2021.json
Labels: project management

#2548 Fix PWA MDN links
  src/content/en/2021/pwa.md
  src/content/ru/2021/pwa.md
Labels: editing

#2549 Fix Jamstack LH scores
  sql/2021/jamstack/median_lighthouse_score.sql
Labels: analysis

#2551 Fix deploy script for ebooks
  .github/workflows/predeploy.yml
Labels: bug, development

#2552 Add RMHolmlund's name
  src/config/2021.json
Labels: project management

#2555 Correct sheet ids for Performance chapter
  src/content/en/2021/performance.md
Labels: editing

#2556 Small tweaks to Third Party chapter
  src/content/en/2021/third-parties.md
Labels: editing

#2560 Add Sankey diagram to Structured Data chapter
  src/content/en/2021/structured-data.md
  src/static/images/2021/structured-data/structured-data-json-ld-entities-relationships.svg
Labels: editing

#2561 Fix predeploy script (again!)
  .github/workflows/predeploy.yml
Labels: bug, development

#2559 Few more fixups to Wasm SQL
  sql/2021/webassembly/compression_methods.sql
  sql/2021/webassembly/proposals.sql
Labels: analysis, ASAP

#2568 Update Alex's website in 2020
  src/config/2020.json
Labels: project management

#2569 Fix typo in Third Parties chapter
  src/content/en/2021/third-parties.md
Labels: editing

#2566 Edits for CMS Chapter
  src/content/en/2021/cms.md
  src/static/images/2021/cms/cms-adoption-geo-region.png
  src/static/images/2021/cms/cms-adoption-geo.png
  src/static/images/2021/cms/cms-adoption-rank.png
  src/static/images/2021/cms/cms-adoption-share.png
  src/static/images/2021/cms/cms-adoption.png
  src/static/images/2021/cms/core-web-vitals-cls-yoy.png
  src/static/images/2021/cms/core-web-vitals-cls.png
  src/static/images/2021/cms/core-web-vitals-fid-yoy.png
  src/static/images/2021/cms/core-web-vitals-fid.png
  src/static/images/2021/cms/core-web-vitals-lcp-yoy.png
  src/static/images/2021/cms/core-web-vitals-lcp.png
  src/static/images/2021/cms/core-web-vitals-yoy.png
  src/static/images/2021/cms/core-web-vitals.png
  src/static/images/2021/cms/image-formats.png
  src/static/images/2021/cms/lighthouse-accessibility.png
  src/static/images/2021/cms/lighthouse-best-practices.png
  src/static/images/2021/cms/lighthouse-performance.png
  src/static/images/2021/cms/lighthouse-seo.png
  src/static/images/2021/cms/resource-weights-css.png
  src/static/images/2021/cms/resource-weights-distribution.png
  src/static/images/2021/cms/resource-weights-fonts.png
  src/static/images/2021/cms/resource-weights-html.png
  src/static/images/2021/cms/resource-weights-images.png
  src/static/images/2021/cms/resource-weights-javascript.png
  src/static/images/2021/cms/resource-weights-page.png
  src/static/images/2021/cms/top-cms-by-rank.png
  src/static/images/2021/cms/top-cms.png
  src/static/images/2021/cms/wordpress-adoption-geo.png
  src/static/images/2021/cms/wordpress-passing-cwv.png
  src/static/images/2021/cms/wordpress-resources-loaded.png
Labels: editing

#2553 Edits for Ecommerce chapter
  sql/2021/ecommerce/pagestats_percentiles_bydevice.sql
  src/content/en/2021/ecommerce.md
  src/static/images/2021/ecommerce/distribution-of-html-bytes-per-ecommerce-page.png
  src/static/images/2021/ecommerce/distribution-of-image-bytes-for-ecommerce.png
  src/static/images/2021/ecommerce/distribution-of-image-requests-for-ecommerce.png
  src/static/images/2021/ecommerce/distribution-of-third-party-bytes.png
  src/static/images/2021/ecommerce/distribution-of-third-party-requests.png
  src/static/images/2021/ecommerce/ecommerce-comparison-2019-to-2021.png
  src/static/images/2021/ecommerce/ecommerce-median-page-kilobytes-by-type.png
  src/static/images/2021/ecommerce/ecommerce-median-page-requests-by-type.png
  src/static/images/2021/ecommerce/ecommerce-page-requests-by-type-at-90th-percentile.png
  src/static/images/2021/ecommerce/ecommerce-page-requests-distribution.png
  src/static/images/2021/ecommerce/ecommerce-page-weight-distribution.png
  src/static/images/2021/ecommerce/ecommerce-real-user-core-web-vitals-experiences.png
  src/static/images/2021/ecommerce/ecommerce-real-user-cumulative-layout-shift-experiences.png
  src/static/images/2021/ecommerce/ecommerce-real-user-first-input-delay-experiences.png
  src/static/images/2021/ecommerce/ecommerce-real-user-largest-contentful-paint-experiences.png
  src/static/images/2021/ecommerce/ecommerce-vendor-growth-covid-19-impact.png
  src/static/images/2021/ecommerce/hreflang-links-ecommerce.png
  src/static/images/2021/ecommerce/median-lighthouse-accessibility-scores-for-ecommerce-websites.png
  src/static/images/2021/ecommerce/median-lighthouse-best-practices-scores-for-ecommerce-websites.png
  src/static/images/2021/ecommerce/median-lighthouse-performance-scores-for-ecommerce-websites.png
  src/static/images/2021/ecommerce/median-lighthouse-scores-for-ecommerce-websites.png
  src/static/images/2021/ecommerce/poppular-image-formats-ecommerce.png
  src/static/images/2021/ecommerce/top-5-ecommerce-platforms-by-crux-rank.png
  src/static/images/2021/ecommerce/top-ab-testing-ecommerce.png
  src/static/images/2021/ecommerce/top-analytics-ecommerce.png
  src/static/images/2021/ecommerce/top-ecommerce-platforms-top-100k-sites.png
  src/static/images/2021/ecommerce/top-ecommerce-platforms-top-10k-sites.png
  src/static/images/2021/ecommerce/top-ecommerce-platforms-top-1m-sites.png
  src/static/images/2021/ecommerce/top-ecommerce-platforms.png
  src/static/images/2021/ecommerce/top-javascript-frameworks-ecommerce.png
  src/static/images/2021/ecommerce/top-javascript-libraries-ecommerce.png
  src/static/images/2021/ecommerce/top-tag-managers-ecommerce.png
  src/static/images/2021/ecommerce/web-push-notification-acceptance-rates-ecommerce.png
Labels: editing

#2573 Updated monetization query to use blink_features
  sql/2021/markup/monetization.sql
Labels: analysis

#2554 Accessibility 2021 chapter
  sql/2021/accessibility/landmark_elements_and_roles.sql
  src/config/2021.json
  src/content/en/2021/accessibility.md
  src/static/images/2021/accessibility/a11y-app-usage-by-rank.png
  src/static/images/2021/accessibility/alt-attribute-lengths.png
  src/static/images/2021/accessibility/button-name-sources.png
  src/static/images/2021/accessibility/color-contrast-2019-2020-2021.png
  src/static/images/2021/accessibility/common-file-extensions-in-alt-text.png
  src/static/images/2021/accessibility/form-input-name-sources.png
  src/static/images/2021/accessibility/form-required-controls.png
  src/static/images/2021/accessibility/page_title-information.png
  src/static/images/2021/accessibility/pages-containing-alt-with-file-extension.png
  src/static/images/2021/accessibility/pages-overriding-focus-styles.png
  src/static/images/2021/accessibility/pages-using-a11y-apps-by-rank.png
  src/static/images/2021/accessibility/pages-using-a11y-apps.png
  src/static/images/2021/accessibility/pages-zooming-scaling-disabled-by-rank.png
  src/static/images/2021/accessibility/pages-zooming-scaling-disabled.png
  src/static/images/2021/accessibility/placeholder-but-no-label.png
  src/static/images/2021/accessibility/sites-using-role.png
  src/static/images/2021/accessibility/tabindex-usage-and-values.png
  src/static/images/2021/accessibility/top-10-aria-roles.png
  src/static/images/2021/accessibility/top10-aria-attributes.png
  src/static/images/2021/accessibility/userpreference-media-queries.png
Labels: writing

#2576 Accessibility 2021 edits
  src/config/2021.json
  src/content/en/2021/accessibility.md
Labels: editing

#2577 Featured stat edits
  src/content/en/2019/cms.md
  src/content/en/2020/css.md
  src/content/en/2020/privacy.md
  src/content/en/2020/pwa.md
  src/content/en/2020/security.md
  src/content/en/2021/css.md
  src/content/en/2021/pwa.md
  src/content/es/2020/seo.md
  src/content/fr/2019/caching.md
  src/content/fr/2019/markup.md
  src/content/fr/2019/resource-hints.md
  src/content/fr/2019/seo.md
  src/content/fr/2019/third-parties.md
  src/content/it/2020/css.md
  src/content/it/2020/privacy.md
  src/content/nl/2020/privacy.md
  src/content/nl/2020/pwa.md
  src/content/nl/2020/security.md
  src/content/pt/2020/css.md
  src/content/ru/2020/css.md
  src/content/ru/2021/pwa.md
Labels: editing

#2357 CDN 2021 queries
  sql/2021/cdn/cdn_usage_by_site_rank.sql
  sql/2021/cdn/distribution_of_compression_types_by_cdn.sql
  sql/2021/cdn/distribution_of_compression_types_cdn_vs_origin.sql
  sql/2021/cdn/distribution_of_http_versions.sql
  sql/2021/cdn/distribution_of_http_versions_cdn_vs_origin.sql
  sql/2021/cdn/distribution_of_tls_time_by_cdn.sql
  sql/2021/cdn/distribution_of_tls_time_cdn_vs_origin.sql
  sql/2021/cdn/distribution_of_tls_versions.sql
  sql/2021/cdn/distribution_of_tls_versions_cdn_vs_origin.sql
  sql/2021/cdn/top_cdns.sql
  sql/2021/cdn/top_cdns_by_rank.sql
  sql/2021/cdn/usage_of_content_cdns.sql
Labels: analysis, ASAP

#2540 CDN 2021 chapter
  src/config/2021.json
  src/content/en/2021/cdn.md
  src/static/images/2021/cdn/cdn-usage-hosted.png
  src/static/images/2021/cdn/cdn-usage-ranking-desktop.png
  src/static/images/2021/cdn/cdn-usage-ranking-mobile.png
  src/static/images/2021/cdn/compression-desktop.png
  src/static/images/2021/cdn/compression-mobile.png
  src/static/images/2021/cdn/http-versions-desktop-3p.png
  src/static/images/2021/cdn/http-versions-desktop.png
  src/static/images/2021/cdn/http-versions-mobile-3p.png
  src/static/images/2021/cdn/http-versions-mobile.png
  src/static/images/2021/cdn/tls-negotiation.png
  src/static/images/2021/cdn/tls-version-desktop-3p.png
  src/static/images/2021/cdn/tls-version-desktop.png
  src/static/images/2021/cdn/tls-version-mobile-3p.png
  src/static/images/2021/cdn/tls-version-mobile.png
  src/static/images/2021/cdn/top-cdns-3p.png
  src/static/images/2021/cdn/top-cdns-subdomain.png
  src/static/images/2021/cdn/top-cdns.png
Labels: writing

#2580 Fix a number of issues causing our production tests to fail
  .github/lighthouse/lighthouse-config-dev.json
  src/content/nl/2020/privacy.md
  src/templates/ja/accessibility_statement.html
Labels: bug, development

#2578 Security chapter
  src/config/2021.json
  src/content/en/2021/security.md
  src/static/images/2021/security/security-adoption-of-csp-and-xfo-per-country.png
  src/static/images/2021/security/security-adoption-of-https-per-country.png
  src/static/images/2021/security/security-adoption-of-security-headers.png
  src/static/images/2021/security/security-cookie-age-usage-by-site-in-mobile-in-days.png
  src/static/images/2021/security/security-cryptominer-market-share.png
  src/static/images/2021/security/security-cryptominer-usage.png
  src/static/images/2021/security/security-csp-directives-usage.png
  src/static/images/2021/security/security-csp-header-length.png
  src/static/images/2021/security/security-distribution-of-cipher-suites.png
  src/static/images/2021/security/security-hsts-max-age-values-in-days.png
  src/static/images/2021/security/security-httponly-secure-samesite-cookie-usage.png
  src/static/images/2021/security/security-https-usage-by-site.png
  src/static/images/2021/security/security-prevalence-of-headers-in-sites-by-rank.png
  src/static/images/2021/security/security-prevalence-of-sandbox-directives-on-frames.png
  src/static/images/2021/security/security-samesite-cookie-attributes.png
  src/static/images/2021/security/security-subresource-integrity-coverage-per-page.png
  src/static/images/2021/security/security-tls-version-by-site.png
  src/static/images/2021/security/security-usage-of-properties-in-well-known-security.png
  src/static/images/2021/security/security-usage-of-well-known-security.png
Labels: writing

#2583 Media 2021 queries
  sql/2021/media/README.md
  sql/2021/media/bytes_and_dimensions.sql
  sql/2021/media/bytes_and_dimensions_by_format.sql
  sql/2021/media/image_0x0.sql
  sql/2021/media/image_1x1.sql
  sql/2021/media/image_alt.sql
  sql/2021/media/image_cdn_usage.sql
  sql/2021/media/image_decode_usage.sql
  sql/2021/media/image_mimetype_ext.sql
  sql/2021/media/image_sizes_accuracy.sql
  sql/2021/media/image_sizes_accuracy_pct.sql
  sql/2021/media/image_sizes_attribute_strings.sql
  sql/2021/media/image_sizing_extrinsic_intrinsic.sql
  sql/2021/media/image_srcset_candidates.sql
  sql/2021/media/image_srcset_densities.sql
  sql/2021/media/image_srcset_descriptor.sql
  sql/2021/media/image_srcset_sizes.sql
  sql/2021/media/img_sizes_explicit_errors.sql
  sql/2021/media/img_with_dimensions.sql
  sql/2021/media/img_xdomain.sql
  sql/2021/media/media_formats.sql
  sql/2021/media/picture_distribution.sql
  sql/2021/media/picture_format_distribution.sql
  sql/2021/media/picture_orientation.sql
  sql/2021/media/picture_switching.sql
  sql/2021/media/picture_using_min_resolution.sql
  sql/2021/media/pixel_volume.sql
  sql/2021/media/portrait_landscape_square.sql
  sql/2021/media/score_progressive_jpeg.sql
  sql/2021/media/siteswithvideo_desktop.sql
  sql/2021/media/siteswithvideo_mobile.sql
  sql/2021/media/top_aspect_ratios.sql
  sql/2021/media/video_adoption.sql
  sql/2021/media/video_attribute_names.sql
  sql/2021/media/video_attribute_widths.sql
  sql/2021/media/video_autoplay_muted.sql
  sql/2021/media/video_preload.sql
  sql/2021/media/video_preload_values.sql
  sql/2021/media/video_source_types.sql
  sql/2021/media/video_tag_and_js_player.sql
Labels: analysis, ASAP

#2588 Correct secondary axis colour on Third Parties graphs
  src/static/images/2021/third-parties/third-parties-facebook-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-google-analytics-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-google-doubleclick-ads-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-google-maps-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-google-tag-manager-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-twitter-main-thread-impact.png
  src/static/images/2021/third-parties/third-parties-youtube-main-thread-impact.png
Labels: editing

#2587 Ukrainian Translation - Page Weight Chapter
  src/content/uk/2020/page-weight.md
Labels: translation

#2589 Create image folder in generate script if not present
  src/tools/generate/generate_figure_images.js
Labels: development

#2563 WebAssembly 2021 chapter
  sql/2021/webassembly/sizes_and_savings_100.sql
  src/config/2021.json
  src/content/en/2021/webassembly.md
  src/static/images/2021/webassembly/br_savings.png
  src/static/images/2021/webassembly/br_sizes.png
  src/static/images/2021/webassembly/compression_methods.png
  src/static/images/2021/webassembly/counts.png
  src/static/images/2021/webassembly/cross_domain.png
  src/static/images/2021/webassembly/instruction_kinds.png
  src/static/images/2021/webassembly/mime_types.png
  src/static/images/2021/webassembly/popular_by_name.png
  src/static/images/2021/webassembly/proposals.png
  src/static/images/2021/webassembly/raw_resp_sizes.png
  src/static/images/2021/webassembly/section_sizes.png
  src/static/images/2021/webassembly/strip_br_savings.png
  src/static/images/2021/webassembly/strip_br_savings_100.png
  src/static/images/2021/webassembly/uncompressed_resp_sizes.png
  src/static/images/2021/webassembly/wasm_opt_bench.png
  src/static/images/2021/webassembly/wasm_opt_br_bench.png
  src/static/images/2021/webassembly/wasm_opt_br_savings.png
  src/static/images/2021/webassembly/wasm_opt_savings.png
Labels: writing

#2572 Implementation of UI for webmention reactions.
  src/server/csp.py
  src/static/css/page.css
  src/static/js/webmentions.js
  src/templates/base/base_chapter.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/tr/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: development

#2592 Privacy 2021: update links to Security chapter
  src/content/en/2021/privacy.md
Labels: editing

#2591 Correct 2021 Chapter Published Dates
  src/config/last_updated.json
Labels: project management

#2585 Fix ecommerce charts to ignore some non-ecommerce technologies
  src/content/en/2021/ecommerce.md
  src/static/images/2021/ecommerce/top-ecommerce-platforms-top-100k-sites.png
  src/static/images/2021/ecommerce/top-ecommerce-platforms-top-10k-sites.png
  src/static/images/2021/ecommerce/top-ecommerce-platforms-top-1m-sites.png
Labels: editing

#2586 2021 Security edits
  sql/2021/security/https_request_over_time.sql
  src/content/en/2021/security.md
  src/static/images/2021/security/security-adoption-of-csp-and-xfo-per-country.png
  src/static/images/2021/security/security-adoption-of-https-per-country.png
  src/static/images/2021/security/security-adoption-of-security-headers.png
  src/static/images/2021/security/security-cookie-age-usage-by-site-in-mobile-in-days.png
  src/static/images/2021/security/security-cryptominer-market-share.png
  src/static/images/2021/security/security-cryptominer-usage.png
  src/static/images/2021/security/security-csp-directives-usage.png
  src/static/images/2021/security/security-distribution-of-cipher-suites.png
  src/static/images/2021/security/security-hsts-max-age-values-in-days.png
  src/static/images/2021/security/security-httponly-secure-samesite-cookie-usage.png
  src/static/images/2021/security/security-https-usage-by-site.png
  src/static/images/2021/security/security-prevalence-of-headers-in-sites-by-rank.png
  src/static/images/2021/security/security-prevalence-of-sandbox-directives-on-frames.png
  src/static/images/2021/security/security-samesite-cookie-attributes.png
  src/static/images/2021/security/security-subresource-integrity-coverage-per-page.png
  src/static/images/2021/security/security-tls-version-by-site.png
  src/static/images/2021/security/security-usage-of-properties-in-well-known-security.png
  src/static/images/2021/security/security-usage-of-well-known-security.png
Labels: editing

#2593 Fix WebMentions error breaking build on merge to main
  src/static/js/webmentions.js
Labels: bug, development

#2545 Editing mobile web chapter
  src/content/en/2021/mobile-web.md
  src/static/images/2021/mobile-web/desktop-cls-example-static.png
  src/static/images/2021/mobile-web/mobile-cls-example-static.png
  src/static/images/2021/mobile-web/mobile-web-akamai-device-distribution-by-day.png
  src/static/images/2021/mobile-web/mobile-web-akamai-device-distribution-by-hour-weekdays.png
  src/static/images/2021/mobile-web/mobile-web-akamai-device-distribution-by-hour-weekends.png
  src/static/images/2021/mobile-web/mobile-web-akimai-device-distribution-by-day.png
  src/static/images/2021/mobile-web/mobile-web-akimai-device-distribution-by-hour-weekdays.png
  src/static/images/2021/mobile-web/mobile-web-akimai-device-distribution-by-hour-weekends.png
  src/static/images/2021/mobile-web/mobile-web-cumulative-layout-shift.png
  src/static/images/2021/mobile-web/mobile-web-first-input-delay.png
  src/static/images/2021/mobile-web/mobile-web-largest-contentful-paint.png
  src/static/images/2021/mobile-web/mobile-web-mobile-traffic-distribution.png
  src/static/images/2021/mobile-web/mobile-web-more-mobile-than-desktop-traffic.png
  src/static/images/2021/mobile-web/mobile-web-most-common-mobile-aria-roles.png
  src/static/images/2021/mobile-web/mobile-web-native-lazy-loading-over-time.png
  src/static/images/2021/mobile-web/mobile-web-popular-input-types.png
  src/static/images/2021/mobile-web/mobile-web-popular-link-protocols.png
  src/static/images/2021/mobile-web/mobile-web-responsive-images.png
  src/static/images/2021/mobile-web/mobile-web-sufficient-color-contrast.png
  src/static/images/2021/mobile-web/mobile-web-usage-of-device-client-hints.png
  src/static/images/2021/mobile-web/mobile-web-usage-of-navigator-devicememory.png
  src/static/images/2021/mobile-web/mobile-web-usage-of-network-client-hints.png
  src/static/images/2021/mobile-web/mobile-web-usage-of-networkinformation-effectivetype.png
  src/static/images/2021/mobile-web/mobile-web-zoom-blocking-viewport-tags.png
  src/templates/base/base.html
Labels: editing

#2595 more Jamstack 2021 queries
  sql/2021/jamstack/adoption.sql
  sql/2021/jamstack/adoption_by_geo.sql
  sql/2021/jamstack/framework_libraries.sql
  sql/2021/jamstack/resource_weights.sql
Labels: analysis, ASAP

#2597 Fix small capitalisation error on home page
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
Labels: editing

#2596 Add Dutch accessibility statement translation extra piece
  src/templates/nl/accessibility_statement.html
Labels: translation

#2599 TinyPNG Capabilities images
  src/static/images/2021/capabilities/async-clipboard-api-page-loads.png
  src/static/images/2021/capabilities/async-clipboard-api.png
  src/static/images/2021/capabilities/file-system-access-api.png
  src/static/images/2021/capabilities/fugu-podium.png
  src/static/images/2021/capabilities/generic-sensor-api-usage.png
  src/static/images/2021/capabilities/generic-sensor-api.png
  src/static/images/2021/capabilities/web-bluetooth.png
  src/static/images/2021/capabilities/web-serial.png
  src/static/images/2021/capabilities/web-share-api-page-loads.png
  src/static/images/2021/capabilities/web-share-api.png
  src/static/images/2021/capabilities/web-usb.png
Labels: performance

#2567 JavaScript 2021 chapter and query updates
  sql/2021/javascript/ajax_async.sql
  sql/2021/javascript/ajax_request_per_page.sql
  sql/2021/javascript/ajax_sync.sql
  sql/2021/javascript/breakdown_of_pages_using_async_defer.sql
  sql/2021/javascript/breakdown_of_scripts_using_async_defer_module_nomodule.sql
  sql/2021/javascript/lighthouse_vulnerabilities.sql
  sql/2021/javascript/lighthouse_vulnerable_libraries.sql
  sql/2021/javascript/module_and_nomodule.sql
  sql/2021/javascript/requests_by_3p.sql
  sql/2021/javascript/web_components_specs.sql
  src/config/2021.json
  src/content/en/2021/javascript.md
  src/static/images/2021/javascript/ajax-apis-per-year.png
  src/static/images/2021/javascript/ajax_beacon.png
  src/static/images/2021/javascript/ajax_fetch.png
  src/static/images/2021/javascript/ajax_xhr.png
  src/static/images/2021/javascript/async-requests-per-page.png
  src/static/images/2021/javascript/average-unminified-js-bytes.png
  src/static/images/2021/javascript/compression-first-third-party.png
  src/static/images/2021/javascript/compression-requests.png
  src/static/images/2021/javascript/javascript-bytes-per-page.png
  src/static/images/2021/javascript/javascript-resource-hint-usage.png
  src/static/images/2021/javascript/js-libs-frameworks.png
  src/static/images/2021/javascript/js-requests-desktop-host.png
  src/static/images/2021/javascript/js-requests-mobile-host.png
  src/static/images/2021/javascript/js-requests-per-page.png
  src/static/images/2021/javascript/js-resources-over-years.png
  src/static/images/2021/javascript/prefetch-hints-per-page.png
  src/static/images/2021/javascript/preload-hints-per-page.png
  src/static/images/2021/javascript/sourcemap-first-third-party.png
  src/static/images/2021/javascript/uncompressed-first-third-party.png
  src/static/images/2021/javascript/unminified-js-audit-scores.png
  src/static/images/2021/javascript/unminified-js-bytes.png
  src/static/images/2021/javascript/unused-javascript-bytes-per-page.png
  src/static/images/2021/javascript/unused-vs-total-javascript.png
  src/static/images/2021/javascript/usage-sync-async-over-years.png
  src/static/images/2021/javascript/usage-sync-async.png
Labels: analysis, ASAP, writing

#2584 Edits for CDN 2021 chapter
  src/content/en/2021/cdn.md
  src/static/images/2021/cdn/cdn-usage-hosted.png
  src/static/images/2021/cdn/cdn-usage-ranking-desktop.png
  src/static/images/2021/cdn/cdn-usage-ranking-mobile.png
  src/static/images/2021/cdn/compression-desktop.png
  src/static/images/2021/cdn/compression-mobile.png
  src/static/images/2021/cdn/http-versions-desktop-3p.png
  src/static/images/2021/cdn/http-versions-desktop.png
  src/static/images/2021/cdn/http-versions-mobile-3p.png
  src/static/images/2021/cdn/http-versions-mobile.png
  src/static/images/2021/cdn/tls-version-desktop-3p.png
  src/static/images/2021/cdn/tls-version-desktop.png
  src/static/images/2021/cdn/tls-version-mobile-3p.png
  src/static/images/2021/cdn/tls-version-mobile.png
  src/static/images/2021/cdn/top-cdns.png
Labels: editing

#2533 Edits for CSS chapter
  src/content/en/2021/css.md
  src/static/images/2021/css/animation-name-categories.png
  src/static/images/2021/css/border-box-declarations-per-page.png
  src/static/images/2021/css/css-in-js-libraries.png
  src/static/images/2021/css/css-initiated-image-formats.png
  src/static/images/2021/css/custom-property-depth.png
  src/static/images/2021/css/custom-property-names.png
  src/static/images/2021/css/custom-property-properties.png
  src/static/images/2021/css/custom-property-usage.png
  src/static/images/2021/css/custom-property-value-types.png
  src/static/images/2021/css/declaration-repetition.png
  src/static/images/2021/css/distribution-of-transition-delays.png
  src/static/images/2021/css/distribution-of-transition-durations.png
  src/static/images/2021/css/flexbox-grid-adoption.png
  src/static/images/2021/css/global-keyword-adoption.png
  src/static/images/2021/css/important-properties-per-page.png
  src/static/images/2021/css/logical-property-and-value-usage.png
  src/static/images/2021/css/media-query-features.png
  src/static/images/2021/css/most-common-shorthands-after-longhands.png
  src/static/images/2021/css/most-popular-attribute-selectors.png
  src/static/images/2021/css/most-popular-breakpoints.png
  src/static/images/2021/css/most-popular-class-names.png
  src/static/images/2021/css/most-popular-color-formats.png
  src/static/images/2021/css/most-popular-features-queried.png
  src/static/images/2021/css/most-popular-font-relative-units-of-length.png
  src/static/images/2021/css/most-popular-id-names.png
  src/static/images/2021/css/most-popular-length-units.png
  src/static/images/2021/css/most-popular-longhand-properties-after-shorthands.png
  src/static/images/2021/css/most-popular-operators-using-calc.png
  src/static/images/2021/css/most-popular-properties-used-in-media-queries.png
  src/static/images/2021/css/most-popular-properties-using-calc.png
  src/static/images/2021/css/most-popular-pseudo-classes.png
  src/static/images/2021/css/most-popular-sass-function-calls.png
  src/static/images/2021/css/most-popular-transition-properties.png
  src/static/images/2021/css/most-popular-units-using-calc.png
  src/static/images/2021/css/most-popular-unknown-properties.png
  src/static/images/2021/css/most-popular-unprefixed-gradient-functions.png
  src/static/images/2021/css/most-popular-unprefixed-pseudo-elements.png
  src/static/images/2021/css/number-of-images-loaded.png
  src/static/images/2021/css/rules-per-page.png
  src/static/images/2021/css/stylesheet-transfer-size.png
  src/static/images/2021/css/stylesheets-per-page.png
  src/static/images/2021/css/timing-functions.png
  src/static/images/2021/css/top-important-properties.png
  src/static/images/2021/css/top-layout-methods.png
  src/static/images/2021/css/total-image-weight.png
  src/static/images/2021/css/units-per-calc-occurence.png
  src/static/images/2021/css/usage-of-background-shorthand-vs-longhands.png
  src/static/images/2021/css/usage-of-control-flow-statements-in-scss.png
  src/static/images/2021/css/usage-of-explicit-nesting-in-scss.png
  src/static/images/2021/css/usage-of-flex-shorthands-vs-longhands.png
  src/static/images/2021/css/usage-of-font-shorthand-vs-longhands.png
  src/static/images/2021/css/usage-of-grid-properties.png
  src/static/images/2021/css/usage-of-margin-padding-shorthands-vs-longhands.png
  src/static/images/2021/css/zero-lengths-by-unit.png
Labels: editing

#2601 Fix back ticks usage in Russian PWA translation
  src/content/ru/2021/pwa.md
Labels: bug, translation

#2602 Fix webmentions for sources that do not provide full meta data
  src/static/js/webmentions.js
Labels: bug, development

#2603 Page Weight 2021 edits
  sql/2021/page-weight/page-weight-trend.sql
  src/config/2021.json
  src/content/en/2021/page-weight.md
  src/static/images/2021/page-weight/bytes-distribution-content-type.png
  src/static/images/2021/page-weight/median-page-weight-trend.png
  src/static/images/2021/page-weight/requests-distribution.png
Labels: ASAP, editing

#2517 Page Weight 2021 Markdown
  sql/2021/page-weight/page-weight-trend.sql
  src/config/2021.json
  src/content/en/2021/page-weight.md
  src/static/images/2021/page-weight/bytes-distribution-content-type.png
  src/static/images/2021/page-weight/bytes-distribution.png
  src/static/images/2021/page-weight/median-page-weight-trend.png
  src/static/images/2021/page-weight/requests-content-type.png
  src/static/images/2021/page-weight/requests-distribution.png
  src/static/images/2021/page-weight/response-distribution-format.png
  src/static/images/2021/page-weight/response-distribution-images.png
Labels: editing

#2590 Web mentions translations
  src/config/2021.json
  src/static/js/webmentions.js
  src/templates/base/base_chapter.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/tr/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: translation

#2605 Edits for WebAssembly 2021 Chapter
  src/content/en/2021/webassembly.md
Labels: editing

#2574 Compression 2021 chapter contents
  src/content/en/2021/compression.md
  src/static/images/2021/compression/compession-methods-by-content-type.png
  src/static/images/2021/compression/compression-algorithms-for-http-responses.png
  src/static/images/2021/compression/compression-format-trend-desktop.png
  src/static/images/2021/compression/compression-format-trend-mobile.png
  src/static/images/2021/compression/compression-levels-brotli.png
  src/static/images/2021/compression/compression-levels-gzip.png
  src/static/images/2021/compression/content-encoding.png
  src/static/images/2021/compression/http-compression-methods-for-image-types.png
  src/static/images/2021/compression/text-compression-lighthouse-scores.png
Labels: ASAP, writing

#2613 Fix quotes in CSS chapter bio
  src/content/en/2021/css.md
Labels: bug, editing

#2609 User singular team role for contibutor cards
  src/templates/base/base_ebook.html
  src/templates/base/contributors.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/tr/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: development

#2616 Add CWV query for SEO 2021
  sql/2021/seo/core-web-vitals.sql
Labels: analysis, ASAP

#2619 Only check branch is clean for npm run start on GitHub
  src/tools/scripts/run_and_test_website.sh
Labels: bug, development

#2618 Typos in Privacy chapter
  src/content/en/2021/privacy.md
Labels: editing

#2622 Add extra semi-colon to webmentions script
  src/static/js/webmentions.js
Labels: development

#2624 Edits for Compression 2021 Chapter
  src/content/en/2021/compression.md
Labels: editing

#2632 Remove unedited flag from Compression chapter
  src/content/en/2021/compression.md
Labels: project management

#2633 Add shantsis as editor to Compression chapter
  src/content/en/2021/compression.md
Labels: editing
