Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-07, with the labels that each got.

#2261 [ES][2020] 2020 JavaScript Spanish Translation
  src/config/2020.json
  src/content/es/2020/javascript.md
Labels: translation

#2268 Discussion CTA and Explore the results are in English
  src/templates/base/base_chapter.html
Labels: translation

#2269 Stop testing website for SQL only changes
  .github/workflows/test_website.yml
Labels: development

#2271 2020 base japanese translation
  src/templates/ja/2020/base.html
Labels: translation

#2277 CSP improvements for Lighthouse v8
  .github/lighthouse/lighthouse-config-dev.json
  .github/lighthouse/lighthouse-config-prod.json
  .github/workflows/production-checks.yml
  .github/workflows/test_website.yml
  src/server/csp.py
Labels: development

#2278 Improve CodeQL performance
  .github/workflows/code-static-analysis.yml
Labels: bug

#2279 Relax the img-src CSP to prevent noise from Google Adwords
  src/server/csp.py
  src/server/stories_csp.py
Labels: development

#2280 Better Lighthouse Audits
  .github/lighthouse/lighthouse-config-dev.json
  .github/lighthouse/lighthouse-config-prod.json
  src/content/en/2019/resource-hints.md
  src/content/fr/2019/resource-hints.md
  src/content/ja/2019/resource-hints.md
  src/content/pt/2019/resource-hints.md
  src/static/css/page.css
Labels: bug, development
