Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-04, with the labels that each got.

#2104 Create Template Files for Turkish Translation
  README.md
  src/templates/tr/2019/base.html
  src/templates/tr/2019/index.html
  src/templates/tr/2020/base.html
  src/templates/tr/2020/index.html
  src/templates/tr/base.html
  src/templates/tr/base_chapter.html
  src/templates/tr/error.html
Labels: translation

#2110 Fix typo in our difficult to type name :-)
  src/content/es/2020/http2.md
  src/templates/ja/base.html
  src/templates/zh-CN/base.html
  src/tools/scripts/deploy.sh
Labels: editing

#2112 Translate the 2020 http2 chapter to Dutch
  src/content/en/2020/security.md
  src/content/ja/2020/security.md
  src/content/nl/2020/accessibility.md
  src/content/nl/2020/capabilities.md
  src/content/nl/2020/cms.md
  src/content/nl/2020/fonts.md
  src/content/nl/2020/http2.md
  src/content/nl/2020/javascript.md
  src/content/nl/2020/markup.md
  src/content/nl/2020/media.md
  src/content/nl/2020/mobile-web.md
  src/content/nl/2020/pwa.md
  src/content/nl/2020/resource-hints.md
  src/content/nl/2020/security.md
  src/content/nl/2020/third-parties.md
  src/templates/nl/2019/methodology.html
  src/templates/nl/2020/methodology.html
Labels: translation

#2116 Turkish Translation:2019 and 2020 Table of Contents
  src/templates/tr/2019/table_of_contents.html
  src/templates/tr/2020/table_of_contents.html
Labels: translation

#2115 2020 seo japanese translation
  src/content/ja/2020/seo.md
Labels: translation

#2118 Convert remaining markdown tables to HTML
  src/content/en/2019/fonts.md
  src/content/en/2019/http2.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/security.md
  src/content/en/2019/third-parties.md
  src/content/en/2020/css.md
  src/content/en/2020/http2.md
  src/content/es/2019/fonts.md
  src/content/es/2019/markup.md
  src/content/es/2019/media.md
  src/content/es/2020/http2.md
  src/content/fr/2019/markup.md
  src/content/fr/2019/media.md
  src/content/fr/2019/third-parties.md
  src/content/it/2020/css.md
  src/content/it/2020/http2.md
  src/content/ja/2019/fonts.md
  src/content/ja/2019/http2.md
  src/content/ja/2019/markup.md
  src/content/ja/2019/media.md
  src/content/ja/2019/security.md
  src/content/ja/2019/third-parties.md
  src/content/ja/2020/css.md
  src/content/ja/2020/http2.md
  src/content/nl/2020/http2.md
  src/content/pt/2019/http2.md
  src/content/pt/2020/css.md
Labels: editing

#2119 Handle markdown in meta data
  src/content/en/2019/caching.md
  src/content/en/2019/media.md
  src/content/en/2019/pwa.md
  src/content/en/2019/resource-hints.md
  src/content/en/2019/third-parties.md
  src/content/en/2020/accessibility.md
  src/content/en/2020/css.md
  src/content/en/2020/fonts.md
  src/content/en/2020/jamstack.md
  src/content/en/2020/markup.md
  src/content/en/2020/media.md
  src/content/en/2020/resource-hints.md
  src/content/es/2019/media.md
  src/content/fr/2019/caching.md
  src/content/fr/2019/markup.md
  src/content/fr/2019/media.md
  src/content/fr/2019/resource-hints.md
  src/content/fr/2019/third-parties.md
  src/content/it/2020/css.md
  src/content/it/2020/markup.md
  src/content/it/2020/resource-hints.md
  src/content/ja/2019/caching.md
  src/content/ja/2019/cdn.md
  src/content/ja/2019/media.md
  src/content/ja/2019/pwa.md
  src/content/ja/2019/resource-hints.md
  src/content/ja/2019/third-parties.md
  src/content/ja/2020/accessibility.md
  src/content/ja/2020/css.md
  src/content/nl/2020/accessibility.md
  src/content/nl/2020/fonts.md
  src/content/nl/2020/markup.md
  src/content/nl/2020/media.md
  src/content/nl/2020/resource-hints.md
  src/content/pt/2020/css.md
  src/static/css/index.css
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_featured_chapters.js
  src/tools/generate/shared.js
Labels: development

#2120 Remove smart quotes for consistency and ease of editing
  src/content/en/2019/accessibility.md
  src/content/en/2019/fonts.md
  src/content/en/2019/security.md
  src/content/en/2020/css.md
  src/content/en/2020/media.md
  src/content/fr/2019/css.md
  src/content/fr/2019/markup.md
  src/content/fr/2019/media.md
  src/content/fr/2020/performance.md
  src/content/ja/2019/security.md
  src/content/nl/2020/markup.md
  src/content/nl/2020/performance.md
  src/tools/generate/generate_typographic_punctuation.js
  src/tools/generate/shared.js
Labels: editing

#2122 Turkish Translation of 2019 and 2020 Contributors Pages
  src/templates/tr/2019/contributors.html
  src/templates/tr/2020/contributors.html
Labels: translation

#2125 Upgrade smartypants 0.1.15
  src/package-lock.json
  src/package.json
  src/tools/generate/generate_typographic_punctuation.js
Labels: development

#2128 Better kbd styling
  src/content/en/2019/accessibility.md
  src/content/nl/2019/accessibility.md
  src/content/pt/2019/accessibility.md
  src/content/zh-CN/2019/accessibility.md
  src/static/css/almanac.css
Labels: editing

#2132 Translated 2020 third-parties chapter to Italian
  src/content/it/2020/third-parties.md
Labels: translation

#2131 2020 markup japanese translation
  src/content/en/2020/markup.md
  src/content/ja/2020/markup.md
Labels: translation

#2136 2020 cms japanese translation
  src/content/ja/2020/cms.md
Labels: translation

#2166 Fix generate scripts for 2021
  src/config/2021.json
  src/tools/generate/generate_chapters.js
  src/tools/scripts/set_lighthouse_urls.sh
Labels: bug, development

#2170 Add proposed 2021 chapters
  src/content/en/2021/localization
  src/content/en/2021/webassembly
Labels: project management
