Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-01, with the labels that each got.

#1860 Fix Stories Template Name
  src/tools/generate/generate_sitemap.js
Labels: bug, development

#1856 ES #498: http2 translated to Spanish
  src/content/en/2020/http2.md
  src/content/es/2020/http2.md
Labels: good first issue, translation

#1853 Add remaining pytest for 100% cover
  src/package.json
  src/server/errors.py
  src/server/tests/errors_test.py
  src/server/tests/language_test.py
  src/server/tests/routes_test.py
Labels: development

#1859 Further edits to 2020 Markup chapter
  src/content/en/2020/markup.md
Labels: editing

#1863 Fix some typos in 2020 PWA chapter
  src/content/en/2020/pwa.md
Labels: editing

#1866 Allow HTML entities in author bios
  src/templates/base/base_chapter.html
  src/templates/base/ebook.ejs.html
Labels: bug, development

#1858 Markup 2020 additional edits
  src/content/en/2020/markup.md
  src/static/images/2020/markup/script-use.png
Labels: editing

#1870 Add Stories to timestamps file
  src/tools/generate/generate_timestamps.js
Labels: bug, development

#1872 Fix typo in Russian translation of Methodology chapter
  src/templates/ru/2020/methodology.html
Labels: translation

#1874 .gitignore updated for JetBrains IDE
  .gitignore
Labels: development

#1879 Allow HTML entities in featured stats
  src/tools/generate/generate_featured_chapters.js
Labels: development

#1877 Copyedit Third Parties 2020
  src/content/en/2020/third-parties.md
  src/static/images/2020/third-parties/cpu-time-by-category.png
  src/static/images/2020/third-parties/distribution-of-request-count.png
  src/static/images/2020/third-parties/page-size-by-category.png
  src/static/images/2020/third-parties/page-size-by-host.png
  src/static/images/2020/third-parties/pages-with-thirdparties.png
  src/static/images/2020/third-parties/redirects-body-size.png
  src/static/images/2020/third-parties/requests-before-dom-by-category.png
  src/static/images/2020/third-parties/requests-cached-by-content-type.png
  src/static/images/2020/third-parties/requests-with-tao.png
  src/static/images/2020/third-parties/thirdparty-by-content-types.png
  src/static/images/2020/third-parties/top-domains-by-prevalence.png
Labels: editing

#1842 Create Italian Resource-Hints
  src/config/2020.json
  src/content/it/2020/resource-hints.md
  src/server/language.py
  src/templates/it/2020/base.html
  src/templates/it/2020/index.html
  src/templates/it/2020/table_of_contents.html
  src/templates/it/base.html
  src/templates/it/base_chapter.html
  src/templates/it/error.html
Labels: translation

#1876 Make Oxford comma optional per language
  src/templates/base/base_chapter.html
  src/templates/base/base_ebook.html
  src/templates/base/contributors.html
  src/templates/base/ebook.ejs.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: development, translation

#1878 FR Translation for 2020 Performance Chapter
  src/content/en/2020/performance.md
  src/content/fr/2020/performance.md
Labels: translation

#1881 Turn on Italian for 2019
  src/config/2019.json
  src/config/2020.json
  src/content/en/2020/resource-hints.md
  src/templates/it/2019/base.html
  src/templates/it/2019/contributors.html
  src/templates/it/2019/index.html
  src/templates/it/2019/table_of_contents.html
  src/templates/it/2020/contributors.html
  src/templates/it/base.html
Labels: translation

#1884 Updates to Italian translations
  src/templates/it/base.html
Labels: translation

#1886 Add Italian to README
  README.md
  src/config/2019.json
  src/config/2020.json
  src/server/language.py
Labels: translation

#1888 Update web vitals script
  src/static/js/web-vitals.js
Labels: development

#1868 Close out final 2020 Fonts Chapter TODOs
  src/content/en/2020/fonts.md
Labels: editing

#1846 Copy edit of 2020 CSS chapter
  src/content/en/2020/css.md
  src/static/css/page.css
  src/static/images/2020/css/calc-complexity-units.png
  src/static/images/2020/css/calc-operators.png
  src/static/images/2020/css/gradient-most-stops.png
  src/static/images/2020/css/keyword-totals.png
  src/static/images/2020/css/usage-of-control-flow-statements-scss.png
  src/templates/base/base.html
Labels: editing

#1889 translate 2020 Capabilities chapter to Dutch
  src/content/nl/2020/capabilities.md
Labels: translation

#1893 Avoid scrollbars on desktop
  src/static/css/page.css
Labels: bug, development

#1892 Ukrainian Translation - Core Templates
  README.md
  src/config/2019.json
  src/config/2020.json
  src/server/language.py
  src/templates/uk/2019/base.html
  src/templates/uk/2019/contributors.html
  src/templates/uk/2019/index.html
  src/templates/uk/2019/table_of_contents.html
  src/templates/uk/2020/base.html
  src/templates/uk/2020/contributors.html
  src/templates/uk/2020/index.html
  src/templates/uk/2020/table_of_contents.html
  src/templates/uk/base.html
  src/templates/uk/base_chapter.html
  src/templates/uk/error.html
Labels: translation

#1894 Copyedit of the 2020 Page Weight chapter
  src/content/en/2020/page-weight.md
  src/static/images/2020/page-weight/bytes-distribution-content-type.png
  src/static/images/2020/page-weight/requests-content-type.png
  src/static/images/2020/page-weight/requests-distribution.png
Labels: editing

#1885 FR translation of 2020 foreword
  src/templates/fr/2019/base.html
  src/templates/fr/2020/base.html
  src/templates/fr/base.html
Labels: translation

#1855 Couple of new queries to see Covid-19 impact on eCommerce
  sql/2020/16_Ecommerce/ecomm_covid_growth.sql
  sql/2020/16_Ecommerce/ecomm_vendors_covid_growth.sql
Labels: analysis

#1891 Ecommerce 2020 chapter
  src/config/2020.json
  src/content/en/2020/ecommerce.md
  src/static/images/2020/ecommerce/distribution-of-html-bytes-per-ecommerce-page.png
  src/static/images/2020/ecommerce/distribution-of-image-bytes-for-ecommerce.png
  src/static/images/2020/ecommerce/distribution-of-image-requests-for-ecommerce.png
  src/static/images/2020/ecommerce/distribution-of-third-party-bytes.png
  src/static/images/2020/ecommerce/distribution-of-third-party-requests.png
  src/static/images/2020/ecommerce/ecommerce-comparison-2019-to-2020.png
  src/static/images/2020/ecommerce/ecommerce-consent-management-platform-adoption.png
  src/static/images/2020/ecommerce/ecommerce-real-user-core-web-vitals-exeriences.png
  src/static/images/2020/ecommerce/ecommerce-real-user-cumulative-layout-shift-experiences.png
  src/static/images/2020/ecommerce/ecommerce-real-user-first-input-delay-experiences.png
  src/static/images/2020/ecommerce/ecommerce-real-user-largest-contentful-paint-experiences.png
  src/static/images/2020/ecommerce/ecommerce-vendor-growth-covid-19-impact.png
  src/static/images/2020/ecommerce/enterprise-ecommerce-platforms-2019.png
  src/static/images/2020/ecommerce/enterprise-ecommerce-platforms-2020.png
  src/static/images/2020/ecommerce/enterprise-ecommerce-platforms.png
  src/static/images/2020/ecommerce/median-page-kilobytes-by-type.png
  src/static/images/2020/ecommerce/median-page-requests-by-type.png
  src/static/images/2020/ecommerce/page-requests-distribution.png
  src/static/images/2020/ecommerce/page-weight-distribution.png
  src/static/images/2020/ecommerce/popular-image-formats-on-ecommerce-sites.png
  src/static/images/2020/ecommerce/top-analytics-solutions-on-ecommerce-sites.png
  src/static/images/2020/ecommerce/top-ecommerce-platforms.png
  src/static/images/2020/ecommerce/web-push-notification-acceptance-rates.png
Labels: writing

#1758 Mobile Web 2020 edits
  src/content/en/2020/mobile-web.md
Labels: editing

#1896 Fix a couple of small styling issues in ebook
  src/static/css/2019.css
  src/static/css/page.css
Labels: bug, development

#1900 Update stories 2019 content
  src/templates/en/2020/stories/content_publishing.html
  src/templates/en/2020/stories/page_content.html
Labels: SEO, development, writing

#1902 Fix Stories URLs
  src/templates/en/2020/stories/content_distribution.html
  src/templates/en/2020/stories/content_publishing.html
Labels: bug

#1905 Remove TODO's from nl 2020 markup
  src/content/nl/2020/markup.md
Labels: translation

#1908 Remove TODO's from 2020 SEO and Resource Hints chapters
  src/content/en/2020/resource-hints.md
  src/content/en/2020/seo.md
  src/content/it/2020/resource-hints.md
Labels: editing

#1912 Remove TODOs from edited chapters
  src/content/en/2020/javascript.md
  src/content/en/2020/privacy.md
Labels: editing

#1914 Change "2029" to "2019" in 2020 English Accessibility chapter
  src/content/en/2020/accessibility.md
Labels: editing

#1917 Accessibility statement not in sitemap
  src/config/last_updated.json
  src/tools/generate/generate_featured_chapters.js
  src/tools/generate/generate_sitemap.js
  src/tools/generate/generate_timestamps.js
  src/tools/generate/shared.js
Labels: bug, development

#1911 Compression 2020 more edits
  src/content/en/2020/compression.md
  src/static/images/2020/compression/compession-methods-by-content-type.png
  src/static/images/2020/compression/compression-algorithms-by-content-type-desktop.png
  src/static/images/2020/compression/compression-algorithms-for-http-requests.png
  src/static/images/2020/compression/compression-algorithms-for-http-responses.png
  src/static/images/2020/compression/content-encoding.png
  src/static/images/2020/compression/http-compression-methods-for-image-types.png
  src/static/images/2020/compression/text-compression-lighthouse-scores.png
  src/templates/en/2020/stories/content_distribution.html
Labels: editing

#1918 Move 2019.css to almanac.css
  src/app.yaml
  src/config/last_updated.json
  src/server/routes.py
  src/server/tests/helpers_test.py
  src/server/tests/routes_test.py
  src/static/css/almanac.css
  src/templates/base/base.html
Labels: development

#1916 Ecommerce chapter feedback
  sql/2020/16_Ecommerce/pagestats_image_bydevice.sql
  src/content/en/2020/ecommerce.md
Labels: editing

#1920 Misc template changes
  .github/linters/.flake8
  src/config/2019.json
  src/config/2020.json
  src/server/helpers.py
  src/server/routes.py
  src/server/tests/helpers_test.py
  src/server/tests/routes_test.py
  src/static/images/2020/capabilities/hero_lg.jpg
  src/static/images/2020/capabilities/hero_lg.webp
  src/static/images/2020/capabilities/hero_sm.jpg
  src/static/images/2020/capabilities/hero_sm.webp
  src/static/images/2020/capabilities/hero_xl.jpg
  src/static/images/2020/jamstack/hero_lg.jpg
  src/static/images/2020/jamstack/hero_lg.webp
  src/static/images/2020/jamstack/hero_sm.jpg
  src/static/images/2020/jamstack/hero_sm.webp
  src/static/images/2020/jamstack/hero_xl.jpg
  src/static/images/2020/privacy/hero_lg.jpg
  src/static/images/2020/privacy/hero_lg.webp
  src/static/images/2020/privacy/hero_sm.jpg
  src/static/images/2020/privacy/hero_sm.webp
  src/static/images/2020/privacy/hero_xl.jpg
  src/templates/base/base_chapter.html
  src/templates/base/base_ebook.html
  src/templates/base/ebook.ejs.html
  src/templates/base/table_of_contents.html
  src/tools/generate/generate_ebooks.js
Labels: development

#1923 Correct capitalisation of ruby in Markup chapter
  src/content/en/2020/markup.md
  src/content/nl/2020/markup.md
Labels: editing

#1922 Translated the 2020 Accessibility chapter to Dutch and fixed a couple of typo's in the English version.
  src/content/en/2020/accessibility.md
  src/content/nl/2020/accessibility.md
Labels: translation

#1924 Copyedit 2020 PWA chapter
  sql/2020/14_PWA/lighthouse_pwa_audits_sw.sql
  src/config/2020.json
  src/content/en/2020/pwa.md
Labels: editing

#1909 Russian figure_data: fix accusative case
  src/templates/ru/base_chapter.html
Labels: translation

#1927 Copyedit 2020 Security chapter
  src/content/en/2020/security.md
Labels: editing

#1930 Misc fixes for JavaScript chapter
  src/content/en/2020/javascript.md
  src/content/nl/2020/javascript.md
  src/static/images/2020/javascript/async-defer-mobile.png
  src/static/images/2020/javascript/bytes-2020.png
  src/static/images/2020/javascript/bytes-by-3p-desktop.png
  src/static/images/2020/javascript/bytes-by-3p-mobile.png
  src/static/images/2020/javascript/compression-method-3p.png
  src/static/images/2020/javascript/compression-method-request.png
  src/static/images/2020/javascript/correlations.png
  src/static/images/2020/javascript/external-inline-mobile.png
  src/static/images/2020/javascript/frameworks-bytes.png
  src/static/images/2020/javascript/frameworks-libraries.png
  src/static/images/2020/javascript/frameworks-main-thread-no-ember-diff.png
  src/static/images/2020/javascript/frameworks-main-thread-no-ember.png
  src/static/images/2020/javascript/frameworks-main-thread.png
  src/static/images/2020/javascript/lighthouse-unminified-js-by-3p.png
  src/static/images/2020/javascript/lighthouse-unminified-js.png
  src/static/images/2020/javascript/main-thread-time.png
  src/static/images/2020/javascript/page-weight-per-content-type.png
  src/static/images/2020/javascript/prefetch-distribution.png
  src/static/images/2020/javascript/preload-distribution.png
  src/static/images/2020/javascript/requests-2019.png
  src/static/images/2020/javascript/requests-2020.png
  src/static/images/2020/javascript/requests-by-3p-desktop.png
  src/static/images/2020/javascript/requests-by-3p-mobile.png
  src/static/images/2020/javascript/unused-js-bytes-distribution.png
  src/static/images/2020/javascript/vulnerabilities-by-severity.png
  src/templates/base/base.html
Labels: editing

#1932 Misc fixes to table of contents menu
  src/static/css/almanac.css
  src/templates/base/base.html
Labels: design, development

#1933 Spellcheck fixes
  src/config/spelling_ignore_words.txt
  src/content/en/2020/accessibility.md
  src/content/en/2020/css.md
  src/content/en/2020/ecommerce.md
  src/content/en/2020/fonts.md
  src/content/en/2020/javascript.md
  src/content/en/2020/media.md
  src/content/en/2020/page-weight.md
Labels: editing

#1934 Translate Fonts 2020 Chapter to Dutch + typo's
  src/config/2020.json
  src/content/en/2020/fonts.md
  src/content/nl/2020/fonts.md
Labels: translation

#1939 Remove unnecessary full stops from big figures
  src/content/en/2020/accessibility.md
  src/content/nl/2020/accessibility.md
Labels: editing

#1940 Stop home page bouncing on mobile
  src/static/css/index.css
Labels: bug, development

#1941 Combine contributors bylines where it makes sense
  src/content/en/2019/markup.md
  src/content/en/2020/accessibility.md
  src/content/fr/2019/seo.md
  src/templates/base/base_chapter.html
  src/templates/base/ebook.ejs.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: design, development

#1938 Add Nuxt and Docusauraus to Jamstack 2020 chapter
  src/content/en/2020/jamstack.md
  src/static/images/2020/jamstack/jamstack-adoption-share-2020-pie.png
  src/static/images/2020/jamstack/jamstack-adoption-share-yoy.png
  src/static/images/2020/jamstack/jamstack-adoption.png
  src/static/images/2020/jamstack/jamstack-carbon-emissions-per-jamstack-page-view.png
  src/static/images/2020/jamstack/jamstack-popularity-of-image-formats.png
  src/static/images/2020/jamstack/jamstack-real-user-cumulative-layout-shift-experiences.png
  src/static/images/2020/jamstack/jamstack-real-user-first-input-delay-experiences.png
  src/static/images/2020/jamstack/jamstack-real-user-largest-contentful-paint-experiences.png
  src/static/images/2020/jamstack/jamstack-third-party-bytes.png
  src/templates/en/2020/stories/content_publishing.html
Labels: editing

#1942 Add typographic punctuation
  src/content/en/2019/caching.md
  src/content/en/2019/compression.md
  src/content/en/2019/fonts.md
  src/content/en/2019/markup.md
  src/content/en/2019/media.md
  src/content/en/2019/performance.md
  src/content/en/2020/compression.md
  src/content/en/2020/markup.md
  src/content/en/2020/resource-hints.md
  src/content/es/2019/css.md
  src/content/es/2019/fonts.md
  src/content/es/2019/javascript.md
  src/content/es/2019/markup.md
  src/content/es/2019/media.md
  src/content/fr/2019/caching.md
  src/content/fr/2019/javascript.md
  src/content/fr/2019/media.md
  src/content/fr/2019/third-parties.md
  src/content/it/2020/resource-hints.md
  src/content/ja/2019/fonts.md
  src/content/ja/2019/media.md
  src/content/nl/2020/capabilities.md
  src/content/nl/2020/cms.md
  src/content/nl/2020/javascript.md
  src/package-lock.json
  src/package.json
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_typographic_punctuation.js
Labels: design, development

#1944 Fix figure number bug
  src/templates/base/base.html
  src/templates/base/ebook.ejs.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
  src/tools/generate/generate_figure_ids.js
Labels: bug, development

#1945 Typographical quotes for metadata
  src/content/en/2019/caching.md
  src/content/en/2019/cdn.md
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_typographic_punctuation.js
Labels: development

#1946 Smart Quotes for English non-chapter pages
  src/templates/en/2019/base.html
  src/templates/en/2019/methodology.html
  src/templates/en/2020/base.html
  src/templates/en/2020/methodology.html
  src/templates/en/base.html
Labels: writing

#1948 Fix hide description bug
  src/templates/base/base.html
Labels: bug, development

#1950 Fix figure links and footnotes for ebook
  src/content/en/2019/third-parties.md
  src/content/en/2020/css.md
  src/content/fr/2019/third-parties.md
  src/content/ja/2019/third-parties.md
  src/content/nl/2020/fonts.md
  src/templates/base/base.html
  src/templates/nl/2020/methodology.html
  src/tools/generate/generate_ebooks.js
Labels: bug, development

#1949 Translation of 2020 accessibility chapter to Japanese
  src/content/ja/2020/accessibility.md
Labels: translation

#1937 2020 javascript japanese translation
  src/content/ja/2020/javascript.md
Labels: translation

#1951 Remove control characters causing HTML validation errors
  src/content/zh-TW/2020/performance.md
Labels: bug, translation

#1952 Update total number of pages in ebook to 600!
  src/templates/en/2020/base.html
  src/templates/fr/2020/base.html
  src/templates/it/2020/base.html
  src/templates/nl/2020/base.html
  src/templates/uk/2020/base.html
Labels: writing
