Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-02, with the labels that each got.

#1956 Change Introductie to Inleiding on Dutch chapters
  src/content/nl/2019/accessibility.md
  src/content/nl/2020/accessibility.md
  src/content/nl/2020/capabilities.md
  src/content/nl/2020/cms.md
  src/content/nl/2020/fonts.md
  src/content/nl/2020/javascript.md
  src/content/nl/2020/markup.md
  src/content/nl/2020/performance.md
Labels: translation

#1957 Extend height of AMP Stories images
  src/static/images/home-hero-2020-part-1.png
  src/static/images/home-hero-2020-part-2.png
  src/static/images/home-hero-2020-part-3.png
  src/static/images/home-hero-2020-part-4.png
Labels: development

#1959 Do fuller HTML linting checks on generated HTML
  .github/linters/.htmlhintrc_morechecks
  .github/workflows/test_website.yml
Labels: development

#1961 Consolidate home page methodology text
  src/templates/en/2019/base.html
  src/templates/en/2020/base.html
  src/templates/en/base.html
  src/templates/es/2019/base.html
  src/templates/es/2020/base.html
  src/templates/es/base.html
  src/templates/fr/2019/base.html
  src/templates/fr/2020/base.html
  src/templates/fr/base.html
  src/templates/hi/2019/base.html
  src/templates/hi/2020/base.html
  src/templates/hi/base.html
  src/templates/it/2019/base.html
  src/templates/it/2020/base.html
  src/templates/it/base.html
  src/templates/ja/2019/base.html
  src/templates/ja/2020/base.html
  src/templates/ja/base.html
  src/templates/nl/2019/base.html
  src/templates/nl/2020/base.html
  src/templates/nl/base.html
  src/templates/pt/2019/base.html
  src/templates/pt/2020/base.html
  src/templates/pt/base.html
  src/templates/ru/2019/base.html
  src/templates/ru/2020/base.html
  src/templates/ru/base.html
  src/templates/uk/2019/base.html
  src/templates/uk/2020/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/2019/base.html
  src/templates/zh-CN/2020/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/2019/base.html
  src/templates/zh-TW/2020/base.html
  src/templates/zh-TW/base.html
Labels: development

#1963 Address keyboard a11y issues
  src/static/js/chapter.js
  src/templates/base/base.html
  src/templates/base/base_chapter.html
  src/templates/en/2019/methodology.html
  src/templates/en/2020/methodology.html
  src/templates/fr/2019/methodology.html
  src/templates/fr/2020/methodology.html
  src/templates/hi/2019/methodology.html
  src/templates/hi/2020/methodology.html
  src/templates/ja/2019/methodology.html
  src/templates/ja/2020/methodology.html
  src/templates/nl/2019/methodology.html
  src/templates/nl/2020/methodology.html
  src/templates/ru/2019/methodology.html
  src/templates/ru/2020/methodology.html
  src/templates/zh-CN/2019/methodology.html
  src/templates/zh-CN/2020/methodology.html
  src/templates/zh-TW/2020/methodology.html
Labels: accessibility, development

#1962 Add year to home page text
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: translation, writing

#1965 Handle larger spine for 2020 ebook
  .github/workflows/predeploy.yml
  src/README.md
  src/templates/base/base_ebook.html
Labels: development

#1966 Upgrade Lighthouse to v7
  .github/lighthouse/lighthouse-config-dev.json
  .github/lighthouse/lighthouse-config-prod.json
  .github/workflows/production-checks.yml
  .github/workflows/test_website.yml
  src/templates/base/base.html
  src/tools/scripts/set_lighthouse_urls.sh
Labels: development

#1967 "she can found be learning" => "she can be found learning"
  src/content/en/2020/seo.md
Labels: editing

#1969 Handle Russian and Ukrainian plurals
  src/server/helpers.py
  src/server/tests/helpers_test.py
  src/templates/base/contributors.html
  src/templates/ru/2019/contributors.html
  src/templates/ru/2020/contributors.html
  src/templates/ru/base.html
  src/templates/uk/2019/contributors.html
  src/templates/uk/2020/contributors.html
  src/templates/uk/base.html
Labels: development, translation

#1935 Update 2020 Privacy chapter for CDNs and Hosting categories
  src/content/en/2020/privacy.md
  src/static/images/2020/privacy/privacy-biggest-third-party-potential-trackers.png
  src/static/images/2020/privacy/privacy-biggest-third-party-trackers.png
  src/static/images/2020/privacy/privacy-tracker-categories.png
  src/static/images/2020/privacy/privacy-websites-that-load-trackers.png
Labels: editing

#1964 Portuguese Translation - foreword block in base.html
  src/config/2020.json
  src/templates/pt/2020/base.html
Labels: translation

#1958 Translated Javascript and Markup chapter to Italian
  src/content/en/2020/markup.md
  src/content/it/2020/javascript.md
  src/content/it/2020/markup.md
Labels: translation

#1970 CodeQL improvements
  .github/workflows/code-static-analysis.yml
Labels: development

#1974 GitHub Action version updates
  .github/workflows/add-to-release-notes.yml
  .github/workflows/code-static-analysis.yml
  .github/workflows/compress-images.yml
  .github/workflows/linter.yml
  .github/workflows/predeploy.yml
  .github/workflows/production-checks.yml
  .github/workflows/progress-tracker.yml
  .github/workflows/test-template-changes.yml
  .github/workflows/test_website.yml
Labels: development

#1915 Copyedit Caching 2020
  src/content/en/2020/caching.md
  src/static/images/2020/caching/cache-control-and-max-age-and-expires-2019.png
  src/static/images/2020/caching/cache-control-and-max-age-and-expires.png
  src/static/images/2020/caching/cache-control-directives.png
  src/static/images/2020/caching/cache-ttl-lighthouse-score.png
  src/static/images/2020/caching/cache-wasted-bytes-lighthouse.png
  src/static/images/2020/caching/cacheable-and-non-cacheable.png
  src/static/images/2020/caching/cacheable-by-resource-type.png
  src/static/images/2020/caching/chrome-dev-tools.png
  src/static/images/2020/caching/invalid-last-modified-and-expires-and-date.png
  src/static/images/2020/caching/last-modified-and-etag-2019.png
  src/static/images/2020/caching/last-modified-and-etag.png
  src/static/images/2020/caching/lighthouse-caching-audit.png
  src/static/images/2020/caching/luna-cat.jpg
  src/static/images/2020/caching/luna-cat.png
  src/static/images/2020/caching/request-response-flow-with-caching.png
  src/static/images/2020/caching/resource-age-party-and-type-wise-groups-1st-party.png
  src/static/images/2020/caching/resource-age-party-and-type-wise-groups-3rd-party.png
  src/static/images/2020/caching/service-workers-controlled-pages-2019-2020.png
  src/static/images/2020/caching/set-cookie-usage-on-cacheable-responses.png
  src/static/images/2020/caching/set-cookie-usage-on-private-and-non-private-cacheable-responses.png
  src/static/images/2020/caching/ttl-cachable-responses.png
  src/static/images/2020/caching/valid-if-none-match-returns-304.png
  src/static/images/2020/caching/vary-headers.png
  src/templates/en/2020/stories/content_distribution.html
Labels: editing

#1976 Fix broken links
  src/config/2020.json
  src/content/en/2020/css.md
  src/content/en/2020/jamstack.md
  src/content/en/2020/security.md
  src/templates/en/2019/methodology.html
  src/templates/en/2020/methodology.html
  src/templates/fr/2019/methodology.html
  src/templates/fr/2020/methodology.html
  src/templates/hi/2019/methodology.html
  src/templates/hi/2020/methodology.html
  src/templates/ja/2019/methodology.html
  src/templates/ja/2020/methodology.html
  src/templates/nl/2019/methodology.html
  src/templates/nl/2020/methodology.html
  src/templates/ru/2019/methodology.html
  src/templates/ru/2020/methodology.html
  src/templates/zh-CN/2019/methodology.html
  src/templates/zh-CN/2020/methodology.html
  src/templates/zh-TW/2020/methodology.html
Labels: editing

#1978 Sorted package.json
  src/package-lock.json
  src/package.json
Labels: development

#1979 Add watermark back to printed ebook
  src/templates/base/base_ebook.html
  src/tools/generate/generate_ebook_pdfs.js
Labels: development

#1981 Translation of 2020 http2 chapter to Japanese
  src/content/ja/2020/http2.md
Labels: translation

#1983 Change height of AMP stories
  src/static/images/ha-60px.png
  src/static/images/ha-amp-logo.png
  src/static/images/ha-square.png
  src/templates/base/base.html
  src/templates/en/2020/stories/content_distribution.html
  src/templates/en/2020/stories/content_publishing.html
  src/templates/en/2020/stories/page_content.html
  src/templates/en/2020/stories/user_experience.html
Labels: development

#1985 Add landscape pictures for AMP Stories
  src/static/stories/web-almanac-2020-content-distribution/WA_Cover-Image_Part-IV-853x640.jpg
  src/static/stories/web-almanac-2020-content-publishing/WA_Cover-Image_Part-II-853x640.jpg
  src/static/stories/web-almanac-2020-content-publishing/WA_Cover-Image_Part-III-853x640.jpg
  src/static/stories/web-almanac-2020-page-content/WA_Cover-Image_Part-I-853x640.jpg
  src/static/stories/web-almanac-2020-user-experience/WA_Cover-Image_Part-II-853x640.jpg
  src/templates/en/2020/stories/content_distribution.html
  src/templates/en/2020/stories/content_publishing.html
  src/templates/en/2020/stories/page_content.html
  src/templates/en/2020/stories/user_experience.html
Labels: development

#1987 Correct tag version number for versions greater than 10
  src/tools/scripts/deploy.sh
Labels: bug, development

#1988 Fixed as identified by webhint.io
  src/app.yaml
  src/static/images/apple-touch-icon.png
  src/templates/base/accessibility_statement.html
  src/templates/base/base.html
  src/templates/base/base_chapter.html
  src/templates/base/contributors.html
  src/templates/base/methodology.html
Labels: development

#1991 Stop exporting whole chapter object in ebook template
  src/templates/base/ebook.ejs.html
Labels: development

#1993 Better apostrophes
  src/content/en/2020/capabilities.md
  src/content/ja/2020/capabilities.md
  src/content/nl/2020/capabilities.md
  src/content/ru/2020/capabilities.md
  src/templates/en/2020/methodology.html
  src/templates/en/2020/stories/content_distribution.html
  src/templates/en/2020/stories/page_content.html
  src/templates/en/accessibility_statement.html
  src/templates/en/base_ebook.html
  src/templates/nl/2019/methodology.html
  src/templates/nl/2020/methodology.html
  src/templates/nl/base.html
  src/templates/nl/base_ebook.html
Labels: editing

#1995 Translation of 2020 css chapter to Japanese
  src/content/en/2020/css.md
  src/content/ja/2020/css.md
Labels: translation

#1996 Italian SEO chapter translation
  src/content/en/2020/seo.md
  src/content/it/2020/seo.md
Labels: translation

#1997 More web stories image fixes
  src/static/images/home-hero-2020-part-1-1200x1200.png
  src/static/images/home-hero-2020-part-1-1200x900.png
  src/static/images/home-hero-2020-part-2-1200x1200.png
  src/static/images/home-hero-2020-part-2-1200x900.png
  src/static/images/home-hero-2020-part-3-1200x1200.png
  src/static/images/home-hero-2020-part-3-1200x900.png
  src/static/images/home-hero-2020-part-4-1200x1200.png
  src/static/images/home-hero-2020-part-4-1200x900.png
  src/templates/en/2020/stories/content_distribution.html
  src/templates/en/2020/stories/content_publishing.html
  src/templates/en/2020/stories/page_content.html
  src/templates/en/2020/stories/user_experience.html
Labels: development

#1998 Remove extra newlines
  src/content/en/2019/caching.md
  src/content/en/2019/cdn.md
  src/content/en/2019/compression.md
  src/content/en/2019/security.md
  src/content/en/2020/caching.md
  src/content/en/2020/compression.md
  src/content/en/2020/css.md
  src/content/en/2020/javascript.md
  src/content/en/2020/media.md
  src/content/en/2020/pwa.md
  src/content/en/2020/seo.md
  src/content/fr/2019/caching.md
  src/content/fr/2019/compression.md
  src/content/fr/2019/media.md
  src/content/it/2020/javascript.md
  src/content/it/2020/seo.md
  src/content/ja/2019/caching.md
  src/content/ja/2019/cdn.md
  src/content/ja/2019/compression.md
  src/content/ja/2019/http2.md
  src/content/ja/2019/security.md
  src/content/ja/2020/css.md
  src/content/ja/2020/javascript.md
  src/content/nl/2020/javascript.md
  src/content/nl/2020/markup.md
Labels: editing

#2004 Fix typo raised in #2003
  src/content/en/2020/css.md
Labels: editing

#2001 Translation of 2020 third-parties chapter to Japanese
  src/content/ja/2020/third-parties.md
Labels: translation

#2005 Ebook spine logo padding
  src/static/css/ebook.css
Labels: development

#2008 Translation of 2020 Page Weight chapter to Japanese
  src/content/ja/2020/page-weight.md
Labels: translation

#2007 Translate the 2020 Security chapter to Dutch
  src/content/en/2020/security.md
  src/content/nl/2020/security.md
Labels: translation

#2011 Improve deploy script
  src/tools/scripts/deploy.sh
Labels: development

#2012 Small Dutch language change: "Conclusie" to "Gevolgtrekking"
  src/content/nl/2019/accessibility.md
  src/content/nl/2020/accessibility.md
  src/content/nl/2020/capabilities.md
  src/content/nl/2020/cms.md
  src/content/nl/2020/fonts.md
  src/content/nl/2020/javascript.md
  src/content/nl/2020/markup.md
  src/content/nl/2020/performance.md
  src/content/nl/2020/security.md
Labels: translation

#2013 Handle large zooms better
  src/static/css/almanac.css
  src/static/css/index.css
  src/static/css/page.css
Labels: accessibility, design, development

#2014 Translate the 2020 Jamstack chapter to Dutch
  src/content/nl/2020/jamstack.md
Labels: translation

#2016 Amp fix
  src/config/last_updated.json
  src/templates/en/2020/stories/content_publishing.html
Labels: bug, development

#2017 Translate the 2020 Page weight chapter to Dutch
  src/content/nl/2020/page-weight.md
Labels: translation

#2019 Fix missing chapter numbers from ToC menu
  src/templates/base/base.html
  src/templates/base/base_ebook.html
Labels: bug, development

#2022 Zoom overflow issues part 2
  src/static/css/almanac.css
  src/static/css/index.css
  src/static/css/page.css
  src/templates/base/base.html
Labels: accessibility, development

#2023 Add option to not generate ebooks in predeploy script
  .github/workflows/predeploy.yml
Labels: development

#2028 Fix typo in Predeploy action
  .github/workflows/predeploy.yml
Labels: bug, development

#2031 Performance improvements to address layout shifts
  src/config/last_updated.json
  src/static/css/almanac.css
  src/static/css/print.css
  src/static/js/almanac.js
  src/static/js/send-web-vitals.js
  src/static/js/web-vitals.js
  src/templates/base.html
  src/templates/base/accessibility_statement.html
  src/templates/base/base.html
  src/templates/base/base_chapter.html
  src/templates/base/contributors.html
  src/templates/base/index.html
  src/templates/base/methodology.html
  src/tools/generate/generate_js.js
Labels: development, performance

#2034 Remove prefers-reduced-data for font loading
  src/static/css/almanac.css
  src/templates/base.html
Labels: bug, development

#2036 Preload the font needed for the index page
  src/templates/base/index.html
Labels: development, performance

#2037 More AMP fixes
  src/templates/en/2020/stories/page_content.html
  src/templates/en/2020/stories/user_experience.html
Labels: bug

#2039 Fix home pages issues with large zooms
  src/config/last_updated.json
  src/static/css/index.css
Labels: accessibility, design, development

#2040 More extreme zoom fixes
  src/static/css/almanac.css
  src/static/css/index.css
  src/static/css/page.css
Labels: accessibility, development

#2042 Translate the 2020 Compression chapter to Dutch
  src/content/nl/2020/compression.md
Labels: translation

#2043 Translation of security chapter to Japanese
  src/content/ja/2020/security.md
Labels: translation

#2044 Upgrade super-linter
  .github/workflows/linter.yml
  .github/workflows/test_website.yml
Labels: development
