Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-05, with the labels that each got.

#2181 Translation of the 2020 Caching chapter to Dutch
  src/content/en/2020/caching.md
  src/content/en/2020/third-parties.md
  src/content/nl/2020/caching.md
  src/content/nl/2020/fonts.md
  src/content/nl/2020/pwa.md
  src/content/nl/2020/third-parties.md
Labels: translation

#2176 2020 fonts japanese translation
  src/content/ja/2020/fonts.md
Labels: translation

#2180 Update chapter tracker to 2021
  .github/workflows/progress-tracker.yml
Labels: development, project management

#2184 2020 mobile web japanese translation
  src/content/ja/2020/mobile-web.md
Labels: translation

#2114 2019 Fonts chapter translation to French
  src/config/2019.json
  src/content/fr/2019/fonts.md
  src/templates/base/base_chapter.html
Labels: translation

#2191 Add Google Scholar meta data
  src/templates/base/base_chapter.html
  src/templates/en/base_chapter.html
  src/templates/es/base_chapter.html
  src/templates/fr/base_chapter.html
  src/templates/hi/base_chapter.html
  src/templates/it/base_chapter.html
  src/templates/ja/base_chapter.html
  src/templates/nl/base_chapter.html
  src/templates/pt/base_chapter.html
  src/templates/ru/base_chapter.html
  src/templates/tr/base_chapter.html
  src/templates/uk/base_chapter.html
  src/templates/zh-CN/base_chapter.html
  src/templates/zh-TW/base_chapter.html
Labels: development

#2203 2020 caching japanese translation
  src/content/ja/2020/caching.md
Labels: translation

#2212 Css missing newline
  src/content/en/2020/css.md
  src/content/it/2020/css.md
  src/content/ja/2020/css.md
  src/content/pt/2020/css.md
Labels: editing

#2213 2020 resource hints japanese translation
  src/content/ja/2020/resource-hints.md
Labels: translation

#2215 Fixes #2209
  src/config/2021.json
  src/templates/base/base_chapter.html
Labels: bug, design, development
