Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-09, with the labels that each got.

#2333 Exclude Jinja templates from CodeQL scanning
  .github/codeql/codeql-config.yml
  .github/workflows/code-static-analysis.yml
  src/server/validate.py
Labels: bug, development

#2335 Turn off uses-passive-event-listeners Lighthouse audit
  .github/lighthouse/lighthouse-config-dev.json
  .github/lighthouse/lighthouse-config-prod.json
Labels: bug

#2272 PWA 2021 queries
  sql/2021/pwa/assetlink_usage.sql
  sql/2021/pwa/install_events.sql
  sql/2021/pwa/lighthouse_pwa_audits.sql
  sql/2021/pwa/lighthouse_pwa_score.sql
  sql/2021/pwa/manifests_and_service_workers.sql
  sql/2021/pwa/manifests_not_json_parsable.sql
  sql/2021/pwa/manifests_preferring_native_apps.sql
  sql/2021/pwa/popular_pwa_libraries.sql
  sql/2021/pwa/popular_pwa_libraries_helper.sql
  sql/2021/pwa/pwa_blink_usage.sql
  sql/2021/pwa/pwa_notification_acceptance_rates.sql
  sql/2021/pwa/sw-registration-properties.sql
  sql/2021/pwa/sw_adoption_over_time.sql
  sql/2021/pwa/sw_adoption_over_time_ranking.sql
  sql/2021/pwa/sw_events.sql
  sql/2021/pwa/sw_methods.sql
  sql/2021/pwa/sw_objects.sql
  sql/2021/pwa/top_manifest_categories.sql
  sql/2021/pwa/top_manifest_display_values.sql
  sql/2021/pwa/top_manifest_icon_sizes.sql
  sql/2021/pwa/top_manifest_orientations.sql
  sql/2021/pwa/top_manifest_properties.sql
  sql/2021/pwa/workbox_methods.sql
  sql/2021/pwa/workbox_packages.sql
  sql/2021/pwa/workbox_usage.sql
  sql/2021/pwa/workbox_versions.sql
Labels: analysis

#2340 Add more 2 more PWA queries
  sql/2021/pwa/README.md
  sql/2021/pwa/sw_objects_name_only.sql
  sql/2021/pwa/sw_registration_properties.sql
  sql/2021/pwa/sw_registration_properties_name_only.sql
Labels: analysis

#2254 Caching 2021 queries
  sql/2021/caching/README.md
  sql/2021/caching/cache_control_directives.sql
  sql/2021/caching/cache_control_directives_invalid.sql
  sql/2021/caching/cache_ttl_and_content_age_diff.sql
  sql/2021/caching/cache_ttl_lighthouse_score.sql
  sql/2021/caching/cache_wastedbytes_lighthouse.sql
  sql/2021/caching/content_age_older_than_ttl.sql
  sql/2021/caching/content_age_older_than_ttl_by_party.sql
  sql/2021/caching/cookie_attributes.sql
  sql/2021/caching/cookie_names.sql
  sql/2021/caching/header_trends.sql
  sql/2021/caching/invalid_last_modified_and_expires_and_date.sql
  sql/2021/caching/max_age_distribution.sql
  sql/2021/caching/non_cacheable_by_resource_type.sql
  sql/2021/caching/resource_age_party_and_type_wise.sql
  sql/2021/caching/resource_age_party_and_type_wise_groups.sql
  sql/2021/caching/service_worker_rank.sql
  sql/2021/caching/set_cookie.sql
  sql/2021/caching/top_cdns.sql
  sql/2021/caching/top_hosts_using_immutable.sql
  sql/2021/caching/ttl.sql
  sql/2021/caching/ttl_by_resource.sql
  sql/2021/caching/valid_if_modified_since_returns_304.sql
  sql/2021/caching/valid_if_none_match_returns_304.sql
  sql/2021/caching/vary_directives.sql
Labels: analysis
