Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2021-12, with the labels that each got.

#2635 Add missing SQL reference to Structured Data chapter
  src/content/en/2021/structured-data.md
Labels: editing

#2604 HTTP chapter 2021
  sql/2021/http/detailed_alt_svc_headers_pages.sql
  src/config/2021.json
  src/content/en/2021/http.md
  src/static/images/2021/http/favicons-that-404.png
  src/static/images/2021/http/http-response-header-sizes.png
  src/static/images/2021/http/http-version-requests.png
  src/static/images/2021/http/http-versions-main-page.png
  src/static/images/2021/http/http2-and-above-resources-by-percentile.png
  src/static/images/2021/http/http2-and-above-third-party-resources-by-percentile.png
  src/static/images/2021/http/http2-or-above-usage-by-ranking.png
  src/static/images/2021/http/http3-support-by-ranking.png
  src/static/images/2021/http/median-http-requests-per-site.png
  src/static/images/2021/http/most-popular-http-response-headers.png
  src/static/images/2021/http/most-used-http-response-status-codes.png
  src/static/images/2021/http/number-of-http-requests-by-percentile.png
  src/static/images/2021/http/preload-link-nopush-header-usage.png
  src/static/images/2021/http/server-http2-or-above-usage.png
  src/static/images/2021/http/server-software-not-using-http2-or-above.png
  src/static/images/2021/http/tcp-connections-by-home-page-http-version.png
  src/static/images/2021/http/tcp-connections-per-http-version-by-percentile.png
  src/static/images/2021/http/tls-version-by-http-version.png
  src/static/images/2021/http/top-cdns-and-http2-or-above-usage.png
  src/static/images/2021/http/upgrade-headers-sent-over-http2.png
  src/static/images/2021/http/webpagetest-alt-svc-example.png
  src/static/images/2021/http/webpagetest-h2-h3-example.jpeg
  src/static/images/2021/http/webpagetest-waterfall-example.png
Labels: ASAP, writing

#2614 Edits for JavaScript 2021 chapter
  sql/2021/javascript/web_components_pct.sql
  src/config/2021.json
  src/content/en/2021/javascript.md
  src/static/images/2021/compression/compression-levels-gzip.png
  src/static/images/2021/compression/content-encoding.png
  src/static/images/2021/javascript/ajax-apis-per-year.png
  src/static/images/2021/javascript/ajax_beacon.png
  src/static/images/2021/javascript/ajax_fetch.png
  src/static/images/2021/javascript/ajax_xhr.png
  src/static/images/2021/javascript/async-requests-per-page.png
  src/static/images/2021/javascript/average-unminified-js-bytes.png
  src/static/images/2021/javascript/compression-first-third-party.png
  src/static/images/2021/javascript/compression-requests.png
  src/static/images/2021/javascript/javascript-bytes-per-page.png
  src/static/images/2021/javascript/javascript-resource-hint-usage.png
  src/static/images/2021/javascript/js-libs-frameworks.png
  src/static/images/2021/javascript/js-requests-desktop-host.png
  src/static/images/2021/javascript/js-requests-mobile-host.png
  src/static/images/2021/javascript/js-requests-per-page.png
  src/static/images/2021/javascript/js-resources-over-years.png
  src/static/images/2021/javascript/prefetch-hints-per-page.png
  src/static/images/2021/javascript/preload-hints-per-page.png
  src/static/images/2021/javascript/sourcemap-first-third-party.png
  src/static/images/2021/javascript/uncompressed-first-third-party.png
  src/static/images/2021/javascript/unminified-js-audit-scores.png
  src/static/images/2021/javascript/unminified-js-bytes.png
  src/static/images/2021/javascript/unused-javascript-bytes-per-page.png
  src/static/images/2021/javascript/unused-vs-total-javascript.png
  src/static/images/2021/javascript/usage-sync-async-over-years.png
  src/static/images/2021/javascript/usage-sync-async.png
Labels: editing

#2634 Edits for Jamstack 2021 Chapter
  src/content/en/2021/jamstack.md
  src/static/images/2021/jamstack/3rd-party-libs-distribution-over-ssgs.png
  src/static/images/2021/jamstack/CLS-distribution-CDN.png
  src/static/images/2021/jamstack/CLS-distribution-SSG.png
  src/static/images/2021/jamstack/FID-distribution-SSG.png
  src/static/images/2021/jamstack/LCP-distribution-CDN.png
  src/static/images/2021/jamstack/median-lighthouse-best-practices-score.png
Labels: editing

#2637 Edits for HTTP 2021 Chapter
  src/content/en/2021/http.md
Labels: editing

#2638 Tinypng JavaScript images
  src/static/images/2021/javascript/ajax-apis-per-year.png
  src/static/images/2021/javascript/ajax_beacon.png
  src/static/images/2021/javascript/ajax_fetch.png
  src/static/images/2021/javascript/ajax_xhr.png
  src/static/images/2021/javascript/async-requests-per-page.png
  src/static/images/2021/javascript/average-unminified-js-bytes.png
  src/static/images/2021/javascript/compression-first-third-party.png
  src/static/images/2021/javascript/compression-requests.png
  src/static/images/2021/javascript/javascript-bytes-per-page.png
  src/static/images/2021/javascript/javascript-resource-hint-usage.png
  src/static/images/2021/javascript/js-libs-frameworks.png
  src/static/images/2021/javascript/js-requests-desktop-host.png
  src/static/images/2021/javascript/js-requests-mobile-host.png
  src/static/images/2021/javascript/js-requests-per-page.png
  src/static/images/2021/javascript/js-resources-over-years.png
  src/static/images/2021/javascript/prefetch-hints-per-page.png
  src/static/images/2021/javascript/preload-hints-per-page.png
  src/static/images/2021/javascript/uncompressed-first-third-party.png
  src/static/images/2021/javascript/unminified-js-audit-scores.png
  src/static/images/2021/javascript/unminified-js-bytes.png
  src/static/images/2021/javascript/unused-javascript-bytes-per-page.png
  src/static/images/2021/javascript/unused-vs-total-javascript.png
  src/static/images/2021/javascript/usage-sync-async-over-years.png
  src/static/images/2021/javascript/usage-sync-async.png
Labels: performance

#2639 Fix column scoping on CSS chapter
  src/content/en/2021/css.md
Labels: accessibility

#2620 Markup 2021 chapter
  src/config/2021.json
  src/content/en/2021/markup.md
  src/static/images/2021/markup/attribute-popularity.png
  src/static/images/2021/markup/buttons.png
  src/static/images/2021/markup/content-encoding.png
  src/static/images/2021/markup/data-attributes.png
  src/static/images/2021/markup/element-count.png
  src/static/images/2021/markup/element-diversity.png
  src/static/images/2021/markup/element-popularity.png
  src/static/images/2021/markup/favicons.png
  src/static/images/2021/markup/lang-region.png
  src/static/images/2021/markup/lang.png
  src/static/images/2021/markup/meta-monetization.png
  src/static/images/2021/markup/meta-names.png
  src/static/images/2021/markup/monetization-by-host.png
  src/static/images/2021/markup/obsolete-elements.png
  src/static/images/2021/markup/page-size-by-year.png
  src/static/images/2021/markup/relative-obsolete-elements.png
  src/static/images/2021/markup/social-meta-names.png
Labels: ASAP, writing

#2646 Markup further edits
  src/content/en/2021/markup.md
  src/static/images/2021/markup/attribute-popularity.png
  src/static/images/2021/markup/buttons.png
  src/static/images/2021/markup/content-encoding.png
  src/static/images/2021/markup/data-attributes.png
  src/static/images/2021/markup/element-count.png
  src/static/images/2021/markup/element-diversity.png
  src/static/images/2021/markup/element-popularity.png
  src/static/images/2021/markup/favicons.png
  src/static/images/2021/markup/lang-region.png
  src/static/images/2021/markup/lang.png
  src/static/images/2021/markup/meta-names.png
  src/static/images/2021/markup/monetization-by-host.png
  src/static/images/2021/markup/obsolete-elements.png
  src/static/images/2021/markup/page-size-by-year.png
  src/static/images/2021/markup/relative-obsolete-elements.png
  src/static/images/2021/markup/social-meta-names.png
Labels: bug, editing

#2534 SEO 2021 markup
  sql/2021/seo/robots-txt-user-agent-usage-by-rank.sql
  src/config/2021.json
  src/content/en/2021/seo.md
  src/static/images/2021/seo/amp-markup-types.png
  src/static/images/2021/seo/canonical-raw-rendered-usage.png
  src/static/images/2021/seo/canonical-tag-usage.png
  src/static/images/2021/seo/core-web-vitals-trend.png
  src/static/images/2021/seo/heading-element-usage.png
  src/static/images/2021/seo/hreflang-usage.png
  src/static/images/2021/seo/image-links.png
  src/static/images/2021/seo/image-loading-property-usage.png
  src/static/images/2021/seo/images-with-alt-attribute.png
  src/static/images/2021/seo/images-with-blank-alt-attribute.png
  src/static/images/2021/seo/images-with-missing-alt-attribute.png
  src/static/images/2021/seo/language-usage-html-http.png
  src/static/images/2021/seo/meta-character-counts.png
  src/static/images/2021/seo/meta-word-counts.png
  src/static/images/2021/seo/most-popular-schema-types.png
  src/static/images/2021/seo/non-empty-heading-element-usage.png
  src/static/images/2021/seo/number-of-images-per-page.png
  src/static/images/2021/seo/outgoing-external-links.png
  src/static/images/2021/seo/outgoing-internal-link.png
  src/static/images/2021/seo/rel-attibute-usage.png
  src/static/images/2021/seo/robots-txt-size-distribution.png
  src/static/images/2021/seo/robots-txt-status-codes.png
  src/static/images/2021/seo/robots-txt-user-agent.png
  src/static/images/2021/seo/robots-usage-presentation.png
  src/static/images/2021/seo/seo-term-trends.png
  src/static/images/2021/seo/structured-data-formats.png
  src/static/images/2021/seo/structured-data-usage.png
  src/static/images/2021/seo/text-links.png
  src/static/images/2021/seo/title-character-counts.png
  src/static/images/2021/seo/title-meta-description-usage.png
  src/static/images/2021/seo/title-word-counts.png
  src/static/images/2021/seo/usage-of-https.png
  src/static/images/2021/seo/vary-usage-agent-header-usage.png
  src/static/images/2021/seo/visible-raw-words-percentile.png
  src/static/images/2021/seo/visible-rendered-words-percentile.png
Labels: ASAP, writing

#2647 Generate missing HTTP images
  src/content/en/2021/http.md
  src/static/images/2021/http/http2-push-counts.png
  src/static/images/2021/http/http2-push-number.png
  src/static/images/2021/http/http2-push-size.png
Labels: bug

#2649 Fix Suggest Edit link
  src/templates/base/base_chapter.html
Labels: bug

#2648 Simplify GitHub avatars
  src/config/2019.json
  src/config/2020.json
  src/config/2021.json
  src/templates/base/base_chapter.html
  src/templates/base/base_ebook.html
  src/templates/base/contributors.html
  src/templates/base/ebook.ejs.html
Labels: development, performance

#2643 Markup 2021 edits
  src/content/en/2021/markup.md
Labels: editing

#2641 Foreword
  src/templates/en/2021/base.html
  src/templates/es/2021/base.html
  src/templates/fr/2021/base.html
  src/templates/hi/2021/base.html
  src/templates/it/2021/base.html
  src/templates/ja/2021/base.html
  src/templates/nl/2021/base.html
  src/templates/pt/2021/base.html
  src/templates/ru/2021/base.html
  src/templates/tr/2021/base.html
  src/templates/uk/2021/base.html
  src/templates/zh-CN/2021/base.html
  src/templates/zh-TW/2021/base.html
Labels: writing, project management

#2652 Remove Emojis from Capabilities chapters
  src/content/en/2021/capabilities.md
Labels: editing

#2654 Fix Todos for Markup
  src/content/en/2021/markup.md
Labels: ASAP, editing

#2655 Update dates for accessibility
  src/templates/en/accessibility_statement.html
  src/templates/es/accessibility_statement.html
  src/templates/fr/accessibility_statement.html
  src/templates/hi/accessibility_statement.html
  src/templates/ja/accessibility_statement.html
  src/templates/nl/accessibility_statement.html
  src/templates/zh-CN/accessibility_statement.html
Labels: editing

#2658 Fix bad image link in Japanese Caching chapter
  src/content/ja/2020/caching.md
Labels: translation

#2662 ES #498: 2020 Ecommerce Spanish Translation
  src/content/en/2020/ecommerce.md
  src/content/es/2020/ecommerce.md
Labels: translation

#2667 Fix Web Mentions reply bug on mobile
  src/static/css/page.css
Labels: bug, development

#2670 Stop CDN chapter failing CI
  src/tools/scripts/set_lighthouse_urls.sh
Labels: bug, development

#2672 Remove unedited flag from HTTP as it was edited
  src/content/en/2021/http.md
Labels: editing

#2677 Focus search input on button click
  src/static/js/almanac.js
  src/templates/base/base.html
Labels: development, design

#2676 Various 404 improvements
  src/app.yaml
  src/content/en/2021/compression.md
  src/content/en/2021/page-weight.md
  src/server/routes.py
  src/server/tests/routes_test.py
  src/templates/base.html
Labels: development, editing

#2682 Fix loading stats on SEO chapter
  src/content/en/2021/seo.md
Labels: editing

#2683 Fix tabindex percentage issue in a11y chapter
  src/content/en/2021/accessibility.md
Labels: editing

#2684 Fix Markup social graph and other minor edits
  sql/2021/markup/meta_nodes_name.sql
  sql/2021/markup/social_markup.sql
  src/content/en/2021/markup.md
  src/static/images/2021/markup/meta-names.png
  src/static/images/2021/markup/social-meta-names.png
Labels: editing

#2679 Fix typo in meyerweb's bio
  src/content/en/2021/css.md
Labels: editing

#2688 Source Have I Been Pwned more
  src/content/en/2021/privacy.md
  src/content/en/2021/third-parties.md
  src/content/nl/2021/privacy.md
  src/static/images/2021/privacy/data_breaches_pwned_accounts_per_class.png
Labels: editing

#2692 2021 css japanese translation
  src/config/2019.json
  src/config/2020.json
  src/config/2021.json
  src/content/en/2021/css.md
  src/content/ja/2019/caching.md
  src/content/ja/2019/cdn.md
  src/content/ja/2019/cms.md
  src/content/ja/2019/compression.md
  src/content/ja/2019/css.md
  src/content/ja/2019/ecommerce.md
  src/content/ja/2019/fonts.md
  src/content/ja/2019/http.md
  src/content/ja/2019/javascript.md
  src/content/ja/2019/media.md
  src/content/ja/2019/mobile-web.md
  src/content/ja/2019/page-weight.md
  src/content/ja/2019/pwa.md
  src/content/ja/2019/resource-hints.md
  src/content/ja/2019/security.md
  src/content/ja/2019/third-parties.md
  src/content/ja/2020/accessibility.md
  src/content/ja/2020/caching.md
  src/content/ja/2020/capabilities.md
  src/content/ja/2020/cms.md
  src/content/ja/2020/compression.md
  src/content/ja/2020/css.md
  src/content/ja/2020/ecommerce.md
  src/content/ja/2020/fonts.md
  src/content/ja/2020/http.md
  src/content/ja/2020/jamstack.md
  src/content/ja/2020/javascript.md
  src/content/ja/2020/markup.md
  src/content/ja/2020/media.md
  src/content/ja/2020/mobile-web.md
  src/content/ja/2020/page-weight.md
  src/content/ja/2020/performance.md
  src/content/ja/2020/privacy.md
  src/content/ja/2020/pwa.md
  src/content/ja/2020/resource-hints.md
  src/content/ja/2020/security.md
  src/content/ja/2020/seo.md
  src/content/ja/2020/third-parties.md
  src/content/ja/2021/css.md
Labels: translation

#2693 Update Jamstack adoption numbers
  src/content/en/2021/jamstack.md
  src/static/images/2021/jamstack/image-adoption.png
Labels: editing

#2695 Temporarily remove CDN from production checks
  src/tools/scripts/set_lighthouse_urls.sh
Labels: bug, project management

#2694 Spellcheck 2021
  src/config/spelling_ignore_words.txt
  src/content/en/2021/accessibility.md
  src/content/en/2021/cms.md
  src/content/en/2021/css.md
  src/content/en/2021/ecommerce.md
  src/content/en/2021/http.md
  src/content/en/2021/jamstack.md
  src/content/en/2021/markup.md
  src/content/en/2021/mobile-web.md
  src/content/en/2021/page-weight.md
  src/content/en/2021/seo.md
  src/content/en/2021/webassembly.md
Labels: editing

#2697 Fix ja caching image
  src/content/ja/2020/caching.md
Labels: editing

#2704 Images per page queries
  sql/2021/media/at_least_one_image_request.sql
  sql/2021/media/at_least_one_img.sql
  sql/2021/media/imgs_per_page.sql
Labels: analysis

#2707 Add RSS Feed functionality
  src/.gitignore
  src/content/en/2019/cdn.md
  src/server/routes.py
  src/server/tests/routes_test.py
  src/static/css/almanac.css
  src/templates/base.html
  src/templates/base/base.html
  src/templates/base/rss.ejs.xml
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/tr/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
  src/tools/generate/generate_chapters.js
  src/tools/generate/generate_rss.js
  src/tools/test/test_status_codes.js
Labels: development

#2709 Compress some more images to make ebook fit
  src/content/en/2021/capabilities.md
  src/static/images/2021/capabilities/fugu-podium.jpg
  src/static/images/2021/capabilities/generic-sensor-api.jpg
  src/static/images/2021/capabilities/generic-sensor-api.png
  src/static/images/2021/capabilities/web-bluetooth.jpg
  src/static/images/2021/capabilities/web-serial.jpg
  src/static/images/2021/capabilities/web-serial.png
  src/static/images/2021/capabilities/web-share-api.jpg
  src/static/images/2021/capabilities/web-share-api.png
  src/static/images/2021/capabilities/web-usb.jpg
  src/static/images/2021/http/webpagetest-alt-svc-example.png
  src/static/images/2021/http/webpagetest-h2-h3-example.jpeg
Labels: performance

#2705 2021 Media markdown
  sql/2021/media/video_attribute_count.sql
  sql/2021/media/video_attribute_count_desktop.sql
  sql/2021/media/video_durations.sql
  sql/2021/media/video_durations_desktop.sql
  sql/2021/media/video_number_of_sources.sql
  sql/2021/media/video_number_of_sources_desktop.sql
  sql/2021/media/video_preload.sql
  sql/2021/media/video_preload_values.sql
  sql/2021/media/video_source_formats.sql
  sql/2021/media/video_source_formats_mobile.sql
  sql/2021/media/video_styles.sql
  sql/2021/media/video_styles_desktop.sql
  src/config/2021.json
  src/content/en/2021/media.md
  src/static/images/2021/media/adoption-of-native-loading-lazy-on-img.png
  src/static/images/2021/media/distribution-of-image-bits-per-pixel.png
  src/static/images/2021/media/distribution-of-image-byte-sizes.png
  src/static/images/2021/media/distribution-of-image-srcset-candidate-densities.png
  src/static/images/2021/media/distribution-of-img-sizes-errors.png
  src/static/images/2021/media/image-format-adoption-mobile.png
  src/static/images/2021/media/image-orientations.png
  src/static/images/2021/media/image-origins.png
  src/static/images/2021/media/image-pixel-counts.png
  src/static/images/2021/media/intrinsic-and-extrinsic-image-sizing.png
  src/static/images/2021/media/median-bits-per-pixel-by-format.png
  src/static/images/2021/media/mobile-image-transfer-size-by-year.png
  src/static/images/2021/media/number-of-imgs-per-page.png
  src/static/images/2021/media/number-of-srcset-candidates.png
  src/static/images/2021/media/picture-feature-usage.png
  src/static/images/2021/media/sites-with-at-least-one-video-element.png
  src/static/images/2021/media/source-element-count.png
  src/static/images/2021/media/srcset-descriptor-adoption.png
  src/static/images/2021/media/top-extensions-of-files-with-a-video-mime-type.png
  src/static/images/2021/media/video-css-display-percentages.png
  src/static/images/2021/media/video-durations.png
  src/static/images/2021/media/video-element-attributes.png
  src/static/images/2021/media/video-preload-values.png
  src/static/images/2021/media/video-widths.png
Labels: ASAP, writing

#2716 Set RSS last updated date to last updated date
  src/templates/base/rss.ejs.xml
  src/tools/generate/generate_rss.js
Labels: development

#2724 Use standard Almanac colours on JavaScript graphs
  src/content/en/2021/javascript.md
  src/static/images/2021/javascript/ajax-apis-per-year.png
  src/static/images/2021/javascript/ajax_beacon.png
  src/static/images/2021/javascript/ajax_fetch.png
  src/static/images/2021/javascript/ajax_xhr.png
  src/static/images/2021/javascript/async-requests-per-page.png
  src/static/images/2021/javascript/compression-first-third-party.png
  src/static/images/2021/javascript/compression-requests.png
  src/static/images/2021/javascript/js-requests-desktop-host.png
  src/static/images/2021/javascript/js-requests-mobile-host.png
  src/static/images/2021/javascript/js-requests-per-page.png
  src/static/images/2021/javascript/js-resources-over-years.png
  src/static/images/2021/javascript/preload-hints-per-page.png
  src/static/images/2021/javascript/uncompressed-first-third-party.png
  src/static/images/2021/javascript/unused-javascript-bytes-per-page.png
  src/static/images/2021/javascript/unused-vs-total-javascript.png
  src/static/images/2021/javascript/usage-sync-async-over-years.png
  src/static/images/2021/javascript/usage-sync-async.png
Labels: editing

#2443 2021 Caching chapter
  src/config/2021.json
  src/content/en/2021/caching.md
  src/static/images/2021/caching/cache-control-directives.png
  src/static/images/2021/caching/cache-control-expires.png
  src/static/images/2021/caching/cacheable-responses.png
  src/static/images/2021/caching/cacheable-set-cookie.png
  src/static/images/2021/caching/caching-by-resource-type.png
  src/static/images/2021/caching/first-party-resource-age-by-content-type.png
  src/static/images/2021/caching/http-304-by-caching-strategy.png
  src/static/images/2021/caching/invalid-date-formats.png
  src/static/images/2021/caching/last-modified-etag.png
  src/static/images/2021/caching/lighthouse-caching-byte-savings.png
  src/static/images/2021/caching/lighthouse-caching-ttl-scores.png
  src/static/images/2021/caching/sw-adoption.png
  src/static/images/2021/caching/top-cdns.png
  src/static/images/2021/caching/vary-directives.png
Labels: ASAP, writing

#2717 Media 2021 Copy Edit
  sql/2021/media/srcset_density_coverage.sql
  src/content/en/2021/media.md
  src/static/images/2021/media/srcset-density-coverage.png
Labels: editing

#2728 Extra spellchecks
  src/config/spelling_ignore_words.txt
  src/content/en/2021/jamstack.md
  src/content/en/2021/media.md
Labels: editing

#2727 Copyedit 2021 Caching chapter
  src/content/en/2021/caching.md
  src/static/images/2021/caching/cacheable-responses.png
  src/static/images/2021/caching/lighthouse-caching-byte-savings.png
  src/static/images/2021/caching/sw-adoption.png
  src/static/images/2021/caching/third-party-resource-age-by-content-type.png
Labels: editing

#2733 Final 2021 spellcheck
  src/content/en/2020/accessibility.md
  src/content/en/2021/caching.md
Labels: editing

#2735 Correct update dates and Caching featured stats
  src/config/last_updated.json
  src/content/en/2021/caching.md
  src/templates/base/rss.ejs.xml
Labels: editing

#2741 2021 markup japanese translation
  src/content/en/2021/markup.md
  src/content/ja/2021/markup.md
Labels: translation

#2747 2021 structured data japanese translation
  src/content/ja/2021/structured-data.md
Labels: translation
