Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2022-06, with the labels that each got.

#2956 Translation of ecommerce chapter to Japanese
  src/content/ja/2021/ecommerce.md
Labels: translation

#2963 Update image formats in summary table
  sql/util/requests.sql
Labels: analysis

#2966 Add fetch priority to hero images
  src/templates/base/base_chapter.html
  src/templates/base/index.html
  src/templates/en/2019/methodology.html
  src/templates/en/2020/methodology.html
  src/templates/en/2021/methodology.html
  src/templates/fr/2019/methodology.html
  src/templates/fr/2020/methodology.html
  src/templates/hi/2019/methodology.html
  src/templates/hi/2020/methodology.html
  src/templates/ja/2019/methodology.html
  src/templates/ja/2020/methodology.html
  src/templates/nl/2019/methodology.html
  src/templates/nl/2020/methodology.html
  src/templates/ru/2019/methodology.html
  src/templates/ru/2020/methodology.html
  src/templates/zh-CN/2019/methodology.html
  src/templates/zh-CN/2020/methodology.html
  src/templates/zh-TW/2020/methodology.html
Labels: development, performance

#2968 2021 jamstack japanese translation
  src/content/en/2021/jamstack.md
  src/content/ja/2021/jamstack.md
Labels: translation

#2972 Fix figure numbering in Resource Hints chapter
  src/content/en/2021/resource-hints.md
  src/tools/generate/generate_figure_ids.js
Labels: bug, development

#2986 Bump Node version used in GitHub Actions from v15 to v16
  .github/workflows/predeploy.yml
  .github/workflows/test-template-changes.yml
  .github/workflows/test_website.yml
Labels: development

#2988 Add 2022 base templates
  src/config/2022.json
  src/templates/base/contributors.html
  src/templates/en/2022/base.html
  src/templates/en/2022/contributors.html
  src/templates/en/2022/index.html
  src/templates/en/2022/table_of_contents.html
  src/templates/es/2022/base.html
  src/templates/es/2022/contributors.html
  src/templates/es/2022/index.html
  src/templates/es/2022/table_of_contents.html
  src/templates/fr/2022/base.html
  src/templates/fr/2022/contributors.html
  src/templates/fr/2022/index.html
  src/templates/fr/2022/table_of_contents.html
  src/templates/hi/2022/base.html
  src/templates/hi/2022/contributors.html
  src/templates/hi/2022/index.html
  src/templates/hi/2022/table_of_contents.html
  src/templates/it/2021/base.html
  src/templates/it/2022/base.html
  src/templates/it/2022/contributors.html
  src/templates/it/2022/index.html
  src/templates/it/2022/table_of_contents.html
  src/templates/ja/2022/base.html
  src/templates/ja/2022/contributors.html
  src/templates/ja/2022/index.html
  src/templates/ja/2022/table_of_contents.html
  src/templates/nl/2022/base.html
  src/templates/nl/2022/contributors.html
  src/templates/nl/2022/index.html
  src/templates/nl/2022/table_of_contents.html
  src/templates/pt/2022/base.html
  src/templates/pt/2022/contributors.html
  src/templates/pt/2022/index.html
  src/templates/pt/2022/table_of_contents.html
  src/templates/ru/2022/base.html
  src/templates/ru/2022/contributors.html
  src/templates/ru/2022/index.html
  src/templates/ru/2022/table_of_contents.html
  src/templates/tr/2022/base.html
  src/templates/tr/2022/contributors.html
  src/templates/tr/2022/index.html
  src/templates/tr/2022/table_of_contents.html
  src/templates/uk/2022/base.html
  src/templates/uk/2022/contributors.html
  src/templates/uk/2022/index.html
  src/templates/uk/2022/table_of_contents.html
  src/templates/zh-CN/2022/base.html
  src/templates/zh-CN/2022/contributors.html
  src/templates/zh-CN/2022/index.html
  src/templates/zh-CN/2022/table_of_contents.html
  src/templates/zh-TW/2022/base.html
  src/templates/zh-TW/2022/contributors.html
  src/templates/zh-TW/2022/index.html
  src/templates/zh-TW/2022/table_of_contents.html
  src/tools/scripts/set_lighthouse_urls.sh
Labels: development

#2978 2021 page weight japanese translation
  src/content/en/2021/page-weight.md
  src/content/ja/2021/page-weight.md
Labels: translation

#2945 Markup 2022 queries
  sql/.sqlfluff
  sql/2022/markup/README.md
  sql/2022/markup/anchors_javascript_void.sql
  sql/2022/markup/anchors_schemes.sql
  sql/2022/markup/anchors_unspecial_scheme.sql
  sql/2022/markup/attributes.sql
  sql/2022/markup/buttons.sql
  sql/2022/markup/comments.sql
  sql/2022/markup/content_encoding.sql
  sql/2022/markup/custom_elements_js_bytes_distribution.sql
  sql/2022/markup/custom_elements_slot_distribution.sql
  sql/2022/markup/custom_elements_template_shadowroot.sql
  sql/2022/markup/data_attributes.sql
  sql/2022/markup/doctype.sql
  sql/2022/markup/document_trends.sql
  sql/2022/markup/element_count_distribution.sql
  sql/2022/markup/element_frequency.sql
  sql/2022/markup/element_popularity.sql
  sql/2022/markup/favicons.sql
  sql/2022/markup/forms.sql
  sql/2022/markup/inputs.sql
  sql/2022/markup/inputs_per_form.sql
  sql/2022/markup/lang.sql
  sql/2022/markup/link_targets.sql
  sql/2022/markup/meta_node_names.sql
  sql/2022/markup/meta_viewports.sql
  sql/2022/markup/obsolete_elements.sql
  sql/2022/markup/svg.sql
  sql/2022/markup/web_components_distribution.sql
  sql/2022/markup/web_components_top1k.sql
Labels: analysis
