Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2022-01, with the labels that each got.

#2757 Ukrainian Translation - 2020 Privacy Chapter
  src/content/uk/2020/privacy.md
Labels: translation

#2764 Translation of webassembly chapter to Japanese
  src/content/en/2021/webassembly.md
  src/content/ja/2021/webassembly.md
Labels: translation

#2763 Truncate long webmentions
  src/static/js/webmentions.js
Labels: development

#2767 Enhance web vitals script
  src/static/js/send-web-vitals.js
Labels: development

#2769 Some more Markup edits
  src/content/en/2021/markup.md
  src/content/ja/2021/markup.md
Labels: editing

#2771 Correct heading in JA 2021 Markup chapter
  src/content/ja/2021/markup.md
Labels: editing

#2772 Compress more images
  src/content/en/2021/compression.md
  src/static/images/2021/compression/compession-methods-by-content-type.png
  src/static/images/2021/compression/compression-algorithms-for-http-responses.png
  src/static/images/2021/compression/compression-format-trend-desktop.png
  src/static/images/2021/compression/compression-format-trend-mobile.png
  src/static/images/2021/compression/compression-levels-brotli.png
  src/static/images/2021/compression/compression-levels-gzip.png
  src/static/images/2021/compression/content-encoding.jpg
  src/static/images/2021/compression/content-encoding.png
  src/static/images/2021/compression/text-compression-lighthouse-scores.png
Labels: performance

#2779 Translation of third-parties chapter to Japanese
  src/content/en/2021/third-parties.md
  src/content/ja/2021/third-parties.md
Labels: translation

#2793 Translation of seo chapter to Japanese
  src/content/en/2021/seo.md
  src/content/ja/2021/seo.md
Labels: translation
