Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2022-09, with the labels that each got.

#3102 Updated FID and INP queries to not exclude 0ms
  sql/2022/javascript/fid.sql
  sql/2022/javascript/inp.sql
Labels: analysis

#3107 Update 2022 Performance query
  sql/2022/performance/ttfb_by_cms.sql
Labels: analysis

#3112 Markup 2022 additional query
  sql/2022/markup/data_attribute_total.sql
Labels: analysis

#3113 Mobile Web 2022 additional query
  sql/2022/mobile-web/tap_target_failures_per_page.sql
Labels: analysis

#3108 HTTP 2022: add queries for getting more preload stats and HTTP/3 support
  sql/2022/http/dns_https_svcb_usage.sql
  sql/2022/http/h3_support.sql
  sql/2022/http/h3_support_each_cdn_breakdown.sql
  sql/2022/http/h3_support_from_cdn.sql
  sql/2022/http/sites_using_link_preload_header.sql
  sql/2022/http/sites_using_link_preload_tag.sql
Labels: analysis

#3116 Additional queries authored while writing
  sql/2022/media/animated_gif_bpp.sql
  sql/2022/media/animated_gif_count.sql
  sql/2022/media/animated_gif_framecount.sql
  sql/2022/media/color_spaces_and_depth.sql
  sql/2022/media/img_with_dimensions.sql
  sql/2022/media/largest_image_per_page_bytes.sql
  sql/2022/media/largest_image_per_page_layout.sql
  sql/2022/media/largest_image_per_page_pixels.sql
  sql/2022/media/portrait_landscape_square.sql
  sql/2022/media/video_adoption.sql
Labels: analysis

#3126 Mobile Web 2022 chapter
  src/config/2022.json
  src/content/en/2022/mobile-web.md
  src/static/images/2022/mobile-web/alt-protocols.png
  src/static/images/2022/mobile-web/appropriately-sized-images.png
  src/static/images/2022/mobile-web/good-cls.png
  src/static/images/2022/mobile-web/good-cwv.png
  src/static/images/2022/mobile-web/good-fid.png
  src/static/images/2022/mobile-web/good-lcp.png
  src/static/images/2022/mobile-web/good-ttfb.png
  src/static/images/2022/mobile-web/input-types.png
  src/static/images/2022/mobile-web/pct-mobile-traffic-rank.png
  src/static/images/2022/mobile-web/picture-srcset.png
  src/static/images/2022/mobile-web/tap-target-failures.png
  src/static/images/2022/mobile-web/zoom-scale-rank.png
Labels: writing, editing

#3133 Add new chapters to base.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/tr/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: development, project management

#3135 Third Parties sql 2022 canonical domain fix
  sql/2022/third-parties/distribution_of_websites_by_number_of_third_parties.sql
  sql/2022/third-parties/number_of_third_parties_by_rank_and_category.sql
Labels: analysis

#3132 2022 Sustainability Chapter
  src/config/2022.json
  src/content/en/2022/sustainability.md
  src/static/images/2022/sustainability/cache-control-header-usage.png
  src/static/images/2022/sustainability/cdn-usage.png
  src/static/images/2022/sustainability/compression-used-on-text-resources.png
  src/static/images/2022/sustainability/green-hosting-percentages.png
  src/static/images/2022/sustainability/green-third-party-requests.png
  src/static/images/2022/sustainability/image-formats-in-use.png
  src/static/images/2022/sustainability/kilobytes-number-by-percentile.png
  src/static/images/2022/sustainability/median-kilobytes-by-cms-and-resource-type-desktop.png
  src/static/images/2022/sustainability/median-kilobytes-by-cms-and-resource-type-mobile.png
  src/static/images/2022/sustainability/median-kilobytes-by-cms.png
  src/static/images/2022/sustainability/median-kilobytes-by-ecommerce.png
  src/static/images/2022/sustainability/native-lazy-loading-usage.png
  src/static/images/2022/sustainability/number-of-bytes-by-percentile-by-type-mobile.png
  src/static/images/2022/sustainability/number-of-requests-by-percentile-by-type-mobile.png
  src/static/images/2022/sustainability/number-of-requests-by-percentile.png
  src/static/images/2022/sustainability/percent-of-total-emissions-by-type-mobile.png
  src/static/images/2022/sustainability/responsive-image-types.png
  src/static/images/2022/sustainability/script-usage.png
  src/static/images/2022/sustainability/static-site-generator-median.png
  src/static/images/2022/sustainability/style-usage.png
  src/static/images/2022/sustainability/total-carbon-emissions-by-percentile.png
  src/static/images/2022/sustainability/unminified-css-savings.png
  src/static/images/2022/sustainability/unminified-javascript-savings.png
  src/static/images/2022/sustainability/unused-css-bytes.png
  src/static/images/2022/sustainability/unused-javascript-bytes.png
  src/static/images/2022/sustainability/video-autoplay-usage.png
  src/static/images/2022/sustainability/video-preload-usage.png
  src/static/images/2022/sustainability/visible-words-rendered.png
Labels: writing

#3136 Reset chapter launch dates
  src/config/last_updated.json
Labels: project management

#3129 2022 Third parties Chapter
  src/config/2022.json
  src/content/en/2022/third-parties.md
  src/static/images/2022/third-parties/async-and-defer-for-third-party-scripts.png
  src/static/images/2022/third-parties/average-potentially-saved-bytes-of-unminified-css.png
  src/static/images/2022/third-parties/average-potentially-saved-bytes-of-unminified-javascript.png
  src/static/images/2022/third-parties/content-encoding-by-content-type.png
  src/static/images/2022/third-parties/first-party-content-encoding-by-year.png
  src/static/images/2022/third-parties/main-thread-blocking-time-by-third-party.png
  src/static/images/2022/third-parties/median-number-of-third-parties-by-rank.png
  src/static/images/2022/third-parties/pages-with-third-parties-that-use-legacy-javascript.png
  src/static/images/2022/third-parties/potential-savings-of-unminified-javascript-by-third-party.png
  src/static/images/2022/third-parties/render-blocking-time-by-most-popular-third-parties.png
  src/static/images/2022/third-parties/size-of-unused-javascript.png
  src/static/images/2022/third-parties/third-parties-blocking-main-thread.png
  src/static/images/2022/third-parties/third-party-content-encoding-by-year.png
  src/static/images/2022/third-parties/third-party-domains-per-page-by-rank-and-category.png
  src/static/images/2022/third-parties/top-third-parties-by-number-of-pages.png
Labels: writing

#3119 2022 SEO Chapter
  src/config/2022.json
  src/content/en/2022/seo.md
  src/static/images/2022/seo/amp-markup.png
  src/static/images/2022/seo/anchor-rel-attr.png
  src/static/images/2022/seo/canonical-usage.png
  src/static/images/2022/seo/content-language.png
  src/static/images/2022/seo/good-cwv-desktop.png
  src/static/images/2022/seo/good-cwv-mobile.png
  src/static/images/2022/seo/has-h-elements.png
  src/static/images/2022/seo/has-title-meta.png
  src/static/images/2022/seo/hreflang-usage.png
  src/static/images/2022/seo/html-versus-http-canonical.png
  src/static/images/2022/seo/https-usage.png
  src/static/images/2022/seo/iframe-loading.png
  src/static/images/2022/seo/image-alt-empty.png
  src/static/images/2022/seo/image-alt-missing.png
  src/static/images/2022/seo/image-alt-present.png
  src/static/images/2022/seo/image-loading-property.png
  src/static/images/2022/seo/indexifembedded-useragents.png
  src/static/images/2022/seo/invalid-head-elements.png
  src/static/images/2022/seo/median-external-links.png
  src/static/images/2022/seo/median-internal-links.png
  src/static/images/2022/seo/meta-description-characters-percentile.png
  src/static/images/2022/seo/meta-description-words-percentile.png
  src/static/images/2022/seo/nonempty-h-elements.png
  src/static/images/2022/seo/pages-with-iframe.png
  src/static/images/2022/seo/popular-schemas.png
  src/static/images/2022/seo/raw-vs-rendered-canonical.png
  src/static/images/2022/seo/raw-vs-rendered-structured-data.png
  src/static/images/2022/seo/robots-size.png
  src/static/images/2022/seo/robots-txt-status-codes.png
  src/static/images/2022/seo/robots-useragents.png
  src/static/images/2022/seo/seo-term-trends.png
  src/static/images/2022/seo/structured-data-formats.png
  src/static/images/2022/seo/title-characters-percentile.png
  src/static/images/2022/seo/title-words-percentile.png
  src/static/images/2022/seo/vary-header.png
  src/static/images/2022/seo/visible-words-raw.png
  src/static/images/2022/seo/visible-words-rendered.png
Labels: writing

#3120 2022 CMS Chapter
  sql/2022/cms/lighthouse_category_scores_per_cms.sql
  sql/2022/cms/top_cms_by_geo.sql
  src/config/2022.json
  src/content/en/2022/cms.md
  src/static/images/2022/cms/cls-cwv-yoy.png
  src/static/images/2022/cms/cms-adoption-geo.png
  src/static/images/2022/cms/cms-adoption-rank.png
  src/static/images/2022/cms/cms-adoption.png
  src/static/images/2022/cms/distribution-cms-page-weight.png
  src/static/images/2022/cms/fid-cwv-yoy.png
  src/static/images/2022/cms/image-format-popularity.png
  src/static/images/2022/cms/lcp-cwv-performance.png
  src/static/images/2022/cms/lcp-cwv-yoy.png
  src/static/images/2022/cms/median-cms-image-size.png
  src/static/images/2022/cms/median-cms-page-weight.png
  src/static/images/2022/cms/median-lighthouse-accessibility.png
  src/static/images/2022/cms/median-lighthouse-best-practices.png
  src/static/images/2022/cms/median-lighthouse-performance.png
  src/static/images/2022/cms/median-lighthouse-seo.png
  src/static/images/2022/cms/median-size-css.png
  src/static/images/2022/cms/median-size-font.png
  src/static/images/2022/cms/median-size-html.png
  src/static/images/2022/cms/median-size-js.png
  src/static/images/2022/cms/median-wordpress-resources.png
  src/static/images/2022/cms/top-5-cms-yoy.png
  src/static/images/2022/cms/top-cwv-performance.png
  src/static/images/2022/cms/top-cwv-yoy.png
  src/static/images/2022/cms/wordpress-adoption-geo-yoy.png
  src/static/images/2022/cms/wordpress-cwv-yoy.png
  src/static/images/2022/cms/wordpress-page-builders.png
Labels: writing

#3128 2022 HTTP Chapter
  src/config/2022.json
  src/content/en/2022/http.md
  src/static/images/2022/http/alt-svc-example.png
  src/static/images/2022/http/connections-comparison-per-page.png
  src/static/images/2022/http/h2-push-usage.png
  src/static/images/2022/http/h3-support-per-request.png
  src/static/images/2022/http/http2-adoption-per-cdn.png
  src/static/images/2022/http/http2-adoption-per-request.png
  src/static/images/2022/http/http2-adoption-per-site.png
Labels: writing

#3087 2022 Accessibility chapter
  src/config/2022.json
  src/content/en/2022/accessibility.md
  src/static/images/2022/accessibility/a11y-app-usage-by-rank.png
  src/static/images/2022/accessibility/alt-attribute-lengths.png
  src/static/images/2022/accessibility/button-name-sources.png
  src/static/images/2022/accessibility/color-contrast-2019-2020-2021-2022.png
  src/static/images/2022/accessibility/common-file-extensions-in-alt-text.png
  src/static/images/2022/accessibility/font-unit-usage.png
  src/static/images/2022/accessibility/forced-colors-mode.png
  src/static/images/2022/accessibility/form-input-name-sources.png
  src/static/images/2022/accessibility/form-required-controls.png
  src/static/images/2022/accessibility/lighthouse-audit-improvements-yoy.png
  src/static/images/2022/accessibility/page_title-information.png
  src/static/images/2022/accessibility/pages-containing-alt-with-file-extension.png
  src/static/images/2022/accessibility/pages-overriding-focus-styles.png
  src/static/images/2022/accessibility/pages-using-a11y-apps-by-rank.png
  src/static/images/2022/accessibility/pages-using-a11y-apps.png
  src/static/images/2022/accessibility/pages-zooming-scaling-disabled-by-rank.png
  src/static/images/2022/accessibility/pages-zooming-scaling-disabled.png
  src/static/images/2022/accessibility/placeholder-but-no-label.png
  src/static/images/2022/accessibility/sites-using-role.png
  src/static/images/2022/accessibility/tabindex-usage-and-values.png
  src/static/images/2022/accessibility/top-10-aria-roles.png
  src/static/images/2022/accessibility/top10-aria-attributes.png
  src/static/images/2022/accessibility/userpreference-media-queries.png
Labels: writing

#3152 Third parties 2022: fix a link and typo
  src/content/en/2022/third-parties.md
Labels: editing

#3151 Correct typo in CMS chapter
  src/content/en/2022/cms.md
Labels: editing

#3137 2022 JavaScript chapter
  src/config/2022.json
  src/content/en/2022/javascript.md
  src/static/images/2022/javascript/babel-rank.png
  src/static/images/2022/javascript/bytes-party.png
  src/static/images/2022/javascript/bytes-per-page.png
  src/static/images/2022/javascript/compression-by-host.png
  src/static/images/2022/javascript/compression-methods.png
  src/static/images/2022/javascript/fid.png
  src/static/images/2022/javascript/frameworks-libraries.png
  src/static/images/2022/javascript/injected-scripts.png
  src/static/images/2022/javascript/inp.png
  src/static/images/2022/javascript/lighthouse-unminified-avg.png
  src/static/images/2022/javascript/lighthouse-unminified-bytes.png
  src/static/images/2022/javascript/lighthouse-unminified.png
  src/static/images/2022/javascript/long-tasks-time.png
  src/static/images/2022/javascript/long-tasks.png
  src/static/images/2022/javascript/modulepreload.png
  src/static/images/2022/javascript/parcel-rank.png
  src/static/images/2022/javascript/prefetch.png
  src/static/images/2022/javascript/preload.png
  src/static/images/2022/javascript/render-blocking-scripts-rank.png
  src/static/images/2022/javascript/requests-party.png
  src/static/images/2022/javascript/requests-per-page.png
  src/static/images/2022/javascript/tbt.png
  src/static/images/2022/javascript/tti.png
  src/static/images/2022/javascript/uncompressed.png
  src/static/images/2022/javascript/unused-js.png
  src/static/images/2022/javascript/webpack-rank.png
Labels: writing, editing

#3099 2022 Capabilities Chapter
  src/config/2022.json
  src/content/en/2022/capabilities.md
  src/static/images/2022/capabilities/Add-to-Home-Screen.gif
  src/static/images/2022/capabilities/Add-to-Home-Screen.webp
  src/static/images/2022/capabilities/Async-Clipboard-API-Usage.png
  src/static/images/2022/capabilities/Gamepad-API-Usage.png
  src/static/images/2022/capabilities/Gamepad-API.gif
  src/static/images/2022/capabilities/Gamepad-API.webp
  src/static/images/2022/capabilities/Media-Session-API.png
  src/static/images/2022/capabilities/Service-Worker-API-Usage.png
  src/static/images/2022/capabilities/Web-Share-API-Usage.png
  src/static/images/2022/capabilities/Web-Share-API.gif
  src/static/images/2022/capabilities/Web-Share-API.webp
Labels: writing, editing

#3147 2022 Markup Chapter
  src/config/2022.json
  src/content/en/2022/markup.md
  src/static/css/page.css
  src/static/images/2022/markup/adoption-of-top-html-elements.png
  src/static/images/2022/markup/attribute-usage.png
  src/static/images/2022/markup/content-encoding.png
  src/static/images/2022/markup/data-attribute-popularity.png
  src/static/images/2022/markup/element-count-distribution.png
  src/static/images/2022/markup/html-document-transfer-size.png
  src/static/images/2022/markup/html-languages.png
  src/static/images/2022/markup/obselete-elements.png
  src/static/images/2022/markup/social-meta-nodes-usage.png
Labels: writing, editing

#3155 Markup: Fixed typos, final polishing
  src/content/en/2022/markup.md
Labels: editing

#3156 fix: fix “obselete” wording and naming
  src/content/en/2022/markup.md
  src/static/images/2022/markup/attribute-usage.png
  src/static/images/2022/markup/obsolete-elements-relative-use.png
  src/static/images/2022/markup/obsolete-elements.png
Labels: editing

#3154 Translation of base to Japanese
  src/templates/ja/2021/base.html
Labels: translation

#3153 Further edits to the CMS chapter
  src/content/en/2022/cms.md
Labels: editing

#3142 2022 Security Chapter
  src/config/2022.json
  src/content/en/2022/security.md
  src/static/images/2022/security/adoption-of-csp-and-xfo-per-country.png
  src/static/images/2022/security/adoption-of-https-per-country.png
  src/static/images/2022/security/adoption-of-security-headers.png
  src/static/images/2022/security/bot-protection-service-usage.png
  src/static/images/2022/security/cookie-age-usage-by-site-in-desktop-in-days.png
  src/static/images/2022/security/cryptominer-market-share.png
  src/static/images/2022/security/cryptominer-usage.png
  src/static/images/2022/security/csp-directives-usage.png
  src/static/images/2022/security/csp-header-length.png
  src/static/images/2022/security/csp-script-src-attribute-usage.png
  src/static/images/2022/security/detecting-status-code-reliability.png
  src/static/images/2022/security/distribution-of-cipher-suites.png
  src/static/images/2022/security/forward-secrecy-support.png
  src/static/images/2022/security/hsts-directives-usage.png
  src/static/images/2022/security/hsts-max-age-values-in-days.png
  src/static/images/2022/security/httponly-secure-samesite-cookie-usage.png
  src/static/images/2022/security/https-usage-by-site.png
  src/static/images/2022/security/percentage-of-cross-origin-headers.png
  src/static/images/2022/security/prevalence-of-headers-in-sites-by-rank.png
  src/static/images/2022/security/prevalence-of-sandbox-directives-on-frames.png
  src/static/images/2022/security/samesite-cookie-attributes.png
  src/static/images/2022/security/sri-hash-function-usage.png
  src/static/images/2022/security/tls-version-by-site.png
  src/static/images/2022/security/usage-of-change-password.png
  src/static/images/2022/security/usage-of-properties-in-well-known-security.png
  src/templates/base/base.html
Labels: writing

#3143 2022 Media Chapter
  sql/2022/media/README.md
  src/config/2022.json
  src/content/en/2022/media.md
  src/static/images/2022/media/adoption-of-loading-lazy-on-img.png
  src/static/images/2022/media/adoption-of-video-over-time.png
  src/static/images/2022/media/distribution-of-animated-gif-frame-counts.png
  src/static/images/2022/media/distribution-of-image-bits-pixel.png
  src/static/images/2022/media/distribution-of-image-byte-sizes.png
  src/static/images/2022/media/distribution-of-image-pixel-counts.png
  src/static/images/2022/media/distribution-of-img-layout-widths.png
  src/static/images/2022/media/distribution-of-img-sizes-errors.png
  src/static/images/2022/media/excess-kilobytes-loaded-per-page-due-to-innaccurate-sizes.png
  src/static/images/2022/media/gif-bits-per-pixel-animated-vs-non-animated.png
  src/static/images/2022/media/image-format-adoption-year-over-year-change.png
  src/static/images/2022/media/image-format-adoption.png
  src/static/images/2022/media/image-hosts-cross-vs-same-domain.png
  src/static/images/2022/media/image-orientations.png
  src/static/images/2022/media/intrinsic-and-extrinsic-image-sizing.png
  src/static/images/2022/media/largest-image-per-page-by-kilobytes.png
  src/static/images/2022/media/largest-image-per-page-by-pixel-count.png
  src/static/images/2022/media/median-bits-per-pixel-by-format.png
  src/static/images/2022/media/number-of-sources-per-video.png
  src/static/images/2022/media/picture-feature-usage.png
  src/static/images/2022/media/srcset-descriptor-usage.png
  src/static/images/2022/media/top-extensions-of-files-with-a-video-mime-type.png
  src/static/images/2022/media/video-attribute-usage.png
  src/static/images/2022/media/video-durations.png
  src/static/images/2022/media/video-preload-attribute-value-usage.png
  src/static/images/2022/media/widest-img-per-page-layout-width.png
Labels: writing, editing

#3148 2022 Fonts Chapter
  src/config/2022.json
  src/content/en/2022/fonts.md
  src/static/images/2022/fonts/bradley-initials.png
  src/static/images/2022/fonts/color-font-formats.png
  src/static/images/2022/fonts/color-font-usage.png
  src/static/images/2022/fonts/compressed-font-outline-sizes.png
  src/static/images/2022/fonts/css-font-metrics-override-usage.png
  src/static/images/2022/fonts/font-outline-sizes.png
  src/static/images/2022/fonts/font-sizes.png
  src/static/images/2022/fonts/fonts-resource-hints-usage.png
  src/static/images/2022/fonts/hosting-type.png
  src/static/images/2022/fonts/openType-feature-usage-in-css.png
  src/static/images/2022/fonts/opentype-features-support-in-fonts.png
  src/static/images/2022/fonts/outline-formats.png
  src/static/images/2022/fonts/popular-variable-font-weight-values.png
  src/static/images/2022/fonts/popular-web-font-mime-types.png
  src/static/images/2022/fonts/popular-web-font-mimetypes-self-hosted.png
  src/static/images/2022/fonts/self-hosted-font-sizes.png
  src/static/images/2022/fonts/usage-of-css-font-variant-values.png
  src/static/images/2022/fonts/usage-of-css-generic-font-family-names.png
  src/static/images/2022/fonts/usage-of-font-display.png
  src/static/images/2022/fonts/usage-of-font-feature-settings-vs-font-variant.png
  src/static/images/2022/fonts/usage-of-font-smoothing-properties.png
  src/static/images/2022/fonts/usage-of-font-variation-settings-axes.png
  src/static/images/2022/fonts/usage-of-variable-fonts.png
  src/static/images/2022/fonts/webfont-usage-by-service.png
  src/static/images/2022/fonts/webfont-usage.png
  src/static/images/2022/fonts/writing-systems-supported-by-fonts.png
Labels: writing

#3145 2022 Interoperability Chapter
  sql/2022/interoperability/README.md
  sql/2022/interoperability/align_items_values.sql
  sql/2022/interoperability/align_values.sql
  sql/2022/interoperability/aspect_ratio.sql
  sql/2022/interoperability/backdrop.sql
  sql/2022/interoperability/cascade_layers.sql
  sql/2022/interoperability/color_functions.sql
  sql/2022/interoperability/color_spaces.sql
  sql/2022/interoperability/contain.sql
  sql/2022/interoperability/contain_values.sql
  sql/2022/interoperability/container.sql
  sql/2022/interoperability/dialog.sql
  sql/2022/interoperability/flex_basis_content.sql
  sql/2022/interoperability/flex_basis_content_2021.sql
  sql/2022/interoperability/flexbox_trends.sql
  sql/2022/interoperability/justify_content_values.sql
  sql/2022/interoperability/layer_adoption.sql
  sql/2022/interoperability/layer_per_page.sql
  sql/2022/interoperability/perspective_none.sql
  sql/2022/interoperability/position_sticky.sql
  sql/2022/interoperability/subgrid.sql
  sql/2022/interoperability/transform_style_preserve_3d.sql
  sql/2022/interoperability/viewport_units.sql
  src/config/2022.json
  src/config/last_updated.json
  src/content/en/2022/interop.md
  src/content/en/2022/interoperability.md
  src/server/validate.py
  src/static/images/2022/interoperability/aspect-ratio-usage.png
  src/static/images/2022/interoperability/cascade-layers-wpt-dashboard.png
  src/static/images/2022/interoperability/color-spaces-and-functions-wpt-dashboard.png
  src/static/images/2022/interoperability/compat-2021-dashboard.png
  src/static/images/2022/interoperability/contain-property-usage.png
  src/static/images/2022/interoperability/containment-wpt-dashboard.png
  src/static/images/2022/interoperability/css-transforms-wpt-dashboard-experimental.png
  src/static/images/2022/interoperability/css-transforms-wpt-dashboard-stable.png
  src/static/images/2022/interoperability/dialog-element-wpt-dashboard.png
  src/static/images/2022/interoperability/forms-wpt-dashboard.png
  src/static/images/2022/interoperability/p3-color-space.jpg
  src/static/images/2022/interoperability/scroll-property-adoption.png
  src/static/images/2022/interoperability/scrolling-wpt-dashboard.png
  src/static/images/2022/interoperability/subgrid-wpt-dashboard.png
  src/static/images/2022/interoperability/typography-and-encodings-wpt-dashboard.png
  src/static/images/2022/interoperability/viewport-units-wpt-dashboard.png
Labels: writing, editing

#3149 Remove the chapters that didn't make it
  src/config/2022.json
  src/config/last_updated.json
  src/content/en/2022/caching.md
  src/content/en/2022/cdn.md
  src/content/en/2022/compression.md
  src/content/en/2022/ecommerce.md
Labels: project management

#3161 Update interoperability.md
  src/content/en/2022/interoperability.md
Labels: editing

#3164 Add missing width and height to Markup image
  src/content/en/2022/markup.md
Labels: editing

#3159 2022 Page Weight Chapter
  src/config/2022.json
  src/content/en/2022/page-weight.md
  src/static/images/2022/page-weight/distribution-of-image-sizes-by-format.png
  src/static/images/2022/page-weight/distribution-of-image-sizes.png
  src/static/images/2022/page-weight/distribution-of-requests-by-content-type.png
  src/static/images/2022/page-weight/distribution-of-requests.png
  src/static/images/2022/page-weight/distribution-of-response-size-by-content-type.png
  src/static/images/2022/page-weight/distribution-of-video-sizes-by-format.png
  src/static/images/2022/page-weight/distribution.png
  src/static/images/2022/page-weight/median-page-weight-by-content-type.png
  src/static/images/2022/page-weight/median-page-weight-over-time.png
  src/static/images/2022/page-weight/median-response-size-by-content-type.png
  src/static/images/2022/page-weight/median-response-size-by-format.png
  src/static/images/2022/page-weight/minified-css-proper-usage.png
  src/static/images/2022/page-weight/minified-javascript-proper-usage.png
  src/static/images/2022/page-weight/text-compression-proper-usage.png
  src/static/images/2022/page-weight/third-party-facades.png
Labels: writing, editing

#3158 2022 WebAssembly Chapter
  src/config/2022.json
  src/content/en/2022/webassembly.md
  src/static/images/2022/webassembly/counts.png
  src/static/images/2022/webassembly/cross_domain.png
  src/static/images/2022/webassembly/language_usage.png
  src/static/images/2022/webassembly/popular_by_name.png
  src/static/images/2022/webassembly/proposals.png
  src/static/images/2022/webassembly/uncompressed_resp_sizes.png
Labels: writing, editing

#3167 Spellcheck for 2022 launch
  src/config/spelling_ignore_words.txt
  src/content/en/2021/http.md
  src/content/en/2021/media.md
  src/content/en/2021/mobile-web.md
  src/content/en/2021/seo.md
  src/content/en/2022/accessibility.md
  src/content/en/2022/cms.md
  src/content/en/2022/css.md
  src/content/en/2022/fonts.md
  src/content/en/2022/http.md
  src/content/en/2022/interoperability.md
  src/content/en/2022/markup.md
  src/content/en/2022/media.md
  src/content/en/2022/mobile-web.md
  src/content/en/2022/page-weight.md
  src/content/en/2022/pwa.md
  src/content/en/2022/security.md
  src/content/en/2022/seo.md
  src/content/en/2022/sustainability.md
  src/content/en/2022/third-parties.md
  src/content/en/2022/webassembly.md
  src/static/images/2022/media/excess-kilobytes-loaded-per-page-due-to-inaccurate-sizes.png
  src/templates/en/2019/methodology.html
  src/templates/en/2020/methodology.html
  src/templates/en/2021/methodology.html
  src/templates/en/2022/methodology.html
  src/templates/fr/2019/methodology.html
  src/templates/fr/2020/methodology.html
  src/templates/hi/2019/methodology.html
  src/templates/hi/2020/methodology.html
  src/templates/ja/2019/methodology.html
  src/templates/ja/2020/methodology.html
  src/templates/nl/2019/methodology.html
  src/templates/nl/2020/methodology.html
  src/templates/ru/2019/methodology.html
  src/templates/ru/2020/methodology.html
  src/templates/zh-CN/2019/methodology.html
  src/templates/zh-CN/2020/methodology.html
  src/templates/zh-TW/2020/methodology.html
Labels: editing

#3178 Fix 2022 logo
  src/templates/base/index.html
Labels: development, design

#3175 Update spellcheck wordlist
  src/config/spelling_ignore_words.txt
  src/content/en/2022/webassembly.md
Labels: editing

#3184 Fix home page header inconsistency
  src/static/css/index.css
Labels: bug, design

#3191 HTTP 2022 Chapter fix typo
  src/content/en/2022/http.md
Labels: 2022 chapter
