Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2022-02, with the labels that each got.

#2799 Correct a11y figure
  src/content/en/2021/accessibility.md
  src/static/images/2021/accessibility/font-unit-usage.png
  src/static/images/2021/accessibility/pages-overriding-focus-styles.png
Labels: editing

#2812 Simplify logic in meta description
  src/templates/base/error.html
  src/templates/en/base_chapter.html
  src/templates/es/base_chapter.html
  src/templates/fr/base_chapter.html
  src/templates/hi/base_chapter.html
  src/templates/it/base_chapter.html
  src/templates/ja/base_chapter.html
  src/templates/nl/base_chapter.html
  src/templates/pt/base_chapter.html
  src/templates/ru/base_chapter.html
  src/templates/uk/base_chapter.html
  src/templates/zh-CN/base_chapter.html
  src/templates/zh-TW/base_chapter.html
Labels: development

#2817 Translation of accessibility chapter to Japanese
  src/content/en/2021/accessibility.md
  src/content/ja/2021/accessibility.md
Labels: translation
