Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2022-07, with the labels that each got.

#2995 Clean up HEAD
  src/templates/base.html
  src/templates/base/accessibility_statement.html
  src/templates/base/base.html
  src/templates/base/base_chapter.html
  src/templates/base/error.html
  src/templates/base/index.html
  src/templates/base/methodology.html
  src/templates/base/search.html
Labels: development, performance

#2996 2021 compression japanese translation
  src/content/en/2021/compression.md
  src/content/ja/2021/compression.md
Labels: translation

#2997 Can't use async on script without src
  src/templates/base.html
Labels: bug, development

#3008 Display chapter dates
  src/static/css/page.css
  src/templates/base/base_chapter.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/tr/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: development, design

#3013 Correct editorconfig config file
  .github/linters/.ecrc
Labels: development

#3014 2021 caching japanese translation
  src/content/en/2021/caching.md
  src/content/ja/2021/caching.md
Labels: translation

#3015 Fix JS error when no updated date
  src/templates/base/base_chapter.html
Labels: bug, development

#3012 Correct names of 2021 Privacy images and reference ebooks from GitHub
  src/.gcloudignore
  src/app.yaml
  src/content/en/2021/privacy.md
  src/content/ja/2021/privacy.md
  src/content/nl/2021/privacy.md
  src/server/routes.py
  src/server/tests/routes_test.py
  src/templates/base/base.html
  src/templates/base/table_of_contents.html
  src/tools/generate/generate_sitemap.js
  src/tools/scripts/deploy.sh
Labels: bug

#2959 Security 2022 queries
  sql/2022/security/README.md
  sql/2022/security/bot_detection.sql
  sql/2022/security/clear-site-data_value_prevalence.sql
  sql/2022/security/cookie_age_percentiles.sql
  sql/2022/security/cookie_attributes.sql
  sql/2022/security/cookie_max_age_expires_top_values.sql
  sql/2022/security/corp_header_prevalence.sql
  sql/2022/security/cryptominer_share.sql
  sql/2022/security/cryptominer_usage.sql
  sql/2022/security/csp_allowed_host_frequency.sql
  sql/2022/security/csp_directives_usage.sql
  sql/2022/security/csp_most_common_header.sql
  sql/2022/security/csp_number_of_allowed_hosts.sql
  sql/2022/security/csp_script_source_list_keywords.sql
  sql/2022/security/feature_adoption_by_country.sql
  sql/2022/security/feature_adoption_by_other_features.sql
  sql/2022/security/feature_adoption_by_technology.sql
  sql/2022/security/feature_adoption_by_topN_technologies.sql
  sql/2022/security/home_page_https_usage.sql
  sql/2022/security/hsts_attributes.sql
  sql/2022/security/hsts_max_age_percentiles.sql
  sql/2022/security/https_request_over_time.sql
  sql/2022/security/https_server_redirects.sql
  sql/2022/security/iframe_allow_directive_values.sql
  sql/2022/security/iframe_allow_directives.sql
  sql/2022/security/iframe_attribute_popular_hosts.sql
  sql/2022/security/iframe_attributes_usage.sql
  sql/2022/security/iframe_sandbox_directives.sql
  sql/2022/security/meta_policies_allowed_vs_disallowed.sql
  sql/2022/security/mimetype_file_extension_mismatch.sql
  sql/2022/security/mixed_content.sql
  sql/2022/security/robot_header_and_meta_tag_prevalence.sql
  sql/2022/security/robot_txt_sensitive_disallow.sql
  sql/2022/security/security_adoption_by_rank.sql
  sql/2022/security/security_headers_prevalence.sql
  sql/2022/security/server_header_value_prevalence.sql
  sql/2022/security/server_information_header_prevalence.sql
  sql/2022/security/sri_coverage_per_page.sql
  sql/2022/security/sri_hash_functions.sql
  sql/2022/security/sri_popular_hosts.sql
  sql/2022/security/sri_usage.sql
  sql/2022/security/tls_ca_issuers_pages.sql
  sql/2022/security/tls_ca_issuers_requests.sql
  sql/2022/security/tls_cipher_suite.sql
  sql/2022/security/tls_forward_secrecy.sql
  sql/2022/security/tls_versions_pages.sql
  sql/2022/security/tls_versions_requests.sql
  sql/2022/security/version-evolution-top-technologies.sql
  sql/2022/security/web_cryptography_api.sql
  sql/2022/security/well-known_change-password.sql
  sql/2022/security/well-known_resource-not-be-200.sql
  sql/2022/security/well-known_security.sql
Labels: analysis

#3022 Update SQLFluff config to latest
  sql/.sqlfluff
Labels: development, analysis

#3024 Prevent Werkzeug 2.2.0 being used
  src/requirements.txt
Labels: bug, development

#3023 Translation of 2021 CDN chapter to Japanese
  src/content/ja/2021/cdn.md
Labels: translation

#3025 Fix default python date format
  src/server/helpers.py
Labels: bug, development

#2960 PWA 2022 queries
  sql/2022/pwa/assetlink_usage.sql
  sql/2022/pwa/fugu.sql
  sql/2022/pwa/install_events.sql
  sql/2022/pwa/lighthouse_pwa_audits.sql
  sql/2022/pwa/lighthouse_pwa_score.sql
  sql/2022/pwa/manifests_and_service_workers.sql
  sql/2022/pwa/manifests_description.sql
  sql/2022/pwa/manifests_file_handlers.sql
  sql/2022/pwa/manifests_iarc.sql
  sql/2022/pwa/manifests_lang.sql
  sql/2022/pwa/manifests_not_json_parsable.sql
  sql/2022/pwa/manifests_note_taking.sql
  sql/2022/pwa/manifests_preferring_native_apps.sql
  sql/2022/pwa/manifests_protocol_handlers.sql
  sql/2022/pwa/manifests_screenshots.sql
  sql/2022/pwa/manifests_screenshots_platform_narrow.sql
  sql/2022/pwa/manifests_screenshots_platform_wide.sql
  sql/2022/pwa/manifests_share_target.sql
  sql/2022/pwa/manifests_shortcuts.sql
  sql/2022/pwa/manifests_window_controls_overlay.sql
  sql/2022/pwa/popular_pwa_libraries.sql
  sql/2022/pwa/popular_pwa_libraries_helper.sql
  sql/2022/pwa/pwa_blink_usage.sql
  sql/2022/pwa/pwa_notification_acceptance_rates.sql
  sql/2022/pwa/pwa_notification_acceptance_rates_over_time.sql
  sql/2022/pwa/sw_adoption_over_time.sql
  sql/2022/pwa/sw_adoption_over_time_ranking.sql
  sql/2022/pwa/sw_events.sql
  sql/2022/pwa/sw_methods.sql
  sql/2022/pwa/sw_objects.sql
  sql/2022/pwa/sw_objects_name_only.sql
  sql/2022/pwa/sw_registration_properties.sql
  sql/2022/pwa/sw_registration_properties_name_only.sql
  sql/2022/pwa/top_manifest_categories.sql
  sql/2022/pwa/top_manifest_display_values.sql
  sql/2022/pwa/top_manifest_icon_sizes.sql
  sql/2022/pwa/top_manifest_orientations.sql
  sql/2022/pwa/top_manifest_properties.sql
  sql/2022/pwa/workbox_methods.sql
  sql/2022/pwa/workbox_packages.sql
  sql/2022/pwa/workbox_usage.sql
  sql/2022/pwa/workbox_versions.sql
Labels: analysis
