Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2022-10, with the labels that each got.

#3193 Translation of methodology chapter to Japanese
  src/templates/ja/2021/methodology.html
Labels: translation

#3192 Translate 2022 PWA chapter for Simplified Chinese
  src/config/2022.json
  src/content/en/2022/pwa.md
  src/content/zh-CN/2022/pwa.md
Labels: translation

#3200 Fix 2019/2021 Home Logo
  src/templates/base/index.html
Labels: bug

#3207 Fix link in 2021 Third-Parties chapter
  src/content/en/2021/third-parties.md
  src/content/ja/2021/third-parties.md
Labels: editing

#3208 Update Third-party TAO SQL
  sql/2022/third-parties/tao_by_third_party.sql
Labels: analysis

#3173 2022 Privacy chapter
  src/config/2022.json
  src/config/last_updated.json
  src/content/en/2021/privacy.md
  src/content/en/2022/privacy.md
  src/static/images/2022/privacy/client-hints-by-rank.png
  src/static/images/2022/privacy/cmp-services.png
  src/static/images/2022/privacy/cname-tracking-by-rank.png
  src/static/images/2022/privacy/cname-tracking-services.png
  src/static/images/2022/privacy/cookie-origins.png
  src/static/images/2022/privacy/fingerprinting-services.png
  src/static/images/2022/privacy/gelocation-services.png
  src/static/images/2022/privacy/iab-prevalence.png
  src/static/images/2022/privacy/iab-publisher-countries.png
  src/static/images/2022/privacy/iab-tcfv2-prevalence.png
  src/static/images/2022/privacy/most-common-cookies.png
  src/static/images/2022/privacy/most-common-trackers.png
  src/static/images/2022/privacy/number-of-trackers-per-site.png
  src/static/images/2022/privacy/permission-policy-features.png
  src/static/images/2022/privacy/permissions-policy-type.png
  src/static/images/2022/privacy/privacy-link-keywords.png
  src/static/images/2022/privacy/referrer-policies.png
  src/static/images/2022/privacy/retargeting-services.png
  src/static/images/2022/privacy/sensor-events.png
Labels: writing

#3212 2022 CDN Chapter
  sql/2022/cdn/top_cdns.sql
  sql/2022/cdn/top_cdns_by_rank.sql
  src/config/2022.json
  src/content/en/2022/cdn.md
  src/static/images/2022/cdn/cdn-client-hints-mobile.png
  src/static/images/2022/cdn/cdn-compression-mobile.png
  src/static/images/2022/cdn/cdn-http-versions-mobile-3p.png
  src/static/images/2022/cdn/cdn-http-versions-mobile.png
  src/static/images/2022/cdn/cdn-image-formats-mobile.png
  src/static/images/2022/cdn/cdn-usage-hosted-comparison.png
  src/static/images/2022/cdn/cdn-usage-hosted.png
  src/static/images/2022/cdn/cdn-usage-ranking-desktop.png
  src/static/images/2022/cdn/tls-negotiation-desktop.png
  src/static/images/2022/cdn/tls-negotiation-mobile.png
  src/static/images/2022/cdn/tls-version-mobile-3p.png
  src/static/images/2022/cdn/tls-version-mobile.png
  src/static/images/2022/cdn/top-cdns-3p.png
  src/static/images/2022/cdn/top-cdns-html.png
  src/static/images/2022/cdn/top-cdns-subdomain.png
Labels: writing, editing

#3214 2022 Jamstack Chapter
  src/config/2022.json
  src/content/en/2022/jamstack.md
  src/static/images/2022/jamstack/all-sites-javascript-frameworks.png
  src/static/images/2022/jamstack/all-sites-paas.png
  src/static/images/2022/jamstack/all-sites-web-frameworks.png
  src/static/images/2022/jamstack/changes-in-jamstack-counts-over-time.png
  src/static/images/2022/jamstack/jamstack-counts.png
  src/static/images/2022/jamstack/jamstack-javascript-frameworks.png
  src/static/images/2022/jamstack/jamstack-paas.png
  src/static/images/2022/jamstack/jamstack-web-frameworks.png
  src/static/images/2022/jamstack/jamstack_web_frameworks.png
Labels: writing, editing

#3218 Updates release 2 dates
  src/config/last_updated.json
Labels: development, project management

#3219 2022 Release 2 spellcheck
  src/config/spelling_ignore_words.txt
  src/content/en/2022/jamstack.md
Labels: editing

#3220 Fix 404s for 2022 Release 2
  src/config/2019.json
  src/config/2020.json
  src/config/2021.json
  src/config/2022.json
  src/content/en/2019/media.md
  src/content/en/2021/css.md
  src/content/en/2022/capabilities.md
  src/content/en/2022/cdn.md
  src/content/en/2022/cms.md
  src/content/en/2022/css.md
  src/content/en/2022/fonts.md
  src/content/en/2022/interoperability.md
  src/content/en/2022/javascript.md
  src/content/en/2022/mobile-web.md
  src/content/en/2022/page-weight.md
  src/content/en/2022/security.md
  src/content/en/2022/sustainability.md
  src/content/en/2022/webassembly.md
  src/content/es/2019/media.md
  src/content/fr/2019/media.md
  src/content/ja/2019/media.md
  src/content/ja/2021/css.md
  src/templates/en/2022/methodology.html
Labels: editing

#3238 Hide reaction tabs with 0 reactions
  src/static/css/page.css
  src/static/js/webmentions.js
  src/templates/base/base_chapter.html
Labels: development

#3246 Center-aligned featured stats
  src/static/css/index.css
Labels: development, design

#3092 2022 Performance chapter
  sql/2022/performance/js_bytes_rank.sql
  src/config/2022.json
  src/config/last_updated.json
  src/config/spelling_ignore_words.txt
  src/content/en/2022/performance.md
  src/static/css/almanac.css
  src/static/images/2022/performance/animations.png
  src/static/images/2022/performance/bfcache-nostore.png
  src/static/images/2022/performance/bfcache-unload.png
  src/static/images/2022/performance/cross-hosted-lcp-images.png
  src/static/images/2022/performance/cwv-fid-inp-device.png
  src/static/images/2022/performance/cwv-fid-inp-rank.png
  src/static/images/2022/performance/cwv-inp-tech.png
  src/static/images/2022/performance/font-display-usage.png
  src/static/images/2022/performance/fonts-resource-hints.png
  src/static/images/2022/performance/good-cls-by-device.png
  src/static/images/2022/performance/good-core-web-vitals-by-device.png
  src/static/images/2022/performance/good-cwv-performance-by-rank-and-year.png
  src/static/images/2022/performance/good-fcp-by-device.png
  src/static/images/2022/performance/good-fid-by-device.png
  src/static/images/2022/performance/good-lcp-by-device.png
  src/static/images/2022/performance/good-ttfb-by-device.png
  src/static/images/2022/performance/inp-device.png
  src/static/images/2022/performance/inp-performance-by-rank.png
  src/static/images/2022/performance/js-bytes-rank.png
  src/static/images/2022/performance/lcp-image-formats.png
  src/static/images/2022/performance/lcp-image-optimization.png
  src/static/images/2022/performance/lcp-image-size-distribution.png
  src/static/images/2022/performance/lcp-image-size-histogram.png
  src/static/images/2022/performance/long-tasks.png
  src/static/images/2022/performance/monthly-cls-lcp.png
  src/static/images/2022/performance/pages-passing-render-blocking-resources-audit.png
  src/static/images/2022/performance/tbt-fid.png
  src/static/images/2022/performance/tbt-inp.png
  src/static/images/2022/performance/tbt.png
  src/static/images/2022/performance/top-lcp-content-types.png
  src/static/images/2022/performance/top-lcp-element-types.png
  src/static/images/2022/performance/top-lcp-initiators-among-pages-whose-lcp-is-not-statically-discoverable.png
  src/static/images/2022/performance/unsized-image-height.png
  src/static/images/2022/performance/unsized-images.png
Labels: writing

#3249 Italian translation of 2022 Fonts chapter
  src/config/2022.json
  src/content/it/2022/fonts.md
Labels: translation

#3256 Fix timezone for chapters
  src/templates/base/base_chapter.html
Labels: bug, development

#3259 Correct Structured Data featured stat
  src/content/en/2022/structured-data.md
Labels: editing

#3261 Replace voice searches stats in accessibility chapter. Fix #3260
  src/content/en/2022/accessibility.md
Labels: writing
