Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2022-08, with the labels that each got.

#2940 Third Parties 2022 queries
  sql/2022/third-parties/a11y_overall_tech_usage_by_rank.sql
  sql/2022/third-parties/a11y_technology_usage.sql
  sql/2022/third-parties/a11y_technology_usage_by_rank.sql
  sql/2022/third-parties/content_encoding.sql
  sql/2022/third-parties/content_encoding_by_content_type.sql
  sql/2022/third-parties/csp_allowed_host_frequency.sql
  sql/2022/third-parties/distribution_of_3XX_response_body_size.sql
  sql/2022/third-parties/distribution_of_lighthouse_unminified_css_by_3p.sql
  sql/2022/third-parties/distribution_of_lighthouse_unminified_js_by_3p.sql
  sql/2022/third-parties/distribution_of_lighthouse_uses_optimized_images_by_3p.sql
  sql/2022/third-parties/distribution_of_size_and_time_by_third_parties.sql
  sql/2022/third-parties/distribution_of_third_parties_by_number_of_websites.sql
  sql/2022/third-parties/distribution_of_websites_by_number_of_third_parties.sql
  sql/2022/third-parties/iframe_allow_attribute.sql
  sql/2022/third-parties/iframe_attribute_popular_hosts.sql
  sql/2022/third-parties/lighthouse_unminified_css_by_3p.sql
  sql/2022/third-parties/lighthouse_unminified_js_by_3p.sql
  sql/2022/third-parties/lighthouse_unminified_uses_optimized_images_by_3p.sql
  sql/2022/third-parties/number_of_third_parties_by_rank.sql
  sql/2022/third-parties/number_of_third_parties_by_rank_and_category.sql
  sql/2022/third-parties/percent_of_third_parties_by_content_type.sql
  sql/2022/third-parties/percent_of_third_parties_using_document_write.sql
  sql/2022/third-parties/percent_of_third_parties_using_legacy_javascript.sql
  sql/2022/third-parties/percent_of_third_parties_using_unload_listener.sql
  sql/2022/third-parties/percent_of_third_party_cache.sql
  sql/2022/third-parties/percent_of_third_party_requests_and_bytes_by_category_and_content_type.sql
  sql/2022/third-parties/percent_of_third_party_with_security_headers.sql
  sql/2022/third-parties/percent_of_websites_with_third_party.sql
  sql/2022/third-parties/percent_of_websites_with_third_party_by_ranking.sql
  sql/2022/third-parties/tao_by_third_party.sql
  sql/2022/third-parties/third_parties_blocking_main_thread.sql
  sql/2022/third-parties/third_parties_blocking_main_thread_percentiles.sql
  sql/2022/third-parties/third_parties_blocking_rendering.sql
  sql/2022/third-parties/third_parties_blocking_rendering_percentiles.sql
  sql/2022/third-parties/top100_third_parties_by_median_body_size_and_time.sql
  sql/2022/third-parties/top100_third_parties_by_number_of_websites.sql
  sql/2022/third-parties/usage_of_lite_youtube_embed.sql
  sql/2022/third-parties/usage_of_partytown.sql
Labels: analysis

#3031 Pin werkzeug to work around bug
  src/requirements.txt
Labels: bug, development

#2941 Caching 2022 queries
  sql/2022/caching/cache_control_directives.sql
  sql/2022/caching/cache_control_directives_invalid.sql
  sql/2022/caching/cache_ttl_and_content_age_diff.sql
  sql/2022/caching/cache_ttl_lighthouse_score.sql
  sql/2022/caching/cache_wastedbytes_lighthouse.sql
  sql/2022/caching/content_age_older_than_ttl.sql
  sql/2022/caching/content_age_older_than_ttl_by_party.sql
  sql/2022/caching/cookie_attributes.sql
  sql/2022/caching/cookie_names.sql
  sql/2022/caching/header_trends.sql
  sql/2022/caching/invalid_last_modified_and_expires_and_date.sql
  sql/2022/caching/max_age_distribution.sql
  sql/2022/caching/non_cacheable_by_resource_type.sql
  sql/2022/caching/resource_age_party_and_type_wise.sql
  sql/2022/caching/resource_age_party_and_type_wise_groups.sql
  sql/2022/caching/service_worker_rank.sql
  sql/2022/caching/set_cookie.sql
  sql/2022/caching/top_cdns.sql
  sql/2022/caching/top_hosts_using_immutable.sql
  sql/2022/caching/ttl.sql
  sql/2022/caching/ttl_by_resource.sql
  sql/2022/caching/valid_if_modified_since_returns_304.sql
  sql/2022/caching/valid_if_none_match_returns_304.sql
  sql/2022/caching/vary_directives.sql
Labels: analysis

#3029 Translation of Resource Hints chapter to Japanese
  src/content/ja/2021/resource-hints.md
Labels: translation

#3037 Security 2022 query fixes
  sql/2022/security/robot_header_and_meta_tag_prevalence.sql
  sql/2022/security/robot_txt_sensitive_disallow.sql
  sql/2022/security/security_headers_prevalence.sql
  sql/2022/security/server_information_header_prevalence.sql
  sql/2022/security/version-evolution-top-technologies.sql
  sql/2022/security/well-known_change-password.sql
  sql/2022/security/well-known_resource-not-be-200.sql
Labels: analysis

#2939 HTTP 2022 queries
  sql/2022/http/connections_per_page_load_dist.sql
  sql/2022/http/early_hints_per_page.sql
  sql/2022/http/h2_adoption_by_cdn_pct.sql
  sql/2022/http/h2_adoption_pages_reqs.sql
  sql/2022/http/h2_adoption_reqs_dist.sql
  sql/2022/http/h2_h3_pushed.sql
  sql/2022/http/priority_hints_per_page.sql
Labels: analysis

#3040 Fix sheet GID for focus_outline_0.sql figure of 2021 accessibility chapter
  src/content/en/2021/accessibility.md
Labels: editing

#3039 Fix sheets GID & SQL file name for video_track_usage figure of 2021 accessibility chapter
  src/content/en/2021/accessibility.md
Labels: editing

#3041 Mobile Web 2022 queries
  sql/2022/mobile-web/README.md
  sql/2022/mobile-web/client_hints.sql
  sql/2022/mobile-web/color_contrast.sql
  sql/2022/mobile-web/correctly_sized_images.sql
  sql/2022/mobile-web/credential_management_api_usage.sql
  sql/2022/mobile-web/ecommerce_with_type_search.sql
  sql/2022/mobile-web/lazy_loading_usage.sql
  sql/2022/mobile-web/mobile_greater_than_desktop.sql
  sql/2022/mobile-web/mobile_traffic_distribution.sql
  sql/2022/mobile-web/most_used_tech.sql
  sql/2022/mobile-web/most_used_tech_by_domain_rank.sql
  sql/2022/mobile-web/navigator_device_memory_usage.sql
  sql/2022/mobile-web/network_info_effective_type_usage.sql
  sql/2022/mobile-web/optimal_type_used_for_email_and_phone.sql
  sql/2022/mobile-web/payment_request_api_usage.sql
  sql/2022/mobile-web/picture_source_srcset_usage.sql
  sql/2022/mobile-web/popular_input_attributes.sql
  sql/2022/mobile-web/popular_link_protocols.sql
  sql/2022/mobile-web/popular_mobile_input_types.sql
  sql/2022/mobile-web/service_worker.sql
  sql/2022/mobile-web/tap_targets.sql
  sql/2022/mobile-web/tap_targets_by_domain_rank.sql
  sql/2022/mobile-web/usage_of_advanced_input_types.sql
  sql/2022/mobile-web/viewport_zoom_scale.sql
  sql/2022/mobile-web/viewport_zoom_scale_by_domain_rank.sql
Labels: analysis

#3042 Translation of http chapter to Japanese
  src/content/ja/2021/http.md
Labels: translation

#3046 Fix translations for 3039 and 3040
  src/content/ja/2021/accessibility.md
Labels: translation

#3027 Compression 2022 Queries
  sql/2022/compression/README.md
  sql/2022/compression/compression_by_content_type.sql
  sql/2022/compression/compression_format_trend.sql
  sql/2022/compression/compression_formats.sql
  sql/2022/compression/compression_formats_text_responses.sql
  sql/2022/compression/first_vs_third_party.sql
  sql/2022/compression/lighthouse_compression_byte_savings.sql
  sql/2022/compression/lighthouse_compression_scores.sql
Labels: analysis

#3045 Enable Japanese 2021 ebook
  src/config/2021.json
  src/config/last_updated.json
  src/static/pdfs/web_almanac_2021_ja.pdf
  src/static/pdfs/web_almanac_2021_ja_cover_A5.pdf
  src/static/pdfs/web_almanac_2021_ja_print_A5.pdf
Labels: translation

#3044 Fix broken inline links
  .github/linters/.markdown-lint.yml
  src/content/en/2019/media.md
  src/content/en/2019/performance.md
  src/content/en/2021/pwa.md
  src/content/es/2019/fonts.md
  src/content/es/2019/media.md
  src/content/es/2019/performance.md
  src/content/fr/2019/fonts.md
  src/content/fr/2019/media.md
  src/content/fr/2020/performance.md
  src/content/ja/2019/fonts.md
  src/content/ja/2019/media.md
  src/content/ja/2019/performance.md
  src/content/ja/2020/css.md
  src/content/ja/2020/ecommerce.md
  src/content/ja/2020/http.md
  src/content/ja/2020/markup.md
  src/content/ja/2020/mobile-web.md
  src/content/ja/2020/performance.md
  src/content/ja/2020/pwa.md
  src/content/ja/2020/resource-hints.md
  src/content/ja/2020/security.md
  src/content/ja/2020/third-parties.md
  src/content/ja/2021/accessibility.md
  src/content/ja/2021/cdn.md
  src/content/ja/2021/javascript.md
  src/content/ja/2021/markup.md
  src/content/ja/2021/privacy.md
  src/content/ja/2021/pwa.md
  src/content/ja/2021/security.md
  src/content/nl/2020/performance.md
  src/content/pt/2020/css.md
  src/content/ru/2020/css.md
  src/content/ru/2021/pwa.md
  src/content/zh-CN/2019/performance.md
  src/content/zh-CN/2020/performance.md
  src/content/zh-TW/2020/performance.md
Labels: translation, editing

#3049 Fix labelling of valid_html_lang query results across 2020 and 2021 accessibility chapters
  src/content/en/2020/accessibility.md
  src/content/en/2021/accessibility.md
  src/content/ja/2020/accessibility.md
  src/content/ja/2021/accessibility.md
  src/content/nl/2020/accessibility.md
Labels: editing

#3051 Hide methodology from ebook if not translated
  src/templates/base/base_ebook.html
Labels: development, translation

#2980 CMS 2022 Queries
  sql/2022/cms/cms_adoption.sql
  sql/2022/cms/cms_adoption_by_geo.sql
  sql/2022/cms/cms_adoption_by_rank.sql
  sql/2022/cms/cms_adoption_by_region.sql
  sql/2022/cms/cms_adoption_by_subregion.sql
  sql/2022/cms/core_web_vitals.sql
  sql/2022/cms/core_web_vitals_by_geo.sql
  sql/2022/cms/core_web_vitals_yoy.sql
  sql/2022/cms/image_format_popularity.sql
  sql/2022/cms/lighthouse_category_scores_per_cms.sql
  sql/2022/cms/page_weight_distribution.sql
  sql/2022/cms/resource_weights.sql
  sql/2022/cms/top_cms.sql
  sql/2022/cms/top_cms_by_geo.sql
  sql/2022/cms/top_cms_by_rank.sql
  sql/2022/cms/wordpress_page_builders.sql
  sql/2022/cms/wordpress_resources.sql
Labels: analysis

#3052 Security 2022 query fixes vol. 2
  sql/2022/security/cookie_age_negative.sql
  sql/2022/security/cookie_age_percentiles.sql
  sql/2022/security/well-known_change-password.sql
  sql/2022/security/well-known_resource-not-be-200.sql
Labels: analysis

#3055 Add client to PWA Lighthouse audit report
  sql/2022/pwa/lighthouse_pwa_audits.sql
  sql/2022/pwa/lighthouse_pwa_score.sql
Labels: analysis

#3060 2022 Capabilities queries
  sql/2022/capabilities/fugu.sql
  sql/2022/capabilities/top.sql
Labels: analysis

#3061 Restrict translation lenth checks to content
  .github/workflows/check-translations-lengths.yml
Labels: development

#2958 Ecommerce 2022 queries
  sql/2022/ecommerce/README.md
  sql/2022/ecommerce/core_web_vitals_distribution_byvendor_bydevice.sql
  sql/2022/ecommerce/core_web_vitals_passingmetrics_byvendor_bydevice.sql
  sql/2022/ecommerce/ecomm_growth.sql
  sql/2022/ecommerce/ecomm_vendors_growth.sql
  sql/2022/ecommerce/median_lighthouse_score_ecommsites.sql
  sql/2022/ecommerce/pagestats_html_bydevice.sql
  sql/2022/ecommerce/pagestats_image_bydevice.sql
  sql/2022/ecommerce/pagestats_image_bydevice_format.sql
  sql/2022/ecommerce/pagestats_percentiles_bydevice.sql
  sql/2022/ecommerce/pct_3pusage_bydevice.sql
  sql/2022/ecommerce/pct_3pusage_bydevice_vendor.sql
  sql/2022/ecommerce/pct_ampusage_bydevice_vendor.sql
  sql/2022/ecommerce/pct_ecommsites_bydevice_compare20212022.sql
  sql/2022/ecommerce/percent_of_ecommsites_using_cmp.sql
  sql/2022/ecommerce/percent_of_ecommsites_using_each_tag_managers.sql
  sql/2022/ecommerce/top_analytics_providers_bydevice_wapp.sql
  sql/2022/ecommerce/top_cdn_bydevice_vendor_cdn.sql
  sql/2022/ecommerce/top_cdn_bydevice_vendor_wapp.sql
  sql/2022/ecommerce/top_jsframework_providers_by_device.sql
  sql/2022/ecommerce/top_jslibs_by_device.sql
  sql/2022/ecommerce/top_vendors.sql
  sql/2022/ecommerce/top_vendors_crux_rank.sql
  sql/2022/ecommerce/webpushstats_ecommsites.sql
Labels: analysis

#3064 Linting fixes for already merged queries.
  sql/2022/css/all_properties.sql
  sql/2022/css/box_sizing_border_box_selectors.sql
  sql/2022/css/calc_operators.sql
  sql/2022/css/calc_properties.sql
  sql/2022/css/calc_units.sql
  sql/2022/css/color_alpha_functions.sql
  sql/2022/css/color_formats.sql
  sql/2022/css/color_p3.sql
  sql/2022/css/css_in_js.sql
  sql/2022/css/custom_property_adoption.sql
  sql/2022/css/custom_property_depth.sql
  sql/2022/css/custom_property_functions.sql
  sql/2022/css/custom_property_names.sql
  sql/2022/css/custom_property_properties.sql
  sql/2022/css/custom_property_value_types.sql
  sql/2022/css/effects_blend_mode_popularity.sql
  sql/2022/css/flexbox_grid.sql
  sql/2022/css/gradient_adoption.sql
  sql/2022/css/gradient_functions.sql
  sql/2022/css/houdini_paint_worklets.sql
  sql/2022/css/i18n_dir_html_elements.sql
  sql/2022/css/i18n_logical_properties.sql
  sql/2022/css/i18n_physical_properties.sql
  sql/2022/css/keyword_totals.sql
  sql/2022/css/layout_properties.sql
  sql/2022/css/media_query_features.sql
  sql/2022/css/media_query_properties.sql
  sql/2022/css/media_query_responsive.sql
  sql/2022/css/media_query_values.sql
  sql/2022/css/meta_important_properties.sql
  sql/2022/css/meta_shorthand_first_properties.sql
  sql/2022/css/multicol.sql
  sql/2022/css/print_page_properties.sql
  sql/2022/css/print_page_pseudo_classes.sql
  sql/2022/css/print_stylesheet_adoption.sql
  sql/2022/css/ruby_adoption.sql
  sql/2022/css/sass_animated_custom_properties.sql
  sql/2022/css/sass_combined_variable_names.sql
  sql/2022/css/sass_combined_variables_distribution.sql
  sql/2022/css/sass_combined_variables_pages.sql
  sql/2022/css/sass_control_flow_statements.sql
  sql/2022/css/sass_custom_function_calls.sql
  sql/2022/css/sass_custom_function_names.sql
  sql/2022/css/sass_custom_functions.sql
  sql/2022/css/sass_function_calls.sql
  sql/2022/css/sass_mixin_calls.sql
  sql/2022/css/sass_mixin_names.sql
  sql/2022/css/sass_nesting.sql
  sql/2022/css/sass_variable_usage.sql
  sql/2022/css/supports_criteria.sql
  sql/2022/css/supports_properties.sql
  sql/2022/css/top_selector_classes_wp_fa_prefixes.sql
  sql/2022/css/top_selector_ids.sql
  sql/2022/css/top_selector_pseudo_classes.sql
  sql/2022/css/transition_animation_names.sql
  sql/2022/css/transition_properties.sql
  sql/2022/css/transition_timing_functions.sql
  sql/2022/css/units_frequency.sql
  sql/2022/ecommerce/pct_ecommsites_bydevice_compare20212022.sql
Labels: analysis

#2987 SEO 2022 Queries
  sql/2022/seo/anchor-rel-attribute-usage.sql
  sql/2022/seo/anchor-same-site-occurance-stats.sql
  sql/2022/seo/content-language-usage.sql
  sql/2022/seo/core-web-vitals.sql
  sql/2022/seo/hreflang-header-usage.sql
  sql/2022/seo/hreflang-link-tag-usage.sql
  sql/2022/seo/html-response-content-language.sql
  sql/2022/seo/html-response-vary-header-used.sql
  sql/2022/seo/iframe-loading-property-usage.sql
  sql/2022/seo/image-alt-stats.sql
  sql/2022/seo/image-loading-property-usage.sql
  sql/2022/seo/lighthouse-seo-stats.sql
  sql/2022/seo/lighthouse_unused_css_js_by_rank.sql
  sql/2022/seo/markup-stats.sql
  sql/2022/seo/media-property-usage-link-tags-rel-alternate.sql
  sql/2022/seo/meta-tag-usage-by-name.sql
  sql/2022/seo/meta-tag-usage-by-property.sql
  sql/2022/seo/outgoing_links_by_rank.sql
  sql/2022/seo/pages-canonical-stats.sql
  sql/2022/seo/pages-containing-a-video-element.sql
  sql/2022/seo/robots-meta-usage.sql
  sql/2022/seo/robots-text-size.sql
  sql/2022/seo/robots-txt-status-codes.sql
  sql/2022/seo/robots-txt-user-agent-usage-by-rank.sql
  sql/2022/seo/robots-txt-user-agent-usage.sql
  sql/2022/seo/seo-stats-by-percentile.sql
  sql/2022/seo/seo-stats.sql
  sql/2022/seo/structured-data-formats.sql
  sql/2022/seo/structured-data-schema-types.sql
  sql/2022/seo/valid-head-elements.sql
  sql/2022/seo/videos-per-page.sql
Labels: analysis

#3065 Add noqa for SEO 2022 queries
  sql/2022/seo/anchor-rel-attribute-usage.sql
  sql/2022/seo/anchor-same-site-occurance-stats.sql
  sql/2022/seo/content-language-usage.sql
  sql/2022/seo/hreflang-header-usage.sql
  sql/2022/seo/hreflang-link-tag-usage.sql
  sql/2022/seo/html-response-content-language.sql
  sql/2022/seo/html-response-vary-header-used.sql
  sql/2022/seo/iframe-loading-property-usage.sql
  sql/2022/seo/image-alt-stats.sql
  sql/2022/seo/image-loading-property-usage.sql
  sql/2022/seo/lighthouse-seo-stats.sql
  sql/2022/seo/lighthouse_unused_css_js_by_rank.sql
  sql/2022/seo/markup-stats.sql
  sql/2022/seo/media-property-usage-link-tags-rel-alternate.sql
  sql/2022/seo/meta-tag-usage-by-name.sql
  sql/2022/seo/meta-tag-usage-by-property.sql
  sql/2022/seo/outgoing_links_by_rank.sql
  sql/2022/seo/pages-canonical-stats.sql
  sql/2022/seo/pages-containing-a-video-element.sql
  sql/2022/seo/robots-meta-usage.sql
  sql/2022/seo/robots-text-size.sql
  sql/2022/seo/robots-txt-status-codes.sql
  sql/2022/seo/robots-txt-user-agent-usage-by-rank.sql
  sql/2022/seo/robots-txt-user-agent-usage.sql
  sql/2022/seo/seo-stats-by-percentile.sql
  sql/2022/seo/seo-stats.sql
  sql/2022/seo/structured-data-formats.sql
  sql/2022/seo/structured-data-schema-types.sql
  sql/2022/seo/valid-head-elements.sql
  sql/2022/seo/videos-per-page.sql
Labels: analysis

#3057 Accessibility 2022 queries
  sql/2022/accessibility/README.md
  sql/2022/accessibility/a11y_overall_tech_usage_by_domain_rank.sql
  sql/2022/accessibility/a11y_technology_usage.sql
  sql/2022/accessibility/a11y_technology_usage_by_domain_rank.sql
  sql/2022/accessibility/alt_ending_in_image_extension.sql
  sql/2022/accessibility/anchors_with_role_button.sql
  sql/2022/accessibility/audio_track_usage.sql
  sql/2022/accessibility/button_name_sources.sql
  sql/2022/accessibility/captcha_usage.sql
  sql/2022/accessibility/color_contrast.sql
  sql/2022/accessibility/common_alt_text_length.sql
  sql/2022/accessibility/common_aria_role.sql
  sql/2022/accessibility/common_element_attributes.sql
  sql/2022/accessibility/focus_outline_0.sql
  sql/2022/accessibility/focus_visible.sql
  sql/2022/accessibility/form_input_name_sources.sql
  sql/2022/accessibility/form_required_controls.sql
  sql/2022/accessibility/landmark_elements_and_roles.sql
  sql/2022/accessibility/lighthouse_a11y_audits.sql
  sql/2022/accessibility/lighthouse_a11y_score.sql
  sql/2022/accessibility/media_query_features.sql
  sql/2022/accessibility/page_title.sql
  sql/2022/accessibility/pages_with_search_input.sql
  sql/2022/accessibility/placeholder_but_no_label.sql
  sql/2022/accessibility/sites_using_role.sql
  sql/2022/accessibility/skip_links.sql
  sql/2022/accessibility/sr_only_classes.sql
  sql/2022/accessibility/tabindex_usage_and_values.sql
  sql/2022/accessibility/table_stats.sql
  sql/2022/accessibility/units_properties.sql
  sql/2022/accessibility/valid_html_lang.sql
  sql/2022/accessibility/video_track_usage.sql
  sql/2022/accessibility/viewport_zoom_scale.sql
  sql/2022/accessibility/viewport_zoom_scale_by_domain_rank.sql
Labels: analysis

#3056 More Mobile web 2022 sql queries
  sql/2022/mobile-web/web_vitals_by_device.sql
Labels: analysis

#2947 Interoperability 2022 queries
  sql/2022/css/layer.sql
  sql/2022/interop/README.md
  sql/2022/interop/align_items_values.sql
  sql/2022/interop/align_values.sql
  sql/2022/interop/aspect_ratio.sql
  sql/2022/interop/backdrop.sql
  sql/2022/interop/cascade_layers.sql
  sql/2022/interop/color_functions.sql
  sql/2022/interop/color_spaces.sql
  sql/2022/interop/contain.sql
  sql/2022/interop/contain_values.sql
  sql/2022/interop/container.sql
  sql/2022/interop/dialog.sql
  sql/2022/interop/flex_basis_content.sql
  sql/2022/interop/flexbox_trends.sql
  sql/2022/interop/justify_content_values.sql
  sql/2022/interop/layer_adoption.sql
  sql/2022/interop/layer_per_page.sql
  sql/2022/interop/perspective_none.sql
  sql/2022/interop/position_sticky.sql
  sql/2022/interop/subgrid.sql
  sql/2022/interop/transform_style_preserve_3d.sql
  sql/2022/interop/viewport_units.sql
Labels: analysis

#3068 Additional queries for Third Parties
  sql/2022/third-parties/percent_of_third_parties_using_legacy_javascript_by_url.sql
  sql/2022/third-parties/scripts_using_async_defer.sql
  sql/2022/third-parties/scripts_using_async_defer_by_3p.sql
Labels: analysis

#3071 Restrict Sample words in queries
  sql/.sqlfluff
  sql/2020/css/css_in_js_frameworks_only.sql
  sql/2021/cdn/distribution_of_http_versions.sql
  sql/2022/seo/valid-head-elements.sql
Labels: development

#3069 Hero images for new 2022 chapters
  src/static/images/2022/interoperability/hero_lg.avif
  src/static/images/2022/interoperability/hero_lg.jpg
  src/static/images/2022/interoperability/hero_lg.webp
  src/static/images/2022/interoperability/hero_sm.avif
  src/static/images/2022/interoperability/hero_sm.jpg
  src/static/images/2022/interoperability/hero_sm.webp
  src/static/images/2022/interoperability/hero_xl.jpg
  src/static/images/2022/sustainability/hero_lg.avif
  src/static/images/2022/sustainability/hero_lg.jpg
  src/static/images/2022/sustainability/hero_lg.webp
  src/static/images/2022/sustainability/hero_sm.avif
  src/static/images/2022/sustainability/hero_sm.jpg
  src/static/images/2022/sustainability/hero_sm.webp
  src/static/images/2022/sustainability/hero_xl.jpg
Labels: design

#2992 Jamstack 2022 Queries
  sql/2022/jamstack/README.md
  sql/2022/jamstack/distribution_cls_desktop.sql
  sql/2022/jamstack/distribution_cls_mobile.sql
  sql/2022/jamstack/distribution_lcp_desktop.sql
  sql/2022/jamstack/distribution_lcp_mobile.sql
  sql/2022/jamstack/jamstack_cdns.sql
  sql/2022/jamstack/jamstack_counts.sql
  sql/2022/jamstack/jamstack_counts_by_rank.sql
  sql/2022/jamstack/jamstack_javascript_frameworks.sql
  sql/2022/jamstack/jamstack_paas.sql
  sql/2022/jamstack/jamstack_paas_yoy.sql
  sql/2022/jamstack/jamstack_random_1000_urls.sql
  sql/2022/jamstack/jamstack_sites.sql
  sql/2022/jamstack/jamstack_ssgs.sql
  sql/2022/jamstack/jamstack_web_frameworks.sql
  sql/2022/jamstack/percentage_cacheable_by_year.sql
  sql/2022/jamstack/percentage_cls_by_year.sql
  sql/2022/jamstack/percentage_lcp_by_year.sql
Labels: analysis

#3072 Add Michelle to Designers team for 2022
  src/config/2022.json
Labels: project management

#2974 Performance 2022 Queries
  sql/2022/performance/README.md
  sql/2022/performance/correlation_preload_lcp.sql
  sql/2022/performance/gaming_metric.sql
  sql/2022/performance/inp_long_tasks.sql
  sql/2022/performance/lcp_element_data.sql
  sql/2022/performance/lcp_element_data_2.sql
  sql/2022/performance/lcp_host.sql
  sql/2022/performance/lcp_preload.sql
  sql/2022/performance/lcp_resource_delay.sql
  sql/2022/performance/lcp_responsive_data.sql
  sql/2022/performance/prelcp_domain_sharding.sql
  sql/2022/performance/ttfb_by_cms.sql
  sql/2022/performance/ttfb_by_rendering.sql
  sql/2022/performance/viewport_meta_zoom_disable.sql
  sql/2022/performance/web_vitals_by_country.sql
  sql/2022/performance/web_vitals_by_device.sql
  sql/2022/performance/web_vitals_by_eff_connection_type.sql
  sql/2022/performance/web_vitals_by_rank.sql
  sql/2022/performance/web_vitals_by_rank_and_device.sql
Labels: analysis

#3074 Additional Performance 2022 queries
  sql/2022/performance/lcp_discoverability.sql
Labels: analysis

#2938 Fonts 2022 queries
  sql/2022/fonts/color_font_usage.sql
  sql/2022/fonts/color_fonts.sql
  sql/2022/fonts/color_fonts_emoji_usage.sql
  sql/2022/fonts/font_display_usage.sql
  sql/2022/fonts/font_feature_settings_vs_font_variant.sql
  sql/2022/fonts/font_format_usage.sql
  sql/2022/fonts/font_metric_override_usage.sql
  sql/2022/fonts/font_opentype_features_usage.sql
  sql/2022/fonts/font_palettes.sql
  sql/2022/fonts/font_palettes_colors.sql
  sql/2022/fonts/font_size_quantiles.sql
  sql/2022/fonts/font_size_quantiles_by_opentype_table.sql
  sql/2022/fonts/font_size_quantiles_without_services.sql
  sql/2022/fonts/font_smoothing_usage.sql
  sql/2022/fonts/font_usage_by_service.sql
  sql/2022/fonts/font_usage_over_time.sql
  sql/2022/fonts/font_writing_scripts.sql
  sql/2022/fonts/outline_formats.sql
  sql/2022/fonts/popular_font_families_by_vendor.sql
  sql/2022/fonts/popular_font_vendors.sql
  sql/2022/fonts/popular_typeface.sql
  sql/2022/fonts/resource_hints_usage.sql
  sql/2022/fonts/types_of_variable_font.sql
  sql/2022/fonts/usage_by_country.sql
  sql/2022/fonts/usage_of_font_loading_api.sql
  sql/2022/fonts/usage_of_system_families.sql
  sql/2022/fonts/variable_font_animation.sql
  sql/2022/fonts/variable_font_axes.sql
  sql/2022/fonts/variable_font_googlefonts_vs_other.sql
  sql/2022/fonts/variable_font_usage.sql
  sql/lib/css-font-parser.js
  sql/lib/text-utils.js
Labels: analysis

#3073 Additional CSS 2022 queries
  sql/2022/css/content_values.sql
  sql/2022/css/lcp_initiator_type.sql
  sql/2022/css/print_all_properties.sql
  sql/2022/css/top_selector_pseudo_elements.sql
  sql/2022/css/units_gtc_percent.sql
  sql/2022/performance/lcp_initiator_type.sql
Labels: analysis

#3028 CDN 2022 queries
  sql/2022/cdn/README.md
  sql/2022/cdn/cdn_usage_by_site_rank.sql
  sql/2022/cdn/distribution_of_compression_types_by_cdn.sql
  sql/2022/cdn/distribution_of_compression_types_cdn_vs_origin.sql
  sql/2022/cdn/distribution_of_http_versions.sql
  sql/2022/cdn/distribution_of_http_versions_cdn_vs_origin.sql
  sql/2022/cdn/distribution_of_tls_time_by_cdn.sql
  sql/2022/cdn/distribution_of_tls_time_cdn_vs_origin.sql
  sql/2022/cdn/distribution_of_tls_versions.sql
  sql/2022/cdn/distribution_of_tls_versions_cdn_vs_origin.sql
  sql/2022/cdn/top_cdns.sql
  sql/2022/cdn/top_cdns_by_rank.sql
  sql/2022/cdn/usage_of_content_cdns.sql
Labels: analysis

#2953 Page Weight 2022 queries
  sql/2022/page-weight/README.md
  sql/2022/page-weight/bytes_per_type.sql
  sql/2022/page-weight/compression-usage.sql
  sql/2022/page-weight/facades-usage.sql
  sql/2022/page-weight/minified_css_usage.sql
  sql/2022/page-weight/minified_js_usage.sql
  sql/2022/page-weight/page_weight_trend.sql
  sql/2022/page-weight/request_type_distribution.sql
  sql/2022/page-weight/response_format_distribution.sql
  sql/2022/page-weight/response_type_distribution.sql
Labels: analysis

#2989 Sustainability 2022 Queries
  sql/2022/sustainability/cache_header_usage.sql
  sql/2022/sustainability/cdn_adoption.sql
  sql/2022/sustainability/cms_bytes_per_type.sql
  sql/2022/sustainability/ecommerce_bytes_per_type.sql
  sql/2022/sustainability/green_third_party_requests.sql
  sql/2022/sustainability/green_web_hosting.sql
  sql/2022/sustainability/image_formats.sql
  sql/2022/sustainability/image_lazy_loading.sql
  sql/2022/sustainability/page_bytes_per_type.sql
  sql/2022/sustainability/requests_by_type.sql
  sql/2022/sustainability/responsive_images.sql
  sql/2022/sustainability/script_count.sql
  sql/2022/sustainability/ssg_bytes_per_type.sql
  sql/2022/sustainability/stylesheet_count.sql
  sql/2022/sustainability/text_compression.sql
  sql/2022/sustainability/unminified_css_bytes.sql
  sql/2022/sustainability/unminified_js_bytes.sql
  sql/2022/sustainability/unused_css_bytes.sql
  sql/2022/sustainability/unused_js_bytes.sql
  sql/2022/sustainability/video_autoplay_values.sql
  sql/2022/sustainability/video_preload_values.sql
Labels: analysis

#3079 More CSS 2022 queries
  sql/2022/css/all_functions.sql
  sql/2022/css/top_selector_attributes.sql
  sql/2022/css/top_selector_pseudo_classes_after_technologies.sql
Labels: analysis

#2951 WebAssembly 2022 queries
  sql/2022/webassembly/README.md
  sql/2022/webassembly/counts.sql
  sql/2022/webassembly/cross_domain.sql
  sql/2022/webassembly/domains.sql
  sql/2022/webassembly/language_usage.sql
  sql/2022/webassembly/module_sizes.sql
  sql/2022/webassembly/page_rankings.sql
  sql/2022/webassembly/popular_by_name.sql
  sql/2022/webassembly/proposals.sql
  sql/2022/webassembly/section_sizes.sql
Labels: analysis

#2979 Media 2022 queries
  sql/2022/media/README.md
  sql/2022/media/animated_gif_count.sql
  sql/2022/media/animated_gif_framecount.sql
  sql/2022/media/at_least_one_image_request.sql
  sql/2022/media/at_least_one_img.sql
  sql/2022/media/bytes_and_dimensions.sql
  sql/2022/media/bytes_and_dimensions_by_format.sql
  sql/2022/media/color_spaces_and_depth.sql
  sql/2022/media/image_0x0.sql
  sql/2022/media/image_1x1.sql
  sql/2022/media/image_alt.sql
  sql/2022/media/image_cdn_usage.sql
  sql/2022/media/image_decode_usage.sql
  sql/2022/media/image_layout_widths.sql
  sql/2022/media/image_sizes_attribute_strings.sql
  sql/2022/media/image_sizes_per_page_accuracy_impact.sql
  sql/2022/media/image_sizing_extrinsic_intrinsic.sql
  sql/2022/media/image_srcset_candidates.sql
  sql/2022/media/image_srcset_densities.sql
  sql/2022/media/image_srcset_descriptor.sql
  sql/2022/media/image_srcset_sizes.sql
  sql/2022/media/image_srcset_sizes_accuracy_pct.sql
  sql/2022/media/image_srcset_sizes_per_image_accuracy_impact.sql
  sql/2022/media/img_sizes_explicit_errors.sql
  sql/2022/media/img_with_dimensions.sql
  sql/2022/media/img_xdomain.sql
  sql/2022/media/imgs_per_page.sql
  sql/2022/media/lazy_loading_adoption_over_time.sql
  sql/2022/media/lcp_element_data.sql
  sql/2022/media/media_formats.sql
  sql/2022/media/picture_distribution.sql
  sql/2022/media/picture_format_distribution.sql
  sql/2022/media/picture_orientation.sql
  sql/2022/media/picture_switching.sql
  sql/2022/media/picture_using_min_resolution.sql
  sql/2022/media/pixel_volume.sql
  sql/2022/media/portrait_landscape_square.sql
  sql/2022/media/score_progressive_jpeg.sql
  sql/2022/media/srcset_density_coverage.sql
  sql/2022/media/top_aspect_ratios.sql
  sql/2022/media/video_adoption.sql
  sql/2022/media/video_attribute_count.sql
  sql/2022/media/video_attribute_names.sql
  sql/2022/media/video_attribute_widths.sql
  sql/2022/media/video_autoplay_muted.sql
  sql/2022/media/video_durations.sql
  sql/2022/media/video_ext.sql
  sql/2022/media/video_number_of_sources.sql
  sql/2022/media/video_preload_values.sql
  sql/2022/media/video_source_formats.sql
  sql/2022/media/video_source_types.sql
  sql/2022/media/video_styles.sql
  sql/2022/media/video_tag_and_js_player.sql
Labels: analysis

#3081 HTTP 2022 additional queries
  sql/2022/http/h2_adoption_each_cdn_breakdown.sql
  sql/2022/http/protocol_advertised_via_altsvc.sql
  sql/2022/http/sites_using_link_preload.sql
  sql/2022/http/sites_with_altsvc.sql
Labels: analysis

#3083 Some more 2022 ecommerce changes
  sql/2022/ecommerce/percent_of_ecommsites_using_csp.sql
  sql/2022/ecommerce/top_vendors_crux_rank.sql
  sql/2022/ecommerce/webpush_adoption_ecommsites.sql
Labels: analysis

#3084 Add some more early hints queries to HTTP chapter
  sql/2022/http/early_hints_per_page.sql
  sql/2022/http/early_hints_usage.sql
  sql/2022/http/priority_hints_usage.sql
Labels: analysis

#3088 Additional Interop 2022 queries
  sql/2022/interop/flex_basis_content_2021.sql
Labels: analysis

#3090 2022 SEO SQL updates
  sql/2022/seo/html-response-vary-header-used.sql
  sql/2022/seo/invalid-head-elements.sql
  sql/2022/seo/invalid-head-sites.sql
  sql/2022/seo/lighthouse-seo-stats.sql
  sql/2022/seo/lighthouse_unused_css_js_by_rank.sql
  sql/2022/seo/outgoing_links_by_rank.sql
  sql/2022/seo/robots-txt-user-agent-usage-by-rank.sql
  sql/2022/seo/valid-head-elements.sql
  sql/2022/seo/videos-per-page.sql
Labels: analysis

#3093 More 2022 Jamstack SQL tweaks
  sql/2022/jamstack/distribution_cls_desktop.sql
  sql/2022/jamstack/distribution_cls_mobile.sql
  sql/2022/jamstack/distribution_lcp_desktop.sql
  sql/2022/jamstack/distribution_lcp_mobile.sql
  sql/2022/jamstack/median_lcp_and_cls.sql
  sql/2022/jamstack/percentage_cacheable_by_year.sql
  sql/2022/jamstack/percentage_cls_by_year.sql
  sql/2022/jamstack/percentage_jamstack_criteria_per_year.sql
  sql/2022/jamstack/percentage_lcp_by_year.sql
Labels: analysis

#3096 More CSS 2022 queries
  sql/2022/css/supports_adoption.sql
Labels: analysis
