Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2022-12, with the labels that each got.

#3302 Handle no Methodology translation
  src/server/__init__.py
  src/server/helpers.py
  src/server/tests/helpers_test.py
  src/templates/base/base.html
  src/templates/base/table_of_contents.html
Labels: development

#3303 Adds Share CTA and Reaction count
  src/static/css/page.css
  src/static/js/almanac.js
  src/static/js/webmentions.js
  src/templates/base.html
  src/templates/base/base_chapter.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/tr/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: development, design

#3305 Fix casing of Reactions section
  src/templates/base/base_chapter.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/tr/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: bug, development

#3306 Fix 2022 Performance typo
  src/content/en/2022/performance.md
Labels: editing

#3308 Minor edits to Sustainability chapter
  src/content/en/2022/sustainability.md
  src/static/images/2022/sustainability/carbon-emissions-by-percentile.png
  src/static/images/2022/sustainability/total-carbon-emissions-by-percentile.png
Labels: editing

#3310 Translation of javascript chapter to Japanese
  src/config/2022.json
  src/content/en/2022/javascript.md
  src/content/ja/2022/javascript.md
Labels: translation
