Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2022-11, with the labels that each got.

#3267 Fix SEO Structured Data issue
  src/content/en/2022/seo.md
  src/static/images/2022/seo/raw-vs-rendered-structured-data.png
Labels: editing

#3237 Simplified Chinese - WebAssembly Chapter 2022
  src/config/2022.json
  src/content/zh-CN/2022/webassembly.md
Labels: translation

#3269 Translation of css chapter to Japanese
  src/content/en/2022/css.md
  src/content/ja/2022/css.md
Labels: translation

#3211 Adds the French translation 2022 Jamstack chapter
  src/config/2022.json
  src/content/fr/2022/jamstack.md
Labels: translation

#3280 Fix figure 6 of Sustainability chapter
  src/content/en/2022/cdn.md
  src/content/en/2022/sustainability.md
  src/content/fr/2022/jamstack.md
  src/content/nl/2019/accessibility.md
  src/content/pt/2019/compression.md
  src/static/images/2022/sustainability/number-of-bytes-by-percentile-by-type-mobile.png
Labels: bug, editing

#3284 Spanish Translation - Privacy chapter
  src/config/2022.json
  src/content/en/2022/privacy.md
  src/content/es/2022/privacy.md
Labels: translation

#3278 feat: add security chapter to 2022/zh-CN directory
  src/config/2022.json
  src/content/en/2022/security.md
  src/content/zh-CN/2022/security.md
Labels: translation
