Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2024-10, with the labels that each got.

#3757 Structured Data 2024 queries
  sql/2024/structured-data/classic_microformats_types.sql
  sql/2024/structured-data/dublin_core_types.sql
  sql/2024/structured-data/facebook_types.sql
  sql/2024/structured-data/jsonld_contexts.sql
  sql/2024/structured-data/jsonld_depth_percentiles.sql
  sql/2024/structured-data/jsonld_entities_relationships.sql
  sql/2024/structured-data/jsonld_relationship_values.sql
  sql/2024/structured-data/jsonld_relationships.sql
  sql/2024/structured-data/jsonld_same_ases.sql
  sql/2024/structured-data/jsonld_types.sql
  sql/2024/structured-data/microdata_item_types.sql
  sql/2024/structured-data/microformats2_types.sql
  sql/2024/structured-data/open_graph_types.sql
  sql/2024/structured-data/present_types.sql
  sql/2024/structured-data/rdfa_prefixes.sql
  sql/2024/structured-data/rdfa_type_ofs.sql
  sql/2024/structured-data/rdfa_vocabs.sql
  sql/2024/structured-data/summary_count.sql
  sql/2024/structured-data/twitter_types.sql
Labels: analysis

#3798 Fix lighthouse testing
  src/tools/scripts/set_lighthouse_urls.sh
Labels: development

#3796 Add 2024 Methodology
  src/templates/en/2024/methodology.html
Labels: writing

#3696 Fonts 2024 Queries
  sql/2024/fonts/README.md
  sql/2024/fonts/common.sql
  sql/2024/fonts/design/fonts_designer.sql
  sql/2024/fonts/design/fonts_family_by_foundry.sql
  sql/2024/fonts/design/fonts_family_by_script.sql
  sql/2024/fonts/design/fonts_foundry.sql
  sql/2024/fonts/design/fonts_license.sql
  sql/2024/fonts/design/fonts_metric.sql
  sql/2024/fonts/design/fonts_script.sql
  sql/2024/fonts/design/styles_family.sql
  sql/2024/fonts/development/fonts_color.sql
  sql/2024/fonts/development/fonts_color_color.sql
  sql/2024/fonts/development/fonts_color_emoji.sql
  sql/2024/fonts/development/fonts_color_entry.sql
  sql/2024/fonts/development/fonts_color_family.sql
  sql/2024/fonts/development/fonts_color_format.sql
  sql/2024/fonts/development/fonts_color_format_by_family.sql
  sql/2024/fonts/development/fonts_color_palette.sql
  sql/2024/fonts/development/fonts_compiler.sql
  sql/2024/fonts/development/fonts_feature.sql
  sql/2024/fonts/development/fonts_feature_kerning.sql
  sql/2024/fonts/development/fonts_feature_opentype.sql
  sql/2024/fonts/development/fonts_format_outline.sql
  sql/2024/fonts/development/fonts_hinting.sql
  sql/2024/fonts/development/fonts_variable.sql
  sql/2024/fonts/development/fonts_variable_axis.sql
  sql/2024/fonts/development/fonts_variable_family.sql
  sql/2024/fonts/development/fonts_variable_format.sql
  sql/2024/fonts/development/fonts_variable_range.sql
  sql/2024/fonts/development/fonts_variable_service.sql
  sql/2024/fonts/development/styles_family_system.sql
  sql/2024/fonts/development/styles_feature_control.sql
  sql/2024/fonts/development/styles_font_feature_settings.sql
  sql/2024/fonts/development/styles_font_variable_settings_axis.sql
  sql/2024/fonts/development/styles_font_variant.sql
  sql/2024/fonts/development/styles_metric_override.sql
  sql/2024/fonts/development/styles_smoothing.sql
  sql/2024/fonts/development/styles_variable_animation.sql
  sql/2024/fonts/performance/fonts.sql
  sql/2024/fonts/performance/fonts_family_by_service.sql
  sql/2024/fonts/performance/fonts_format_file.sql
  sql/2024/fonts/performance/fonts_format_file_by_service.sql
  sql/2024/fonts/performance/fonts_service.sql
  sql/2024/fonts/performance/fonts_services.sql
  sql/2024/fonts/performance/fonts_size.sql
  sql/2024/fonts/performance/fonts_size_by_country.sql
  sql/2024/fonts/performance/fonts_size_by_format.sql
  sql/2024/fonts/performance/fonts_size_by_service.sql
  sql/2024/fonts/performance/fonts_size_by_table.sql
  sql/2024/fonts/performance/pages_link_relationship.sql
  sql/2024/fonts/performance/scripts_font_face.sql
  sql/2024/fonts/performance/styles_font_display.sql
  sql/2024/fonts/performance/styles_font_display_by_family.sql
Labels: analysis

#3749 Accessibility 2024: Queries
  sql/2024/accessibility/a11y_frontend_technology.sql
  sql/2024/accessibility/a11y_overall_tech_usage_by_domain_rank.sql
  sql/2024/accessibility/a11y_technology_usage.sql
  sql/2024/accessibility/a11y_technology_usage_by_domain_rank.sql
  sql/2024/accessibility/alt_ending_in_image_extension.sql
  sql/2024/accessibility/anchors_with_role_button.sql
  sql/2024/accessibility/audio_track_usage.sql
  sql/2024/accessibility/button_name_sources.sql
  sql/2024/accessibility/captcha_usage.sql
  sql/2024/accessibility/color_contrast.sql
  sql/2024/accessibility/common_alt_text_length.sql
  sql/2024/accessibility/common_aria_role.sql
  sql/2024/accessibility/common_element_attributes.sql
  sql/2024/accessibility/focus_outline_0.sql
  sql/2024/accessibility/focus_visible.sql
  sql/2024/accessibility/form_input_name_sources.sql
  sql/2024/accessibility/form_required_controls.sql
  sql/2024/accessibility/landmark_elements_and_roles.sql
  sql/2024/accessibility/lighthouse_a11y_audits.sql
  sql/2024/accessibility/lighthouse_a11y_audits_by_cms.sql
  sql/2024/accessibility/lighthouse_a11y_score.sql
  sql/2024/accessibility/lighthouse_score_by_cms.sql
  sql/2024/accessibility/lighthouse_score_by_country.sql
  sql/2024/accessibility/lighthouse_score_by_frontend.sql
  sql/2024/accessibility/lighthouse_score_by_government.sql
  sql/2024/accessibility/lighthouse_score_by_government_with_urls.sql
  sql/2024/accessibility/lighthouse_score_by_tld.sql
  sql/2024/accessibility/media_query_features.sql
  sql/2024/accessibility/page_title.sql
  sql/2024/accessibility/pages_with_search_input.sql
  sql/2024/accessibility/placeholder_but_no_label.sql
  sql/2024/accessibility/sites_using_role.sql
  sql/2024/accessibility/skip_links.sql
  sql/2024/accessibility/sr_only_classes.sql
  sql/2024/accessibility/tabindex_usage_and_values.sql
  sql/2024/accessibility/table_stats.sql
  sql/2024/accessibility/units_properties.sql
  sql/2024/accessibility/valid_html_lang.sql
  sql/2024/accessibility/video_track_usage.sql
  sql/2024/accessibility/viewport_zoom_scale.sql
  sql/2024/accessibility/viewport_zoom_scale_by_domain_rank.sql
Labels: analysis

#3809 Accessibility 2024 Chapter
  src/config/2024.json
  src/config/contributors.json
  src/content/en/2024/accessibility.md
  src/server/config.py
  src/static/images/2024/accessibility/US-state-governments-map.png
  src/static/images/2024/accessibility/US-state-governments.png
  src/static/images/2024/accessibility/a11y-app-usage-by-rank.png
  src/static/images/2024/accessibility/accessible-governments-world.png
  src/static/images/2024/accessibility/accessible-governments.png
  src/static/images/2024/accessibility/alt-attribute-lengths.png
  src/static/images/2024/accessibility/button-name-sources.png
  src/static/images/2024/accessibility/color-contrast-2019-2020-2021-2022-2024.png
  src/static/images/2024/accessibility/common-file-extensions-in-alt-text.png
  src/static/images/2024/accessibility/country-by-geoid.png
  src/static/images/2024/accessibility/country-by-tld-globe.png
  src/static/images/2024/accessibility/country-by-tld.png
  src/static/images/2024/accessibility/font-unit-usage.png
  src/static/images/2024/accessibility/form-input-name-sources.png
  src/static/images/2024/accessibility/form-required-controls.png
  src/static/images/2024/accessibility/javascript-frontend-ui.png
  src/static/images/2024/accessibility/javascript-meta-frameworks.png
  src/static/images/2024/accessibility/lighthouse-audit-markup-improvements.png
  src/static/images/2024/accessibility/lighthouse-audit-median-score-yoy.png
  src/static/images/2024/accessibility/microsoft-inclusivity-gudelines.png
  src/static/images/2024/accessibility/page_title-information.png
  src/static/images/2024/accessibility/pages-overriding-focus-styles.png
  src/static/images/2024/accessibility/pages-using-a11y-apps-by-rank.png
  src/static/images/2024/accessibility/pages-using-a11y-apps.png
  src/static/images/2024/accessibility/pages-with-element-role-yty.png
  src/static/images/2024/accessibility/pages-zooming-scaling-disabled.png
  src/static/images/2024/accessibility/placeholder-but-no-label.png
  src/static/images/2024/accessibility/platform-cms.png
  src/static/images/2024/accessibility/tabindex-usage-and-values.png
  src/static/images/2024/accessibility/top-10-aria-roles.png
  src/static/images/2024/accessibility/top10-aria-attributes.png
  src/static/images/2024/accessibility/traditional-cms.png
  src/static/images/2024/accessibility/userpreference-media-queries.png
  src/tools/test/test_status_codes.js
Labels: writing

#3722 Third-party 2024 queries
  sql/2024/third-parties/a11y_overall_tech_usage_by_rank.sql
  sql/2024/third-parties/a11y_technology_usage.sql
  sql/2024/third-parties/a11y_technology_usage_by_rank.sql
  sql/2024/third-parties/compressed_images_by_3p.sql
  sql/2024/third-parties/content_encoding.sql
  sql/2024/third-parties/content_encoding_by_content_type.sql
  sql/2024/third-parties/csp_allowed_host_frequency.sql
  sql/2024/third-parties/distribution_of_3XX_response_body_size.sql
  sql/2024/third-parties/distribution_of_lighthouse_unminified_css_by_3p.sql
  sql/2024/third-parties/distribution_of_lighthouse_unminified_js_by_3p.sql
  sql/2024/third-parties/distribution_of_lighthouse_unused_css_by_3p.sql
  sql/2024/third-parties/distribution_of_lighthouse_unused_js_by_3p.sql
  sql/2024/third-parties/distribution_of_lighthouse_uses_optimized_images_by_3p.sql
  sql/2024/third-parties/distribution_of_size_and_time_by_third_parties.sql
  sql/2024/third-parties/distribution_of_third_parties_by_frame.sql
  sql/2024/third-parties/distribution_of_third_parties_by_number_of_websites.sql
  sql/2024/third-parties/distribution_of_websites_by_number_of_third_parties.sql
  sql/2024/third-parties/distribution_of_websites_by_number_of_third_party_providers.sql
  sql/2024/third-parties/iframe_allow_attribute.sql
  sql/2024/third-parties/iframe_attribute_popular_hosts.sql
  sql/2024/third-parties/lighthouse_average_unminified_css_by_3p.sql
  sql/2024/third-parties/lighthouse_average_unminified_js_by_3p.sql
  sql/2024/third-parties/lighthouse_third_party_facades.sql
  sql/2024/third-parties/lighthouse_unminified_css_by_3p.sql
  sql/2024/third-parties/lighthouse_unminified_js_by_3p.sql
  sql/2024/third-parties/lighthouse_unminified_js_by_3p_by_url.sql
  sql/2024/third-parties/lighthouse_unminified_uses_optimized_images_by_3p.sql
  sql/2024/third-parties/lighthouse_unused_css_bytes_by_3p.sql
  sql/2024/third-parties/lighthouse_unused_js_bytes_by_3p.sql
  sql/2024/third-parties/number_of_third_parties_by_rank.sql
  sql/2024/third-parties/number_of_third_parties_by_rank_and_category.sql
  sql/2024/third-parties/number_of_third_party_providers_by_rank.sql
  sql/2024/third-parties/number_of_third_party_providers_by_rank_and_category.sql
  sql/2024/third-parties/number_of_third_party_requests_by_rank.sql
  sql/2024/third-parties/number_of_third_party_requests_per_page_by_rank.sql
  sql/2024/third-parties/percent_of_third_parties_by_content_type.sql
  sql/2024/third-parties/percent_of_third_parties_using_document_write.sql
  sql/2024/third-parties/percent_of_third_parties_using_legacy_javascript.sql
  sql/2024/third-parties/percent_of_third_parties_using_legacy_javascript_by_url.sql
  sql/2024/third-parties/percent_of_third_party_cache.sql
  sql/2024/third-parties/percent_of_third_party_requests_and_bytes_by_category_and_content_type.sql
  sql/2024/third-parties/percent_of_third_party_with_security_headers.sql
  sql/2024/third-parties/percent_of_websites_with_third_party.sql
  sql/2024/third-parties/percent_of_websites_with_third_party_by_ranking.sql
  sql/2024/third-parties/scripts_using_async_defer.sql
  sql/2024/third-parties/scripts_using_async_defer_by_3p.sql
  sql/2024/third-parties/tao_by_third_party.sql
  sql/2024/third-parties/third_parties_blocking_main_thread.sql
  sql/2024/third-parties/third_parties_blocking_main_thread_percentiles.sql
  sql/2024/third-parties/third_parties_blocking_main_thread_percentiles_by_host.sql
  sql/2024/third-parties/third_parties_blocking_rendering.sql
  sql/2024/third-parties/third_parties_blocking_rendering_percentiles.sql
  sql/2024/third-parties/third_parties_using_legacy_javascript.sql
  sql/2024/third-parties/top100_third_parties_by_median_body_size_and_time.sql
  sql/2024/third-parties/top100_third_parties_by_number_of_websites.sql
  sql/2024/third-parties/top20_third_parties_by_client_and_frame_location.sql
  sql/2024/third-parties/usage_of_lite_youtube_embed.sql
  sql/2024/third-parties/usage_of_partytown.sql
Labels: analysis
