Repository HTTPArchive/almanac.httparchive.org, pull requests merged in 2024-11, with the labels that each got.

#3653 Privacy 2024 queries
  sql/2024/privacy/ads_accounts_distribution.sql
  sql/2024/privacy/ads_and_sellers_graph.sql
  sql/2024/privacy/ads_lines_distribution.sql
  sql/2024/privacy/ccpa_most_common_phrases.sql
  sql/2024/privacy/ccpa_prevalence.sql
  sql/2024/privacy/common_ads_variables.sql
  sql/2024/privacy/cookies_top_first_party_names.sql
  sql/2024/privacy/cookies_top_third_party_domains.sql
  sql/2024/privacy/cookies_top_third_party_names.sql
  sql/2024/privacy/easylist-tracker-detection.sql
  sql/2024/privacy/fingerprinting_most_common_apis.sql
  sql/2024/privacy/fingerprinting_most_common_scripts.sql
  sql/2024/privacy/fingerprinting_script_count.sql
  sql/2024/privacy/most_common_client_hints.sql
  sql/2024/privacy/most_common_cmps_for_iab_tcf_v2.sql
  sql/2024/privacy/most_common_cname_domains.sql
  sql/2024/privacy/most_common_countries_for_iab_tcf_v2.sql
  sql/2024/privacy/most_common_referrer_policy.sql
  sql/2024/privacy/most_common_strings_for_iab_usp.sql
  sql/2024/privacy/number_of_ara_destinations_registered_by_third_parties_and_publishers.sql
  sql/2024/privacy/number_of_privacy_sandbox_attested_domains.sql
  sql/2024/privacy/number_of_websites_per_technology.sql
  sql/2024/privacy/number_of_websites_per_technology_category.sql
  sql/2024/privacy/number_of_websites_with_bounce_tracking.sql
  sql/2024/privacy/number_of_websites_with_client_hints.sql
  sql/2024/privacy/number_of_websites_with_dnt.sql
  sql/2024/privacy/number_of_websites_with_gpc.sql
  sql/2024/privacy/number_of_websites_with_iab.sql
  sql/2024/privacy/number_of_websites_with_referrerpolicy.sql
  sql/2024/privacy/number_of_websites_with_related_origin_trials.sql
  sql/2024/privacy/number_of_websites_with_whotracksme_trackers.sql
  sql/2024/privacy/privacy-sandbox-adoption-by-third-parties-by-publishers.sql
  sql/2024/privacy/top_ara_destinations_registered_by_most_publishers.sql
  sql/2024/privacy/top_ara_destinations_registered_by_most_third_parties.sql
  sql/2024/privacy/top_direct_ads_demand.sql
  sql/util/ads_txt_parser.py
  sql/util/bq_to_sheets.ipynb
  sql/util/bq_writer.py
  sql/util/breaches.py
  sql/util/functions.sql
  sql/util/haveibeenpwned.py
  sql/util/populate_easylist_adserver.py
  sql/util/trackers_whotracksme.py
  sql/util/whotracksme_trackers.py
  src/requirements.txt
Labels: analysis

#3736 Sustainability 2024: Queries
  sql/2024/sustainability/cache_header_usage.sql
  sql/2024/sustainability/cdn_adoption.sql
  sql/2024/sustainability/cms_bytes_per_type.sql
  sql/2024/sustainability/cms_bytes_per_type_2022.sql
  sql/2024/sustainability/ecommerce_bytes_per_type.sql
  sql/2024/sustainability/ecommerce_bytes_per_type_2022.sql
  sql/2024/sustainability/favicons.sql
  sql/2024/sustainability/global_emissions_per_page.sql
  sql/2024/sustainability/global_emissions_per_page_2022.sql
  sql/2024/sustainability/green_third_party_requests.sql
  sql/2024/sustainability/green_web_hosting.sql
  sql/2024/sustainability/page_byte_pre_type.sql
  sql/2024/sustainability/query_run_size.sql
  sql/2024/sustainability/responsive_images.sql
  sql/2024/sustainability/script_count.sql
  sql/2024/sustainability/ssg_bytes_per_type.sql
  sql/2024/sustainability/ssg_bytes_per_type_2022.sql
  sql/2024/sustainability/stylesheet_count.sql
  sql/2024/sustainability/text_compression.sql
  sql/2024/sustainability/unminified_css_bytes.sql
  sql/2024/sustainability/unminified_js_bytes.sql
  sql/2024/sustainability/unused_css_bytes.sql
  sql/2024/sustainability/unused_js_bytes.sql
  sql/2024/sustainability/use_of_prefers_dark_mode_usage.sql
  sql/2024/sustainability/video_autoplay_values.sql
  sql/2024/sustainability/video_preload_values.sql
Labels: analysis

#3763 HTTP queries for 2024
  sql/2024/http/connections_per_page_load_dist.sql
  sql/2024/http/dns_https_svcb_usage.sql
  sql/2024/http/dns_https_svcb_usage_cdn.sql
  sql/2024/http/early_hints_per_page.sql
  sql/2024/http/early_hints_usage.sql
  sql/2024/http/early_hints_usage_as_percentile_within_used.sql
  sql/2024/http/early_hints_usage_as_usage.sql
  sql/2024/http/early_hints_usage_percentile_within_used.sql
  sql/2024/http/fetchpriority_usage.sql
  sql/2024/http/h2_adoption_by_cdn_pct.sql
  sql/2024/http/h2_adoption_each_cdn_breakdown.sql
  sql/2024/http/h2_adoption_pages_reqs.sql
  sql/2024/http/h2_adoption_reqs_dist.sql
  sql/2024/http/h3_support.sql
  sql/2024/http/h3_support_each_cdn_breakdown.sql
  sql/2024/http/h3_support_from_cdn.sql
  sql/2024/http/h3_switches.sql
  sql/2024/http/h3_usage_site.sql
  sql/2024/http/lcp_element_data_by_type.sql
  sql/2024/http/lcp_element_data_with_urls.sql
  sql/2024/http/preload_as_values.sql
  sql/2024/http/preload_as_values_fetchpriority.sql
  sql/2024/http/priority_hints_per_page.sql
  sql/2024/http/priority_hints_usage.sql
  sql/2024/http/protocol_advertised_via_altsvc.sql
  sql/2024/http/resource_hint_overuse_examples.sql
  sql/2024/http/resource_hint_usage.sql
  sql/2024/http/resource_hint_usage_percentile.sql
  sql/2024/http/sites_cdn_with_altsvc.sql
  sql/2024/http/sites_using_link_preload_header.sql
  sql/2024/http/sites_using_link_preload_tag.sql
  sql/2024/http/sites_with_altsvc.sql
  sql/2024/http/third_party_origins_with_altsvc..sql
  sql/2024/http/unused_preloads.sql
Labels: analysis

#3731 CMS 2024 queries
  sql/2024/cms/cms_adoption.sql
  sql/2024/cms/cms_adoption_by_geo.sql
  sql/2024/cms/cms_adoption_by_region.sql
  sql/2024/cms/cms_adoption_by_subregion.sql
  sql/2024/cms/core_web_vitals.sql
  sql/2024/cms/core_web_vitals_by_geo.sql
  sql/2024/cms/core_web_vitals_yoy.sql
  sql/2024/cms/image_format_popularity.sql
  sql/2024/cms/lighthouse_category_scores_per_cms.sql
  sql/2024/cms/lighthouse_category_scores_per_cms_yoy.sql
  sql/2024/cms/page_weight_distribution.sql
  sql/2024/cms/resource_weights.sql
  sql/2024/cms/top_cms.sql
  sql/2024/cms/top_cms_by_geo.sql
  sql/2024/cms/top_cms_by_rank.sql
  sql/2024/cms/wordpress_page_builders.sql
  sql/2024/cms/wordpress_resources.sql
Labels: analysis

#3834 Jamstack 2024 chapter
  sql/2024/jamstack/hugo_astro_next.sql
  sql/2024/jamstack/jamstack-overview.sql
  sql/2024/jamstack/jamstack_distribution_by_rank.sql
  sql/2024/jamstack/js_frameworks.sql
  sql/2024/jamstack/paas.sql
  sql/2024/jamstack/ssg.sql
  src/config/2024.json
  src/config/contributors.json
  src/content/en/2024/jamstack.md
  src/static/images/2024/jamstack/astro-hugo-next-js-size.png
  src/static/images/2024/jamstack/astro-hugo-next-transfer-size.png
  src/static/images/2024/jamstack/core-web-vitals.png
  src/static/images/2024/jamstack/css-size.png
  src/static/images/2024/jamstack/global-adoption.png
  src/static/images/2024/jamstack/hybrid-high-traffic-adoption.png
  src/static/images/2024/jamstack/hybrid-static-site-generators.png
  src/static/images/2024/jamstack/javascript-frameworks.png
  src/static/images/2024/jamstack/javascript-size.png
  src/static/images/2024/jamstack/page-transfer-size.png
  src/static/images/2024/jamstack/prerendered-high-traffic-adoption.png
  src/static/images/2024/jamstack/prerendered-static-site-generators.png
  src/static/images/2024/jamstack/total-requests.png
  src/static/images/2024/jamstack/transfer-excluding-css-js.png
Labels: analysis, writing

#3738 Media 2024 queries
  sql/2024/media/animated_gif_bpp.sql
  sql/2024/media/animated_gif_count.sql
  sql/2024/media/animated_gif_framecount.sql
  sql/2024/media/at_least_one_image_request.sql
  sql/2024/media/at_least_one_img.sql
  sql/2024/media/bytes_and_dimensions.sql
  sql/2024/media/bytes_and_dimensions_by_format.sql
  sql/2024/media/color_spaces_and_depth.sql
  sql/2024/media/image_0x0.sql
  sql/2024/media/image_1x1.sql
  sql/2024/media/image_alt.sql
  sql/2024/media/image_cdn_usage.sql
  sql/2024/media/image_decode_usage.sql
  sql/2024/media/image_layout_widths.sql
  sql/2024/media/image_sizes_attribute_strings.sql
  sql/2024/media/image_sizes_per_page_accuracy_impact.sql
  sql/2024/media/image_sizing_extrinsic_intrinsic.sql
  sql/2024/media/image_srcset_candidates.sql
  sql/2024/media/image_srcset_densities.sql
  sql/2024/media/image_srcset_descriptor.sql
  sql/2024/media/image_srcset_sizes.sql
  sql/2024/media/image_srcset_sizes_accuracy_pct.sql
  sql/2024/media/image_srcset_sizes_per_image_accuracy_impact.sql
  sql/2024/media/img_sizes_explicit_errors.sql
  sql/2024/media/img_with_dimensions.sql
  sql/2024/media/img_xdomain.sql
  sql/2024/media/imgs_per_page.sql
  sql/2024/media/largest_image_per_page_bytes.sql
  sql/2024/media/largest_image_per_page_layout.sql
  sql/2024/media/largest_image_per_page_pixels.sql
  sql/2024/media/lazy_loading_adoption_over_time.sql
  sql/2024/media/lcp_element_data.sql
  sql/2024/media/media_formats.sql
  sql/2024/media/picture_distribution.sql
  sql/2024/media/picture_format_distribution.sql
  sql/2024/media/picture_orientation.sql
  sql/2024/media/picture_switching.sql
  sql/2024/media/picture_using_min_resolution.sql
  sql/2024/media/pixel_volume.sql
  sql/2024/media/portrait_landscape_square.sql
  sql/2024/media/score_progressive_jpeg.sql
  sql/2024/media/srcset_density_coverage.sql
  sql/2024/media/top_aspect_ratios.sql
  sql/2024/media/video_adoption.sql
  sql/2024/media/video_attribute_count.sql
  sql/2024/media/video_attribute_names.sql
  sql/2024/media/video_attribute_widths.sql
  sql/2024/media/video_autoplay_muted.sql
  sql/2024/media/video_durations.sql
  sql/2024/media/video_ext.todo.sql
  sql/2024/media/video_formats.sql
  sql/2024/media/video_media.sql
  sql/2024/media/video_number_of_sources.sql
  sql/2024/media/video_preload_values.todo.sql
  sql/2024/media/video_source_formats.sql
  sql/2024/media/video_source_types.todo.sql
  sql/2024/media/video_styles.sql
  sql/2024/media/video_tag_and_js_player.todo.sql
Labels: analysis

#3786 Ecommerce 2024 queries
  sql/2024/ecommerce/core_web_vitals_passingmetrics_byvendor_bydevice.sql
  sql/2024/ecommerce/core_web_vitals_yoy.sql
  sql/2024/ecommerce/median_lighthouse_score_ecommsites.sql
  sql/2024/ecommerce/top_ecommerce.sql
  sql/2024/ecommerce/top_payment_by_geo.sql
  sql/2024/ecommerce/top_payment_yoy.sql
  sql/2024/ecommerce/top_shipping_by_geo.sql
  sql/2024/ecommerce/top_shipping_yoy.sql
  sql/2024/ecommerce/top_shopsystem_by_geo.sql
  sql/2024/ecommerce/top_vendors_crux_rank.sql
Labels: analysis

#3794 Sustainability2024 Chapter
  src/config/2024.json
  src/config/contributors.json
  src/content/en/2024/sustainability.md
  src/static/images/2024/sustainability/cache-control-header-usage.png
  src/static/images/2024/sustainability/carbon-emissions-by-percentile-2022.png
  src/static/images/2024/sustainability/carbon-emissions-by-percentile-2024.png
  src/static/images/2024/sustainability/cdn-usage.png
  src/static/images/2024/sustainability/emissions-by-percentile-by-type-desktop.png
  src/static/images/2024/sustainability/emissions-by-percentile-by-type-mobile.png
  src/static/images/2024/sustainability/favicon-usage.png
  src/static/images/2024/sustainability/green-third-party-requests.png
  src/static/images/2024/sustainability/image-format-adoption-2-year-change.png
  src/static/images/2024/sustainability/image-format-adoption.png
  src/static/images/2024/sustainability/kilobytes-by-percentile-by-type-mobile-.png
  src/static/images/2024/sustainability/kilobytes-by-percentile-by-type-mobile.png
  src/static/images/2024/sustainability/kilobytes-per-type.png
  src/static/images/2024/sustainability/lazy-loading-adoption.png
  src/static/images/2024/sustainability/median-emissions-by-cms-2022.png
  src/static/images/2024/sustainability/median-emissions-by-cms-2024.png
  src/static/images/2024/sustainability/median-emissions-by-cms-and-resource-type.png
  src/static/images/2024/sustainability/median-emissions-by-ecommerce-2022.png
  src/static/images/2024/sustainability/median-emissions-by-ecommerce-2024.png
  src/static/images/2024/sustainability/median-emissions-by-ssg-2022.png
  src/static/images/2024/sustainability/median-emissions-by-ssg-2024.png
  src/static/images/2024/sustainability/median-kilobytes-by-cms-and-resource-type.png
  src/static/images/2024/sustainability/median-kilobytes-by-cms.png
  src/static/images/2024/sustainability/median-kilobytes-by-ecommerce.png
  src/static/images/2024/sustainability/median-kilobytes-by-ssg.png
  src/static/images/2024/sustainability/non-composited-animations-per-page.png
  src/static/images/2024/sustainability/number-of-kb-by-percentile.png
  src/static/images/2024/sustainability/number-of-requests-by-percentile-and-type-mobile.png
  src/static/images/2024/sustainability/number-of-requests-by-percentile.png
  src/static/images/2024/sustainability/percent_green_hosting.png
  src/static/images/2024/sustainability/responsive-image-types.png
  src/static/images/2024/sustainability/style-usage.png
  src/static/images/2024/sustainability/text-compression.png
  src/static/images/2024/sustainability/unminified-css-savings.png
  src/static/images/2024/sustainability/unminified-js-savings.png
  src/static/images/2024/sustainability/unused_css.png
  src/static/images/2024/sustainability/unused_js.png
  src/static/images/2024/sustainability/video-autoplay-usage.png
  src/static/images/2024/sustainability/video-preload-usage.png
Labels: writing

#3815 Markup 2024 Chapter
  sql/2024/markup/attributes.sql
  sql/2024/markup/buttons.sql
  sql/2024/markup/comments.sql
  sql/2024/markup/content_encoding.sql
  sql/2024/markup/custom_elements_adoption.sql
  sql/2024/markup/custom_elements_js_bytes_distribution.sql
  sql/2024/markup/data_attribute_total.sql
  sql/2024/markup/data_attributes.sql
  sql/2024/markup/distinct_lang.sql
  sql/2024/markup/doctype.sql
  sql/2024/markup/document_size_distribution.sql
  sql/2024/markup/document_trends.sql
  sql/2024/markup/document_trends_is_root_page.sql
  sql/2024/markup/element_count_distribution.sql
  sql/2024/markup/element_frequency.sql
  sql/2024/markup/element_popularity.sql
  sql/2024/markup/favicons.sql
  sql/2024/markup/forms.sql
  sql/2024/markup/inputs.sql
  sql/2024/markup/inputs_per_form.sql
  sql/2024/markup/lang.sql
  sql/2024/markup/links.sql
  sql/2024/markup/meta_node_names.sql
  sql/2024/markup/meta_viewports.sql
  sql/2024/markup/obsolete_elements.sql
  src/config/2024.json
  src/config/contributors.json
  src/content/en/2024/markup.md
  src/static/images/2024/markup/attribute_usage.png
  src/static/images/2024/markup/buttons.png
  src/static/images/2024/markup/content_encoding.png
  src/static/images/2024/markup/custom_element_popularity.png
  src/static/images/2024/markup/custom_elements_adoption.png
  src/static/images/2024/markup/custom_elements_js_bytes_distribution.png
  src/static/images/2024/markup/data_attribute_frequency.png
  src/static/images/2024/markup/data_attribute_popularity.png
  src/static/images/2024/markup/distinct_elements_per_page.png
  src/static/images/2024/markup/document_size_distribution.png
  src/static/images/2024/markup/document_trends.png
  src/static/images/2024/markup/elements_per_page.png
  src/static/images/2024/markup/favicons.png
  src/static/images/2024/markup/input_buttons.png
  src/static/images/2024/markup/meta_viewports.png
  src/static/images/2024/markup/obsolete_elements.png
  src/static/images/2024/markup/popular_lang.png
  src/static/images/2024/markup/popular_regional_lang.png
  src/static/images/2024/markup/popularity_attribute_usage.png
  src/static/images/2024/markup/popularity_of_top_elements.png
  src/static/images/2024/markup/social_meta_nodes.png
  src/static/images/2024/markup/top_elements.png
Labels: writing

#3838 Ecommerce 2024 chapter
  src/config/2024.json
  src/config/contributors.json
  src/content/en/2024/ecommerce.md
  src/static/images/2024/ecommerce/ecommerce-platforms-distribution.png
  src/static/images/2024/ecommerce/median-lighthouse-accessibility-score.png
  src/static/images/2024/ecommerce/median-lighthouse-best-practices-score.png
  src/static/images/2024/ecommerce/median-lighthouse-performance-score.png
  src/static/images/2024/ecommerce/median-lighthouse-seo-score.png
  src/static/images/2024/ecommerce/mobile-cls-performance.png
  src/static/images/2024/ecommerce/mobile-core-web-vitals-performance.png
  src/static/images/2024/ecommerce/mobile-inp-performance.png
  src/static/images/2024/ecommerce/mobile-lcp-performance.png
  src/static/images/2024/ecommerce/mobile-payment-provider-distribution.png
  src/static/images/2024/ecommerce/platform-adoption-by-rank.png
  src/static/images/2024/ecommerce/top-5-platforms-2021-2024.png
  src/static/images/2024/ecommerce/top-ecommerce-platform-by-country.png
Labels: writing

#3836 CDN 2024 chapter
  sql/2024/cdn/README copy.md
  sql/2024/cdn/cdn_usage_by_site_rank.sql
  sql/2024/cdn/client_hints_cdn_vs_origin.sql
  sql/2024/cdn/distribution_of_compression_types_by_cdn.sql
  sql/2024/cdn/distribution_of_compression_types_cdn_vs_origin.sql
  sql/2024/cdn/distribution_of_http_versions.sql
  sql/2024/cdn/distribution_of_http_versions_cdn_vs_origin.sql
  sql/2024/cdn/distribution_of_tls_time_by_cdn.sql
  sql/2024/cdn/distribution_of_tls_time_cdn_vs_origin.sql
  sql/2024/cdn/distribution_of_tls_versions.sql
  sql/2024/cdn/distribution_of_tls_versions_cdn_vs_origin.sql
  sql/2024/cdn/early_hints_by_cdn.sql
  sql/2024/cdn/early_hints_cdn_vs_origin.sql
  sql/2024/cdn/image_formats.sql
  sql/2024/cdn/top_cdns.sql
  sql/2024/cdn/top_cdns_by_rank.sql
  sql/2024/cdn/usage_of_content_cdns.sql
  src/config/2024.json
  src/config/contributors.json
  src/content/en/2024/cdn.md
  src/static/images/2024/cdn/cdn-client-hints-mobile.png
  src/static/images/2024/cdn/cdn-compression-mobile.png
  src/static/images/2024/cdn/cdn-early-hints-mobile.png
  src/static/images/2024/cdn/cdn-http-versions-mobile-3p.png
  src/static/images/2024/cdn/cdn-http-versions-mobile.png
  src/static/images/2024/cdn/cdn-image-formats-mobile.png
  src/static/images/2024/cdn/cdn-types-compression-mobile.png
  src/static/images/2024/cdn/cdn-usage-hosted-comparison.png
  src/static/images/2024/cdn/cdn-usage-hosted.png
  src/static/images/2024/cdn/cdn-usage-ranking-mobile.png
  src/static/images/2024/cdn/tls-negotiation-desktop.png
  src/static/images/2024/cdn/tls-negotiation-mobile.png
  src/static/images/2024/cdn/tls-version-mobile-3p.png
  src/static/images/2024/cdn/tls-version-mobile.png
  src/static/images/2024/cdn/top-cdns-3p.png
  src/static/images/2024/cdn/top-cdns-html.png
  src/static/images/2024/cdn/top-cdns-subdomain.png
Labels: writing

#3741 Cookies sql 2024
  sql/2024/cookies/0_extract_cookies.sql
  sql/2024/cookies/CHIPS_top_20_first_party_cookies.sql
  sql/2024/cookies/CHIPS_top_20_third_party_cookies.sql
  sql/2024/cookies/README.md
  sql/2024/cookies/age_expire_cookies_per_type_quantiles.sql
  sql/2024/cookies/age_expire_cookies_quantiles.sql
  sql/2024/cookies/age_expires_cookies_cdf.sql
  sql/2024/cookies/nb_cookies_cdf.sql
  sql/2024/cookies/nb_cookies_per_type_quantiles.sql
  sql/2024/cookies/nb_cookies_quantiles.sql
  sql/2024/cookies/prevalence_attributes_per_type.sql
  sql/2024/cookies/prevalence_type_attributes_per_rank.sql
  sql/2024/cookies/size_cookies_cdf.sql
  sql/2024/cookies/size_cookies_per_type_quantiles.sql
  sql/2024/cookies/size_cookies_quantiles.sql
  sql/2024/cookies/size_extract_largest.sql
  sql/2024/cookies/top_20_domains_setting_cookies.sql
  sql/2024/cookies/top_20_first_party_cookies.sql
  sql/2024/cookies/top_20_third_party_cookies.sql
Labels: analysis

#3791 SEO 2024 queries
  sql/2024/seo/anchor-rel-attribute-usage-2024.sql
  sql/2024/seo/anchor-same-site-occurance-stats-2024.sql
  sql/2024/seo/content-language-2024.sql
  sql/2024/seo/core-web-vitals-2024.sql
  sql/2024/seo/hreflang-header-usage-2024.sql
  sql/2024/seo/hreflang-link-tag-usage-2024.sql
  sql/2024/seo/html-response-content-language-2024.sql
  sql/2024/seo/html-response-vary-header-used-2024.sql
  sql/2024/seo/iframe-loading-property-usage-2024.sql
  sql/2024/seo/image-alt-stats-2024.sql
  sql/2024/seo/image-loading-property-usage-2024.sql
  sql/2024/seo/invalid-head-elements-2024.sql
  sql/2024/seo/invalid-head-sites-2024.sql
  sql/2024/seo/lighthouse-seo-stats-2024.sql
  sql/2024/seo/mark-up-stats-2024.sql
  sql/2024/seo/media-property-usage-link-tags-rel-alternate-2024.sql
  sql/2024/seo/meta-tag-usage-by-name-2024.sql
  sql/2024/seo/meta-tag-usage-by-property-2024.sql
  sql/2024/seo/outgoing_links_by_rank -2024.sql
  sql/2024/seo/pages-canonical-stats-2024.sql
  sql/2024/seo/pages-containing-a-video-element-2024.sql
  sql/2024/seo/robots-meta-usage-2024.sql
  sql/2024/seo/robots-text-size-2024.sql
  sql/2024/seo/robots-txt-size-2024.sql
  sql/2024/seo/robots-txt-status-codes -2024.sql
  sql/2024/seo/robots-txt-user-agent-usage-2024.sql
  sql/2024/seo/seo-stats-2024.sql
  sql/2024/seo/seo-stats-by-percentile-2024.sql
  sql/2024/seo/structured-data-formats-2024.sql
  sql/2024/seo/structured-data-schema-types-2024.sql
  sql/2024/seo/unused-css-js-2024.sql
  sql/2024/seo/videos_per_page-2024.sql
Labels: analysis

#3822 Chart resizing script
  src/tools/scripts/chart-adjustments.ipynb
Labels: editing

#3732 Page Weight 2024 Queries
  sql/2024/page-weight/bytes_per_type.sql
  sql/2024/page-weight/compression-usage.sql
  sql/2024/page-weight/cwv_trend.sql
  sql/2024/page-weight/facades-usage.sql
  sql/2024/page-weight/minified_css_usage.sql
  sql/2024/page-weight/minified_js_usage.sql
  sql/2024/page-weight/page_weight_trend.sql
  sql/2024/page-weight/request_type_distribution.sql
  sql/2024/page-weight/response_format_distribution.sql
  sql/2024/page-weight/response_type_distribution.sql
Labels: analysis

#3718 Add BibTeX citation box (#1325)
  src/static/css/page.css
  src/templates/base/base_chapter.html
  src/templates/en/base.html
  src/templates/es/base.html
  src/templates/fr/base.html
  src/templates/hi/base.html
  src/templates/it/base.html
  src/templates/ja/base.html
  src/templates/nl/base.html
  src/templates/pt/base.html
  src/templates/ru/base.html
  src/templates/tr/base.html
  src/templates/uk/base.html
  src/templates/zh-CN/base.html
  src/templates/zh-TW/base.html
Labels: development

#3844 Fonts 2024 Chapter
  src/config/2024.json
  src/config/contributors.json
  src/content/en/2024/fonts.md
  src/static/images/2024/fonts/color-font-format-usage-over-time.png
  src/static/images/2024/fonts/color-font-format-usage.png
  src/static/images/2024/fonts/color-font-formats.png
  src/static/images/2024/fonts/color-font-usage-over-time.png
  src/static/images/2024/fonts/font-display-usage.png
  src/static/images/2024/fonts/font-outline-formats.png
  src/static/images/2024/fonts/font-outline-glyf-cff-comparison-compressed.png
  src/static/images/2024/fonts/font-outline-glyf-cff-comparison.png
  src/static/images/2024/fonts/font-resource-hint-usage.png
  src/static/images/2024/fonts/font-sizes.png
  src/static/images/2024/fonts/font-smoothing-usage.png
  src/static/images/2024/fonts/font-variation-axes.png
  src/static/images/2024/fonts/generic-family-name-usage.png
  src/static/images/2024/fonts/hosting-type.png
  src/static/images/2024/fonts/nabla-color.png
  src/static/images/2024/fonts/opentype-feature-support-fonts.png
  src/static/images/2024/fonts/opentype-features-low-level-vs-high-level-properties.png
  src/static/images/2024/fonts/popular-font-feature-settings-values.png
  src/static/images/2024/fonts/popular-mime-types-self-hosted.png
  src/static/images/2024/fonts/popular-mime-types.png
  src/static/images/2024/fonts/ttf-font-sizes.png
  src/static/images/2024/fonts/variable-font-axes.png
  src/static/images/2024/fonts/variable-font-usage-by-service.png
  src/static/images/2024/fonts/variable-font-usage-over-time.png
  src/static/images/2024/fonts/web-font-usage-by-service.png
  src/static/images/2024/fonts/webfont-usage.png
  src/static/images/2024/fonts/woff2-font-sizes-google-vs-self-hosted.png
  src/static/images/2024/fonts/woff2-font-sizes.png
  src/static/images/2024/fonts/writing-systems.png
Labels: writing

#3846 CMS Chapter Updates
  src/config/contributors.json
  src/content/en/2024/cms.md
  src/static/images/2024/cms/cms-adoption-share.png
Labels: writing

#3827 Cookies 2024 chapter
  src/Dockerfile
  src/config/2024.json
  src/config/contributors.json
  src/content/en/2024/cookies.md
  src/static/images/2024/cookies/age-cookies-cdf-desktop-mobile.png
  src/static/images/2024/cookies/attestation-files.png
  src/static/images/2024/cookies/cookie-prefixes-desktop.png
  src/static/images/2024/cookies/cookie-prefixes-mobile.png
  src/static/images/2024/cookies/cookies-attributes-overview-desktop.png
  src/static/images/2024/cookies/cookies-attributes-overview-mobile.png
  src/static/images/2024/cookies/first-and-third-party-prevalence-by-rank-desktop.png
  src/static/images/2024/cookies/first-and-third-party-prevalence.png
  src/static/images/2024/cookies/first-and-third-party-prevalence.png-by-rank-mobile.png
  src/static/images/2024/cookies/hero_lg.avif
  src/static/images/2024/cookies/hero_lg.png
  src/static/images/2024/cookies/hero_lg.webp
  src/static/images/2024/cookies/hero_sm.avif
  src/static/images/2024/cookies/hero_sm.jpg
  src/static/images/2024/cookies/hero_sm.webp
  src/static/images/2024/cookies/number-cookies-cdf-desktop.png
  src/static/images/2024/cookies/number-cookies-cdf-mobile.png
  src/static/images/2024/cookies/same-site-desktop.png
  src/static/images/2024/cookies/same-site-mobile.png
  src/static/images/2024/cookies/secondary-domains.png
  src/static/images/2024/cookies/size-cookies-cdf-desktop-mobile.png
  src/static/images/2024/cookies/top-cookie-domains.png
  src/static/images/2024/cookies/top-first-party-CHIPS.png
  src/static/images/2024/cookies/top-first-party-cookies-set.png
  src/static/images/2024/cookies/top-third-party-CHIPS.png
  src/static/images/2024/cookies/top-third-party-cookies-set.png
Labels: writing

#3811 Structured Data 2024 Chapter
  src/config/2024.json
  src/config/contributors.json
  src/content/en/2024/structured-data.md
  src/static/images/2024/structured-data/dublin-core-usage-by-device.png
  src/static/images/2024/structured-data/dublin-core-usage-by-year-desktop.png
  src/static/images/2024/structured-data/dublin-core-usage-by-year.png
  src/static/images/2024/structured-data/facebook-meta-tag-usage-by-device.png
  src/static/images/2024/structured-data/facebook-meta-tag-usage-by-year-desktop.png
  src/static/images/2024/structured-data/facebook-meta-tag-usage-by-year-mobile.png
  src/static/images/2024/structured-data/jsonld-by-device.png
  src/static/images/2024/structured-data/jsonld-year-on-year-mobile.png
  src/static/images/2024/structured-data/microdata-by-device.png
  src/static/images/2024/structured-data/microdata-year-on-year-mobile.png
  src/static/images/2024/structured-data/microformats-desktop-year-on-year.png
  src/static/images/2024/structured-data/microformats-mobile-year-on-year.png
  src/static/images/2024/structured-data/microformats-usage-desktop.png
  src/static/images/2024/structured-data/microformats2-by-device.png
  src/static/images/2024/structured-data/microformats2-desktop-year-on-year.png
  src/static/images/2024/structured-data/microformats2-mobile-year-on-year.png
  src/static/images/2024/structured-data/open-graph-usage-by-device.png
  src/static/images/2024/structured-data/open-graph-usage-by-year-desktop.png
  src/static/images/2024/structured-data/open-graph-usage-by-year.png
  src/static/images/2024/structured-data/rdfa-usage-by-device.png
  src/static/images/2024/structured-data/rdfa-usage-by-year-desktop.png
  src/static/images/2024/structured-data/rdfa-usage-by-year.png
  src/static/images/2024/structured-data/sameas-year-on-year-by-device.png
  src/static/images/2024/structured-data/sameas-year-on-year-mobile.png
  src/static/images/2024/structured-data/structured-data-google-gemini.png
  src/static/images/2024/structured-data/structured-data-image-carousel.png
  src/static/images/2024/structured-data/structured-data-json-ld-relationships-1.svg
  src/static/images/2024/structured-data/structured-data-json-ld-relationships-2.svg
  src/static/images/2024/structured-data/structured-data-perplexity.png
  src/static/images/2024/structured-data/structured-data-usage-by-year-desktop.png
  src/static/images/2024/structured-data/structured-data-usage-by-year-mobile.png
  src/static/images/2024/structured-data/structured-data-via-culinaria-bing.png
  src/static/images/2024/structured-data/structured-data-you-com.png
  src/static/images/2024/structured-data/twitter-meta-tag-usage-by-device.png
  src/static/images/2024/structured-data/twitter-meta-tag-usage-by-year-desktop.png
  src/static/images/2024/structured-data/twitter-meta-tag-usage-by-year.png
Labels: writing

#3899 Fix contributors search icon alignment on mobile
  src/templates/base/contributors.html
Labels: bug

#3910 Markdown third parties 2024
  sql/2024/third-parties/depth_of_gtm_calls.sql
  src/config/2024.json
  src/config/contributors.json
  src/config/last_updated.json
  src/content/en/2024/structured-data.md
  src/content/en/2024/third-parties.md
  src/static/images/2024/third-parties/3p_req_categories_by_rank.png
  src/static/images/2024/third-parties/3p_req_types_by_rank.png
  src/static/images/2024/third-parties/depth_of_gtm_called_urls.png
  src/static/images/2024/third-parties/median_depth_categories.png
  src/static/images/2024/third-parties/median_depth_tp_inclusion_chains.png
  src/static/images/2024/third-parties/num_3p_by_rank.png
  src/static/images/2024/third-parties/num_3p_req_per_page_by_rank.png
  src/static/images/2024/third-parties/percent_pages_using_atleast_one_3p.png
  src/static/images/2024/third-parties/top_3p_by_num_pages.png
Labels: writing
